### ISSUE TITLE
Yahka dead

### ISSUE THREAD

**Issue by Hirbod** [jensweigele/ioBroker.yahka#1]
Hi,

nach einigen Wochen hat sich Yahka einfach verabschiedet. Alle Geräte waren nicht mehr erreichbar. Auf dem iPad hat es funktioniert aber iOS tot. Hab die bridge entfernt, alles neu installiert, Name, serial, mac I'd etc - wirklich alles geändert. Aber die bridge erscheint nicht mal mehr. Hat jemand irgend eine Ahnung? Mein halbes Haus basiert auf yahka (gerade meine innr Birnen). Hab keine Siri Steuerung mehr. Jemand ne Idee?

Nichts in den Logs..

**Comment by jensweigele** [comment]
Kannst du bitte mal Version 0.5.4 testen und das Verbose Logging anschalten (und das Adapter Logging auf "debug" stellen)?

Mehr Infos hier: http://forum.iobroker.net/viewtopic.php?f=23&t=4136&start=40#p52273

**Comment by jensweigele** [comment]
Besteht das Problem nicht?
Wenn nicht schließe ich das Ticket demnächst

**Comment by jansios** [comment]
Ich vermute mal, dass es sich hier um das gleiche Problem wie bei Issue #9 handelt. Ich habe das Problem mit der 0.5.5 auch vor kurzem gehabt nach einem kurzen Stromausfall und somit einem harten Absturz des Raspberry inkl. ioBroker und natürlich yahka. Erst das Neuvergeben eines neuen Usernames brachten es wieder zum Fliegen und ich musste im Apple Homekit die Raumzuordnungen neu machen. Sehr ärgerlich, dennoch insg. ein schöner Adapter, also weiter so ;)

Gibt es etwas, was ich Dir zur Verfügung stellen kann, sollte der Effekt erneut auftreten? Spezielle Logs o.ä.? Wäre vielleicht auch für andere interessant, denn bei Issue #9 scheint es wie erwähnt um das gleiche Problem zu gehen und im Forum habe ich es auch bereits gelesen.

**Comment by StephanBeutel** [comment]
Hi,
ich hatte auch schon ein paar Mal das Problem.
Leider ist im Log nichts zu sehen.

Reproduzieren kann man es ganz einfach - einfach den Stecker ziehen (Strom trennen) ohne den Server vorher zu stoppen. Nach einem Neustart tritt das Problem aus.

**Comment by jansios** [comment]
Hallo Jens, ich hatte heute morgen um 07:34 Uhr leider einen ungeplanten Stromausfall und habe den selben Effekt wieder. Apple Home meldet, alle Geräte würde nicht antworten. Ich lasse nachts um 04:00 Uhr grundsätzlich ein Backup des gesamten ioBroker-Verzeichnisses machen mit gestoppten ioBroker. Nun lag die Vermutung nahe aufgrund der bisherigen Beobachtungen, dass der Fehler sich "innerhalb dieses Verzeichnisses" befindet und ich habe die Sicherung zurückgespielt - leider hat sich an der Situation nichts geändert, die Geräte antworten immer noch nicht. Ich kann Dir bei Bedarf mein komplettes ioBroker-Verzeichnis von nach dem Stromausfall zur Verfügung stellen, falls es Dir hilft.
Gibt es sonst etwas Neues zu dem Thema? Konntest Du den Effekt nachstellen?
Danke!
Gruß, Jan

**Comment by jensweigele** [comment]
Hi, 
mir fehlt im Moment leider die Zeit dieses Projekt zu betreuen. 
Bezüglich der Probleme: ich kann mir nur vorstellen, das die Yahka-Instanz quasi als "fehlerhaft" gekennzeichnet wird. Möglicherweise kann man diesen Fehlerzustand irgendwie auslösen. Hierzu müsste man aber wirklich analysieren was vor sich geht. Möglicherweise hilft auch einfach ein Update von hap-nodejs.
Vielleicht kann das jemand von der Community machen.

Grüße
 Jens

**Comment by StephanBeutel** [comment]
Hi, ich hatte jetzt mal wieder ein System down. Hab dann die beiden Dateien gelöscht und die Instanz neu gestartet. Die Dateien wurden wieder angelegt. 
Im iobroker log kann ich sehen, das die Instanz gestartet wurde und alle Geräte hinzugefügt wurden.
Leider sind diese trotzdem alle nicht erreichbar.

**Comment by jensweigele** [comment]
Kannst du mal VerboseLogging einschalten und Log-Level auf Debug stellen? (siehe https://github.com/jensweigele/ioBroker.yahka/issues/1#issuecomment-281510191)
