### ISSUE TITLE
Nach Update auf 0.9.1 werden Services teilweise nicht angezeigt

### ISSUE THREAD

**Issue by sharky-os** [jensweigele/ioBroker.yahka#100]
Habe von 0.9.0 auf 0.9.1 geupdatet, weil ich auch die Probleme mit dem Batterie Service hatte.
Nun funktioniert zwar alles, aber mir werden in der Adapterkonfig die Services teilweise nicht mehr angezeigt,
obwohl sie in Homekit immernoch vorhanden sind und ganz normal funkionieren. Ich kann auch keinen Zusammenhang erkennen, warum einige angezeigt werden und andere nicht.

Gruß Marco

**Comment by jensweigele** [comment]
Kannst du mal die Entwicklerkonsole im Browser aufmachen und schauen ob da Fehlermeldungen beim Öffnen des Admin-Interfaces erscheinen?

**Comment by sharky-os** [comment]
Hi Jens,
sorry kann es leider nicht mehr testen. Hab Deine Antwort zu spät gesehen und den Adapter mittlerweile neu aufgesetzt.
