### ISSUE TITLE
Using camera's stream without converting

### ISSUE THREAD

**Issue by Donderda** [jensweigele/ioBroker.yahka#101]
Hi, is it possible to use the IPCam's stream without the need of conversion? According to VLC, my Cameras are using these Codecs:

```
Codec: H264 - MPEG-4 AVC (part 10)
Resolution: 640x325
FPS: 20
Format: Planar 4:2:0 YUV
```

**Comment by nicoh88** [comment]
@Donderda Kann ich das Issue schließen? Du wirst den Stream immer durch `ffmpeg` jagen müssen, damit HomeKit ihn anzeigen kann.

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!
