### ISSUE TITLE
Dont work with iOS 12.1.4

### ISSUE THREAD

**Issue by amnesia106** [jensweigele/ioBroker.yahka#102]
since the last ios update, i cant add the "home" device. its not displayed.

**Comment by jensweigele** [comment]
It's working for me with iOS 12.1.4
Can you give us a more detailed explanation?
What is the "home" device??

**Comment by amnesia106** [comment]
i mean with "home" the bridge (adapter) 
- iPhone 5s works - iPhone 6 not - iPhone Xs not -
On the two last devices, the home app is the yahka bridge not displayed when i will add them.

**Comment by amnesia106** [comment]
I resolve the problem. On iPhone 5s i send my another devices a invite for the home bridge. Now it works with this workaround.

**Comment by jensweigele** [comment]
Looks like you are using different iCloud Accounts for the different devices.
A bridge may only be paired with one iCloud Account (apple restriction)

Is it true that you have multiple iCloud Accounts?

**Comment by amnesia106** [comment]
when i will add the bridge in the home app, and i dont see this, what does that have to do with the account?

**Comment by jensweigele** [comment]
Without answering to my questions I can't do further investigations.
Nevertheless: the problem is solved for you and nobody else mentioned problems with iOS 12.1.4.

Once somebody else has the problem again, please reopen or create a new ticket.
