### ISSUE TITLE
Error Yahka Adapter on QNAP Docker

### ISSUE THREAD

**Issue by HuboSky** [jensweigele/ioBroker.yahka#103]
Hi,
i installed iobroker into the docker on my qnap. Everything runs well, but the Yahka adapter don't want to work. 
I got following logs:
`host.QNAP	2019-03-01 20:35:11.675	error	instance system.adapter.yahka.0 terminated with code 1 ()
Caught	2019-03-01 20:35:11.675	error	by controller[0]: at /opt/iobroker/node_modules/iobroker.yahka/main.js:84:18
Caught	2019-03-01 20:35:11.675	error	by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
Caught	2019-03-01 20:35:11.675	error	by controller[0]: at Object../main.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:290:30)
Caught	2019-03-01 20:35:11.675	error	by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.yahka/main.js:271:17)
Caught	2019-03-01 20:35:11.675	error	by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
Caught	2019-03-01 20:35:11.675	error	by controller[0]: at Object../yahka.ioBroker-adapter.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:2139:16)
Caught	2019-03-01 20:35:11.675	error	by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
Caught	2019-03-01 20:35:11.675	error	by controller[0]: at Object../yahka.homekit-bridge.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:1577:25)
Caught	2019-03-01 20:35:11.675	error	by controller[0]: at Object.importHAPCommunityTypesAndFixes (/opt/iobroker/node_modules/iobroker.yahka/main.js:364:26)
Caught	2019-03-01 20:35:11.674	error	by controller[0]: at module.exports (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs-community-types/types.js:856:45)
Caught	2019-03-01 20:35:11.674	error	by controller[0]: TypeError: Cannot read property 'generate' of undefined
Caught	2019-03-01 20:35:11.674	error	by controller[0]: ^
Caught	2019-03-01 20:35:11.674	error	by controller[0]: CommunityTypes.InputVoltageAC.UUID = UUID.generate('CommunityTypes:usagedevice:InputVoltageAC');
Caught	2019-03-01 20:35:11.674	error	by controller[0]: /opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs-community-types/types.js:856
host.QNAP	2019-03-01 20:34:43.221	info	object change system.adapter.yahka.0`
Hope you can help me.
Thanks a lot!
Brgds
Bernd

**Comment by captaindork** [comment]
I know it does not really answer your question, but i have installed it inside an LXC Container on QNAP and it this runs for some Months quite well... if that is an option...

**Comment by HuboSky** [comment]
thanks! i will check that possibilitiy in the meantime.

**Comment by HuboSky** [comment]
i just searched for an guide to to that, cause i'm quite new in linux an docker and all this stuff. do you have a guide how to install debian lxc container on the qnap?? something to mount like the docker folders? thanks again!

**Comment by captaindork** [comment]
Actually i just installed the latest ubuntu and well i only mounted a NAS folder for Backups, not the opt/iobroker itself. You could for sure do that as well, but i would say that’s really personal preference and a matter of how your „backup/restore strategy“ looks like. Actually you do not need to mount anything to make it work. For install you can then use the normal iobroker guides. 
You probably need to choose „bridged networking“ for the container. Did you configure this for your docker container? ... maybe that’s your issue...

**Comment by HuboSky** [comment]
i tried that yesterday evening, same issue.
I installed the LXC Debian on my qnap docker, without mounting any folder.
But i want to do that, cause of the backups.
I think, the network ist not the problem. I had issues regarding with the network, so i learned and tested a lot if this is the problem. I installed already a few adapters, Logitech Harmony, Xaiomi Roborock and alle are orking well, only the Yahka Adapter don't want to work.

**Comment by captaindork** [comment]
I personally believe it is not because of the shares. Network in my Opinion must be Bridge (not NAT). As you tested both, I don‘t feel I am of great help. I guess the DEVs will need to have a look at your logs, as you initially posted.

**Comment by HuboSky** [comment]
i hope that somebody will help me, cause i bouht a raspberry today, to split the smarthome center from the nas. everything installed and i got the same issue with this adapter on the raspberry.

> 

host.raspberrypi | 2019-03-02 16:13:19.546 | error | instance system.adapter.yahka.0 terminated with code 1 ()
-- | -- | -- | --
host.raspberrypi | 2019-03-02 16:13:19.546 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.yahka/main.js:84:18
host.raspberrypi | 2019-03-02 16:13:19.546 | error | Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
host.raspberrypi | 2019-03-02 16:13:19.546 | error | Caught by controller[0]: at Object../main.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:290:30)
host.raspberrypi | 2019-03-02 16:13:19.546 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.yahka/main.js:271:17)
host.raspberrypi | 2019-03-02 16:13:19.546 | error | Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
host.raspberrypi | 2019-03-02 16:13:19.546 | error | Caught by controller[0]: at Object../yahka.ioBroker-adapter.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:2326:16)
host.raspberrypi | 2019-03-02 16:13:19.545 | error | Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
host.raspberrypi | 2019-03-02 16:13:19.545 | error | Caught by controller[0]: at Object../yahka.homekit-bridge.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:1764:25)
host.raspberrypi | 2019-03-02 16:13:19.545 | error | Caught by controller[0]: at Object.importHAPCommunityTypesAndFixes (/opt/iobroker/node_modules/iobroker.yahka/main.js:382:26)
host.raspberrypi | 2019-03-02 16:13:19.545 | error | Caught by controller[0]: at module.exports (/opt/iobroker/node_modules/hap-nodejs-community-types/types.js:856:45)
host.raspberrypi | 2019-03-02 16:13:19.545 | error | Caught by controller[0]: TypeError: Cannot read property 'generate' of undefined
host.raspberrypi | 2019-03-02 16:13:19.545 | error | Caught by controller[0]: ^
host.raspberrypi | 2019-03-02 16:13:19.545 | error | Caught by controller[0]: CommunityTypes.InputVoltageAC.UUID = UUID.generate('CommunityTypes:usagedevice:InputVoltageAC');
host.raspberrypi | 2019-03-02 16:13:19.544 | error | Caught by controller[0]: /opt/iobroker/node_modules/hap-nodejs-community-types/types.js:856
host.raspberrypi | 2019-03-02 16:13:18.745 | info | instance system.adapter.yahka.0 started with pid 2067

the only installation in which the adapter is running without problems ist in my virtualbox with debian in my windows 10 pc. 
so, pls heeeeeelllllppppp!!
Brgds
Bernd

**Comment by dnguyenlong** [comment]
> i hope that somebody will help me, cause i bouht a raspberry today, to split the smarthome center from the nas. everything installed and i got the same issue with this adapter on the raspberry.
> 
> > 
> 
> host.raspberrypi	2019-03-02 16:13:19.546	error	instance system.adapter.yahka.0 terminated with code 1 ()
> host.raspberrypi	2019-03-02 16:13:19.546	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.yahka/main.js:84:18
> host.raspberrypi	2019-03-02 16:13:19.546	error	Caught by controller[0]: at **webpack_require** (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
> host.raspberrypi	2019-03-02 16:13:19.546	error	Caught by controller[0]: at Object../main.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:290:30)
> host.raspberrypi	2019-03-02 16:13:19.546	error	Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.yahka/main.js:271:17)
> host.raspberrypi	2019-03-02 16:13:19.546	error	Caught by controller[0]: at **webpack_require** (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
> host.raspberrypi	2019-03-02 16:13:19.546	error	Caught by controller[0]: at Object../yahka.ioBroker-adapter.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:2326:16)
> host.raspberrypi	2019-03-02 16:13:19.545	error	Caught by controller[0]: at **webpack_require** (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
> host.raspberrypi	2019-03-02 16:13:19.545	error	Caught by controller[0]: at Object../yahka.homekit-bridge.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:1764:25)
> host.raspberrypi	2019-03-02 16:13:19.545	error	Caught by controller[0]: at Object.importHAPCommunityTypesAndFixes (/opt/iobroker/node_modules/iobroker.yahka/main.js:382:26)
> host.raspberrypi	2019-03-02 16:13:19.545	error	Caught by controller[0]: at module.exports (/opt/iobroker/node_modules/hap-nodejs-community-types/types.js:856:45)
> host.raspberrypi	2019-03-02 16:13:19.545	error	Caught by controller[0]: TypeError: Cannot read property 'generate' of undefined
> host.raspberrypi	2019-03-02 16:13:19.545	error	Caught by controller[0]: ^
> host.raspberrypi	2019-03-02 16:13:19.545	error	Caught by controller[0]: CommunityTypes.InputVoltageAC.UUID = UUID.generate('CommunityTypes:usagedevice:InputVoltageAC');
> host.raspberrypi	2019-03-02 16:13:19.544	error	Caught by controller[0]: /opt/iobroker/node_modules/hap-nodejs-community-types/types.js:856
> host.raspberrypi	2019-03-02 16:13:18.745	info	instance system.adapter.yahka.0 started with pid 2067
> the only installation in which the adapter is running without problems ist in my virtualbox with debian in my windows 10 pc.
> so, pls heeeeeelllllppppp!!
> Brgds
> Bernd

#104 #105 not solved yet :(

**Comment by HuboSky** [comment]
sad to read that, but also happy about your answer, cause now i know version 8.2 is running, til the solution. thanks, dnguyenlong!

**Comment by jensweigele** [comment]
Did you have any errors while installing the adapter?

**Comment by devilbes** [comment]
> Did you have any errors while installing the adapter?

no

**Comment by HuboSky** [comment]
installation runs without error.
