### ISSUE TITLE
Error on Yahka 0.9.1 and 0.9.0

### ISSUE THREAD

**Issue by hilde0407** [jensweigele/ioBroker.yahka#105]
My Adapter crash with error:

host.volker-BT3-Pro | 2019-03-02 21:43:04.193 | error | instance system.adapter.yahka.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2019-03-02 21:43:04.193 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.yahka/main.js:84:18
Caught | 2019-03-02 21:43:04.193 | error | by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
Caught | 2019-03-02 21:43:04.193 | error | by controller[0]: at Object../main.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:290:30)
Caught | 2019-03-02 21:43:04.193 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.yahka/main.js:271:17)
Caught | 2019-03-02 21:43:04.193 | error | by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
Caught | 2019-03-02 21:43:04.193 | error | by controller[0]: at Object../yahka.ioBroker-adapter.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:2326:16)
Caught | 2019-03-02 21:43:04.193 | error | by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
Caught | 2019-03-02 21:43:04.193 | error | by controller[0]: at Object../yahka.homekit-bridge.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:1764:25)
Caught | 2019-03-02 21:43:04.192 | error | by controller[0]: at Object.importHAPCommunityTypesAndFixes (/opt/iobroker/node_modules/iobroker.yahka/main.js:382:26)
Caught | 2019-03-02 21:43:04.192 | error | by controller[0]: at module.exports (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs-community-types/types.js:856:45)
Caught | 2019-03-02 21:43:04.192 | error | by controller[0]: TypeError: Cannot read property 'generate' of undefined
Caught | 2019-03-02 21:43:04.192 | error | by controller[0]: ^
Caught | 2019-03-02 21:43:04.192 | error | by controller[0]: CommunityTypes.InputVoltageAC.UUID = UUID.generate('CommunityTypes:usagedevice:InputVoltageAC');
Caught | 2019-03-02 21:43:04.192 | error | by controller[0]: /opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs-community-types/types.js:856
host.volker-BT3-Pro | 2019-03-02 21:43:03.536 | info | instance system.adapter.yahka.0 started with pid 9649

On version 0.8.2 adapter works!

Please help!

**Comment by dnguyenlong** [comment]
Habe das gleiche Problem mit 0.9.1. Bei 0.7.1 jedoch das gleiche.

**Comment by HuboSky** [comment]
bei mir auch und dank eurer posts, läuft zumindest mal 8.2!

**Comment by darkbrain85** [comment]
Hier ebenfalls kein Start nach dem Update auf 0.9.0 oder 0.9.1. 



2019-03-03 21:38:55.237 - error: Caught by controller[0]: /opt/iobroker/node_modules/hap-nodejs-community-types/types.js:856
--
2019-03-03 21:38:55.237 - error: Caught by controller[0]: CommunityTypes.InputVoltageAC.UUID = UUID.generate('CommunityTypes:usagedevice:InputVoltageAC');
2019-03-03 21:38:55.237 - error: Caught by controller[0]: ^
2019-03-03 21:38:55.237 - error: Caught by controller[0]: TypeError: Cannot read property 'generate' of undefined
2019-03-03 21:38:55.237 - error: Caught by controller[0]: at module.exports (/opt/iobroker/node_modules/hap-nodejs-community-types/types.js:856:45)
2019-03-03 21:38:55.237 - error: Caught by controller[0]: at Object.importHAPCommunityTypesAndFixes (/opt/iobroker/node_modules/iobroker.yahka/main.js:382:26)
2019-03-03 21:38:55.237 - error: Caught by controller[0]: at Object../yahka.homekit-bridge.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:1764:25)
2019-03-03 21:38:55.237 - error: Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
2019-03-03 21:38:55.237 - error: Caught by controller[0]: at Object../yahka.ioBroker-adapter.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:2326:16)
2019-03-03 21:38:55.237 - error: Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
2019-03-03 21:38:55.237 - error: Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.yahka/main.js:271:17)
2019-03-03 21:38:55.237 - error: Caught by controller[0]: at Object../main.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:290:30)
2019-03-03 21:38:55.237 - error: Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
2019-03-03 21:38:55.237 - error: Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.yahka/main.js:84:18
2019-03-03 21:38:55.237 - error: host.debian instance system.adapter.yahka.0 terminated with code 1 ()

**Comment by jensweigele** [comment]
Irgendwas stimmt bei euch mit der UUID Bibliothek nicht.
Gab es Fehler bei der Installation oder beim Update?

**Comment by DavidPasch** [comment]
Nö, sieht gut aus.

$ ./iobroker add yahka  --host iobroker
NPM version: 6.4.1
npm install iobroker.yahka --production --save --prefix "/opt/iobroker" (System call)
host.iobroker install adapter yahka
got /opt/iobroker/node_modules/iobroker.yahka/admin
upload [19] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.png yahka.png image/png
upload [18] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js.map yahka.admin.js.map application/json
upload [17] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js yahka.admin.js application/javascript
upload [16] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/words.js words.js application/javascript
upload [15] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index_m.html index_m.html text/html
upload [14] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index.html index.html text/html
upload [13] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/home_icon_large.png home_icon_large.png image/png
upload [12] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/js/metro.min.js ext/metroui/js/metro.min.js application/javascript
upload [11] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/selection.json ext/metroui/fonts/selection.json application/json
upload [10] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.woff ext/metroui/fonts/metro.woff application/font-woff
upload [9] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.ttf ext/metroui/fonts/metro.ttf application/x-font-ttf
upload [8] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.svg ext/metroui/fonts/metro.svg image/svg+xml
upload [7] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.eot ext/metroui/fonts/metro.eot application/vnd.ms-fontobject
upload [6] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro.min.css ext/metroui/css/metro.min.css text/css
upload [5] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-schemes.min.css ext/metroui/css/metro-schemes.min.css text/css
upload [4] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-rtl.min.css ext/metroui/css/metro-rtl.min.css text/css
upload [3] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-responsive.min.css ext/metroui/css/metro-responsive.min.css text/css
upload [2] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-icons.min.css ext/metroui/css/metro-icons.min.css text/css
upload [1] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-colors.min.css ext/metroui/css/metro-colors.min.css text/css
upload [0] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/css/yahka.admin.css css/yahka.admin.css text/css
host.iobroker object system.adapter.yahka created
host.iobroker object yahka.meta._accessoryCategories created
host.iobroker create instance yahka
host.iobroker object system.adapter.yahka.0.outputCount created
host.iobroker object system.adapter.yahka.0.inputCount created
host.iobroker object system.adapter.yahka.0.uptime created
host.iobroker object system.adapter.yahka.0.memRss created
host.iobroker object system.adapter.yahka.0.memHeapTotal created
host.iobroker object system.adapter.yahka.0.memHeapUsed created
host.iobroker object system.adapter.yahka.0.connected created
host.iobroker object system.adapter.yahka.0.alive created
host.iobroker object system.adapter.yahka.0 created
process exited with code 0

**Comment by darkbrain85** [comment]
Kann ich bestätigen! Installation läuft normal durch!

**Comment by DavidPasch** [comment]
Vll. was mit dem LXC Container zu tun? Auf meiner VM läufts, auf den LXC nicht.

**Comment by captaindork** [comment]
Bei mir läuft 0.9.1 in LXC (seit die Version erschienen ist).
Ich habe jetzt nicht nochmal gelöscht/neuinstalliert oder sowas. Aber bei mir ist’s stabil mit >100 Geräten. Denke also nicht dass es an LXC „generell“ liegt

**Comment by DavidPasch** [comment]
Habe seit gestern mehrfach nen LXC neu aufgesetzt (Debian) mit sauberen iobroker Installationen. Jedes mal das "generate" Problem bei yahka.

**Comment by Dommoe** [comment]
Moin zusammen,

ich habe das gleiche Problem. 
Meine Installation ist auf einem Raspberry Pi.
Habe am Wochenende mehrmals das komplette System neu installiert.

**Comment by darkbrain85** [comment]
Hier ist es Debian 9 in einer ESXi VM. Scheint also unabhängig von Containern zu sein...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hilde0407** [comment]
Einen Tag später, noch einmal versucht, den Adapter auf die neuste Version zu bringen ... läuft! Keine Ahnung warum! Ich habe keine Updates installiert, noch irgend etwas verändert. Installiert habe ich den Adapter über Github.

**Comment by hilde0407** [comment]
Nach einem Neustart des Servers, leider der selbe Fehler!

**Comment by dnguyenlong** [comment]
Nach etlichen De- und Neuinstallation sowie Updates habe ich nun die Version 8.2 installiert, die @HuboSky erwähnt hat. Bridge läuft und alle Geräte sind vorhanden. Läuft sogar besser als meine vorherige Homebridge. Sobald positive Updates zu diesem Issue folgen, werde ich die Version dementsprechend updaten. Ansonsten never change a running system. :)

**Comment by peterbaumert** [comment]
Hab es auf nem debian laufen, alles aktuell und gleiches problem. npm rebuild hat auch nicht geholfen nur der downgrade auf die 0.8.2

**Comment by DavidPasch** [comment]
Habs aus'm GitHup geupdated - nachdem Peter wohl die Lösung fand. Läuft nun problemlos auf 0.9.1!

**Comment by hilde0407** [comment]
Kann ich leider nicht bestätigen! Von GitHub update durchgeführt! Fehler:

`

host.volker-BT3-Pro | 2019-03-09 17:16:51.998 | info | Restart adapter system.adapter.yahka.0 because enabled
-- | -- | -- | --
host.volker-BT3-Pro | 2019-03-09 17:16:51.998 | error | instance system.adapter.yahka.0 terminated with code 1 ()
host.volker-BT3-Pro | 2019-03-09 17:16:51.998 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.yahka/main.js:84:18
host.volker-BT3-Pro | 2019-03-09 17:16:51.998 | error | Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
host.volker-BT3-Pro | 2019-03-09 17:16:51.997 | error | Caught by controller[0]: at Object../main.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:290:30)
host.volker-BT3-Pro | 2019-03-09 17:16:51.997 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.yahka/main.js:271:17)
host.volker-BT3-Pro | 2019-03-09 17:16:51.997 | error | Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
host.volker-BT3-Pro | 2019-03-09 17:16:51.997 | error | Caught by controller[0]: at Object../yahka.ioBroker-adapter.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:2326:16)
host.volker-BT3-Pro | 2019-03-09 17:16:51.997 | error | Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
host.volker-BT3-Pro | 2019-03-09 17:16:51.997 | error | Caught by controller[0]: at Object../yahka.homekit-bridge.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:1764:25)
host.volker-BT3-Pro | 2019-03-09 17:16:51.997 | error | Caught by controller[0]: at Object.importHAPCommunityTypesAndFixes (/opt/iobroker/node_modules/iobroker.yahka/main.js:382:26)
host.volker-BT3-Pro | 2019-03-09 17:16:51.997 | error | Caught by controller[0]: at module.exports (/opt/iobroker/node_modules/hap-nodejs-community-types/types.js:920:45)
host.volker-BT3-Pro | 2019-03-09 17:16:51.997 | error | Caught by controller[0]: TypeError: Cannot read property 'generate' of undefined
host.volker-BT3-Pro | 2019-03-09 17:16:51.996 | error | Caught by controller[0]: ^
host.volker-BT3-Pro | 2019-03-09 17:16:51.996 | error | Caught by controller[0]: CommunityTypes.InputVoltageAC.UUID = UUID.generate('CommunityTypes:usagedevice:InputVoltageAC');
host.volker-BT3-Pro | 2019-03-09 17:16:51.996 | error | Caught by controller[0]: /opt/iobroker/node_modules/hap-nodejs-community-types/types.js:920
host.volker-BT3-Pro | 2019-03-09 17:16:51.365 | info | instance system.adapter.yahka.0 started with pid 19813
host.volker-BT3-Pro | 2019-03-09 17:16:21.333 | info | Restart adapter system.adapter.yahka.0 because enabled

`

**Comment by DavidPasch** [comment]
@hilde0407 Mach noch mal in der Admin-Ansicht der Adapter nen "Upload".

**Comment by Dommoe** [comment]
Moin zusammen,

mit welchem Link habt ihr das Update gemacht?
Ich habe mit dem Link:
https://github.com/jensweigele/ioBroker.yahka.git
das Update gemacht aber leider läuft dann nichts.
Vielen Dank für die Hilfe, bin neu bei GitHub :)

**Comment by DavidPasch** [comment]
Soweit auch richtig. Dann aber in der Adapter-Ansicht in den Expertenmodus schalten (oben, die blauen Kreise, der letzte mit Person in nem Ordner Symbol) und dann beim Adapter Homekit hinten den Pfeil nach oben klicken.

**Comment by Dommoe** [comment]
Danke für deine Antwort.
Hab ich gemacht geht leider immer noch nicht.
`

host.raspberrypi | 2019-03-09 20:05:45.178 | error | instance system.adapter.yahka.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2019-03-09 20:05:45.178 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.yahka/main.js:84:18
Caught | 2019-03-09 20:05:45.178 | error | by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
Caught | 2019-03-09 20:05:45.178 | error | by controller[0]: at Object../main.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:290:30)
Caught | 2019-03-09 20:05:45.178 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.yahka/main.js:271:17)
Caught | 2019-03-09 20:05:45.178 | error | by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
Caught | 2019-03-09 20:05:45.178 | error | by controller[0]: at Object../yahka.ioBroker-adapter.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:2326:16)
Caught | 2019-03-09 20:05:45.178 | error | by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
Caught | 2019-03-09 20:05:45.177 | error | by controller[0]: at Object../yahka.homekit-bridge.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:1764:25)
Caught | 2019-03-09 20:05:45.177 | error | by controller[0]: at Object.importHAPCommunityTypesAndFixes (/opt/iobroker/node_modules/iobroker.yahka/main.js:382:26)
Caught | 2019-03-09 20:05:45.177 | error | by controller[0]: at module.exports (/opt/iobroker/node_modules/hap-nodejs-community-types/types.js:920:45)
Caught | 2019-03-09 20:05:45.177 | error | by controller[0]: TypeError: Cannot read property 'generate' of undefined
Caught | 2019-03-09 20:05:45.177 | error | by controller[0]: ^
Caught | 2019-03-09 20:05:45.177 | error | by controller[0]: CommunityTypes.InputVoltageAC.UUID = UUID.generate('CommunityTypes:usagedevice:InputVoltageAC');
Caught | 2019-03-09 20:05:45.176 | error | by controller[0]: /opt/iobroker/node_modules/hap-nodejs-community-types/types.js:920
host.raspberrypi | 2019-03-09 20:05:43.502 | info | instance system.adapter.yahka.0 started with pid 9499

`

**Comment by DavidPasch** [comment]
Hmmm... hab nix anderes gemacht. Vll. 2x hintereinander, aber sonst nichts besonderes.

**Comment by JanOleBrode** [comment]
@DavidPasch: Der Pull Request wurde noch nicht in Master gemerged. Die Änderung ist also nur wirksam wenn man sich den PR lokal patcht, oder wie bist du vorgegangen?

**Comment by DavidPasch** [comment]
Ich hab ernsthaft nur die URL vom grünen Button genommen, in iobroker den install from github Button genommen, URL rein kopiert, installieren lassen und in der Adapter-Ansicht den Upload-Pfeil geklickt.

Ich mach mal nen Restart, nicht das da irgendwas durch "Zufall" funktioniert.

**Comment by DavidPasch** [comment]
Okay... da muß er sich verschluckt haben. Fehler wieder da ... so wie @hilde0407 oben beschrieben hat, mist ...

**Comment by Hubobel** [comment]
nach einem Server-Reboot (Debian 9) will der Adapter bei mir auch nicht....

**Comment by jensweigele** [comment]
Der Pull-Request ist nun gemerged. Probiert bitte nochmal die Installation via GitHub.

**Comment by hilde0407** [comment]
Habe den Adapter komplett gelöscht und über GitHub erneut installiert, leider der selbe Fehler!
`

host.volker-BT3-Pro | 2019-03-09 21:03:13.021 | info | Restart adapter system.adapter.yahka.0 because enabled
-- | -- | -- | --
host.volker-BT3-Pro | 2019-03-09 21:03:13.016 | error | instance system.adapter.yahka.0 terminated with code 1 ()
host.volker-BT3-Pro | 2019-03-09 21:03:13.016 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.yahka/main.js:84:18
host.volker-BT3-Pro | 2019-03-09 21:03:13.016 | error | Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
host.volker-BT3-Pro | 2019-03-09 21:03:13.016 | error | Caught by controller[0]: at Object../main.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:290:30)
host.volker-BT3-Pro | 2019-03-09 21:03:13.016 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.yahka/main.js:271:17)
host.volker-BT3-Pro | 2019-03-09 21:03:13.016 | error | Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
host.volker-BT3-Pro | 2019-03-09 21:03:13.016 | error | Caught by controller[0]: at Object../yahka.ioBroker-adapter.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:2326:16)
host.volker-BT3-Pro | 2019-03-09 21:03:13.016 | error | Caught by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
host.volker-BT3-Pro | 2019-03-09 21:03:13.015 | error | Caught by controller[0]: at Object../yahka.homekit-bridge.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:1764:25)
host.volker-BT3-Pro | 2019-03-09 21:03:13.015 | error | Caught by controller[0]: at Object.importHAPCommunityTypesAndFixes (/opt/iobroker/node_modules/iobroker.yahka/main.js:382:26)
host.volker-BT3-Pro | 2019-03-09 21:03:13.015 | error | Caught by controller[0]: at module.exports (/opt/iobroker/node_modules/hap-nodejs-community-types/types.js:920:45)
host.volker-BT3-Pro | 2019-03-09 21:03:13.015 | error | Caught by controller[0]: TypeError: Cannot read property 'generate' of undefined
host.volker-BT3-Pro | 2019-03-09 21:03:13.015 | error | Caught by controller[0]: ^
host.volker-BT3-Pro | 2019-03-09 21:03:13.015 | error | Caught by controller[0]: CommunityTypes.InputVoltageAC.UUID = UUID.generate('CommunityTypes:usagedevice:InputVoltageAC');
host.volker-BT3-Pro | 2019-03-09 21:03:13.014 | error | Caught by controller[0]: /opt/iobroker/node_modules/hap-nodejs-community-types/types.js:920
host.volker-BT3-Pro | 2019-03-09 21:03:12.404 | info | instance system.adapter.yahka.0 started with pid 26713

`

**Comment by DavidPasch** [comment]
Same here ... same problem.

**Comment by HuboSky** [comment]
Kurze Frage, bleiben die bereits eingerichteten Geräte im Yahka erhalten, wenn man mit verschiedenen Updates bzw. Versionen testet?

**Comment by hilde0407** [comment]
Normalerweise ja! Bei mir war es der Falle, dass meine Einstellungen weg waren, als ich den Upload Button getätigt habe.

**Comment by HuboSky** [comment]
Ob ich mir das antun will, vor allem da die positiven Berichte eher in der Minderheit sind. 
Gibt es denn schon eine allgemein, funktionierende Lösung?

**Comment by Hubobel** [comment]
Also ich bin erst einmal zurück auf 0.8.2....und das läuft ohne Probleme.

**Comment by jensweigele** [comment]
Status: Ich kann den Fehler nun auf meinem Mac mit einer neue ioBroker Instanz reproduzieren. Ich untersuche den Fehler jetzt.
 
Status: I'm able to reproduce the issue on my mac with a newly installed ioBroker instance. I'm investigating now.

**Comment by joerghildering** [comment]
Bei mir läufts auch nur mit 0.8.2. ioBroker läuft bei mir auf einer Proxmox VM

**Comment by jensweigele** [comment]
Kann jemand von euch mal bitte mit dem aktuellen Master testen?

**Comment by DavidPasch** [comment]
Sieht gut aus. Läuft nach update, läuft nach Neustart. LXC Container auf Proxmox auf Intel NUC.

**Comment by hilde0407** [comment]
Kann ich bestätigen! Der Adapter läuft!

**Comment by jensweigele** [comment]
Version 0.9.2 ist nun auf NPM veröffentlicht

**Comment by HuboSky** [comment]
Yihaa! Version 0.9.2 läuft ohne Fehler!!!
