### ISSUE TITLE
Keine Installation möglich 

### ISSUE THREAD

**Issue by nickenick98** [jensweigele/ioBroker.yahka#106]
wenn ich die 9.1 installieren möchte sagt es mir das ein Binary Datei fehlen

**Comment by peterbaumert** [comment]
hatte ich auch, bei mir hat git gefehlt.
apt install git
eventuell ist es bei dir das selbe

**Comment by schmdt** [comment]
Vielleicht kannst du sagen, welches Binary genau fehlt? Oder die komplette Fehlermeldung zeigen?

**Comment by nickenick98** [comment]
$ ./iobroker upgrade yahka
Update yahka from @0.8.1 to @0.9.1
NPM version: 6.5.0
npm install iobroker.yahka@0.9.1 --production --save --prefix "/opt/iobroker" (System call)
npm
 ERR! code ENOGIT
npm 
ERR! Error while executing:npm ERR! undefined ls-remote -h -t https://github.com/homespun/hap-nodejs-community-types.git

npm ERR! npm ERR!
 undefinednpm ERR! No git binary found in $PATH
npm
 ERR! npm ERR! Failed using git.

npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:npm ERR!     /root/.npm/_logs/2019-03-05T16_29_32_183Z-debug.log

npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.yahka"
got /opt/iobroker/node_modules/iobroker.yahka/admin
upload [19] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.png yahka.png image/png
upload [18] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js.map yahka.admin.js.map application/json
upload [17] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js yahka.admin.js application/javascript
upload [16] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/words.js words.js application/javascript
upload [15] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index_m.html index_m.html text/html
upload [14] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index.html index.html text/html
upload [13] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/home_icon_large.png home_icon_large.png image/png
upload [12] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/js/metro.min.js ext/metroui/js/metro.min.js application/javascript
upload [11] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/selection.json ext/metroui/fonts/selection.json application/json
upload [10] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.woff ext/metroui/fonts/metro.woff font/woff
upload [9] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.ttf ext/metroui/fonts/metro.ttf font/ttf
upload [8] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.svg ext/metroui/fonts/metro.svg image/svg+xml
upload [7] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.eot ext/metroui/fonts/metro.eot application/vnd.ms-fontobject
upload [6] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro.min.css ext/metroui/css/metro.min.css text/css
upload [5] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-schemes.min.css ext/metroui/css/metro-schemes.min.css text/css
upload [4] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-rtl.min.css ext/metroui/css/metro-rtl.min.css text/css
upload [3] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-responsive.min.css ext/metroui/css/metro-responsive.min.css text/css
upload [2] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-icons.min.css ext/metroui/css/metro-icons.min.css text/css
upload [1] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-colors.min.css ext/metroui/css/metro-colors.min.css text/css
upload [0] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/css/yahka.admin.css css/yahka.admin.css text/css
Adapter "yahka" updated
process exited with code 0

**Comment by schmdt** [comment]
No git binary found

Dann hat Peter recht. Dir fehlt git, dass müsstest du installieren.

**Comment by jensweigele** [comment]
Ich schließe das Ticket.
Nach dem installieren von git, wird es dir vermutlich ergehen wie allen anderen -> #105

**Comment by jensweigele** [comment]
Mit dem aktuellen Master sollte die Git Installation nichtmehr notwendig sein
