### ISSUE TITLE
Adapter version 0.9.1 not starting!

### ISSUE THREAD

**Issue by Mr-REM-Esq** [jensweigele/ioBroker.yahka#111]
host.iobroker | 2019-03-11 13:57:52.766 | error | instance system.adapter.yahka.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2019-03-11 13:57:52.766 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.yahka/main.js:84:18
Caught | 2019-03-11 13:57:52.766 | error | by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
Caught | 2019-03-11 13:57:52.766 | error | by controller[0]: at Object../main.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:290:30)
Caught | 2019-03-11 13:57:52.766 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.yahka/main.js:271:17)
Caught | 2019-03-11 13:57:52.765 | error | by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
Caught | 2019-03-11 13:57:52.765 | error | by controller[0]: at Object../yahka.ioBroker-adapter.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:2326:16)
Caught | 2019-03-11 13:57:52.765 | error | by controller[0]: at __webpack_require__ (/opt/iobroker/node_modules/iobroker.yahka/main.js:20:30)
Caught | 2019-03-11 13:57:52.765 | error | by controller[0]: at Object../yahka.homekit-bridge.ts (/opt/iobroker/node_modules/iobroker.yahka/main.js:1764:25)
Caught | 2019-03-11 13:57:52.765 | error | by controller[0]: at Object.importHAPCommunityTypesAndFixes (/opt/iobroker/node_modules/iobroker.yahka/main.js:382:26)
Caught | 2019-03-11 13:57:52.765 | error | by controller[0]: at module.exports (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs-community-types/types.js:920:45)
Caught | 2019-03-11 13:57:52.764 | error | by controller[0]: TypeError: Cannot read property 'generate' of undefined
Caught | 2019-03-11 13:57:52.764 | error | by controller[0]: ^
Caught | 2019-03-11 13:57:52.764 | error | by controller[0]: CommunityTypes.InputVoltageAC.UUID = UUID.generate('CommunityTypes:usagedevice:InputVoltageAC');
Caught | 2019-03-11 13:57:52.764 | error | by controller[0]: /opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs-community-types/types.js:920

**Comment by joerghildering** [comment]
Same to me. The last working version is 0.8.2. The newer versions doesn't start after upgrade.

**Comment by jensweigele** [comment]
further discussions in #105
