### ISSUE TITLE
Zugriff per VPN?

### ISSUE THREAD

**Issue by joerghildering** [jensweigele/ioBroker.yahka#112]
Besteht irgendwie die Möglichkeit die Home App auf dem iPhone ohne eine Apple Steuerzentrale(iPad, iPod, TV) per VPN zu nutzen?

**Comment by Baenker** [comment]
das lässt Apple nicht zu

**Comment by jensweigele** [comment]
Ich bin mir nicht sicher.
Die Steuerzentrale ist nur für die Automation und den Remote-Zugriff über die iCloud notwendig.
Technisch gesehen sollte es meiner Meinung nach möglich sein, sich per VPN mit der Bridge zu verbinden.
Käme auf einen Versuch an.

**Comment by joerghildering** [comment]
Ich hätte auch gedacht das es sich mit einer VPN Verbindung genauso verhalten sollte als wenn man im lokalen Netz ist. Ist leider nicht der Fall. Die Geräte werden alle in der Home App als offline angezeigt

**Comment by Baenker** [comment]
Ich bin mir da relativ sicher das es nicht geht. Warum sollte Apple so etwas zulassen? Apple hat einen sicheren Weg bereit gestellt. Mein Sonos System kann ich per Sonos App auch nicht steuern wenn ich mich per VPN verbinde. Was ja eigentlich auch Quatsch ist aber Firmen neigen dazu den Käufer zu bevormunden. Es ist auf jeden Fall kein Problem vom Adapter sondern ein generelles Problem welches nur Apple lösen kann. Meine Hue-Lampen über die Hue-Bridge direkt mit Homekit verknüpft funktionieren genauso wenig wie die Geäte die per Yahka angebunden sind oder wie die Geräte die früher per Homebrige angebunden waren.
