### ISSUE TITLE
Camera Stream does not work anymore

### ISSUE THREAD

**Issue by DanielWeeber** [jensweigele/ioBroker.yahka#113]
Hey, 

strangely the camera live stream does not work anymore.
Getting the instant screenshot is working fine, but when I click on any cam its not working anymore.

I had to use a different interface than eth0 in the configuration if that makes any difference. It was working like that one or two versions ago

//edit: In debug mode I only see the executed command. No error messages or anything like that

ffmpeg -re -i rtsp://admin:password@192.168.0.7:554/live/ch1 -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 25 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params S1fRRsyvl2L4cka13ISXwqvdmRYUOE+nfmZURY3I srtp://192.168.1.105:52511?rtcpport=52511&localrtcpport=52511&pkt_size=1378

//edit: Cannot test the old versions anymore, because of the same error as described here:
https://forum.iobroker.net/topic/20545/yahka-homekit-0-9-1-startet-nicht/7
//edit2: After I upgraded again to 0.9.2, because the test with 0.9.0 did not work, it is working again

**Comment by nicoh88** [comment]
> After I upgraded again to 0.9.2, because the test with 0.9.0 did not work, it is working again
