### ISSUE TITLE
The values from the app home do not come accurate.

### ISSUE THREAD

**Issue by Anzic23** [jensweigele/ioBroker.yahka#114]
on the version of the program 0,9,2 values which are set in the home come in IoBroker shift. For example, I send the value of the thermostat 13, 13,2 or 12,8 returns to the IoBroker. If am running 15.5 returns 15.7.

**Comment by DanielWeeber** [comment]
Cannot confirm this. Also I would like to recommend setting minStep via properties to 0.5. Noone needs a 1/100th temperature setting in my opinion.

**Comment by Anzic23** [comment]
minStep via properties to 0.5 solve the problem.
