### ISSUE TITLE
Feature request: Push Notifications

### ISSUE THREAD

**Issue by moritzabcde** [jensweigele/ioBroker.yahka#115]
Is there any chance to add push notification to the Home App? I would really like to add notifications like "Close the windows, it's cold outside" or similar as a service to my devices.
Thank you!

**Comment by jensweigele** [comment]
Not possible via Yahka.
But there are different services on the internet which could help you (e.g. https://ifttt.com)

**Comment by moritzabcde** [comment]
Hey Jens!
Could you write a few words why it's not possible. Is this a restriction by apple?
Thank you!

**Comment by Donderda** [comment]
@moritzabcde this kind of notification is already possible. You have to configure it in your home app.

**Comment by moritzabcde** [comment]
I allowed sending notifications for some of my adapters, if that's what you mean. I can't find any documentation or the instance of yahka itself about this. Could you just give me a few hints on what I should google? Thank you!

**Comment by Donderda** [comment]
Well - if I activate notification e.g. on my door / window sensors, I get a notification when it's opened. Same for my garage door opener. What's your problem?

**Comment by moritzabcde** [comment]
For example: I'd like to send a custom notification from temperature sensor that tells me "It's colder inside than outside, you might consider to close the windows".
Did you configure Yahka to send you the notifications? Are they like the ones from the link above?
