### ISSUE TITLE
Wind speed

### ISSUE THREAD

**Issue by DocUltra** [jensweigele/ioBroker.yahka#116]
Hi,

is it possible to get the wind speed of any wheater adapter, because currently it isn´t possible?

Thks
Doc

**Comment by DocUltra** [comment]
Hallo, welche Auswahl muss ich treffen um die Windgeschwindigkeit über eine Wetteradapter mir anzeigen zu lassen? Temperatur geht

**Comment by nicoh88** [comment]
@DocUltra Konntest du dein Problem lösen?

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!
