### ISSUE TITLE
Switch with different Commands for "state","set:ON" and "set:OFF"

### ISSUE THREAD

**Issue by MrDrache333** [jensweigele/ioBroker.yahka#117]
I use the iRobot Roomba Pugin to Control my Roomba over HomeKit. No Problem is to integrate characteristic's for the Battery State, if the Roomba is Charging or if the Filter is not correct/Full.

My Problem is, that I have a different ON-Command, OFF-Command and State in ioBroker for that.
![Picture 1](https://user-images.githubusercontent.com/22854641/55077322-bb0d3700-5097-11e9-9d20-e759e62d1308.jpg)

For that it would be nice to be able to select a different Source for each Task.

I tryed to use the MultiState, but I did not get it to work. Maybe just my fault? Is there any Way to do this or can it be simply implemented?
My current configuration (just to Start the Roomba via Siri) is just a Switch for that. The thing is...the Start-command is only set to true once and acts like a button. So...no actual state after that push.

![Bildschirmfoto 2019-03-27 um 13 42 25](https://user-images.githubusercontent.com/22854641/55077675-9ebdca00-5098-11e9-89e1-4767735c9704.jpg)

I could create a different Switch for each Task and a Sensor for the current State, but it could be done with only one Switch.

Actually, the only thing a have as an own Sensor is if the Bin is Full and if it's inserted Correctly.
![IMG_0281](https://user-images.githubusercontent.com/22854641/55077553-59010180-5098-11e9-9960-6358d5b32a89.PNG)

**Comment by nicoh88** [comment]
@MrDrache333 Konntest du dein Problem lösen? Wenn ja, wie?

**Comment by MrDrache333** [comment]
Ja, aber nicht mit diesem Adapter. Habe den Roomba jetzt über Node-Red und dem HomeKit Plugin integriert. Dort wird dann auf jede Änderung von jedem Status reagiert und entsprechend eine Gruppe von Sensoren und schaltern einem Gerät zugewiesen und immer aktuell gehalten.

**Comment by nicoh88** [comment]
@MrDrache333 mit dem [hier](https://github.com/husky-koglhof/ioBroker.homekit)?

Sollte über ein Skript (egal ob Blockly oder Node-Red) auch mit YAHKA abbildbar sein.
Ich mache dann hier zu.
