### ISSUE TITLE
Homematic Dimmer flackern mit Werten über Slider

### ISSUE THREAD

**Issue by YuriBiemanov** [jensweigele/ioBroker.yahka#119]
Hallo zusammen,

Ich bin neu bei diesem Adapter.

Was mir beim Dimmer auffiel:

Wähle ich über Siri einen Dimmwert, zb. 50%, wird dieser direkt gesteuert. Egal ob 0-50 oder 100-50.Schalte ich nun aber einen Wert über den HomeKit Slider springt der Wert zwischen dem eingestellten und dem tatsächlichen hin und her Und die Lampe flackert. 

Gruß
Yuri

**Comment by Standarduser** [comment]
Bei mir genau das Gleiche. Zum Einsatz kommt ein HM-LC-Dim1TPBU-FM. Ohne die Verwendung von Yahka werden die Dimmwerte, die über ioBroker gesetzt werden, direkt angefahren. Die Aktualisierung der Rückmeldung erfolgt wie gewohnt ein wenig Zeitverzögert.

Wenn ich das Licht nun per Yahka einbinde, fängt das Licht an zu schwingen - egal, ob die Bedienung mittels Slider in der Home-App erfolgt, oder über Objekte in ioBroker.

Beispiel: der Dimmer steht auf 50% und wird per Slider auf 0% gezogen. Dann passiert folgendes (zu sehen am Slider und auch am Licht selbst, jedoch geht das Licht nicht wirklich auf 0):
50% - 0 - 49 - 0 - 49 - 0 - 48 - 0 - 47 - 0 - 47 ..... aus

Weiteres Beispiel: Das Licht ist aus und wird auf 45% gestellt:
0% - 45 - 0 - 23 ........... 45

Konfiguriert habe ich das so:
<img width="984" alt="Bildschirmfoto 2019-05-02 um 12 57 33" src="https://user-images.githubusercontent.com/8029204/57071177-e8be4f00-6cd9-11e9-8810-e96b964238d2.png">

Was noch auffällt: im Laufe der Tests wird der Effekt weniger, kommt jedoch irgendwann in ursprünglicher Stärke zurück.

**Comment by nicoh88** [comment]
@YuriBiemanov @Standarduser 

Habt ihr das Problem noch?

Ich kenne das Problem, hatte es bei den Devolo Rollladensteuerungen! Wenn ich den Slider in HomeKit bewegt habe, hat er innerhalb von einer Sekunde, ca. 4-5 Werte über Z-Wave an die Steuerung gesendet. Habe es dann über einen zusätzlichen Datenpunkt abgefangen - somit hat er erst nach 1500ms den Wert gesendet, wenn dieser vom "Slider" nicht mehr geändert wurde.

<img width="909" alt="Bildschirmfoto 2020-06-08 um 23 57 52" src="https://user-images.githubusercontent.com/264264/84084504-e6055180-a9e3-11ea-8a0f-75dac02786fe.png">

**Comment by Standarduser** [comment]
Bei Conversion einfach HomematicDirectionToHomekitPosition auswählen, dann kannst du dir das Script sparen. Hat bei mir immer super funktioniert, mittlerweile habe ich jedoch keine Homematic-Dimmer mehr.
