### ISSUE TITLE
OptionalCharacteristic - für alle Services - Neue CommunityTypes

### ISSUE THREAD

**Issue by baerenmarke90** [jensweigele/ioBroker.yahka#120]
Hallo,

wie können denn neue Community Types in Yahka importiert werden?

VG

**Comment by PhilippLeitner** [comment]
Hallo,

gibt es hierfür schon eine Lösung?

LG

**Comment by SpeedmaxX** [comment]
Hallo,
Es wäre super, wenn das noch unterstützt werden würde. 

Vg - SM

**Comment by nicoh88** [comment]
Würde ich auch gut finden. Es sind bereits einige `CommunityTypes` verfügbar - aber nur wenn diese auch einen `Service` haben. Es wird noch dauern, könnte aber vielleicht mal umgesetzt werden.

Ich stelle mir da einen Button, beim Mapping, vor: **Beliebige Characteristic hinzufügen**
Egal welcher "Service-Typ" aktiv ist. So könnte man auch den Verbrauch (energy) bei einer Steckdose (outlet) hinzufügen und den Verbrauch in der Eve-App anzeigen lassen.

@jensweigele Lass uns bei Gelegenheit mal darüber quatschen.

**Comment by jensweigele** [comment]
Mit dem aktuellen Master können beliebige Characteristics zu einem Service hinzugefügt werden.
Testen konnte ich es nicht wirklich - das überlass ich euch ;-)
Falls Ihr was findet, bitte ein neues Ticket aufmachen.

**Comment by nicoh88** [comment]
Läuft. 😄 

<img width="700" alt="Bildschirmfoto 2020-11-25 um 10 29 00" src="https://user-images.githubusercontent.com/264264/100209260-f2d21f00-2f09-11eb-9e46-23eb8cb4b7b2.png">
![IMG_1238](https://user-images.githubusercontent.com/264264/100209266-f49be280-2f09-11eb-800f-adb8c47c7e21.PNG)
![IMG_1239](https://user-images.githubusercontent.com/264264/100209270-f5cd0f80-2f09-11eb-81c9-e3ffe67e7b5c.PNG)
![IMG_1240](https://user-images.githubusercontent.com/264264/100209272-f665a600-2f09-11eb-89c8-ffa5efe9401c.PNG)

**Comment by sannc** [comment]
Einrichten konnte ich mit der neuen Version alles, aber irgendwie kommt es nicht in der Home App an … habe ich Tomaten auf den Augen oder was bei der Einrichtung übersehen?

<img width="1148" alt="Bildschirmfoto 2020-12-22 um 14 26 54" src="https://user-images.githubusercontent.com/13866650/102893446-e4701800-4461-11eb-85c5-729b112f3f01.png">

<img width="506" alt="Bildschirmfoto 2020-12-22 um 14 27 05" src="https://user-images.githubusercontent.com/13866650/102893458-ea65f900-4461-11eb-9a8d-ad4b37bf8aa0.png">

**Comment by nicoh88** [comment]
CommunityTypes werden nicht in der Apple Home angezeigt. Ich benutze dafür in der Regel die Eve- oder „Controller for HomeKit“ App.

Gruß

**Comment by sannc** [comment]
Ah, ok. Schade.

**Comment by Flacus** [comment]
Ich bekomme nur ganze KWH angezeigt in EVE, außer ich Konvertiere die Zahlen in Yahke mit SCALEINT.
Wie bekommen ich bei einem Balkonsolarmodul den die Nachkommerstellen richtig formatiert ?

**Comment by unstressable** [comment]
> CommunityTypes werden nicht in der Apple Home angezeigt. Ich benutze dafür in der Regel die Eve- oder „Controller for HomeKit“ App.
> 
> Gruß

verstehe ich das richtig, dass alle community-type services nicht in der offiziellen Home-App angezeigt werden, aber in den genannten Drittanbieter-Apps schon?

**Comment by nicoh88** [comment]
Korrekt
