### ISSUE TITLE
Voreingestellte Farben können nicht angewählt werden

### ISSUE THREAD

**Issue by denzel1994** [jensweigele/ioBroker.yahka#122]
Hallo zusammen, 
ich habe seit kurzem das Problem, dass voreingestellte Farben nicht mehr angewählt werden können. Die Farben springen immer zurück auf die Ursprungsfarbe. An den Lichtern selber ändert sich die Farbe aber auch garnicht erst.
Im Farbrad funktioniert es jedoch ohne Probleme.

Dazu am besten das kurze Video angucken:
![IMG_1641 TRIM](https://user-images.githubusercontent.com/36551243/57021761-742dd680-6c2d-11e9-9d86-99ea355c2d70.gif)

Beste Grüße Lars

**Comment by nicoh88** [comment]
@denzel1994 Konntest du das Problem lösen?

Ließ dir mal meinen letzten Post in #76 durch.

**Comment by nicoh88** [comment]
Same #76
