### ISSUE TITLE
Icons ändern

### ISSUE THREAD

**Issue by chrissh81** [jensweigele/ioBroker.yahka#123]
Ist es möglich für einen Switch, das Wasserhahn oder Rasensprenger-Symbol zu verwenden oder ändern?

**Comment by Baenker** [comment]
Im ValveType kann man mit einem selbst erstellten Datenpunkt verwenden: Typ Werteliste mit 2 Werten. 0 für ein Wasserhahn Icon oder 1 für ein Sprenger Icon.

siehe auch: https://forum.iobroker.net/topic/22787/yahka-sprinkler-mit-zeitsteuerung/12

**Comment by chrissh81** [comment]
Danke,

Ich hatte das Thema eröffnet.

Gruß Christian Hessing
Von meinem iPhone gesendet
