### ISSUE TITLE
Dimmer Werte werden nicht an iobroker übergeben

### ISSUE THREAD

**Issue by Church2** [jensweigele/ioBroker.yahka#124]
Ich verwende die neuen InOut Parameter für Dimmer wie folgt:

<img width="1860" alt="image" src="https://user-images.githubusercontent.com/39483049/58004300-3f51c880-7ae3-11e9-9907-eb38e19db507.png">

Leider werden die Werte aber nicht an iobroker übergeben. Im Log steht auch nicht wie sonst "writing state to iobroker..."

<img width="818" alt="image" src="https://user-images.githubusercontent.com/39483049/58004268-29440800-7ae3-11e9-94a9-b7e209b4d0d9.png">

Stimmt etwas mit meiner Konfiguration nicht?

**Comment by nicoh88** [comment]
@Church2 Konntest du das Problem lösen?

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!
