### ISSUE TITLE
Moisture Sensor

### ISSUE THREAD

**Issue by georgbachmann** [jensweigele/ioBroker.yahka#126]
Is it possible to add a moisture sensor? I use a Xiaomi Mi Plant Sensor to measure the moisture of my plant and it would be nice to display it in homekit.
I currently use humidity as the service type, but I guess moisture would be more correct?
Would be just a small improvement as my workaround works for me anyway...
Cheers,
Georg

**Comment by nicoh88** [comment]
Hi @georgbachmann,

is this from apple supported?
I find no "moisture" in [HAP-NodeJS](https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/gen/HomeKit.ts).

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!
