### ISSUE TITLE
Shelly 2.5 Rolllade Fehler in der HomeKit Anzeige

### ISSUE THREAD

**Issue by Philipp92** [jensweigele/ioBroker.yahka#128]
Ich habe einen Shelly 2.5 erfolgreich eingerichtet.
Im Homekit kann ich hoch und runter fahren - alles funktioniert.

Wenn ich jedoch nur auf beispielsweise 30% öffne/schließe, dann dreht danach das Rädchen und es steht zuerst unter dem Objekt "Wird geöffnet..." dann "Schließen..." und so bleibt der Status bis ich einmal auf den Home Button drücke und wieder zurück in die Home App gehe, dann wird der Status in % richtig angezeigt.

Weiß jemand woran das liegt?
![IMG_6549](https://user-images.githubusercontent.com/51400553/59882386-60dbf380-93b2-11e9-8d0a-cd8bd320cc2f.PNG)
![IMG_6548](https://user-images.githubusercontent.com/51400553/59882388-60dbf380-93b2-11e9-8fda-171363cf133a.PNG)

**Comment by DanielWeeber** [comment]
Sieht für mich nach nem Zuordnugsproblem bei deinen Parametern aus. Lies dir die Doku in HAP-NodeJS durch und lerne, was "Current" und "Target" Positions sind. Abhängig davon dann Parameter übergeben.

**Comment by nicoh88** [comment]
@Philipp92 

Konntest du dein Problem lösen?

Ich habe Devolo Rollladensteuerungen, hier gibt es das Problem, dass es keinen Datenpunkt für "DIRECTION" (wie beim Homematic) gibt. Das heißt, HomeKit muss raten, in welche Richtung der Rollladen fährt. Am Ende, sollte es in der HomeApp aber nicht mehr "kreiseln". Ich habe da für jeden Rollladen ein Blockly-Skript gebastelt, was die Problem anhand des Stromverbrauchs löst.

Machst du mal einen Screenshot der Datenpunkte vom Shelly 2.5?

Gruß Nico

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!
