### ISSUE TITLE
Adapter startet nach Update auf Docker nicht mehr

### ISSUE THREAD

**Issue by 19Homer73** [jensweigele/ioBroker.yahka#130]
![13-07-_2019_22-10-09](https://user-images.githubusercontent.com/24566412/61176099-30573600-a5bb-11e9-9866-943827615272.jpg)

**Comment by 19Homer73** [comment]
Jemand eine Idee warum nicht mehr?

Danke & Grüße,
Homer

**Comment by sbeneke** [comment]
Bei mir war der "Fehler" ein Versionsupdate von Node.js. Mit folgendem Befehl kannst du dies prüfen:
grep error /opt/iobroker/log/iobroker.$(date +%Y-%m-%d).log
Bei mir steht u.a. folgendes, also Modul entfernen und neu installieren:
effective way to hose your system2019-07-27 14:53:35.861  - error: Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/iobroker.yahka/node_modules/ed25519-hap/build/Release/ed25519.node'
2019-07-27 14:53:35.861  - error: Caught by controller[0]: was compiled against a different Node.js version using
2019-07-27 14:53:35.861  - error: Caught by controller[0]: NODE_MODULE_VERSION 57. This version of Node.js requires
2019-07-27 14:53:35.861  - error: Caught by controller[0]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
Hat jemand den Befehlsaufruf für re-compiling parat?

**Comment by nicoh88** [comment]
@19Homer73 Kann ich das Issue schließen? Scheint gelöst.

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!
