### ISSUE TITLE
Television inputs

### ISSUE THREAD

**Issue by maoten2000** [jensweigele/ioBroker.yahka#131]
please include the tv inputs selection in the next update for the television service inside yahka.

**Comment by reptil1990** [comment]
I would love to get the TV-Adapter running.
I did some research with the existing homebridge adapter, but couldn´t get it to work.

**Comment by mutex1980** [comment]
I did some research. After reading here

[https://github.com/KhaosT/HAP-NodeJS/issues/641](url)

and inspecting the code from here

[https://github.com/n0rt0nthec4t/HAP-NodeJS-Accessories/blob/master/SonyTV_accessory.js](url)

I found this code

`this.__TVService.addLinkedService(this.__TVInputs[inputIndex].__InputService);`

showing that a concept of "linked services" seems to be necessary to setup television devices with input sources. It linkes services to other services in an accessory. I wonder if there is a way to accomplish this with YAHKA?

**Comment by nicoh88** [comment]
Doppelt mit #89?

**Comment by jensweigele** [comment]
Weiteres Tracking in #89
