### ISSUE TITLE
Sonoff MultiState Problem wenn ich den Knopf an der Steckdose nutze

### ISSUE THREAD

**Issue by legacycode** [jensweigele/ioBroker.yahka#132]
Ich habe eine Steckdose mit Tasmota geflashed und einen externen MQTT Server. Tasmota erwartet die Kommandos auf dem Topic mqtt.0.cmnd.sonoff_5E3C8D.POWER und die entsprechenden Statusänderungen kommen auf dem Topic mqtt.0.stat.sonoff_5E3C8D.POWER rein. Hier meine Settings im Plugin:

![image](https://user-images.githubusercontent.com/668759/61777100-a5690d80-adfc-11e9-83d2-d8f983663f5e.png)

Das funktioniert soweit alles ganz gut, solange ich über HomeKit schalte. Wenn ich zwischenzeitlich den Knopf an der Stecksode betätige, dann kommt yahka durcheinander. In diesem Fall steht der korrekte Wert im reading:

![image](https://user-images.githubusercontent.com/668759/61777798-dbf35800-adfd-11e9-8de8-d874c236a99c.png)

Und nach meiner Auffassung auch der korrekte und evtl. veraltete Wert im writing Topic:

![image](https://user-images.githubusercontent.com/668759/61777882-05ac7f00-adfe-11e9-8e64-4be5e75901f8.png)

Wenn ich jetzt versuche die Steckdose mit Homekit zu schalten muss ich öfter drücken, ohne das etwas passiert. yahka hält die Steckdose immernoch für eingeschaltet, da der aktuelle State mit dem State des veralteten writing Topics verglichen wird. Nach meiner Auffassung müsste aber gegen das zwischenzeitlich veränderte reading Topic verglichen werden:

![image](https://user-images.githubusercontent.com/668759/61778175-8d928900-adfe-11e9-8dfb-d62d06032c98.png)

Entscheidend ist hier wohl die dritte Zeile im o.g. Screenshot. Hier die Schritte, um dieses Problem zu reproduzieren:

1. Einen yahka switch, wie im ersten Screenshot anlegen
2. Steckdose über Homekit einschalten -> Steckdose schaltet ein -> Status in Homekit ist ein
3. Steckdose am Schalter ausschalten -> Steckdose schaltet aus -> Status in Homekit ist aus
4. Steckdose über Homekit einschalten -> Steckdose reagiert nicht -> Status in Homekit ist ein
5. Steckdose über Homekit ausschalten -> Steckdose reagiert nicht ->Status in Homekit ist aus
6. Steckdocse über Homekit einschalten -> Steckdose schaltet ein -> Status in Homekit ist ein

Ich glaube, dass der Statuswechsel nicht aus dem write topic, sondern ebenfalls aus dem read topic gelesen werden sollte.

Beste Grüße.

legacycode

**Comment by nicoh88** [comment]
@legacycode 

Konntest du zwischenzeitlich dein Problem lösen?

Hier wirst du wohl an einem ioBroker Skript, welches den Wert "korrigiert", nicht vorbeikommen. Oder, war es ein Bug im MQTT-Adapter?

Gruß Nico

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!

**Comment by idcchris** [comment]
es ist zwar geschlossen aber ich hab eine Lösung die bei mir geht.
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/17980736/100244900-bf0dee00-2f37-11eb-9447-4ecca9969048.png">
