### ISSUE TITLE
Error exports.a�pName = 0 appName;

### ISSUE THREAD

**Issue by hecarrara** [jensweigele/ioBroker.yahka#134]
host.raspberrypi | 2019-08-10 09:52:41.968 | error | instance system.adapter.yahka.0 terminated with code 1 ()
-- | -- | -- | --
host.raspberrypi | 2019-08-10 09:52:41.968 | error | Caught by controller[0]: at bootstrap_node.js:625:3
host.raspberrypi | 2019-08-10 09:52:41.968 | error | Caught by controller[0]: at startup (bootstrap_node.js:204:16)
host.raspberrypi | 2019-08-10 09:52:41.968 | error | Caught by controller[0]: at Function.Module.runMain (module.js:694:10)
host.raspberrypi | 2019-08-10 09:52:41.968 | error | Caught by controller[0]: at Function.Module._load (module.js:498:3)
host.raspberrypi | 2019-08-10 09:52:41.968 | error | Caught by controller[0]: at tryModuleLoad (module.js:506:12)
host.raspberrypi | 2019-08-10 09:52:41.967 | error | Caught by controller[0]: at Module.load (module.js:566:32)
host.raspberrypi | 2019-08-10 09:52:41.967 | error | Caught by controller[0]: at Object.Module._extensions..js (module.js:664:10)
host.raspberrypi | 2019-08-10 09:52:41.967 | error | Caught by controller[0]: at Module._compile (module.js:617:28)
host.raspberrypi | 2019-08-10 09:52:41.967 | error | Caught by controller[0]: at Object.runInThisContext (vm.js:139:10)
host.raspberrypi | 2019-08-10 09:52:41.967 | error | Caught by controller[0]: at createScript (vm.js:80:10)
host.raspberrypi | 2019-08-10 09:52:41.967 | error | Caught by controller[0]: SyntaxError: Invalid or unexpected token
host.raspberrypi | 2019-08-10 09:52:41.966 | error | Caught by controller[0]: ^
host.raspberrypi | 2019-08-10 09:52:41.966 | error | Caught by controller[0]: exports.a�pName = 0 appName;
host.raspberrypi | 2019-08-10 09:52:41.966 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.yahka/main.js:1268

**Comment by jensweigele** [comment]
How did you install the adapter?
Which Node and ioBroker Version are you using?

**Comment by hecarrara** [comment]
The adapter was  working fine, suddenly starts this error. I didn't want to remove and reinstall because I will loose all my devices configured.

Node v8.14.0
Iobroker 1.5.14

**Comment by hecarrara** [comment]
I deleted instance, delete adapter, reinstall it and it came back.
