### ISSUE TITLE
OptionalCharacteristic - Werte aus Wechselrichter in KW

### ISSUE THREAD

**Issue by riconr1** [jensweigele/ioBroker.yahka#136]
Hallo ist es Möglich ein Stromsensor zu erstellen? 
Ich möchte gerne die Werte aus meinem Fronius Wechselrichter / Smartmeter in Homekit sehen können. Dafür finde ich in keinem Service Typ die Möglichkeit Werte abzufragen.

Über Hilfe wäre ich und so wie ich das gelesen habe auch viele Andere dankbar.

Gruß Enrico

**Comment by nicoh88** [comment]
Hi @riconr1,

theoretisch ist das möglich. Man braucht eine zusätzliche Characteristic, um diese ordentlich nutzen zu können, muss man Yahka etwas aufbohren.

Es wird noch dauern, könnte aber vielleicht mal umgesetzt werden. Ich stelle mir da einen Button, beim Mapping, vor "Beliebige Characteristic hinzufügen" egal welcher "Service-Typ" aktiv ist. So könnte man auch den Verbrauch (energy) bei einer Steckdose (outlet) hinzufügen und den Verbrauch in der Eve-App anzeigen lassen.

@jensweigele

**Comment by riconr1** [comment]
Das wäre richtig genial. Schreib mir, was ich testen oder anderweitig helfen kann.

LG

**Comment by jensweigele** [comment]
Weiteres Tracking in #120

**Comment by jensweigele** [comment]
Durch #120 sind nun diverse Community-Characteristics zu beliebigen Services hinzufügbar - dadurch kannst du vielleicht deine Anforderung erfüllen.

**Comment by nicoh88** [comment]
@riconr1 

Servus, du kannst mit der aktuellen Master "**Custom Characteristic**" bei jedem Gerät hinzufügen - siehe meinen Kommentar [hier](https://github.com/jensweigele/ioBroker.yahka/issues/120#issuecomment-733587461).

**Comment by riconr1** [comment]
Ganz lieben Dank, am Wochenende teste ich das mal. Ich freue mich schon 😊

Mit freundlichen Grüßen 
Enrico Nauen

**Comment by tobst96** [comment]
Wird dies noch umgesetzt oder ist es schon implementiert?
