### ISSUE TITLE
Properties

### ISSUE THREAD

**Issue by backfisch88** [jensweigele/ioBroker.yahka#137]
Hallo!

Bin bei meiner Fehlersuche über mehrere Screenshots gestolpert, wo es einen extra Knopf „Properties“ neben der Charakteristik steht, wo man extra Einstellungen wie eine Thermostat Begrenzung machen könnte. 

<img width="1282" alt="0B7A5EE4-417A-4590-AE7D-2897F94609A3" src="https://user-images.githubusercontent.com/7542512/64906131-85f6ae80-d6e2-11e9-89bb-0eb8e5240245.png">

Gibt es diese Funktion noch?! Und oder hab ich den Knopf dazu einfach nicht gefunden 🤭

Vielen Dank!

**Comment by nicoh88** [comment]
Im ioBroker Repo ist mittlerweile die 0.11.0.
Hier gibt es den "Properties" Knopf und man kann einen Wert in das Feld schreiben. 👍 

Gruß
