### ISSUE TITLE
error iobroker.yahka adapter Invalid or unexpected token

### ISSUE THREAD

**Issue by hecarrara** [jensweigele/ioBroker.yahka#138]
I already try to remove and add the adapter, but the same error remain every time.
Node.js
    v10.16.3
NPM
    6.11.3
YAHKA 0.9.2
> 
host.raspberrypi | 2019-09-17 15:19:31.691 | error | instance system.adapter.yahka.0 terminated with code 1 ()
-- | -- | -- | --
host.raspberrypi | 2019-09-17 15:19:31.691 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.raspberrypi | 2019-09-17 15:19:31.691 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
host.raspberrypi | 2019-09-17 15:19:31.691 | error | Caught  by controller[0]:     at Object.<anonymous>  (/opt/iobroker/node_modules/multicast-dns/node_modules/dns-packet/index.js:3:15)
host.raspberrypi | 2019-09-17 15:19:31.690 | error | Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:25:18)
host.raspberrypi | 2019-09-17 15:19:31.690 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:692:17)
host.raspberrypi | 2019-09-17 15:19:31.690 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.raspberrypi | 2019-09-17 15:19:31.690 | error | Caught by controller[0]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.raspberrypi | 2019-09-17 15:19:31.690 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:653:32)
host.raspberrypi | 2019-09-17 15:19:31.690 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.raspberrypi | 2019-09-17 15:19:31.690 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:723:23)
host.raspberrypi | 2019-09-17 15:19:31.689 | error | Caught by controller[0]: SyntaxError: Invalid or unexpected token
host.raspberrypi | 2019-09-17 15:19:31.689 | error | Caught by controller[0]:              ^
host.raspberrypi | 2019-09-17 15:19:31.689 | error | Caught by controller[0]: exports.voStr�ng = function (type) {
host.raspberrypi | 2019-09-17 15:19:31.688 | error | Caught by controller[0]: /opt/iobroker/node_modules/multicast-dns/node_modules/dns-packet/types.js:3
host.raspberrypi | 2019-09-17 15:19:30.914 | info | instance system.adapter.yahka.0 started with pid 22876

>

**Comment by nicoh88** [comment]
@hecarrara 

Konntest du dein Problem lösen?

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!
