### ISSUE TITLE
Feature Request: Add iOS 11 HomeKit devices

### ISSUE THREAD

**Issue by captaindork** [jensweigele/ioBroker.yahka#14]
Hi!

Is it planned to add the new homekit devicetypes from iOS 11 to yahka?
There are for example sprinklers and faucets now, and it would be great to allow them through yahka.

THX

**Comment by jensweigele** [comment]
Hi,

I updated the meta database to the latest devicetypes from HAP-NodeJS. You could test it by installing the current master.

Best Regards
 Jens

**Comment by captaindork** [comment]
Hi,
Thanks a lot, but how can I actually test? If in ioBroker I install it via npm, then i basically get the old production release. If I chose to install from github, then i get the new master, but „cannot find start file“ error (also discussed on ioBroker forums).

**Comment by jensweigele** [comment]
Hi,

I published the 0.6.0-beta.1 to NPM. Additionally it is now possible to install the latest adapter via the git-url: https://github.com/jensweigele/iobroker.yahka-dist

Best Regards

**Comment by captaindork** [comment]
KhaosT/HAP-NodeJS#504
