### ISSUE TITLE
Cam in Yahka without Sound? Kamera in Yahka ohne Ton?

### ISSUE THREAD

**Issue by fabianbmann** [jensweigele/ioBroker.yahka#141]
ENG: Is there no way to hear the sound of the camera in the home app? ffmpeg has the option to transfer the audio track of an rtsp feed as well. Is it possible to enable this in the next update?

DEU: Gibt es keine Möglickeit, den Ton der Kamera in der Home App zu hören? ffmpeg hat doch die Möglichkeit, auch die Audiospur eines rtsp Feeds zu übertragen. Ist es möglich, dies im nächsten Update zu aktivieren?

Great Job!! Love Your Adapter!

**Comment by nicoh88** [comment]
@fabianbmann 

Konntest du dein Problem lösen?

**Comment by fabianbmann** [comment]
Nein, leider nicht. Ich habe die Kameras zurück gesendet und mir andere geholt. Das war mir alles zu aufwendig und Ressourcen fressend für den Raspberry. Ich habe es leider nicht geschafft, Yahka so einzustellen, dass der Ton übertragen wird. -Sorry- Ich wünsche dir viel Erfolg...
