### ISSUE TITLE
yahka error log iobroker

### ISSUE THREAD

**Issue by DocUltra** [jensweigele/ioBroker.yahka#142]
I´ve got the following error

`

host.ioBroker | 2019-11-01 15:05:20.212 | error | instance system.adapter.yahka.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2019-11-01 15:05:20.212 | error | by controller[92]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":false,"ack":true,"from":"system.adapter.yahka.0"}],"option
Caught | 2019-11-01 15:05:20.212 | error | by controller[92]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":false,"ack":true,"from":"system.adapter.yahka.0"}]
Caught | 2019-11-01 15:05:20.212 | error | by controller[92]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":false,"ack":true,"from":"system.adapter.yah
Caught | 2019-11-01 15:05:20.212 | error | by controller[92]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:socket emitting packet with ack id 4
Caught | 2019-11-01 15:05:20.212 | error | by controller[92]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:socket calling ack 2 with [null,"system.adapter.yahka.0.alive"]
Caught | 2019-11-01 15:05:20.212 | error | by controller[92]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser decoded 32[null,"system.adapter.yahka.0.alive"] as {"type":3,"nsp":"/","id":2,"data":[null,"system.adapter.yahka.0.alive"]}
Caught | 2019-11-01 15:05:20.212 | error | by controller[92]: Fri, 01 Nov 2019 14:05:20 GMT engine.io-client:socket socket receive: type "message", data "32[null,"system.adapter.yahka.0.alive"]"
Caught | 2019-11-01 15:05:20.212 | error | by controller[92]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["getStates",["system.adapter.admin.0.logging"]],"options":{"compress":true},"id":3,"nsp":"/"} as 23["getSta
Caught | 2019-11-01 15:05:20.212 | error | by controller[92]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["getStates",["system.adapter.admin.0.logging"]],"options":{"compress":true},"id":3,"nsp":"/"}
Caught | 2019-11-01 15:05:20.212 | error | by controller[92]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["getStates",["system.adapter.admin.0.logging"]],"options":{"compress":true},"id":3,"nsp":"/"
Caught | 2019-11-01 15:05:20.212 | error | by controller[92]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:socket emitting packet with ack id 3
Caught | 2019-11-01 15:05:20.212 | error | by controller[92]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:socket calling ack 1 with [null,["system.adapter.admin.0.logging"]]
Caught | 2019-11-01 15:05:20.211 | error | by controller[92]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser decoded 31[null,["system.adapter.admin.0.logging"]] as {"type":3,"nsp":"/","id":1,"data":[null,["system.adapter.admin.0.logging"]]}
Caught | 2019-11-01 15:05:20.211 | error | by controller[92]: Fri, 01 Nov 2019 14:05:20 GMT engine.io-client:socket socket receive: type "message", data "31[null,["system.adapter.admin.0.logging"]]"
Caught | 2019-11-01 15:05:20.211 | error | by controller[91]: Fri, 01 Nov 2019 14:05:20 GMT engine.io-client:socket flushing 17 packets in socket
Caught | 2019-11-01 15:05:20.211 | error | by controller[90]: Fri, 01 Nov 2019 14:05:20 GMT engine.io-client:socket flushing 11 packets in socket
Caught | 2019-11-01 15:05:20.211 | error | by controller[89]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":false,"ack":true,"from":"system.adapter.yahka.0"}],"option
Caught | 2019-11-01 15:05:20.211 | error | by controller[89]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":false,"ack":true,"from":"system.adapter.yahka.0"}]
Caught | 2019-11-01 15:05:20.211 | error | by controller[89]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":false,"ack":true,"from":"system.adapter.yah
Caught | 2019-11-01 15:05:20.211 | error | by controller[88]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:socket emitting packet with ack id 2
Caught | 2019-11-01 15:05:20.211 | error | by controller[87]: at emitListeningNT (net.js:1314:10) errorCode: -65537 }
Caught | 2019-11-01 15:05:20.211 | error | by controller[87]: at Server.emit (events.js:198:13)
Caught | 2019-11-01 15:05:20.211 | error | by controller[87]: at EventedHTTPServer.<anonymous> (/opt/iobroker/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)
Caught | 2019-11-01 15:05:20.211 | error | by controller[87]: at EventedHTTPServer.emit (events.js:198:13)
Caught | 2019-11-01 15:05:20.211 | error | by controller[87]: at HAPServer._onListening (/opt/iobroker/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
Caught | 2019-11-01 15:05:20.210 | error | by controller[87]: at HAPServer.emit (events.js:198:13)
Caught | 2019-11-01 15:05:20.210 | error | by controller[87]: at Bridge.Accessory._onListening (/opt/iobroker/node_modules/hap-nodejs/lib/Accessory.js:661:20)
Caught | 2019-11-01 15:05:20.210 | error | by controller[87]: at Advertiser.startAdvertising (/opt/iobroker/node_modules/hap-nodejs/lib/Advertiser.js:47:30)
Caught | 2019-11-01 15:05:20.210 | error | by controller[87]: at Object.create [as createAdvertisement] (/opt/iobroker/node_modules/mdns/lib/advertisement.js:64:10)
Caught | 2019-11-01 15:05:20.210 | error | by controller[87]: at new Advertisement (/opt/iobroker/node_modules/mdns/lib/advertisement.js:56:10)
Caught | 2019-11-01 15:05:20.210 | error | by controller[87]: { Error: dns service error: unknown
Caught | 2019-11-01 15:05:20.210 | error | by controller[86]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["subscribe","yahka.0.checkLogging",null],"options":{"compress":true},"nsp":"/"} as 2["subscribe","yahka.0.c
Caught | 2019-11-01 15:05:20.210 | error | by controller[86]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["subscribe","yahka.0.checkLogging",null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.210 | error | by controller[85]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["subscribe","yahka.0.checkLogging",null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.210 | error | by controller[84]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"} as 2["subscribe","system.a
Caught | 2019-11-01 15:05:20.210 | error | by controller[84]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.210 | error | by controller[84]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.209 | error | by controller[84]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"name":"yah
Caught | 2019-11-01 15:05:20.209 | error | by controller[84]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"na
Caught | 2019-11-01 15:05:20.209 | error | by controller[84]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香
Caught | 2019-11-01 15:05:20.209 | error | by controller[84]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:socket emitting packet with ack id 9
Caught | 2019-11-01 15:05:20.209 | error | by controller[83]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"} as 2["subscribe","system.a
Caught | 2019-11-01 15:05:20.209 | error | by controller[83]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.209 | error | by controller[83]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.209 | error | by controller[83]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"name":"yah
Caught | 2019-11-01 15:05:20.209 | error | by controller[83]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"na
Caught | 2019-11-01 15:05:20.209 | error | by controller[83]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香
Caught | 2019-11-01 15:05:20.209 | error | by controller[83]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:socket emitting packet with ack id 8
Caught | 2019-11-01 15:05:20.209 | error | by controller[83]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"} as 2["subscribe","system.a
Caught | 2019-11-01 15:05:20.209 | error | by controller[83]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.208 | error | by controller[83]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.208 | error | by controller[83]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"name":"yah
Caught | 2019-11-01 15:05:20.208 | error | by controller[83]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"na
Caught | 2019-11-01 15:05:20.208 | error | by controller[83]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香
Caught | 2019-11-01 15:05:20.208 | error | by controller[82]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:socket emitting packet with ack id 7
Caught | 2019-11-01 15:05:20.208 | error | by controller[81]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"} as 2["subscribe","system.a
Caught | 2019-11-01 15:05:20.208 | error | by controller[81]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.208 | error | by controller[81]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.208 | error | by controller[81]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"name":"yah
Caught | 2019-11-01 15:05:20.208 | error | by controller[81]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"na
Caught | 2019-11-01 15:05:20.208 | error | by controller[81]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香
Caught | 2019-11-01 15:05:20.208 | error | by controller[81]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:socket emitting packet with ack id 6
Caught | 2019-11-01 15:05:20.207 | error | by controller[80]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"} as 2["subscribe","system.a
Caught | 2019-11-01 15:05:20.207 | error | by controller[79]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.207 | error | by controller[79]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.207 | error | by controller[79]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"name":"yah
Caught | 2019-11-01 15:05:20.207 | error | by controller[79]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"na
Caught | 2019-11-01 15:05:20.207 | error | by controller[79]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香
Caught | 2019-11-01 15:05:20.207 | error | by controller[78]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:socket emitting packet with ack id 5
Caught | 2019-11-01 15:05:20.207 | error | by controller[77]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"} as 2["subscribe","system.a
Caught | 2019-11-01 15:05:20.207 | error | by controller[77]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.207 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.207 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"name":"yah
Caught | 2019-11-01 15:05:20.207 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"na
Caught | 2019-11-01 15:05:20.206 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香
Caught | 2019-11-01 15:05:20.206 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:socket emitting packet with ack id 4
Caught | 2019-11-01 15:05:20.206 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"} as 2["subscribe","system.a
Caught | 2019-11-01 15:05:20.206 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.206 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.206 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"name":"yah
Caught | 2019-11-01 15:05:20.206 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"na
Caught | 2019-11-01 15:05:20.206 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香
Caught | 2019-11-01 15:05:20.206 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:socket emitting packet with ack id 3
Caught | 2019-11-01 15:05:20.206 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"} as 2["subscribe","system.a
Caught | 2019-11-01 15:05:20.206 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.206 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.205 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"name":"yah
Caught | 2019-11-01 15:05:20.205 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"na
Caught | 2019-11-01 15:05:20.205 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香
Caught | 2019-11-01 15:05:20.205 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:socket emitting packet with ack id 2
Caught | 2019-11-01 15:05:20.205 | error | by controller[76]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"} as 2["subscribe","system.a
Caught | 2019-11-01 15:05:20.205 | error | by controller[75]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.205 | error | by controller[75]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["subscribe","system.adapter.*",null,null],"options":{"compress":true},"nsp":"/"}
Caught | 2019-11-01 15:05:20.205 | error | by controller[74]: Fri, 01 Nov 2019 14:05:20 GMT engine.io-client:socket flushing 1 packets in socket
Caught | 2019-11-01 15:05:20.205 | error | by controller[74]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoded {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"name":"yah
Caught | 2019-11-01 15:05:20.205 | error | by controller[74]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-parser encoding packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香"},{"na
Caught | 2019-11-01 15:05:20.205 | error | by controller[74]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:manager writing packet {"type":2,"data":["getObjectView","system","instance",{"startkey":"system.adapter.","endkey":"system.adapter.香
Caught | 2019-11-01 15:05:20.205 | error | by controller[74]: Fri, 01 Nov 2019 14:05:20 GMT socket.io-client:socket emitting packet with ack id 1
Caught | 2019-11-01 15:05:20.204 | error | by controller[74]: Fri, 01 Nov 2019 14:05:19 GMT socket.io-parser encoded {"type":2,"data":["setState","system.adapter.yahka.0.outputCount",{"val":8,"ack":true,"from":"system.adapter.yahka.0"},null],
Caught | 2019-11-01 15:05:20.204 | error | by controller[74]: Fri, 01 Nov 2019 14:05:19 GMT socket.io-parser encoding packet {"type":2,"data":["setState","system.adapter.yahka.0.outputCount",{"val":8,"ack":true,"from":"system.adapter.yahka.0"
Caught | 2019-11-01 15:05:20.204 | error | by controller[74]: Fri, 01 Nov 2019 14:05:19 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.outputCount",{"val":8,"ack":true,"from":"system.adapter.y
Caught | 2019-11-01 15:05:20.204 | error | by controller[74]: Fri, 01 Nov 2019 14:05:19 GMT socket.io-parser encoded {"type":2,"data":["setState","system.adapter.yahka.0.inputCount",{"val":0,"ack":true,"from":"system.adapter.yahka.0"},null],"
Caught | 2019-11-01 15:05:20.204 | error | by controller[74]: Fri, 01 Nov 2019 14:05:19 GMT socket.io-parser encoding packet {"type":2,"data":["setState","system.adapter.yahka.0.inputCount",{"val":0,"ack":true,"from":"system.adapter.yahka.0"}
Caught | 2019-11-01 15:05:20.204 | error | by controller[74]: Fri, 01 Nov 2019 14:05:19 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.inputCount",{"val":0,"ack":true,"from":"system.adapter.ya
Caught | 2019-11-01 15:05:20.204 | error | by controller[74]: Fri, 01 Nov 2019 14:05:19 GMT socket.io-parser encoded {"type":2,"data":["setState","system.adapter.yahka.0.uptime",{"val":1,"ack":true,"from":"system.adapter.yahka.0"},null],"opti
Caught | 2019-11-01 15:05:20.204 | error | by controller[74]: Fri, 01 Nov 2019 14:05:19 GMT socket.io-parser encoding packet {"type":2,"data":["setState","system.adapter.yahka.0.uptime",{"val":1,"ack":true,"from":"system.adapter.yahka.0"},nul
Caught | 2019-11-01 15:05:20.204 | error | by controller[74]: Fri, 01 Nov 2019 14:05:19 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.uptime",{"val":1,"ack":true,"from":"system.adapter.yahka.
Caught | 2019-11-01 15:05:20.204 | error | by controller[74]: Fri, 01 Nov 2019 14:05:19 GMT socket.io-parser encoded {"type":2,"data":["setState","system.adapter.yahka.0.memHeapUsed",{"val":12.71,"ack":true,"from":"system.adapter.yahka.0"},nu
Caught | 2019-11-01 15:05:20.204 | error | by controller[74]: Fri, 01 Nov 2019 14:05:19 GMT socket.io-parser encoding packet {"type":2,"data":["setState","system.adapter.yahka.0.memHeapUsed",{"val":12.71,"ack":true,"from":"system.adapter.yahk
Caught | 2019-11-01 15:05:20.204 | error | by controller[74]: Fri, 01 Nov 2019 14:05:19 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.memHeapUsed",{"val":12.71,"ack":true,"from":"system.adapt

`

**Comment by j0sHuA96** [comment]
Same here

**Comment by Jonfried92** [comment]
Got the same yesterday.
For me it was enough to remove the device, which i added last.
After that i added the new device again and it worked....
