### ISSUE TITLE
Yahka crashes with compact mode enabled

### ISSUE THREAD

**Issue by Marty56** [jensweigele/ioBroker.yahka#143]
Not compatible with js-controller 2.0.
Adapter accepts compact mode but then crashes.

**Comment by Apollon77** [comment]
Can we please get error log or such?!

**Comment by Marty56** [comment]
Have send the log.

**Comment by nicoh88** [comment]
Hi Jungs, ist das Problem gelöst?

**Comment by nicoh88** [comment]
In der #140 geht es weiter - mache hier zu.
