### ISSUE TITLE
Homekit kopplung nicht möglich mit default Namen in Cofig

### ISSUE THREAD

**Issue by chris299** [jensweigele/ioBroker.yahka#144]
Homekit kopplung nicht möglich mit default Bridge-Namen in der Adapterconfig
ich vermute, es liegt an dem Doppelpunkt im default-namen.
Wenn man den Namen anpasst auf z.B: "Homekitbridge" dann geht es einwandfrei.

Vielen Dank für die Bereitstellung dieses Adapters und die Unterstüzung der iobroker communitiy!

**Comment by nicoh88** [comment]
Sollte gelöst sein, mittlerweile ist der Default-Name "Yahka-0", "Yahka-1" und so weiter.
