### ISSUE TITLE
Iobroker State auswahl nicht Scrollbar

### ISSUE THREAD

**Issue by Omega236** [jensweigele/ioBroker.yahka#145]
sowhol unter firefox 70.0.1 als auch unter Chrome 78.0.xxx lässt sich die IOBroker States ansicht nicht scrollen.

Außerdem wenn man den X-Button in der State-Auswahl drückt, wird der Hintergrund Grau und man kann nichts mehr machen.

**Comment by nicoh88** [comment]
Hallo @Omega236 

im ioBroker Repo ist mittlerweile die 0.11.0 - das Problem sollte gelöst sein.

Gruß Nico
