### ISSUE TITLE
crash bei Gerät mit 2 Services

### ISSUE THREAD

**Issue by chris299** [jensweigele/ioBroker.yahka#146]
habe versucht einen Switch mit 2 Services zu konfigurieren. mit einem geht es, beim Zweiten sieht das Log dann so aus:
(geht wieder weg, wenn man den zweiten Service entfernt)

yahka.0 | 2019-11-19 20:34:19.902 | error | at Socket.onack (/usr/local/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
-- | -- | -- | --
yahka.0 | 2019-11-19 20:34:19.902 | error | at Socket.<anonymous> (/usr/local/iobroker/node_modules/iobroker.yahka/main.js:3562:21)
yahka.0 | 2019-11-19 20:34:19.902 | error | at changeInterceptor (/usr/local/iobroker/node_modules/iobroker.yahka/main.js:3549:85)
yahka.0 | 2019-11-19 20:34:19.902 | error | at  TIoBrokerInOutFunction_State../yahka.functions/iofunc.base.ts.TIoBrokerInOutFunction_StateBase.subscriptionEvent  (/usr/local/iobroker/node_modules/iobroker.yahka/main.js:2270:18)
yahka.0 | 2019-11-19 20:34:19.902 | error | at  TIoBrokerInOutFunction_State../yahka.functions/iofunc.base.ts.TIoBrokerInOutFunction_StateBase.executeCallback  (/usr/local/iobroker/node_modules/iobroker.yahka/main.js:2278:13)
yahka.0 | 2019-11-19 20:34:19.902 | error | at /usr/local/iobroker/node_modules/iobroker.yahka/main.js:3013:31
yahka.0 | 2019-11-19 20:34:19.902 | error | at Characteristic.On.Characteristic.setValue (/usr/local/iobroker/node_modules/hap-nodejs/lib/Characteristic.js:323:10)
yahka.0 | 2019-11-19 20:34:19.902 | error | at Characteristic.On.emit (events.js:203:15)
yahka.0 | 2019-11-19 20:34:19.902 | error | at Characteristic.On.<anonymous> (/usr/local/iobroker/node_modules/iobroker.yahka/main.js:3025:17)
yahka.0 | 2019-11-19 20:34:19.902 | error | at /usr/local/iobroker/node_modules/hap-nodejs/lib/util/once.js:12:13
yahka.0 | 2019-11-19 20:34:19.902 | error | Error: This callback function has already been called by someone else; it can only be called one time.
yahka.0 | 2019-11-19 20:34:19.902 | error | uncaught exception: This callback function has already been called by someone else; it can only be called one time.
yahka.0 | 2019-11-19 20:34:19.878 | info | adding HK_Presence with UUID: 58b1dff1-b013-42db-93f2-6214f43ca475

**Comment by stuermera** [comment]
Versuch mal dem 2ten Service ein Sub-Service zu geben.
Ich hab das bei einer 4-Fach Verteilerleiste so gelöst, in dem ich den Sub-Service einfach "1" für dne ersten Service, "2" für den zweiten usw. genannt hab.

**Comment by krobipd** [comment]
> 
> 
> Versuch mal dem 2ten Service ein Sub-Service zu geben.
> Ich hab das bei einer 4-Fach Verteilerleiste so gelöst, in dem ich den Sub-Service einfach "1" für dne ersten Service, "2" für den zweiten usw. genannt hab.

vielen lieben dank für den tipp. hatte gerate selbst das problem. fatal error ohne ende. einfach wie du geschrieben hast oben bei rechts bei sub-service 1,2,3 eingetragen und jetzt läufts wunderbar. eventuelle sollte man überlegen diese nummerierung automatisch im hintergrund zu machen. falls es immer gleich ist, wäre ja sinnvoll.

**Comment by nicoh88** [comment]
Das Problem ist gelöst - ich würde hier zu machen. Eine automatische Nummerierung im Hintergrund wird es voraussichtlich nicht geben. Sorry.
