### ISSUE TITLE
ioBroker still uses version 0.7.1

### ISSUE THREAD

**Issue by d4rkd3v1l** [jensweigele/ioBroker.yahka#148]
Is it correct, that ioBroker still uses version 0.7.1? For me it looks like 0.9.2 is the latest release, so I'm kinda confused, why I cannot upgrade to 0.9.2 using `iobroker upgrade` >.<

**Comment by Patrick12300** [comment]
Go to the adapter tab and click (under the wrench on the upper left) on the github icon and type "yahka" in the field and install it. Then you have the newest version. 
I hope it helped you with your problem :)

**Comment by nicoh88** [comment]
Im Repo ist jetzt die 0.11.0 #171
