### ISSUE TITLE
Service "Television" gone?

### ISSUE THREAD

**Issue by andiweli** [jensweigele/ioBroker.yahka#149]
Hi!

I can remember having a service named "Television" in the service list.
I configured my two TVs as "Television" service and was able to switch them on and off through a button in the "Home"-App on iOS. Simply by assigning the "POWER" switch of the outlet shown in the sonoff-Adapter.

Since a few months this feature is gone.
I can only set outlets and switches.

Any idea?

**Comment by nicoh88** [comment]
Konntest du dein Problem lösen? Wenn ja, wie?

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!

**Comment by andiweli** [comment]
Nein konnte ich nicht lösen. 
Auch seit iOS14 kein TV Gerät möglich. Es wird stattdessen einfach eine Nicht-EU-Steckdose angezeigt.

**Comment by nicoh88** [comment]
@andiweli Ok, hilft das [hier](https://github.com/jensweigele/ioBroker.yahka/issues/190) weiter?

**Comment by andiweli** [comment]
> @andiweli Ok, hilft das [hier](https://github.com/jensweigele/ioBroker.yahka/issues/190) weiter?

Leider nein. 
Bis vor einiger Zeit wurde bei dieser Konfiguration bei mir immer ein TV Gerät in der Home App angezeigt. Seit einiger Zeit aber entweder eine einzelne Steckdose oder eine ganze Kabelleiste. 

![681EEDF5-8DA0-4558-9512-3C6F85986891](https://user-images.githubusercontent.com/11447150/97159410-1d9a4d80-177b-11eb-9610-9c486040c3ad.jpeg)
![BD61ED3D-0D49-4F2F-A613-AFF4E706E92D](https://user-images.githubusercontent.com/11447150/97159418-21c66b00-177b-11eb-83b6-408c0ee87251.png)

**Comment by andiweli** [comment]
So sah es zuvor aus. 
An der Config wurde bei mir in Yahka nichts verändert. 
![B41B7A17-B8CA-4684-A54F-85568DE89AA5](https://user-images.githubusercontent.com/11447150/97159827-b4ffa080-177b-11eb-834e-2a816261192b.jpeg)

**Comment by DanielWeeber** [comment]
Ich müsste es selbst mal testen, aber was mit dem ersten Blick auffällt ist, dass du nicht alle required Charakteristics benutzt. Alle die, die required sind, müssen mindestens mal gesetzt werden.

In der drunterliegenden Library kann man schön nachschauen:

https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/gen/HomeKit-TV.ts#L481

**Comment by andiweli** [comment]
Ich kanns mal durchprobieren, jedoch hatte es ja mit diesen Einstellungen zuvor monatelang funktioniert.

**Comment by jensweigele** [comment]
Mit iOS 14 wurde hier das Verhalten geändert.
Mit dem aktuellen Master kann man das TV Gerät als eigenständiges Gerät veröffentlichen und dann als Kategorie "Television" auswählen.
Die Implementierung ist noch nicht abgeschloßen, sollte aber rudimentär funktionieren.
Es ist nun auch Möglich, die Input-Sources mit dem TV zu verlinken.
Mehr Details sind in meinem letzten Kommentar zu #89 zu finden.

**Comment by nicoh88** [comment]
https://github.com/jensweigele/ioBroker.yahka/wiki/Fernseher-mit-YAHKA-simulieren
