### ISSUE TITLE
Yahka Bridge not visible in Homekit App after iobroker-data backup

### ISSUE THREAD

**Issue by dlukacic** [jensweigele/ioBroker.yahka#151]
I had a issue with my iobroker installation and had to re-install iobroker. To recover my valuable data I copied my backup version of "/opt/iobroker/iobroker-data/objects.json". Everything works except the Homekit. The Yahka Adapter starts fine, alle my old objects and the bridge configuration are visible in the adapter, but I cannot find it in the Homekit app. I tried to setup the old bridge in Homekit app again using my predefined Homekit code in the bridge configuration, but I cannot find the device. When scanning my home network I cannot find a device with the predefined MAC address from the bridge configuration. 

Any hints for me, why the bridge is not seen in my LAN? Thanks so much for your support. 

Davor

**Comment by Baenker** [comment]
I have the same problem. What did you do to solve?

**Comment by dlukacic** [comment]
I needed to integrate the yahka-bridge in homekit app again. In the iOS homekit app you go to your home (most left button on the bottem side of the app). thank click on the "house symbol" on the upper left corner and scroll down to "...& bridges" ...and add the bridge configured in yahka adapter. Hope this helps.
