### ISSUE TITLE
Keine Instanz nach Upgrade auf 0.9.2

### ISSUE THREAD

**Issue by valbuz** [jensweigele/ioBroker.yahka#152]
Nach einem Upgrade von 0.7.1 auf 0.9.2 fehlt meine Instanz.
Adapter wurde bereits gelöscht und neu installiert, ohne Erfolg.
ioBroker Reboot etc. ohne Erfolg.

Bitte um Hilfe.
pat

**Comment by nicoh88** [comment]
@valbuz Konntest du dein Problem lösen? Wenn ja, wie?

**Comment by valbuz** [comment]
Update auf 0.11.0
