### ISSUE TITLE
push button

### ISSUE THREAD

**Issue by drtp** [jensweigele/ioBroker.yahka#157]
Hi, 

sometimes it is advantageous or necessary to use push buttons instead of switches (e.g. for TVs or garage doors or whatsoever). Therefore, I would like to see an option to configure a switch as a push button, which means that the switch automatically goes back into its off state several milliseconds after it was set into its on state. 

Of course, this behaviour could be realized by a simple Javascript. However, this has to be done for every switch which should behave like a push button. For e.g. 100 different TV push buttons this would be somehow confusing in combination with a high effort. A simple push button flag as part of the switch configuration would be a much more simple solution, I guess. 

Best regards,

Thorsten

**Comment by drtp** [comment]
What a pity that it seems nobody is really interested in improving this adapter. There are several things that can be done to make it much more reliable.

**Comment by Apollon77** [comment]
Effectively the logic for a "push button" writing into a states with role "button" in this case needs to be:
* read: returns always false
* write: independetly from set value set value "true"

**Comment by Apollon77** [comment]
> What a pity that it seems nobody is really interested in improving this adapter. There are several things that can be done to make it much more reliable.

Such a post after 11 days of waiting?

**Comment by drtp** [comment]
Well, the yahka adapter is a really cool thing and it works good so far. However, I am a little bit disappointed that its functionality has not been improved for a long time now, although there are a lot of issues. 

For instance, I wonder why nobody seems to be interested in implementing a simple push button functionality that gives the user the opportunity to use such buttons for e.g. opening garage doors or controlling TVs or other devices without having the problem that the respective button within the Home App always toggles between on and off state. 

Okay, we can overcome this problem by writing a respective Javascript that sets the switch back to false after it hast been set to true. However, if you use plenty of push buttons (e.g. for controlling the channels of your TV) it is a little bit - let's say - exhausting to create a Javascript for each of them that does nothing else than switching it back to its off state.

**Comment by izi1** [comment]
Hallo zusammen,
I would also find the pushbutton function suggested by drtp very helpful.

**Comment by nicoh88** [comment]
Ich konnte auch keine Möglichkeit finden, einen ioBroker "Button" über Yahka zu nutzen.

Ich habe in einem solchen Fall, dann immer einen Datenpunkt (true/false) angelegt und bei `true` über ein ioBroker Skript den Button gesteuert. Nach 5 Sekunden, dann wieder zurück auf `false`.

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!

**Comment by DutchmanNL** [comment]
> Ich konnte auch keine Möglichkeit finden, einen ioBroker "Button" über Yahka zu nutzen.
> 
> Ich habe in einem solchen Fall, dann immer einen Datenpunkt (true/false) angelegt und bei `true` über ein ioBroker Skript den Button gesteuert. Nach 5 Sekunden, dann wieder zurück auf `false`.

ist auch die einzige Möglichkeit, es gibt keine buttons in HomeKit da muss man dan apple anbeten
