### ISSUE TITLE
Option to provide advertised IP for docker compatibility

### ISSUE THREAD

**Issue by fefaul** [jensweigele/ioBroker.yahka#158]
Hi,

it would be nice to get an option to provide the advertised IP instead of only allowing us to choose the adapter yahka is listening on. This would be especially helpful when running iobroker in a docker instance, currently the only way to use it is to assign an IP "main network" all other devices are in, to the container.

Seems the guys from home assistant solve the issue
docker-compose -f iobroker-compose.yml up

https://www.home-assistant.io/integrations/homekit/#advertise_ip

Some more details can be found in this thread https://github.com/home-assistant/home-assistant/issues/15692

Would be nice to see this feature integrated. I'd be volunteering to test and provide assistance.

**Comment by Anzic23** [comment]
is there any solution? could it be temporary?

**Comment by jensweigele** [comment]
Can please somebody test the following:
Go to the settings and select the 0.0.0.0 interface -> Save & Close
Go to "Objects" in ioBroker Admin, enable the expert mode
Search for "system.adapter.yahka.0" and click the edit button
Under "Native" you can find the different configs for the bridges and cameras. 
Make the textfield larger and search for 
```
  "interface": "0.0.0.0"
```
Change "0.0.0.0" to the ip you would like to publish the service and hit save.
The adapter should be restarted.

If that solves you problem, I can just add the ability to put in the IP address manually via the Yahka-Admin interface

**Comment by jensweigele** [comment]
Closed due to inactivity

**Comment by Master-Rudi** [comment]
I tried your solution but it did not work for me on a Unraid docker system. In a further system on a raspberry it worked fine. After transferring it to Unraid Docker I can not find Yahka on my Phone

I used the port of my NAS 192.168.178.121 and the port 1885 and forwarded the port 1885 to the internal Docker IP in the docker config.
