### ISSUE TITLE
Kamera zufügen - Windows 10 - FFmpeg

### ISSUE THREAD

**Issue by funboxbolzer** [jensweigele/ioBroker.yahka#159]
Hallo, 
ich habe den iobroker auf einem Windows10 laufen. Mein Yahka funktioniert auch wunderbar. Nur habe ich ein Problem beim zufügen einer Kamera. sobald die Kamera im Homekit zugefügt wird und ich das Bild streamen will, gibt es einen Error im Adapter. Aus der Meldung habe ich gelesen, dass FFmpeg nicht installiert ist. Ich habe dies jetzt nach [https://de.wikihow.com/FFmpeg-unter-Windows-installieren](url) dieser Anleitung installiert.
Leider funktioniert es trotzdem nicht.
Gibt es da eine Workaround oder ist es unter Windows nicht möglich eine Kamera zu integrieren? 
Gruß Klaus

**Comment by nicoh88** [comment]
Hi Klaus,

konntest du dein Problem lösen?
Wenn ja, wie?
Wenn nein, kannst du eine genauere Fehlermeldung posten?

Viele Grüße

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!
