### ISSUE TITLE
Error: bind EADDRINUSE

### ISSUE THREAD

**Issue by MaikB85** [jensweigele/ioBroker.yahka#162]
Hi,

ich hab Probleme den YAHKA-Adapter ans Laufen zu bekommen. Das Problem habe ich, seit ich den iobroker Server gewechselt habe. iobroker läuft bei mir jetzt in einem Jail auf FreeNAS (FreeBSD). Der Adapter startet gar nicht erst. Hier mal ein Auszug aus meiner LOG:
`host.iobroker	2020-02-10 11:09:13.900	info	Restart adapter system.adapter.yahka.0 because enabled
host.iobroker	2020-02-10 11:09:13.899	info	instance system.adapter.yahka.0 terminated with code 0 (NO_ERROR)
host.iobroker	2020-02-10 11:09:13.899	error	Caught by controller[0]: port: 5353 }
host.iobroker	2020-02-10 11:09:13.899	error	Caught by controller[0]: address: '192.168.2.17',
host.iobroker	2020-02-10 11:09:13.899	error	Caught by controller[0]: syscall: 'bind',
host.iobroker	2020-02-10 11:09:13.899	error	Caught by controller[0]: code: 'EADDRINUSE',
host.iobroker	2020-02-10 11:09:13.899	error	Caught by controller[0]: errno: 'EADDRINUSE',
host.iobroker	2020-02-10 11:09:13.899	error	Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
host.iobroker	2020-02-10 11:09:13.899	error	Caught by controller[0]: at state.handle.lookup (dgram.js:242:18)
host.iobroker	2020-02-10 11:09:13.899	error	Caught by controller[0]: { Error: bind EADDRINUSE 192.168.2.17:5353
yahka.0	2020-02-10 11:09:13.394	info	(95009) Terminated (NO_ERROR): Without reason
yahka.0	2020-02-10 11:09:13.394	info	(95009) terminating
yahka.0	2020-02-10 11:09:13.380	info	(95009) cleaned up ...
yahka.0	2020-02-10 11:09:13.379	info	(95009) cleaning up ...
yahka.0	2020-02-10 11:09:13.379	error	(95009) Error: bind EADDRINUSE 192.168.2.17:5353 at state.handle.lookup (dgram.js:242:18) at process._tickCallback (internal/process/next_tick.js:63:19)
yahka.0	2020-02-10 11:09:13.379	error	(95009) uncaught exception: bind EADDRINUSE 192.168.2.17:5353
yahka.0	2020-02-10 11:09:13.371	info	(95009) adding Licht_Ben_Leon with UUID: dc96eb0e-b61d-4c71-8938-5c6a1f3ad7ed
yahka.0	2020-02-10 11:09:13.369	info	(95009) adapter ready, checking config
yahka.0	2020-02-10 11:09:13.364	info	(95009) starting. Version 0.10.0 in /opt/iobroker/node_modules/iobroker.yahka, node: v10.17.0`

wenn ich als IP 0.0.0.0 auswähle habe ich die gleiche Meldung. Der Port ist irgendwie immer 5353. selbst wenn ich als Port einen vorgebe, steht in der Log immer noch 5353. Die IP Adresse die oben in der Log steht ist die IP unter der der iobroker Server erreichbar ist. 

Da die Konfiguration vorher unter einem Raspberry einwandfrei lief, vermute ich es hängt auch mit dem FreeNAS/FreeBSD Jail zusammen. Ich weiß nur nicht was ich machen kann. Wäre schon hilfreich, wenn ich mal einen anderen Port testen könnte.

Gruß Maik

**Comment by nicoh88** [comment]
Hi Maik, konntest du dein Problem lösen? Wenn ja, wie?

Gruß Nico

**Comment by MaikB85** [comment]
Nein leider nicht. Hängt wohl irgendwie mit den Jails zusammen in FreeNAS. Deshalb hab ich eine Ubuntu VM erstellt in FreeNAS. So läuft es dann. Wegen den Systemressourcen wäre mir die Jail Variante allerdings lieber gewesen. Konnte aber nirgends im Internet eine Lösung finden.

**Comment by nicoh88** [comment]
Hmm, okay. Da werden wir sicherlich nichts machen können - scheint an FreeNAS zu liegen.

Danke für die Info!
Ich mache hier zu.

**Comment by MaikB85** [comment]
Ja FreeNAS oder FreeBSD. Die librarys die es für Linux gibt, gibt es so nicht direkt für FreeBSD.
