### ISSUE TITLE
Upgrade to new nodejs-hap 0.5

### ISSUE THREAD

**Issue by Apollon77** [jensweigele/ioBroker.yahka#164]
... but this is a complete rewrite in ts ... so some things are different and also buffer-shim is no oger there and all such stuff ... I had a short try but gave up :-(

**Comment by jensweigele** [comment]
I started working some weeks ago but didn't find the time to complete. I'm going to publish my dev-branch on github so that others can continue.
I also try to find some time to continue on it.

**Comment by Apollon77** [comment]
No problem!
We currently test in a small group a 0.11.0 with updated hap-nodejs to latest 0.4.x to support nodejs 12 because we want to declare nodejs 12 as "nodejs version to go for iobroker" ... So it is not that pressing (besude all the fixes and stuff in hap 0.5 :-)) )

We had a first naive try with 0.5 in the test group, but I learned that it is more then just upgrading dep and replacing some paths ;-)

**Comment by Apollon77** [comment]
If you want check the PRs if one of those should also go into the 0.11.0 then would be good idea :-)

**Comment by nicoh88** [comment]
👍

**Comment by Apollon77** [comment]
@nicoh88 It is better to use "thumbs up" on first post instead posting "+1" :-)

**Comment by nicoh88** [comment]
Hi Ingo,

da hast du Recht. Aber bei einem 👍 bei deinem Post, würde @jensweigele keine Benachrichtigung bekommen (sollte er überhaupt noch welche bekommen). Ich bin aber guter Dinge, dass wir ihn 2020 wieder motiviert bekommen und eine glorreiche Zeit für den YAHKA-Adapter bevorsteht. 🥇 

Gruß Nico

**Comment by jensweigele** [comment]
Im Aktuellen Master ist die letzte nodejs-hap Version integriert!
