### ISSUE TITLE
Menüleiste fixieren

### ISSUE THREAD

**Issue by albbino** [jensweigele/ioBroker.yahka#166]
Es wäre überaus praktisch wenn die Menüleiste
`[+ Gerät hinzufügen | + Kamera hinzufügen | - Gerät entfernen | + Gerät duplizieren | Service hinzufügen ]`

oben fixiert wäre und nicht beim scrollen der Geräte aus dem Bild verschwindet. Hat man viele Geräte und will zu einem Gerät einen Service hinzufügen muss man erst nach unten scrollen das Gerät auswählen und dann wieder komplett nach oben scrollen um die Menüleiste zu sehen. Unpraktisch wie ich finde.

**Comment by drtp** [comment]
Kann ich nur begrüßen. Hatte es [hier im ioBroker-Forum](https://forum.iobroker.net/topic/3778/yet-another-homekit-adapter/1003) auch schon mal angesprochen.

**Comment by nicoh88** [comment]
@Alanin Danke. Sorry, dass es so lange gedauert hat.

Was mir aufgefallen ist, schon vor deinen Änderungen: Wenn man in einem Gerät, mehrere Services hat und einen davon löscht, schmeißt es einem direkt aus dem Menü und man muss das Gerät, links an der Leiste neu auswählen, kannst du dir das mal anschauen?

Danke

**Comment by nicoh88** [comment]
@Alanin Habe es mir gerade nochmal angeschaut. Irgendwie, müssen wir uns da was anderes überlegen! 💣

Der "Geräte" Bereich muss vom "Eigenschaften und Dienste" Bereich getrennt werden und unabhängig voneinander scrollbar sein. Wenn ich aktuell ein Gerät am Ende der Liste auswählen, muss ich wieder hochsollen, damit ich die "Eigenschaften und Dienste" zu sehen.

Sorry, dass du nochmal ran musst. Mein Fehler, habe den Wunsch, das Ziel nicht genauer definiert. Verstehst du was ich meine? Würde mein Vorschlag das Problem lösen?

Viele Grüße

**Comment by Alanin** [comment]
Bekommen wir hin. Muss mal schauen wann genau. Wollte nicht gleich zu viel umbauen. Aber ich entkopple das.

**Comment by Alanin** [comment]
Bin leider noch nicht dazu gekommen. Zu viel auf Arbeit zu tun. Aber ich bin dran.

**Comment by jensweigele** [comment]
Ist im aktuellen Master nun korrekt umgesetzt

**Comment by nicoh88** [comment]
@jensweigele Sieht aber nicht ganz optimal aus oder? 😅 Safari Problem?

<img width="1028" alt="Bildschirmfoto 2020-11-20 um 23 34 31" src="https://user-images.githubusercontent.com/264264/99856870-3afbe500-2b8a-11eb-9c38-c4dff29b1be6.png">

**Comment by jensweigele** [comment]
@nicoh88 probier es nochmal mit dem aktuellen Master ;-)

**Comment by nicoh88** [comment]
Perfekt! Läuft!
