### ISSUE TITLE
Service Binding to 0.0.0.0 not working

### ISSUE THREAD

**Issue by h-alf** [jensweigele/ioBroker.yahka#167]
The service is not reachable via wlan0 if the binding is set to 0.0.0.0.

**Comment by nicoh88** [comment]
Can you speak german? Have you already solved the problem?

**Comment by h-alf** [comment]
Hi,

klar, deutsch geht auch.

Problem nach wie vor existent. 
Wenn ich yahka an alle interface binde (0.0.0.0), dann ist es per home app nicht erreichbar.
Wenn ich yahka wieder zurück auf ein interface lege, ist es wieder erreichbar.

freundliche grüße
harald

**Comment by nicoh88** [comment]
Komisch. Bei mir läuft es über `0.0.0.0` - aktiv ist `eth0`, `wlan0` oder ein anderes Interface wird nicht genutzt.

Ich entnehme deiner Nachricht, dass du `wlan0` aktiv nutzt. Läuft über `ethX` auch Traffic? Oder sind die restlichen Interface außer `wlan0` down?

Aktuellste Version von iobroker.yahka hast du installiert?

```
cd /opt/iobroker
npm list --depth=0 | grep -i yahka
```

`├── iobroker.yahka@0.11.0`

Gruß Nico

**Comment by h-alf** [comment]
Hallo Nico,

ich nutze sowohl wlan0 als auch eth0 in unterschiedlichen subnetzen.

Ich habe Sensoren in beiden subnetzen.

Yahka ist in der neuesten Version installiert.

Auf welchem Port läuft yahka?
Ich könnte einen portscan auf den interfaces machen.

Freundliche Grüße 
.h

**Comment by DanielWeeber** [comment]
Hier sind definitiv mehr Infos zum Setup notwendig. Wird aber eher am Installationsort liegen, als an Yahka.

**Comment by h-alf** [comment]
Kein Problem, was brauchst du?

Freundliche Grüße 
.h

**Comment by DanielWeeber** [comment]
Naja, einfach alle Infos zu deinem Setup. Auf was für HW, Docker, virtualisiert, welche NICs, Firewalls, etc.

**Comment by h-alf** [comment]
Hardware Raspberry Pi 4, 4GB

debian 10.4

eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 192.168.9.100/24 brd 192.168.9.255 scope global dynamic noprefixroute eth0
       valid_lft 863233sec preferred_lft 755233sec
    inet6 fe80::7dda:994f:4e9d:2a9c/64 scope link
       valid_lft forever preferred_lft forever
wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    inet 192.168.99.100/24 brd 192.168.99.255 scope global dynamic noprefixroute wlan0
       valid_lft 68096sec preferred_lft 57296sec
    inet6 fe80::ee99:c44c:96ae:a3b6/64 scope link
       valid_lft forever preferred_lft forever

eth0 und wlan0 integriert im Pi.

Sowohl web.0 als auch vis.0 reagieren auf beiden interfaces.

Sensoren sind sowohl im 192.168.99.0/24 als auch im 192.168.9.0/24 Netz, alle sind erreichbar.

Brauchst Du sonst nochwas?

**Comment by DanielWeeber** [comment]
netstat -rn, bitte

Du hast Yahka aber nicht nur auf ein Interface gebunden, oder?
0.0.0.0 muss nicht jedes Interface heissen.

Der Sinn das auf mehreren Interfaces zu haben ergibt sich mir aber auch noch nicht ganz. Deine Clients werden nur in einem Netz davon sein.

![Bildschirmfoto 2020-08-15 um 12 03 49](https://user-images.githubusercontent.com/2935130/90334424-c71bd080-dfcd-11ea-84d0-6c3e184bbacb.png)

**Comment by h-alf** [comment]
Hi Jens,

hier der output:

Kernel-IP-Routentabelle
Ziel            Router          Genmask         Flags   MSS Fenster irtt Iface
0.0.0.0         192.168.9.254   0.0.0.0         UG        0 0          0 eth0
0.0.0.0         192.168.99.254  0.0.0.0         UG        0 0          0 wlan0
192.168.9.0     0.0.0.0         255.255.255.0   U         0 0          0 eth0
192.168.99.0    0.0.0.0         255.255.255.0   U         0 0          0 wlan0

> Du hast Yahka aber nicht nur auf ein Interface gebunden, oder?
> 
Momentan habe ich Yahka nur auf das 192.168.99.100 if gebunden, da dort die meisten Clients geroutet ankommen.
Auf dem 192.168.9.100er if kommen nur die Clients die über VPNs an.
Wenn ich auf 0.0.0.0 - Listen on all interfaces Stelle bekomme ich keine Verbindung mehr aus dem 99er Netz, noch nicht einmal, wenn ich mich direkt im gleichen Subnetz (kein routing) befinde. Der Zugriff aus dem 9er Netz funktioniert bei 0.0.0.0.
Es sieht für mich so aus, als ob bei 0.0.0.0 nur das erste if in der metrik genommen wird (eth0).

Das mit den Sensoren und Clients in verschiedenen VLANs ist wahrscheinlich meinem Beruf geschuldet, ich bin Senior Network Engineer. Ich habe momentan 23 VLANs mit entsprechenden Routern/Firewalls laufen.
Die Firewalls habe ich für die Tests auf Durchzug gestellt.

Wenn ich Yahka einen fixen Port über die Config verpasse, sollte ich mit netstat oder nmap eigentlich sehen können, ob der Dienst an die jeweiligen ifs gebunden ist.
Welcher Port ist hier sinnvoll?
Oder kann ich irgendwo im Log sehen, welches random port sich der Dienst gezogen hat?

Falls du noch irgendwelche Informationen benötigst, gib bitte Bescheid.

Freundliche Grüße
Harald

**Comment by jensweigele** [comment]
Yahka kann hier leider nicht viel machen. Yahka nutz HAP-NodeJS, welches wiederum die Bibliothek @homebridge/ciao nutzt.
HomeKit nutzt für das Auffinden der Geräte/Bridges und für Verbindungsaufbau "Bonjour". Dafür gibt es diverse Tools zum analysieren des Protokolls. Soweit ich weiß, kann auch Wireshark das Bonjour Protokoll parsen.
Vielleicht kannst du darüber etwas rausfinden und ggfls. ein wenig bei den HAP-NodeJS bzw. ciao-Repositories recherchieren.

 Solltest du Infos finden, kannst du dich gerne melden!
