### ISSUE TITLE
Homekit lightbulb ColorTemperature in kelvin

### ISSUE THREAD

**Issue by 0x1234567890** [jensweigele/ioBroker.yahka#168]
I cant setup the ColorTemperature in my homekit lightbulb.

![image](https://user-images.githubusercontent.com/1353407/75121824-15dc5380-5698-11ea-9e49-f3529b11f62a.png)

but the color temperatue will be send in range from 140 to 500. (140 = cold; 500 = warmwhite)

![image](https://user-images.githubusercontent.com/1353407/75121844-49b77900-5698-11ea-9713-b12e05088183.png)

How i can control it?

My Range in Kelvin is from 2700 to 6500.

![image](https://user-images.githubusercontent.com/1353407/75121882-a87cf280-5698-11ea-980b-473ca7c6a2ac.png)

**Comment by nicoh88** [comment]
@0x1234567890 

You are German? You need a little script, to convert homekit-values to kelvin.

```
HomeKit: 140 to 500
Yeelight: 2700 to 6500.
```

Example, quick'n'dirty:
![Bildschirmfoto 2020-06-08 um 21 16 34](https://user-images.githubusercontent.com/264264/84071045-5fde1080-a9cd-11ea-9957-fd2fc762408d.png)


To HomeKit:
```
if (value < 3000) {
return 140;
} else if (value < 4000) {
return 300;
} else if (value < 5000) {
return 400;
} else {
return 500;
}
```

To IOBroker:
```
if (value <= 140) {
return 3000;
} else if (value <= 300) {
return 4000;
} else if (value <= 400) {
return 5000;
} else {
return 6500;
}
```

@jensweigele 

Klingt nach einer neuen `Conversion` oder? `ColorTempKelvinToHomeKit`

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!
