### ISSUE TITLE
Feature Request: Add Conversion Functions Editor

### ISSUE THREAD

**Issue by captaindork** [jensweigele/ioBroker.yahka#17]
Hi yahka Team,

while yahka allows for some built-in conversion functions, there are a lot more required to get homematic or other devices mapped properly to homekit devices. Most of times there is not more than 4 states that need to be translated to 4 different states, but sometimes it is just a function/calculation e.g. RGB to hue and saturation... or 0 and 1 to false and true... 

It would be great to have some feature that would allow to add custom conversion functions.

**Comment by DanielWeeber** [comment]
+1, please revive

**Comment by jensweigele** [comment]
With the current master, you can now use the conversion function "Script" to add custom functions.
If you have multiple devices with the same conversion functions, you need to copy+paste those scripts currently.
If you have some conversion functions, just open an issue with your functions and I'll try to incorporate them into the next release.
