### ISSUE TITLE
Banchrichtigung an Applewatch schicken

### ISSUE THREAD

**Issue by Micha996** [jensweigele/ioBroker.yahka#170]
Hallo,

ist es möglich an meine Applewatch bzw IPhone eine Banchrichtigung zu schicken wenn z. Bsp die Türklingel betätigt wird. 

Ich habe die Türklingel mit homematic über iobroker eingebunden..

**Comment by drtp** [comment]
Ja, z.B. mit Pushover oder Telegram. Ist aber keine Sache des yahka-Adapters.

**Comment by Micha996** [comment]
Ja das habe ich auch schon ausprobiert, ich dachte das ginge wie z. Bsp mit dem Rolladenaktor,  wenn ich da das Rollo öffne bzw schließe bekomme ich eine Mitteilung von Homekit..  Zbsp Rolladen würde geöffnet bzw.  geschlossen.

**Comment by krobipd** [comment]
das ist ganz einfach, geht aber nur bei sensoren.
einfach bei dem gekoppelten iphone die benachrichtung für den sensor einschalten und schon erscheint die meldung auch auf der apple watch.

**Comment by Marty56** [comment]
Leider kann man den Text nicht dynamisch ändern. Es wird immer nur der Name beim Einrichten des Geräts übernommen.

**Comment by drtp** [comment]
Du kannst doch den Namen eines Geräts jederzeit nachträglich in der Home App ändern. Mach ich auch, weil das z.B. direkten Einfluss auf die Sprachsteuerung per Siri hat.

**Comment by Marty56** [comment]
Das ist ja nicht gerade "dynamisch". Was ich meine ist, dass iobroker den Namen ändert und damit eine Art Messaging per Home App realisieren kann.

**Comment by drtp** [comment]
Der ganze yahka-Adapter ist doch so ausgelegt, dass man jedes einzelne Gerät manuell anlagen und verwalten muss. Das geht z.B. über die Homebridge über die config.json bei HomeMatic-Geräten  deutlich einfacher. Aber leider ist der yahka-Adpater so nicht angelegt. Daher macht es aus meiner Sicht auch keinen großen Sinn, wenn hier irgendwelche Automatismen zur Namensgebung im Hintergrund laufen. Vor allen Dingen dann nicht, wenn sie nicht so arbeiten würden, wie man sich das vorstellt. Und da hat wohl jeder seine eigenen Wünsche und Vorlieben.

**Comment by nicoh88** [comment]
@Marty56 Du kannst dich über ioBroker Skripts beispielsweise per Telegram benachrichtigen lassen, wenn sich ein Objekt durch die Steuerung von HomeKit / YAHKA in inBroker ändert. 

Seitens YAHKA ist hier nichts anderes vorgesehen - da ist das Apple Ökosystem sehr begrenzt. Hier kannst du nur auf die Standardbenachrichtigungen, die in Apple Home einstellbar sind, zurückgreifen - bei Bewegungsmeldern oder ähnlichem.
