### ISSUE TITLE
Bridge erscheint nicht nicht in Home App

### ISSUE THREAD

**Issue by jul1792** [jensweigele/ioBroker.yahka#174]
Hallo zusammen,
leider erscheint die iobrokerbridge nicht in der Home App. Ich habe auch den Namen der Bridge geändert, sodass keine Sonderzeichen mehr drin sind. 
Ich habe iobroker auf einem OpenMediaVault Server via Docker installiert. Könnte das das Problem sein?  
Ich möchte gerne YAHKA nutzen, um auf meine Homematic IP Thermostate (über Access Point) zuzugreifen.
Weiß hier jemand eine Lösung?
Danke!

**Comment by jul1792** [comment]
Ich habe auf dem gleichen Server übrigens noch Homebridge laufen. Könnte das das Problem sein?

**Comment by TheMBeat** [comment]
Hallo @jul1792,

ich habe das selbe Problem, jedoch noch keien Lösung gefunden. 
Wie hast du das Network deines ioBroker Container gesetzt? 
Wahrscheinlich im Bridge-Mode, eine möglich Lösung könnte sein hier Host zu verwenden, dies hat bei mir allerdings noch nicht funktioniert.

Gruß

**Comment by jul1792** [comment]
Hallo @TheMBeat 
danke für deinen Tipp. Tatsächlich war das die Lösung. Ich habe den Container einfach auf Host umgestellt und sofort erschien der iobroker-Hub in der Home-App.
Vielleicht klappt es bei dir auch demnächst. Wenn du Fragen zu meinen Docker-Einstellungen hast, dann schreib hier gerne.

Beste Grüße

**Comment by TheMBeat** [comment]
Hallo @jul1792 ,
leider funktioniert es bei mir nicht. Ich kann nachdem ich den Container auf Host gestellt habe, die Webinterface garnicht mehr erreichen. Der Container startet jedoch ordnungsgemäß.
Beste Grüße

**Comment by nicoh88** [comment]
@TheMBeat Konntest du dein Problem mittlerweile lösen?

[Avahi](https://github.com/jensweigele/ioBroker.yahka#missing-avahi-daemon-linux) ist installiert?

**Comment by royakaacky** [comment]
@jul1792  @TheMBeat 

Ich hatte das Problem auch mal. Der Standardname des Servers im Adapter ist bei mir "yahka.0" gewesen. Also nicht die Instanz des Apdaters. Sondern der Name des Homekit Servers. Ich hatte irgendwo gelesen, dass das nicht sein darf. Ich hatte den Namen nach "HomeKitServer" geändert. Dann ging es.

**Comment by thogens** [comment]
Hi,
ich habe genau dasselbe Problem. DerAdapter lief eine Weile einwandfrei und nachdem ich kürzlich einiges geupdatet hatte, habe ich gar nicht mehr nach dem Adapter geschaut.
Heute wollte ich ein neues Gerät verknüpfen, welches aber nicht am iPhone erschien.
Nachdem ich alles gelöcht und wieder installiert habe, sehe ich die Bridge nicht mehr.
Ich habe:
- den Namen geändert
- am iPhone alle Geräte gelöscht
- ioBroker läuft bei mir im Docker auf meiner Synology als "Bridge". 
-> Sollte das das Problem sein?
Wie kriege ich das auf Host umgestellt? Muss ich ioBroker neu aufsetzen?

Danke und Gruß,
Thomas

**Comment by nicoh88** [comment]
@thogens 

Wenn du eh schon alles gelöscht hast ...
Hast du nur den "Namen" geändert? Wichtiger wäre der "**Benutzername**" - wenn du die Bridge nicht sauber, während noch eine Konnektivität bestanden hat, aus HomeKit entfernt hast.

![Bildschirmfoto 2020-06-14 um 21 01 35](https://user-images.githubusercontent.com/264264/84601761-daea6f80-ae82-11ea-8ac3-f3be17c3c555.png)

Avahi läuft? Mit einem Netzwerkscanner kannst du prüfen ob "hap" über Avahi / Bonjour veröffentlicht wird.

![4548js](https://user-images.githubusercontent.com/264264/84601857-97443580-ae83-11ea-99f4-ca09319284c5.gif)

Viele Grüße

**Comment by TheMBeat** [comment]
@nicoh88 ich konnte das Problem bisher nicht lösen. Habe es leider auch noch nicht weiter verfolgt. Avahi ist installiert und der Adapter starte auch richtig. Den Namen habe ich auch geändert.
Ich werde, wenn ich Zeit habe mal einen Netzwerkscanner testen.

**Comment by TheMBeat** [comment]
Hallo @nicoh88 ich konnte nach langer Zeit ein wenig weiter testen und habe einen Weg gefunden.
1. ioBroker läuft in einem Container mit MACVLAN für einen eigene IP --> Nachteil, Host und Container können nicht einfach kommunizieren. Wird aber benötigt, da in einem anderen Container (Net Bridge) eine DB läuft.
2. Grobe Lösung: Auf dem Host eine virtuelle MACVLAN Schnittstelle erstellen im Mode Bridge und anschließend eine Route anlegen.

Genauere Artikel:
https://blog.oddbit.com/post/2018-03-12-using-docker-macvlan-networks/
https://collabnix.com/2-minutes-to-docker-macvlan-networking-a-beginners-guide/
