### ISSUE TITLE
Adapter nicht erreichbar nach Wechsel der APs im selben Netz

### ISSUE THREAD

**Issue by rainbowcat1989** [jensweigele/ioBroker.yahka#175]
Hallo,

sobald ich den AP Wechsel im selben Netz ( Unifi) ist der Adapter nicht mehr erreichbar und die Geräte stehen mit "keine Antwort" da . 

Alle anderen Funktionen sind natürlich gewährleistet . (Internet ,Verbindung zum Iobroker Host etc.)

Ich habe lange nach dem Fehler gesucht warum im Schlafzimmer Apple Home nicht funktioniert , aber im Wohnzimmer. Nun ist mir klar , sobald der Client der in meinem Fall das iPhone /Ipad ist auf den anderen Access Point wechselt, funktioniert es nicht mehr. 

Alle Netzwerk relevanten Daten bleiben gleich beim Wechsel . (IP-Adresse , Mac-Adresse und das Netz) . 

Ist hier etwas bekannt ?

Gruß

Marcus

**Comment by synth3** [comment]
Hallo - ich hatte ein ähnliches Problem:
- Neuer AP hinter dem alten Router/Modem
- Netz des alten Routers ohne Beschränkungen über den neuen AP verfügbar gemacht
- Meine Geräte verbinden sich nur noch über den neuen AP
- Seitdem war die eingerichtete Bridge/deren Geräte nicht erreichbar

Ich habe das Problem für mich lösen können, indem ich:
- Bridge-Config in eine neue Instanz kopiert habe
- den `pincode` und `username` geändert habe
- die "neue" Bridge zu Homekit hinzugefügt und dann die "alte" Bridge aus Homekit gelöscht habe.

Das hilft dir nicht wirklich - ich weiß, aber evtl. hilft es um die Ursache herauszufinden.
Aber als (etwas unschönen) workaround könntest du eine weitere Instanz für deinen neuen AP zu Homekit hinzufügen...

Ich könnte mir vorstellen, dass sich Homekit beim Pairing Hardwaremerkmale vom AP merkt. Gggfs. hat man die Probleme nicht, wenn man einen Apple-TV, ein iPad oder einen HomePot als Homekit Steuerzentrale dazwischen hat.
Aber das sind nur Ideen/Vermutungen - wirklich Ahnung habe ich davon nicht. ;)

**Comment by nicoh88** [comment]
@rainbowcat1989 Konntest du dein Problem lösen? Wenn ja, wie?

**Comment by Baenker** [comment]
Das ist aber doch kein Problem von yahka!? Das selbe Problem wird in den Netz bestehen mit anderen Bridges. Vermutlich ist es ein Problem von den AP bzw den Netzwerk und dessen Einstellungen. Ich habe bei mir mehrere AP. Es ist völlig egal wo mein Iphone, ipad oder Apple Watch sich einloggt. Homekit funktioniert immer und auch dann wenn es nicht im Netz ist sondern ich auf der Arbeit oder im Urlaub bin. Da man in Yahka aber nichts einstellen kann womit das zusammen hängt, wird Yahka eher nicht das Problem sein... Gerade Unify ist ein sehr gutes System aber man muss es halt entsprechend administrieren und dazu sich entsprechend gut auskennen damit das System so arbeitet wie man es will. Sonos User haben auch immer mal wieder mit Ihren Unfify System zu kämpfen bis es rund läuft. Yahka ist es schlicht egal wo das Endgerät sich aufhällt. Yahka kommuniziert doch nur mit der Homekit-Zentrale.

Die spannenden Fragen sind also: Funktionieren andere Bridges mit der Konfiguration? Funktioniert Homekit außerhalb vom eigenen Netzwerk?

**Comment by nicoh88** [comment]
Ich kann mich da @Baenker nur anschließen. Es ist definitiv kein Problem das Adapters - dennoch wollen wir natürlich zu helfen, wenn hier noch Interesse besteht.

Grundlegend ist Apple der Netzwerkaufbau völlig egal welcher Hersteller, welches Netz, usw. - hier wird auch nichts gespeichert. Ich habe vor ein paar Tagen alle meine WLAN-APs von FRITZ!Repeatern 1750E auf TP-Link RE450 mit `OpenWRT` umgestellt - auch der Router wurde getauscht (FRITZ!Box 6490 Cable > Vodafone Station mit deaktiviertem WLAN und DHCP). DNS, DHCP & VPN macht jetzt ein Raspberry Pi mit `Pi-Hole` direkt an der Vodafone Station. Nichts ist mehr wie vorher und ioBroker in Verbindung mit Yahka funktioniert wie vorher ohne Probleme.

--

Macht der neue **Unifi-AP** ein neues Netzwerk auf? Da kommerzielle Lösungen für fachlich unerfahrene Endanwender die Einrichtung so einfach wie möglich gestallten wollen, wird bei einem AP oder Repeater oftmals ein zweites Netz aufgemacht. Oder hat der **Unifi-AP** eine passende IP im bestehenden `/24` Netzwerk?

Hat der neue **Unifi-AP** eine Firewall? Gerne werden hier Bonjour-, Avahi- und UPNP-Pakete gefiltert, was zu deinem Fehlerbild passen würde.

--

Gruß Nico

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!
