### ISSUE TITLE
Nach restore auf anderer Maschine keine Funktion

### ISSUE THREAD

**Issue by Marty56** [jensweigele/ioBroker.yahka#176]
Ich musste eine neue Maschine aufsetzen und habe dazu das Backup eingespielt.
Der Yahka Adapter ist grün, im log werden die UIDD von den diversen Geräten angezeigt, aber die Verbindung zu HomeKit schlägt fehl.

**Comment by nicoh88** [comment]
Hallo @Marty56, konntest du dein Problem lösen? Wenn ja, wie?

In der Adapter-Konfiguration sollte der `Benutzername` (meisten eine Mac-Adresse) und der `Pin-Code` gleich sein.

**Comment by Baenker** [comment]
Damit es wieder geht muss man leider in Homekit die Geräte löschen und im Adapter eine neue Mac Adresse vergeben danach findet Homekit den Adapter wieder und man kann alles wieder steuern. Eine andere Möglichkeit gibt es leider nach einen restore nicht. Zumindest war es bei mir so.

**Comment by nicoh88** [comment]
Echt? Das ist natürlich nicht schön, wenn man in HomeKit dann die Räumen, Szenen und ggf. Automationen neu erstellen bzw. zuordnen muss. 😢 

Normale `homebridge` Installationen habe ich schon mehrfach erfolgreich umgezogen. Warum sollte das mit ioBroker nicht gehen? Ich versuche es mal nachzustellen.

**Comment by Marty56** [comment]
> Hallo @Marty56, konntest du dein Problem lösen? Wenn ja, wie?
> 
> In der Adapter-Konfiguration sollte der `Benutzername` (meisten eine Mac-Adresse) und der `Pin-Code` gleich sein.

MIt der Holzhammermethode. Die Yahka Bridge in der Home App löschen, damit auch alle Regeln und dann eine neue Yahka Bridge neu dort installieren und wieder alle Regeln manuell eintippen.

**Comment by nicoh88** [comment]
Das sollte so eigentlich nicht sein.

**Was und wie habt ihr wiederhergestellt?** Das gesamte `/opt/iobroker` Verzeichnis, nur bestimmte Dateien oder über welche Methode?

**Comment by Baenker** [comment]
Komplette Neuinstallation iobroker. Nur minimal ohne Adapter oder so. Danach restore von einen Backup von ioBroker (Backup wurde über Backup-Adapter erstellt). Minimal-Backup.

Nach Abschluß vom Backup waren alle Adapter installiert und Yahka war auch grün aber HomeKit zeigte alle Geräte ohne Antwort an.

Bei mir läuft das ganze im Docker. Das ist aber nebensächlich.

**Comment by nicoh88** [comment]
Würde das gerne mal nachstellen, weil es für mich auch wichtig wäre zu wissen. Heißt der Adapter "[Backitup](https://www.npmjs.com/package/iobroker.backitup)"?

**Comment by Baenker** [comment]
Ja. Das Backup ist aber das gleiche welches man mit iobroker backup per Terminalbefehl erstellen kann.

**Comment by nicoh88** [comment]
Ich kann das Problem **reproduzieren**. Habe bis jetzt keine Lösung gefunden.

`Username`/`MAC` ist in der in Adapter-Konfiguration gleich, habe es auch mal mit einem festen Port probiert, ohne Erfolg. Wobei nur der `Username`/`MAC` ausschlaggebend ist! Mit Homebridge habe ich es schon ein paar mal gemacht - da kopiert man den gesamten Ordner inkl. `accessories` und `persist`. Keine Ahnung, was hier jetzt anderes ist.

Aufgefallen ist mir der Ordner `yahka.0.hapdata` unter `/opt/iobroker/iobroker-data/`, aber auch damit, in unterschiedlichen Reihenfolgen, brachte mich nicht zum Erfolg. 
Die Geräte UUIDs bleiben auch gleich ...

@jensweigele Hast du einen Tipp für uns?

**Comment by nicoh88** [comment]
Dokumentiert im Wiki:
https://github.com/jensweigele/ioBroker.yahka/wiki/ioBroker.yahka-auf-ein-anderes-System-umziehen

**Comment by nicoh88** [comment]
In der Readme hinzugefügt:
https://github.com/jensweigele/ioBroker.yahka/blob/master/README.md#backup--restore

**Comment by Niko11111** [comment]
Hallo,

ich bin von einem pi3 auf einen pi4 umgezogen. Nach dem Backup Restore war, wie oben beschrieben, der yahka Adapter grün, aber keine. Geräte in HomeKit. Dann bin ich schnell auf diesen Post gekommen und habe die Daten im hapdata vom alten System kopiert. 

Lieder springt der Adapter jetzt immer sofort wieder auf rot und verbindet sich nicht mehr und natürlich sind die Geräte daher immer noch nicht in HomeKit. 

Wo liegt mein Fehler? Ich traue mich jetzt nicht irgendwas anderes zu ändern, da ich keine Lust habe wieder alles händisch einzulegen. Daher warte ich mal ab, ob mir hier geholfen werden kann.

Viele Grüße und Danke

**Comment by TDCroPower** [comment]
Mich hat es beim Backup einspielen jetzt leider auch getroffen, hatte leider mein altes Verzeichnis schon entfernt gehabt bevor ich das Problem mit dem yahka Adapter entdeckt hatte.

Die Lösung des Problems wird jedoch schon mit der Version 2.2.0 in den BackItup Adapter eingebaut...
https://github.com/simatec/ioBroker.backitup/issues/519

**Comment by unstressable** [comment]
> Mich hat es beim Backup einspielen jetzt leider auch getroffen, hatte leider mein altes Verzeichnis schon entfernt gehabt bevor ich das Problem mit dem yahka Adapter entdeckt hatte.
> 
> Die Lösung des Problems wird jedoch schon mit der Version 2.2.0 in den BackItup Adapter eingebaut... [simatec/ioBroker.backitup#519](https://github.com/simatec/ioBroker.backitup/issues/519)

Der Fehler scheint noch immer da zu sein, zumindest habe ich noch wie vor genau das Problem.
Umgezogen von Raspi4 auf neue Hardware mit Docker Image.

Netzwerk ist auf Host eingestellt, sollten also alle Ports offen sein.
Backitup in der Version: 2.10.11
Hab extra nach dem ioBroker Restore nochmal ein einzelnes YAHKA Restore probiert.

Geht leider nicht.

**Comment by simatec** [comment]
Backitup sichert alle Daten, die sich im yahka Verzeichnis befinden und stellt diese wieder her.
