### ISSUE TITLE
Liest der Entwickler dieses Adapters noch die Issues und pflegt den Adapter?

### ISSUE THREAD

**Issue by Marty56** [jensweigele/ioBroker.yahka#177]
Ich habe den Eindruck, dass der Entwickler den Support für den Adapter aufgegeben hat.

Falls das der Fall ist, sollte das ReadMe geändert werden.

**Comment by drtp** [comment]
Den Eindruck habe ich leider auch. Der Adapter hat viel Potential, doch leider scheint er weder für den Entwickler noch für das restliche ioBroker-Team von großem Interesse zu sein. Da legt man den Fokus wohl zumindest im Moment eher auf Alexa, Android und die Aktualisierung des js-controllers. Wäre toll, wenn sich irgendwann mal wieder jemand deises wirklich guten Adapters annehmen könnte. Mir persönlich fehlen dazu leider sowohl die Zeit als auch die Fähigkeiten.

**Comment by MC-1984** [comment]
Ich denke auch, dass es ein sehr wichtiger Adapter für alle die auf iPhones/iPad unterwegs sind. Wäre echt super, wenn sich jemand der das technische know-how hat dem Adapter annehmen könnte...

**Comment by denzel1994** [comment]
Dem schließe ich mich an.

**Comment by izi1** [comment]
Hallo zusammen,
ich findeden Adapter auch sehr gut und würde mich freuen wenn er weiterentwickelt würde.
Ich wäre auch gerne bereit dafür etwas zu spenden.

Danke@ jensweigele

**Comment by nicoh88** [comment]
Hallo Zusammen,

ich sehe es ähnlich. Es ist sehr schade, dass @jensweigele scheinbar für den Adapter keine Zeit mehr findet - vermutlich haben sich seine Prioritäten geändert. 

Dieser Adapter ist für jeden iOS-User wichtig und ich bin auch etwas enttäuscht, dass sich kein Entwickler findet, der diesen Adapter aktiv weiterentwickelt und verbessert. Das Potential ist enorm! Was bis hierhin geleistet wurde, aber verdient aber definitiv auch Anerkennung! 

Ich glaube @jensweigele ließt hier nicht mehr mit! Aber über andere Kanäle ist er noch erreichbar. Ich habe bei ihm, erfolgreich, das Collaborater-Recht erfragt - da ich ein paar Sachen im Wiki dokumentieren wollte und ein wenig in den Issues aufräumen möchte. Für mich als ioBroker-Einsteiger gab es nämlich einige Stolpersteine und wenig Dokumentation.

Ich hätte auch einige Ideen, nur leider fehlt mir das Know-How es in Programmierungen umzusetzen. 👎

**Comment by jensweigele** [comment]
Ich lese hier in der Tat noch mit, mir fehlt es nur an Zeit, die Tickets sinnvoll zu bearbeiten.
Ich habe mir aber vorgenommen, wieder ein bisschen mehr Zeit in den Adapter zu investieren.

**Comment by Alanin** [comment]
@jensweigele brauchst du ggf. Unterstützung? Ich bin selbst Entwickler (bisher zwar nicht im Bereich iobroker) und könnte mich sicherlich einarbeiten...

**Comment by nicoh88** [comment]
@Alanin 

Danke! PRs sind natürlich immer Willkommen!
Du kannst dir ja mal [alle Issues mit dem Label _enhancement_](https://github.com/jensweigele/ioBroker.yahka/labels/enhancement) ansehen.

Ich denke, #166 wäre ein guter Einstieg, ohne Apple HomeKit-Einflüsse.

Ansonsten wäre das Thema `OptionalCharacteristic` ganz schön - 3 Issues - [siehe](https://github.com/jensweigele/ioBroker.yahka/projects). Mehr dazu, gerne in einem Issue nachfragen, ich kann dann Beispiele liefern. 👍

**Comment by Alanin** [comment]
@nicoh88 alles klar. schaue ich mir mal an. gibt es irgendwo eine Beschreibung, wie man am besten vorgeht bei der Entwicklung? Irgendwie als zweiten (lokalen) Adapter im System haben, Skripte anpassen/testen und am Ende commit/push und pr...

**Comment by Alanin** [comment]
Wie wollen wir das mit der Entwicklung machen? Soll ich einen fork ziehen, dort entwickeln und dann PR zurück. Oder kann ich hier im repo die Berechtigung fürs erstellen von branches und commits bekommen?

**Comment by jensweigele** [comment]
Erstelle bitte einen Fork und stelle einen PR
Danke!

**Comment by DanielWeeber** [comment]
Ich hatte @jensweigele früher auch öfters geholfen mit der Bearbeitung. Oder mit ein paar Ideen zur Erweiterung ;) Könnte ich gerne wieder etwas mitmachen.
Wichtig ist hier eine Trennung zwischen echten Bugs und Fragen zur Bedienung zu trennen. Viele haben einfach keine Ahnung von der ganzen Thematik und wie HomeKit funktioniert - und die Fragen sind hier einfach falsch.

**Comment by nicoh88** [comment]
@DanielWeeber Cool. Freue mich. Suche dir was aus, vermutlich ist für dich alles mit Label "enhancement" oder "bug" interessant. 😄 Habe die Tage etwas aufgeräumt.
