### ISSUE TITLE
Minustemperaturen werden in Homekit App mit 0 Grad dargestellt

### ISSUE THREAD

**Issue by eumats** [jensweigele/ioBroker.yahka#18]
Hallo,

Minustemperaturen wurden in Homekit nur mit 0 Grad eingezeigt. Dabei ist es egal, ob der Datenpunkt in ioBroker mit der Quelltemperatur den Typ String oder Zahl oder sonst etwas hat.
Wenn man das debugging von yahka einschaltet sieht man, dass der Wert (z.B. -3) anscheinend korrekt verarbeitet wird.

`forwarding value from ioBroker ('-3') to homekit as ('-3)`

Es wäre super, wenn  du jemand mal schauen könnte woran das liegt. Ich komme mit meinen rudimentären Programmierkenntnissen hier leider nicht weiter.

Danke und Gruß
B. Müller

**Comment by jensweigele** [comment]
Die Definition von "Current Temparature" in HAP-NodeJS gibt als "min value" 0 vor.
Vor kurzem gab es einen Pull-Request um diesen Wert zu ändern (https://github.com/KhaosT/HAP-NodeJS/pull/529) - leider wurde er abgelehnt.

Ich hab nun einen Fix in Yahka eingebaut. D.h. mit der nächsten Version sollte es funktionieren (oder du testest den aktuellen Master)

**Comment by eumats** [comment]
Es funktioniert in 0.6.0-beta.2. Danke!
