### ISSUE TITLE
No Category selectable

### ISSUE THREAD

**Issue by jannnfe** [jensweigele/ioBroker.yahka#180]
Hello,
i have the newest Version of the Adapter, the newest version of iobroker (js-controller) and node 12.18 installed. In different browsers it is not possible to choose a category like "Lightbulb" while adding a new Device. Already existing Devices ar displaying with a "?" on the left side and also there is not possible to update the category.
What should i do?
Thanks!

**Comment by nicoh88** [comment]
@jannnfe Kann dein Problem nicht nachvollziehen. Kannst du es genauer erklären, eventuell mit Screenshot?

Gruß Nico

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!
