### ISSUE TITLE
tv-service hilfe

### ISSUE THREAD

**Issue by krobipd** [jensweigele/ioBroker.yahka#181]
hallo

mich würde es sehr interessieren wie ich den tv-service richtig konfiguriere. bekomme es einfach nicht hin. 

also im grunde gehts ja, ein und ausschalten aber inputs wechseln bzw festlegen - wie geht das? was muss ich wo und wie machen?

habe bereits viel selbst herum probiert aber ich komme einfach auf keine lösung.

**Comment by DanielWeeber** [comment]
Das ist kein Issue. Am besten im Forum fragen.

**Comment by nicoh88** [comment]
https://github.com/jensweigele/ioBroker.yahka/wiki/Fernseher-mit-YAHKA-simulieren
