### ISSUE TITLE
Wie zwei Instanzen mit gleichen Geräten erstellen

### ISSUE THREAD

**Issue by paba42** [jensweigele/ioBroker.yahka#182]
Hallo!

Ich habe zwei Instanzen von yahka laufen, da meine Frau und ich beide ein iPhone haben, aber eine Freigabe sich als unpraktisch erwiesen hat. Das klappt auch alles sehr gut.

Nun würde ich gerne mehrere Geräte eintragen, weil ich einige neue Geräte installiert habe. Klar kann ich die Einstellungen doppelt vornehmen, was aber sehr aufwändig ist. Kann ich irgendwie Dateien zwischen den Instanzen kopieren, um die Geräte in beiden Instanzen gleich zu haben?
Das muss nicht automatisch sein, kommt ja nicht dauernd vor.

Danke!

Beste Grüße

Paul

**Comment by nicoh88** [comment]
Sorry, da gibt es aktuell keine Möglichkeit und für eine Umsetzung zuwenig Bedarf.
