### ISSUE TITLE
Bug: Variable "Name" wird nicht an HomeKit gesendet

### ISSUE THREAD

**Issue by t6a** [jensweigele/ioBroker.yahka#184]
Der Adapter ist einer der Hauptgründe, weshalb ich zu ioBroker gewechselt habe.

Bei allen virtuellen Geräten gibt es die Variable "Name". Jedoch wird diese vollkommen ignoriert / nicht an HomeKit weitergeleitet.

Ich habe es einmalig geschafft, indem ich zuerst das Variablen-Feld "Name" zu einem Datenpunkt verlinkt habe und danach den Namen vom Device, unter Device Properties, geändert habe. Sehr merkwürdig. Wenn sich nun aber der Datenpunkt verändert, wird dies nicht weiter an HomeKit gesendet. Man muss erst wieder den Namen vom Service unter Device Properties ändern, damit dann der Datenpunkt an HomeKit gesendet wird und sich der Name vom Gerät in HomeKit ändert.

**Comment by nicoh88** [comment]
@t6a Was meinst du mit "virtuellen Geräten"? Selbst angelegt Objekte / Datenpunkte?

Gruß Nico

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!
