### ISSUE TITLE
Bug: 1 Service löschen => alle Services gelöscht?

### ISSUE THREAD

**Issue by t6a** [jensweigele/ioBroker.yahka#185]
Wenn ich ein Service eines Geräts lösche, werden alle Services gelöscht. Ich kann auch keinen anderen hinzufügen und muss das Gerät neu einrichten...

**Comment by nicoh88** [comment]
Hi @t6a,

kann es sein, dass du nachdem du an einem gespeicherten Gerät, ein Service löschst, das Gerät nur links am Rand aus dem Menü wieder auswählen musst?

Gruß Nico

**Comment by nicoh88** [comment]
@Alanin

Was mir aufgefallen ist, schon vor deinen Änderungen mit der Menüleiste: Wenn man in einem Gerät, mehrere Services hat und einen davon löscht, schmeißt es einem direkt aus dem Menü und man muss das Gerät, links an der Leiste neu auswählen, kannst du dir das mal anschauen?

**Comment by Alanin** [comment]
Kannst du mich bei den ganzen issues assignen, die ich machen soll? Danke dir!

**Comment by nicoh88** [comment]
Hi @jensweigele,

da du gerade kleine Verbesserung am Adapter Admin Interface machst. Hier nochmal kurz ein Video zum Problem: https://nh.loggn.de/yahka-wiki/issue-185.mov

Gruß Nico

**Comment by jensweigele** [comment]
Ist im aktuellen Master gefixt
