### ISSUE TITLE
[Feature Request] Variable für Seriennummer in State Feldern

### ISSUE THREAD

**Issue by anarchocactus** [jensweigele/ioBroker.yahka#187]
Hallo,

Ein Vorschlag zur Verbesserung:

Unter "Device Properties" kann ich eine Seriennnummer eintragen. Diese Seriennummer könnte man direkt in den State-Feldern in Form einer Variable verwenden, z.B. hm-rpc.0.\<serial\>.1.HUMIDITY. Das hätte den Vorteil, dass man speziell Devices mit mehreren States, wie z.B. einen Thermostat einfacher duplizieren kann. Man müsste nur noch die Bezeichnungen und die Seriennummer austauschen und fertig. Der spätere Austausch eines physikalischen Device wäre dann auch einfacher zu machen.

Gruss, Ben

**Comment by jensweigele** [comment]
@anarchocactus : wenn du den Service "AccessoryInformation" hinzufügst, kannst du genau das tun ;-)
Dieser Service überschreibt dann die Werte die du zuvor bei Name, Serial usw. eingetragen hast.

**Comment by anarchocactus** [comment]
Danke für die Antwort. Ich stehe allerdings gerade etwas auf dem Schlauch, zu verstehen, wie mir das bei dem o.g. use case nützlich sein könnte. Hast Du mal ein kurzes Beispiel?

**Comment by jensweigele** [comment]
Ich versuche morgen ein Beispiel zu posten

**Comment by jensweigele** [comment]
Ich habe nochmal ein bisschen getestet und festgestellt, dass es mit der aktuellen Implementierung nicht funktioniert.
Ich werde heute oder in den nächsten Tagen einen Fix in den Master pushen um das zu fixen.
Die Config sieht dann etwa so aus: 
![image](https://user-images.githubusercontent.com/8476620/100146730-a26fa880-2e9a-11eb-956e-7f2f84236d14.png)


Ich melde mich hier wenn der Fix veröffentlicht ist

**Comment by jensweigele** [comment]
Fix ist im Master verfügbar.
Bei Problemen gerne melden.
