### ISSUE TITLE
Television Service no Icon on iOS 14

### ISSUE THREAD

**Issue by denzel1994** [jensweigele/ioBroker.yahka#188]
Any Chance to get the TV Icon back for the Television Service on iOS 14?
On iOS 13 everything was perfectly fine.

iOS 13:
<img width="111" alt="Bildschirmfoto 2020-09-18 um 02 18 16" src="https://user-images.githubusercontent.com/36551243/93540959-88bf5b80-f955-11ea-8258-9ba9d7066c59.png">

Now on iOS 14 the Icon changed:
![IMG_0BDA758E4185-1](https://user-images.githubusercontent.com/36551243/93540998-9ffe4900-f955-11ea-901c-f2b35cda45ef.jpeg)

**Comment by ciddi89** [comment]
Hey, I think it's a bug of iOS 14 and not of yahka. I have the same issue in Homebridge. It's my thought.

**Comment by denzel1994** [comment]
> Hey, I think it's a bug of iOS 14 and not of yahka. I have the same issue in Homebridge. It's my thought.

The solution ist to unbridge the TV from the yahka bridge. So that you have to add the TV as external accessory instead of adding it automatically together with the bridge.

<img width="705" alt="Bildschirmfoto 2020-09-19 um 23 09 11" src="https://user-images.githubusercontent.com/36551243/93689273-33a65580-facd-11ea-8d15-4b87b94c759f.png">


Many homebridge-plugins have this option. Like [homebridge-bravia](https://github.com/normen/homebridge-bravia). Maybe this can be implemented here.

**Comment by ciddi89** [comment]
> > Hey, I think it's a bug of iOS 14 and not of yahka. I have the same issue in Homebridge. It's my thought.
> 
> The solution ist to unbridge the TV from the yahka bridge. So that you have to add the TV as external accessory instead of adding it automatically together with the bridge.
> 
> <img alt="Bildschirmfoto 2020-09-19 um 23 09 11" width="705" src="https://user-images.githubusercontent.com/36551243/93689273-33a65580-facd-11ea-8d15-4b87b94c759f.png">
> 
> Many homebridge-plugins have this option. Like [homebridge-bravia](https://github.com/normen/homebridge-bravia). Maybe this can be implemented here.

Ah thanks you're right. I set it in Homebridge to External Accessory and now it is shown as a TV again. So maybe it is possible to change it in yahka too?

**Comment by jensweigele** [comment]
Ist im aktuellen Master erledigt - siehe auch #89

**Comment by nicoh88** [comment]
https://github.com/jensweigele/ioBroker.yahka/wiki/Fernseher-mit-YAHKA-simulieren
