### ISSUE TITLE
Unable to activate Irrigation System

### ISSUE THREAD

**Issue by oberstel** [jensweigele/ioBroker.yahka#189]
When using Service-Type "IrrigationSystem" it is not possible to active the configured device. Attribute "Active" has no function. 
After configuring the "Activate" attribute with proper Object-ID etc. Homekit don't let me turn on or off the device.

**Comment by jensweigele** [comment]
I think it's a problem of your configuration.
I did a short test and had to add a Valve to the system.
If you are using the latest master, you can link the Valve to the Irrigation System (there is a box on the top right corner).
The linking is still work in progress - renaming the services for example will break the link.

If you have a look here: https://github.com/homebridge/HAP-NodeJS/issues?q=irrigation+system
You will see, that there are a lot of possiblities on how to configure IrrigationSystem with Faucet, Valves etc.
