### ISSUE TITLE
iOS 14 Feuchtigkeitssensoren im Status (StatusFault)

### ISSUE THREAD

**Issue by lukaaars** [jensweigele/ioBroker.yahka#191]
Ich besitze einige Feuchtigkeitssensoren, bei denen ich bei zu wenig oder zu viel Feuchtigkeit den StatusFault auf 1 setzen lasse. Seit iOS 14 scheint StatusFault aber nicht mehr zu funktionieren, bzw. wird kein "Fehler entdeckt" mehr angezeigt.

Hat noch jemand dieses Problem?

![E6138BA0-A3AD-4D45-8709-DE907E7F4C7D_1_102_o](https://user-images.githubusercontent.com/2846693/93767584-86405880-fc18-11ea-8d0e-b6b8fae76a2a.jpeg)

**Comment by sailor25462** [comment]
Ich have the same issue with my smoke detectors. 
It seems to have no effect if some of the "fault" indicators are kicking in. for example, I use "reachable" as data for "status.active" as well as "status.fault". I was expecting that one of them should cause at least some sort of reaction, but no. Sensor remains "bereit" and does no throw any error.

**Comment by nicoh88** [comment]
@lukaaars Scheint ein Problem in iOS zu sein. Konntest du es lösen? Oder hast es ein Update gelöst?

**Comment by sailor25462** [comment]
Es wäre auch einmal interessant zu vergleichen, wie sich die Sensoren unter iOS 14 bei Homebridge verhalten.

**Comment by jensweigele** [comment]
Ich schließe das Ticket - ist wohl ein iOS Bug, da es unter MacOS scheinbar funktioniert.

**Comment by unstressable** [comment]
Problem ist auch unter iOS15.1.1 noch vorhanden.
Seid ihr sicher, dass es an iOS liegt?

Keine Reaktion auf Veränderung von "StatusFault"; "StatusActive" funktioniert. Das zeigt er zumindest in der Home App in den Geräteeigenschaften an.
