### ISSUE TITLE
Not each and every Service Type is working as expected

### ISSUE THREAD

**Issue by oberstel** [jensweigele/ioBroker.yahka#192]
There are several different Service Types which can be selected when adding a Service to a Device.
As far as I concern, some Service Types are not working at all.  Like “Label”... there is no way to configure this Service properly. The Home App shows always “not supported”.
Same as for Speaker, Microphone, AccessoryInformation, ServiceLabel, InputSource and some other.
 
![27062AAB-A683-4E14-990F-4B2F3C0717B7](https://user-images.githubusercontent.com/15839784/94033390-34870200-fdc1-11ea-9082-0a82c2709f6d.jpeg)
![29BE9AE0-6BF2-4F63-9F2D-2C70837630F6](https://user-images.githubusercontent.com/15839784/94033408-3781f280-fdc1-11ea-9545-0d31b2e33a91.jpeg)

Can somebody confirm this behavior?
If so, why do we have those options in the Adapter even if they’re not working properly?

**Comment by b3ster** [comment]
+1

**Comment by DanielWeeber** [comment]
Das ist nicht korrekt.
Das grundlegende Prinzip von HomeKit ist, dass es im Endeffekt nur eine Datenbank ist. Diese Datenbank (einfach gesprochen) beinhaltet viele Services und States, die in vielen beliebigen (nicht unendlich) Kombinationen kombinierbar sind.

Schau dir das z.B. hier an, dann versteht man es eigentlich ganz gut:

https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/gen/HomeKit.ts


z.B. Service LightBulb kann versch. Charakteristiken haben, die wieder einzeln bestimmt sind

`export class Lightbulb extends Service {

  static UUID: string = '00000043-0000-1000-8000-0026BB765291';

  constructor(displayName?: string, subtype?: string) {
    super(displayName, Lightbulb.UUID, subtype);

    // Required Characteristics
    this.addCharacteristic(Characteristic.On);

    // Optional Characteristics
    this.addOptionalCharacteristic(Characteristic.Brightness);
    this.addOptionalCharacteristic(Characteristic.Hue);
    this.addOptionalCharacteristic(Characteristic.Saturation);
    this.addOptionalCharacteristic(Characteristic.Name);
    this.addOptionalCharacteristic(Characteristic.ColorTemperature);
    this.addOptionalCharacteristic(Characteristic.CharacteristicValueTransitionControl); // Ambient Lightning
    this.addOptionalCharacteristic(Characteristic.SupportedCharacteristicValueTransitionConfiguration); // Ambient Lightning
  }
}
`

Jeder dieser Charakteristiken hat wiederrum versch. Sachen definiert, mindestens mal was gültige Eingabewerte sind etc.

`export class ColorTemperature extends Characteristic {

  static readonly UUID: string = '000000CE-0000-1000-8000-0026BB765291';

  constructor() {
    super('Color Temperature', ColorTemperature.UUID);
    this.setProps({
      format: Formats.UINT32,
      maxValue: 500,
      minValue: 140,
      minStep: 1,
      perms: [Perms.READ, Perms.WRITE, Perms.NOTIFY]
    });
    this.value = this.getDefaultValue();
  }
}`

Dein angesprochenes "LabelNameSpace" ist eine Charakteristik für den Service "ServiceLabel", ein sogenannter Slat Service
Der wird bisher eigentlich noch von keinem (anderem) Service der HomeKit DB genutzt, weswegen Apple (nicht Yahka) dann "nicht unterstützt" anzeigt. 

Ich habe mal gelesen, dass es für Stateful Switches benutzt wurde, aber ich bezweifle, dass das eine korrekte Verwendung (des Service) war.

Ich kann nur empfehlen mal den HomeKit Accessory Simulator zu benutzen und die Homekit Datenbank selbst mit Daten zu füttern (anstatt Yahka). Dann erkennt man, dass Yahka eher nur eine Übermittlung, anstatt eine Logik darstellt.

<img width="1331" alt="Bildschirmfoto 2020-10-23 um 13 59 18" src="https://user-images.githubusercontent.com/2935130/97001042-fd2e8100-1537-11eb-8809-514900058556.png">
