### ISSUE TITLE
Valve device doesn't turn off when SetDuration expired (RemainingDuration=0)

### ISSUE THREAD

**Issue by oberstel** [jensweigele/ioBroker.yahka#193]
It is not possible to use the Service Type "Valve" in a proper way:
When defining a given duration using the Home App (5min - 1h), the counter runs after activating (active=1) and starting irrigation (in use=1) correctly.
But when the specified runtime has been reached, nothing happens!
I would expect that parameter _active_ will be set do _0_ to stop the irrigation... actually nothing happens.

This seems to be a bug.

**Comment by lukaaars** [comment]
Für RemainingDuration muss eine separate Variable erstellt werden und ein Skript, dass die Zeit runter zählt und den Service stoppt.
Guck dir sonst mal den Gartenbewässerung-Adapter von TA2k an: https://github.com/TA2k/ioBroker.gartenbewaesserung
Da gibt es eine Variable die runter zählt, kann man dann bei Yahka einfügen.

**Comment by oberstel** [comment]
> Für RemainingDuration muss eine separate Variable erstellt werden und ein Skript, dass die Zeit runter zählt und den Service stoppt.
Ja, dass kann man natürlich bauen... Allerdings meine ich verstanden zu haben, dass genau dieses Herunterzählen durch Homekit bereits gemacht wird. Denn wenn man SetDuration über die App einstellt und daraufhin auch RemainingDuration setzt, dann erfolgt ja genau so ein Countdown nach der Aktivierung (in Use)... 
Nur das am Ende (bei 00:00 angekommen) dann leider nix passiert und das ist m.E. ein Bug. Denn so ist die Countdown Funktion komplett sinnlos.

**Comment by DanielWeeber** [comment]
Du kannst gerne helfen etwaige Bugs zu beheben!

**Comment by jensweigele** [comment]
@oberstel könntest du mal bitte einen Screenshot deiner Config posten? 
Dadurch ist es für mich einfacher, dass nachzustellen.

**Comment by Baenker** [comment]
Ich würde hier nichts ändern. Es läuft alles so wie ich es mir vorstelle. So fände ich es ziemlich doof wenn nach Ablauf vom Timer etwas automatisch passiert. Ich steuere je nach Fall was nach Ablauf passiert. Kann eine Push sein. Kann sein das der Timer erneut startet oder das meine Bewässerung ausgeschaltet wird.

Es ist also eine Sache der Erwartung ob es ein Fehler ist oder nicht. Für mich ist es ein Feuture. Ich kann es so steuern wie ich es mir vorstelle.

**Comment by DanielWeeber** [comment]
Ich finde die Frage ist hier eher wie Apple (also HomeKit itself) es handhabt. Dort wird kein Counter automatisch gezählt o.ä.

Siehe HomeKit Accessory Simulator

![Bildschirmfoto 2020-11-29 um 15 49 16](https://user-images.githubusercontent.com/2935130/100545100-75384700-325a-11eb-908e-fd2be6892708.png)

Die versch. Parameter beeinflussen eigtl nur die Anzeige. ValveTyp 0,1 entweder ein Wasserhahn oder Sprinkler
Die Kombination von Active/InUse ist wie bei Thermostaten das Current/Target Prinzip
IsConfigured dann, ob das Wasser "läuft" (in Deutsch toll mit "laufen" übersetzt)

Für mich sollte es also so bleiben. HomeKit ist keine Logik, nur eine Datenbank.

**Comment by Baenker** [comment]
Mein Reden. Also bitte nichts ändern...

@DanielWeeber Ist das Homekit Asseccory Simulator für jeden frei zugänglich oder nur für entwickler? Finde ich sehr spannend und würde es mir gerne angucken.

**Comment by DanielWeeber** [comment]
Das ist in den Additional Xcode Tools enthalten. Xcode muss dafür nicht installiert sein.

https://www.google.com/search?q=additional+xcode+tools&oq=Additional+Xcode+Tools&aqs=chrome.0.0i19j0i19i22i30l5.4621j1j7&sourceid=chrome&ie=UTF-8

Eine Apple ID ist notwendig, ich glaube aber kein Developer Account. Also free.

**Comment by jensweigele** [comment]
Ich denke das Verhalten ist so "gewünscht" (von Apple) - jeder kann über Skripte bzw. andere Logik entscheiden, was passiert wenn der Countdown abgelaufen ist.
