### ISSUE TITLE
Services in der APP ungleich YAHKA

### ISSUE THREAD

**Issue by unstressable** [jensweigele/ioBroker.yahka#196]
Hab rausgefunden, dass die Farbeinstellungen in der Homekit APP erscheinen, wenn man einen Wert bei "HUE" in YAHKA setzt.
Soweit so gut.

Wenn man sich aber entscheidet statt einer farbigen Birne eine andere (z.B. ohne Farbe, oder Weißtöne) einzubauen, entsprechend den Haken und die Werte bei "HUE" wieder weg macht, dann bleibt die Farbeinstellungsoption in der Homekit App vorhanden.

Das ist auch bei allen anderen Optionen so.

Es sollte so sein, dass die Optionen, welche nicht angehakt sind zurückgesetzt werden.

**Comment by nicoh88** [comment]
Ist mir auch schon aufgefallen - ist definitiv ein Bug. Man muss das Gerät löschen und neu anlegen. Sehr unschön.

Das liegt an verwaiste Einträgen in der `objects.json`. Müsste sich @jensweigele mal anschauen!

**Comment by unstressable** [comment]
Ich glaube man muss nur den Service löschen, nicht das gesamte Gerät.
Das hat den Vorteil, dass man das Gerät in der Home-APp nicht neu sortieren bzw. ggf. umbeschriften muss.

**Comment by jensweigele** [comment]
Der Fehler sollte mit dem aktuellen Master behoben sein!
