### ISSUE TITLE
Objektauswahl nicht scrollbar

### ISSUE THREAD

**Issue by unstressable** [jensweigele/ioBroker.yahka#197]
Bei der Auswahl eines iobrokerStates kann die Objektauswahl nicht gescrollt werden.
Bei den anderen Adaptern funktioniert das wunderbar. Z.B. bei dem KNX Adapter.

Aktuell mit mit den Cursortasten navigiert werden, was etwas umständlich ist.

**Comment by nicoh88** [comment]
@Alanin Bist du noch da?

**Comment by nicoh88** [comment]
@Alanin Würde dir dieses Issue hier auch zuweisen, dazu musst du aber einmal im Issue antworten. 👍

**Comment by Alanin** [comment]
Pling

**Comment by DanielWeeber** [comment]
Das ist auch ein Browser abhängiges Problem. Soweit im Chrome nachvollziehbar, wenn ich zufällig das gleiche meine wie OP, im Safari z.B. nicht.

**Comment by unstressable** [comment]
Kann man in dem Adapter nicht das "Standard" Objektauswahlmenü einbinden, wie es die anderen Adapter wie z.B. Javascript und KNX auch nutzen?
Das wurde vor kurzem durch ein Update angepasst, sieht chick aus und funktioniert tadellos:

![image](https://user-images.githubusercontent.com/50423935/97010581-e131dc00-1545-11eb-8166-554d5edf1471.png)

**Comment by nicoh88** [comment]
@Alanin **Reminder:** Ich weiß du hast viel zu tun. 😄 Vielleicht kommst du die Tage mal zu deinen [Tasks]. 👍 (https://github.com/jensweigele/ioBroker.yahka/issues?q=assignee%3AAlanin+is%3Aopen+)

**Comment by unstressable** [comment]
Außerdem hab ich gerade noch festgestellt, dass die Objekte nur beim aufrufen des Konfigurationsmenüs aktualisiert werden.
Wenn ich ein neues Objekte anlege, währende das YAHKA Konfig-Menü offen ist, wird das neue Objekt nicht angezeigt.

Der Oben gepostete Objektexplorer vom JS-Adapter prüft bei jedem Öffnen nach neuen Objekten ist mir aufgefallen, somit erspart man sich das komplette schließen des Adapter-Menüs.

**Comment by jensweigele** [comment]
@GermanBluefox  / @Apollon77  weiß einer von euch, ob die Objektauswahl die unstressable gepostet hat, ein Standardelement in ioBroker ist?
Wenn ja, gibt es irgendwo Doku zur Einbindung?

**Comment by Apollon77** [comment]
ja das ist "selectId" ... Doku weiss nicht ... ich kenne keine. Denke nur "Adapter die es nutzen" sind referenzen :-(

**Comment by GermanBluefox** [comment]
Das ist leider ein ReactJS Component und momentan geht nur in React Adapters

**Comment by jensweigele** [comment]
Könnt Ihr das bitte mal mit dem aktuellen Master checken?
Die States werden nun auch bei jedem öffnen aktualisiert - hier wäre mal interessant zu sehen, ob dadurch irgendwelche Verzögerungen oder andere Seiteneffekte auftreten.

**Comment by unstressable** [comment]
> Könnt Ihr das bitte mal mit dem aktuellen Master checken?
> Die States werden nun auch bei jedem öffnen aktualisiert - hier wäre mal interessant zu sehen, ob dadurch irgendwelche Verzögerungen oder andere Seiteneffekte auftreten.

Sieht super aus! Endlich kann ich mit der Maus scrollen. Wenn Probleme auftreten, melde ich mich. Danke dir!

OT: Kann man eigentlich irgendwie das Lampensymbol für die Home-App ändern? Hier stehen diverse zur Verfügung wie ich immer wieder in Screenshots aus dem Netz sehe. Yahka lässt mich aber mit "lightbulb" nur eines verwenden :(

**Comment by jensweigele** [comment]
Gehe in der HomeApp auf die Einstellungen der Lampe und drücke auf das Icon neben dem Namen:
![image](https://user-images.githubusercontent.com/8476620/103011184-caa20400-4539-11eb-92fc-6300c3e1f1cd.jpeg)
