### ISSUE TITLE
Homekit int scaling not straight forward

### ISSUE THREAD

**Issue by max3-2** [jensweigele/ioBroker.yahka#198]
Hi,

im using a CT value light which needs input from 250 to 454 in iobroker. Homekit sends values from 140 to 500. I tried to use map with the two datapoints and also int scaling with the min may as above, both failed by producing values far off.

To be sure, I computed the scaling function and used it in function. Now it works. What am I doing wrong with the more easy to use `scaleInt` or `map`? Is this a bug or my mistake?

**Comment by DanielWeeber** [comment]
CT value from Hue is another mathematical unit than CT from Homekit. You do not have to have int scaling functions at all, just convert the two units.

**Comment by max3-2** [comment]
Care to elaborate on the units / the conversion in this case? And what's the best way to perform...?

**Comment by DanielWeeber** [comment]
```
ColorTemperature
This characteristic describes color temperature which is represented in the reciprocal megakelvin (MK-1) or mirek scale. MK = 1,000,000 / K where MK is the desired mirek value and K is temperature in Kelvins.

UUID 000000CE-0000-1000-8000-0026BB765291
Type public.hap.characteristic.color-temperature
Permissions Paired Read, Paired Write, Notify
Format uint32
Minimum Value 50
Maximum Value 400
Step Value 1

```
https://en.wikipedia.org/wiki/Mired

iobroker.hue expects Kelvin, if I recall correctly

**Comment by max3-2** [comment]
> iobroker.hue expects Kelvin, if I recall correctly

I guess this is a typo - .ct should be color temperature

Also - can you pinpoint to where the documentation is from?


But to go back to my initial post: I do *not* think this is a unit system error. As described in my initial post, ct needs to be between 250 and 450 approx - this is by no way kelvin, I guess this lightbulb is just using a smaller range of colors but also using mired. How (and **if**) to translate is another question, however:

My initial point stands. Using an int conversion with two min-max bounds should yield linear interpolation between the ranges, as is did with my custom linear equation. However this is NOT working as expected, the values from homekit to iobroker skyrocket to everywhere even when just printing them to the log

**Comment by jensweigele** [comment]
I think it could be related to #201 - same advise here: please try with the latest master and reopen if still present!

**Comment by DanielWeeber** [comment]
Just double checked

Bri and Sat correspond to .bri and .sat of the iobroker object, conversion (each) level255
hue just corresponds to .hue from the iobroker object, no conversion needed
ct corresponds to .ct from the iobroker object, conversion script with

`return 1000000/value;`

This converts from mired (apple) to kelvin (iobroker.hue) and vice-versa

![Bildschirmfoto 2020-11-22 um 18 07 03](https://user-images.githubusercontent.com/2935130/99910349-bf1aad80-2ced-11eb-91be-3184b493fb6a.png)
