### ISSUE TITLE
Homekit Abstürze 

### ISSUE THREAD

**Issue by Trunks1982** [jensweigele/ioBroker.yahka#199]
Hallo seid dem Ios 14 draussen ist habe ich nir noch Homekit Abstürze wenn der Yahka Adapter läuft.Mache ich diesen aus läuft Homekit wieder ganz normal.

**Comment by Baenker** [comment]
Was genau heißt Homekit Abstürze? Scheint kein generelles Problem zu sein da ich bei mir keine Auffälligkeiten habe. Ich kann einzelne über yahka angebundene Geräte steuern (mache ich aber eher selten) und bekomme immer eine Push wenn Fenster oder Garage geöffnet wird (ebenfalls über Yahka angebunden).

**Comment by Trunks1982** [comment]
Also bei mir stürzt imme die homekit app auf dem iphone ab.Wenn ich den Yahka Adapter beende gehts sofort wieder.Habe schon home app gelöscht und neu installiert wieder gleiche Problem.

**Comment by Baenker** [comment]
Trotzdem eher ein Einzelproblem. Lösch mal alle Geräte aus Yahka ind teste dann nochmal. Danach ein Gerät anlegen und wieder testen bis Du das Gerät oder den Service gefunden hast...
Bei mir und meiner Frau auf keinem Gerät Probleme. Alle mit ios14 bzw ipados14

**Comment by Trunks1982** [comment]
Die Geräte werden nicht das Problem sein.Es sind ja die gleichen wie unter IOS13 drin.Zeigt auch keine Fehler im IoBroker log.Beim falschen Anlegen kam immer ein Fehler im log oder Yak würde erst gar nicht grün.

**Comment by Baenker** [comment]
Komische Logik. Yahka ist auch noch die selbe Version. Wir haben die gleiche Ios und yahka Version nur unterschiedliche Geräte. Ich würde also dort suchen. Da bisher nur Du Probleme hast. Wenn es ein generelles Problem wäre, hätten sich schon mehr gemeldet. Aber Du kannst auch warten bis ein Entwickler sich das Problem anguckt. Nur passiert hier leider recht wenig. Was der Entwickler braucht wäre defintiv ein Log mit Debug

**Comment by Trunks1982** [comment]
Ok gerade nochmal iPhone komplett zurück gesetzt, ganz neu eingerichtet und Homekit ist beim zweiten Öffnen wieder abgestürzt.Werde doch dann mal die gerate entfernen und nach und nach wieder reinholen.

**Comment by DanielWeeber** [comment]
Yahka selbst hat so ja auch nichts mit der Home App selber zu tun, sondern füllt (und ruft) nur die HomeKit Datenbank ab.
Entweder ist also irgendein Schmarn in der HomeKit Datenbank, was die Home App zum Abstürzen bringt (also "seltsame" Geräte/Services in Yahka eingestellt) oder du hast ein ganz anderes Problem.

Solltest du vermuten, dass es mit Yahka zusammen hängt, solltest du auch in den Logs im ioBroker was erkennen können.

**Comment by Trunks1982** [comment]
Irgend nen Schmarrn 😁war nicht drin hat auf ios 13 funktioniert.Aber hab jetzt alle Geräte gelöscht und geb soe gerade nach und nach wieder ein.Bis jetzt läuft alles wieder.

**Comment by DanielWeeber** [comment]
@nicoh88 Leider kann ich keine Issues schließen

**Comment by jensweigele** [comment]
Ich habe mit diesem Fehler nun auch einige Zeit verbracht :(
iOS 14 scheint sehr pingelig zu sein wenn die Services nicht genau die richtigen Characteristiken unterstützen.
Wenn man bspw. eine "LighBulb" nur mit "On" und "Hue" anlegt, crashed die App.
Ich habe nun ein "Enabled"-Flag auf der Service-Ebene eingeführt, um einzelne Services auschalten zu können (damit kann man sich besser an das Problem "herantasten")
