### ISSUE TITLE
Rotes Dreieck mit Ausrufungszeichen in Elgato Eve

### ISSUE THREAD

**Issue by bjwelker** [jensweigele/ioBroker.yahka#2]
Hi, ich habe mal Elgato Eve getestet. Dort habe ich leider bei dem Türsensor sowie Temperatur und Luftfeuchtigkeit in Rotes Dreieck mit Ausrufungszeichen. Die Werte werden zwar angezeigt aber irgendetwas scheint Ihn da zu stören hast du da evtl. eine Idee was er noch haben möchte damit es geht. Bei Active hab icch schon true und 1 probiert hat aber auch nichts gebracht.

**Comment by jensweigele** [comment]
Kannst du mal Screenshots von der iOS App und der Konfiguration hier anhängen?

**Comment by jensweigele** [comment]
Ich schließe das Ticket. Falls es noch Probleme gibt, bitte wieder öffnen.
