### ISSUE TITLE
Merge mit Fork der Kameras unterstützt

### ISSUE THREAD

**Issue by eumats** [jensweigele/ioBroker.yahka#20]
Hallo,

der Fork von [(https://github.com/kirovilya/ioBroker.yahka)] unterstützt die Einbindung von IP-Kameras mit ffmpeg. Es wäre super, wenn die dort durchgeführten Änderungen mit diesem Hauptzweig zusammengeführt werden könnten.
Ich kann das leider aufgrund meines fehlenden Wissens nicht durchführen, würde mich aber als Tester anbieten.

Danke und Gruß
B. Müller

**Comment by jensweigele** [comment]
Kannst du mir mal bitte eine Beispielkonfiguration schicken? Mir ist noch nicht ganz klar, was man genau konfigurieren muss für den Kamera Stream

**Comment by eumats** [comment]
Anbei meine Konfiguration. Diese Funktionier mit einer Foscam.

![yahka 1](https://user-images.githubusercontent.com/32279788/34029175-623c2a64-e167-11e7-8117-a11f9298faa3.jpg)

Super wäre es auch, wenn man das ffmpeg Kommando in yahka konfigurierbar gestallten könnte. Denn ich muss zumindest den Aufruf zum Erzeugen des initialen Bildes für meine Cam anpassen.
**Original:** ./ffmpeg.js: let ffmpegCommand = '-re -i ' + this.ffmpegSource + ' -t 1 -s '+ resolution + ' -f image2 -';
**meine Konfiguration:** ./ffmpeg.js:  let ffmpegCommand = '-re -ss 10 -i ' + this.ffmpegSource + ' -t 1 -s '+ resolution + ' -f image2 -vframes 1 -';
Dabei scheint es wohl auch wichtig zu sein, welche Option vor und welche nach der Source steht.

Der Live-Stream läuft meistens, ist aber manchmal "pixelig". Aber dort habe ich an den Einstellungen noch nicht gespielt.

Die ffmpeg Installation auf einem Raspi3 ist hier beschrieben: [http://forum.iobroker.net/viewtopic.php?f=23&t=4136&start=380#p95473](url)

**Comment by matze1708** [comment]
Ja stimmt, gerade das drehen der Cam wäre top.
Habe es in der ffmpeg.js händisch angepasst, hat zur folge das mein Standbild richtig ist und der Stresm wieder so kommt wie von der cam.
Kann aber leider den dreh wert nicht anpassen, da er sn einer anderen stelle im Code wieder überschrieben wird.
Deswegen wäre dieser Variabel toll.

**Comment by jensweigele** [comment]
Ich habe schon angefangen mit dem "mergen". Ich implementiere aber einige Teile neu, damit es besser zur Architektur des Adapters passt. Zudem übersetze ich Teile des Codes in TypeScript.

**Comment by eumats** [comment]
Das hört sich doch super an...

**Comment by jensweigele** [comment]
Die Beta 2 ist in der Lage IP-Kameras einzubinden. 
Ich versuche in den nächsten Tagen noch etwas Doku dazu zu schreiben

**Comment by eumats** [comment]
Erstmal danke für Implementieren. Folgendes ist mir beim Testen aufgefallen:
Der Knopf "Add Camera" hat keine Funktion. Also bei Betätigen passiert nix. Ich konnte die Kamera nur über "Gerät hinzufügen" (Kategorie: Camera) und "Service hinzufügen" (CameraRTPStreamManagement) hinzufügen. Leider habe ich keine Ahnung, was ich bei den Feldern eintragen soll... ;-(
![yahka beta](https://user-images.githubusercontent.com/32279788/34647835-43e64110-f38e-11e7-984f-d4d66c6e8a1b.jpg)

**Comment by eumats** [comment]
Mit beta3 geht das Hinzufügen der Kamera perfekt. Der Live Stream kann auch gestartet werden.
Nur das Standbild/Einzelbild wird nicht getriggert.

"Normalerweise" wird die Aktualisierung des Standbildes/Einzelbildes sofort bei dem Aufschalten der Kamera im HomeKit getriggert, dass hat man in der "geforkten" Variante am ffmpeg Aufruf im debug Modus gesehen. In der beta3 wird keine ffmpeg Aufruf für das Standbild/Einzelbild ausgegeben. Bei dem Livestram schon...

**Comment by eumats** [comment]
Danke für das schnelle Fixen. Folgenden Auffälligkeiten zur beta4:
1. Bei "FFMPEG Command Line - Einzelbild:" ist "${resolution}" nicht definiert und sollte in der default Konfiguration durch "${width}x${height}" ersetzt werden. Sonst wird ffmpeg mit "-s undefined" aufgerufen.
2. Im Debug erscheint zwar nun das ffmpeg Kommando (Snapshot run: ffmpeg -re -ss 10 -i rtsp://user:pw@192.168.123.123:88/videoSub -t 1 -s 480x270 -f image2 -vframes 1 -) aber der Prozess wird nicht gestartet. Also ps ax zeigt kein ffmpeg Prozess an. Starte ich hingegen den Lifestream, ist bei ps ax der ffmpeg Prozess zu sehen.
3. Ich habe bei der Konfiguration folgenden eingetragen: Breite: 640, Höhe: 360. Beim Lifestream wird die Auflösung gemäß debug und Prozessliste übernommen. Hingegen beim Snapshot nicht. Da wird aus 640x360 ein 480x270. Ist das so gewollt?

**Comment by eumats** [comment]
Wie bereits im iobroker Forum besprochen, funktioniert es mit der beta4 nun perfekt. Die mit beta3 erzeugte Kamera musste nur gelöscht und mit beta4 neu erzeugt werden.

Und mit der von Dir zugelieferte Konfiguration kann sogar direkt die Snapshot Funktion der Foscam genutzt werden.

[
  "-re",
  "-i",
  "http://ip-cam:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=USER&pwd=PW",
  "-t",
  "1",
  "-s",
  "${width}x${height}",
  "-f",
  "image2",
  "-"
]

**Comment by jensweigele** [comment]
0.6.0 ist nun released - Ticket kann geschlossen werden.
