### ISSUE TITLE
Homekit int scaling ignore minimum

### ISSUE THREAD

**Issue by MiJo112** [jensweigele/ioBroker.yahka#201]
The yahka adapter ignore the minimum value and convert wrong.
See Screenshots
![image](https://user-images.githubusercontent.com/35043404/98291201-09d8bd80-1fab-11eb-821a-3d9aee60851b.png)
![image](https://user-images.githubusercontent.com/35043404/98291349-49070e80-1fab-11eb-995d-009a155090d1.png)

**Comment by jensweigele** [comment]
Please test with the current Master.
There was a fix commited some months ago but I'm not sure in which version this was released.
If the bug still exists, please reopen the ticket
