### ISSUE TITLE
Keine Verbindung seit iOS14.2

### ISSUE THREAD

**Issue by tomjuuu** [jensweigele/ioBroker.yahka#202]
Ich habe seit iOS14.2 keine Verbindung mehr zu meiner yahka Instanz. Alle Geräte "keine Antwort".
Das Entfernen aus HomeKit hat nichts gebracht, bzw jetzt kann ich yahka überhaupt nicht mehr zu Homekit hinzufügen.
Was kann man in so einer Situation machen?

**Comment by nicoh88** [comment]
Hi @tomjuuu,

da du die **YAHKA** Instanz in HomeKit eh schon entfernt hast, wirst du eh die Geräte erneut den Räumen zuordnen müssen. Ein Versuch wäre, erstmal den "Benutzernamen" / die Mac-Adresse zu ändern und den Adapter neuzustarten. Einfach eine Zahl tauschen o.ä.

![Bildschirmfoto 2020-11-15 um 21 04 25](https://user-images.githubusercontent.com/264264/99195535-adce2000-2786-11eb-973a-b78020e3c520.png)

Viel Glück.
Nico

**Comment by tomjuuu** [comment]
Hi Nico, vielen Dank für die Hilfe, ich hab das System jetzt aktualisiert und hab den yahka Benutzernamen geändert und es funktioniert wieder.  :-)
VG, Tom
