### ISSUE TITLE
Link services empty

### ISSUE THREAD

**Issue by DanielWeeber** [jensweigele/ioBroker.yahka#203]
Related #89 

Link services dropdown seems empty

![Bildschirmfoto 2020-11-24 um 23 43 48](https://user-images.githubusercontent.com/2935130/100160259-8296af80-2eaf-11eb-97bf-8eaea0327738.png)

**Comment by nicoh88** [comment]
@DanielWeeber Hast du den "Dienstnamen" eingeben und gespeichert? (ggf. neu laden)

https://github.com/jensweigele/ioBroker.yahka/wiki/Fernseher-mit-YAHKA-simulieren

**Comment by jensweigele** [comment]
@DanielWeeber kannst du mehr Details dazu liefern?
Welche Services hast du noch konfiguriert?

**Comment by DanielWeeber** [comment]
Funktioniert mit Dienstnamen,  habe ich übersehen. Aber es erscheint auch noch ein weiteres leeres Feld?

Gleichzeitig habe ich nun das Problem, dass nach dem ganzen Testen bzgl. Television ich jetzt in HomeKit ein "Television" habe was "Keine Antwort" zeigt, ich habe in Yahka aber nichts mehr mit "Television" drin

<img width="1580" alt="Bildschirmfoto 2021-01-08 um 09 50 04" src="https://user-images.githubusercontent.com/2935130/103994268-0920fb00-5197-11eb-8dd3-64dfe363c020.png">

**Comment by jensweigele** [comment]
In dem Screenshot sieht man zwei Services: "TV" und "" (der gerade offen ist).
Die Link-To-Box bietet immer "" und die Services des Geräts an.
D.h. es sind drei Services: "", "TV" und "" (der gerade offen ist).
Yahka sollte in der "Link-To-Box" den Service selbst nicht zur Auswahl anbieten (Verknüpfung mit sich selbst macht wenig Sinn).


Da du die Geräte ja ohne Bridge veröffentlichen musst, ist dein HomeKit vermutlich mit dem Gerät verknüpft das es einfach nicht mehr gibt. Gehe in Homekit und entferne das Gerät.

**Comment by DanielWeeber** [comment]
Ist nur Yahka noch drin.

![image](https://user-images.githubusercontent.com/2935130/104008774-33c87f00-51aa-11eb-837f-32d5eacd2180.png)

![image](https://user-images.githubusercontent.com/2935130/104008813-4478f500-51aa-11eb-908f-cfcb17e14b09.jpeg)

**Comment by jensweigele** [comment]
Drücke mal lange auf "Television" und gehe zu den Eigenschaften von dem Gerät (rechts unten) und schau mal ob du dort "Gerät entfernen" sagen kannst.
Das Gerät ist weder eine Steuerzentrale, noch eine Bridge - daher erscheint es auch nicht in dem ersten Screenshot.

**Comment by DanielWeeber** [comment]
Leider passiert gar nichts wenn ich auf den Knopf lange drücke, das war mein erster Versuch

**Comment by jensweigele** [comment]
Seltsam - bei mir öffnet sich beim tap auf "Keine Antwort", ein Popup mit allen Geräten die nicht antworten.
Findest du das Gerät noch irgendwo anders in dem Raum (unten in der Liste)?

**Comment by DanielWeeber** [comment]
Leider nein

**Comment by nicoh88** [comment]
Ich vermutet, du müsstest die Television-Bridge wieder anlegen, damit diese wieder verfügbar ist, dann kannst du sie entfernen und sollte dann weg sein.

Die Schwierigkeit wird die richtige MAC-Adresse (Username) sein.

Gruß Nico

**Comment by DanielWeeber** [comment]
Taucht leider in zwei verschiedenen Drittanbieter-Home-Apps nicht auf.
Keine Ahnung, was ich damals als Mac genommen hatte... :/

**Comment by jensweigele** [comment]
Im schlimmsten Fall, musst du ein neues Haus anlegen und neu konfigurieren.
Was anderes fällt mir nun auch nicht mehr ein.

**Comment by nicoh88** [comment]
@DanielWeeber: Das tut für dich sehr leid, wenn du alles wieder neu anlegen und einrichten müsstest. 😢 

Hast du vielleicht ein Backup von Ende November 2020, dass du in der `objects.json` schauen kannst?
**Ich drücke die Daumen!** Eventuell wird das "Problem", dass man den nicht mehr verfügbaren TV nicht entfernen kann, mit iOS 14.4 gelöst. 

Ich mache hier zu.

----

ALTER... 😅 
Check mal `/opt/iobroker/iobroker-data/yahka.0.hapdata`

**Comment by DanielWeeber** [comment]
Stimmt, da finde ich die alten Televisions. Nur sind da nicht die MACs?
Oder bin ich blind?
`root@iobroker:/opt/iobroker/iobroker-data/yahka.0.hapdata# grep -ri 'Television' ./
./AccessoryInfo.4DCE3A0215B9.json:{"displayName":"Television CC5B","category":"31","pincode":"123-45-678","signSk":"2f1eb55e32860bd5b09e42337b1924274cb6aaaa5232a09d2a75c8d0614924e551aa9ff2fb655c33c84463ea594f89d5e2627b94205ce964d54c5532e9df7ae7","signPk":"51aa9ff2fb655c33c84463ea594f89d5e2627b94205ce964d54c5532e9df7ae7","pairedClients":{"5516FD1D-1506-4581-828D-7935745A64A5":"9a14bfb82d82a0dd9a86d730b67e053224e47dcdb09452052aa0164967bb767e","6CD5E650-7556-4E61-9790-F7E856DDF2AF":"5d93355b23c33b587b0ca0b35e7ef49fa237d2c8d52230cefb1b3be895ed2cd8"},"pairedClientsPermission":{"5516FD1D-1506-4581-828D-7935745A64A5":1,"6CD5E650-7556-4E61-9790-F7E856DDF2AF":0},"configVersion":2,"configHash":"d69be03a039863f1bc2eac5bcb56c2f824873d5a","setupID":"KI3K"}
./AccessoryInfo.4DCE3A0215B2.json:{"displayName":"Television 29B0","category":"31","pincode":"123-45-678","signSk":"625dee023d4abfc13f809b9427e38cbafb70362ede80b4f0be8b2301d9834bed2f8265508e32ffb24408e06845218c46feb8453b915f73d4d8592b225885e604","signPk":"2f8265508e32ffb24408e06845218c46feb8453b915f73d4d8592b225885e604","pairedClients":{"5516FD1D-1506-4581-828D-7935745A64A5":"9a14bfb82d82a0dd9a86d730b67e053224e47dcdb09452052aa0164967bb767e","6CD5E650-7556-4E61-9790-F7E856DDF2AF":"5d93355b23c33b587b0ca0b35e7ef49fa237d2c8d52230cefb1b3be895ed2cd8"},"pairedClientsPermission":{"5516FD1D-1506-4581-828D-7935745A64A5":1,"6CD5E650-7556-4E61-9790-F7E856DDF2AF":0},"configVersion":2,"configHash":"d69be03a039863f1bc2eac5bcb56c2f824873d5a","setupID":"J2N0"}
./AccessoryInfo.D8BE54000011.json:{"displayName":"Television 674F","category":"8","pincode":"123-45-678","signSk":"945778427b0ec55b09fb1e05ed11f76078c6d98dc6bd4bf1db314c55a77dfaf0bbcc96bef79ea74f2a1c7f45f60a1dc841dd97ad022c91f64ea26fa0f2db2be3","signPk":"bbcc96bef79ea74f2a1c7f45f60a1dc841dd97ad022c91f64ea26fa0f2db2be3","pairedClients":{},"pairedClientsPermission":{},"configVersion":2,"configHash":"fa239c63e9a2e37b36158f10ae31898c9ad40fae","setupID":"LA16"}
`

**Comment by nicoh88** [comment]
Habe eigentlich gedacht, dass der Block hinter `AccessoryInfo.` die MAC-Adresse ist.

**Comment by DanielWeeber** [comment]
Du hast vollkommen recht. Eine konnte ich wieder hinzufügen und das Gerät löschen - half aber nicht. Die andere Mac konnte ich auf dem IOS Gerät nicht hinzufügen ("Konnte nicht hinzugefügt werden"), jetzt kriege ich es nicht mehr hin, dass es auftaucht. Egal, ob ich das Device neu einrichte oder nicht. Ich fummel mal weiter, das hat auf jeden Fall schon sehr geholfen. Danke.
