### ISSUE TITLE
Nach Umzug von raspi auf eine proxmox vm stürzt yahka ab

### ISSUE THREAD

**Issue by tardar** [jensweigele/ioBroker.yahka#207]
Hi zusammen,

ich habe meinen ioBroker vom RasPi auf einen mit Proxmox bestückten miniPC umgezogen.
Es läuft auch soweit alles wunderbar.

Allerdings wollte ich gerade HomeKit neu einrichten, was auch funktioniert hat (er hat geräte erkannt und angelegt, allerdings "Status: "Aktualisieren / keine Antwort"

Wird das Update der Status angefordert, stürzt yahka ab.

Ein Logfile habe ich Euch angehängt.

Findet sich jemand, der helfen kann ?

Danke Euch und ein schönes Wochenende 🙂
Tardar

[ioBroker_yahka_error_geraete_werden_nicht_aktualisiert.txt](https://github.com/jensweigele/ioBroker.yahka/files/5647158/ioBroker_yahka_error_geraete_werden_nicht_aktualisiert.txt)

Installation sieht wie folgt aus:
ioBroker 4.1.10
js-controller 3.1.6
nodeJs 12.20.0
yahka 0.11.0

Braucht ihr noch mehr Infos, dann ergänze ich die natürlich gerne 😉

**Comment by nicoh88** [comment]
@tardar 

Hast du YAHKA mal auf die aktuelle Master geupgraded?

Viele Grüße

**Comment by jensweigele** [comment]
Dein Problem steht direkt in den ersten Zeilen deines Logs:

> 2020-12-05 14:31:44.922 - error: yahka.0 (2371) TypeError: Cannot read property 'substring' of null
at TIoBrokerConversion_Script.eval [as toHKFunction] (eval at TIoBrokerConversion_Script (/opt/iobroker/node_modules/iobroker.yahka/main.js:1:1), :2:12)

Du scheinst eine Script-Funktion zu haben, die "substring" ausführt - auf einem undefinierten Wert.
Schaue mal ob in deinen Scripts irgendwo ".substring" auftaucht und führe eine Null/Undefined-Prüfung durch.

Vermutlich wurde in deiner neuen Instanz, der Variable noch kein Wert zugewiesen - dass ist wohl ein ähnliches Problem wie in #160, nur dass der Fehler diesmal in deinem Skript liegt.

**Comment by tardar** [comment]
Welche Art von Script meinst du ?
#In einem Blockly oder Javascript Script?
Oder an einer anderen Stelle ? :)
