### ISSUE TITLE
Daten/Einstellungen kopieren

### ISSUE THREAD

**Issue by valbuz** [jensweigele/ioBroker.yahka#209]
Versuche eine bestehende Yahka Installation auf einen neuen ioBroker zu zügeln (Nur Yahka!)
Versuchte dies mittels kopieren der Dateien: 
AccessoryInfo.xxxx und
IdentifierCache.xxx

Leider ohne Erfolg.

Gibt es eine Möglichkeit dies zu machen?

Danke
pat

**Comment by nicoh88** [comment]
Hallo @valbuz 

hast du die ganzen Objekte und Einstellungen auch wieder hergestellt? (`iobroker backup` / `iobroker restore`)
Ansonsten sollte das mit `AccessoryInfo.xxxx` und `IdentifierCache.xxx` richtig sein.

https://github.com/jensweigele/ioBroker.yahka/wiki/ioBroker.yahka-auf-ein-anderes-System-umziehen

Gruß Nico

**Comment by valbuz** [comment]
Hallo Nico.
Ich habe mir ein neues System installiert und natürlich auch einen neuen yahka-Adapter.
Und jetzt wollte ich die Einstellungen zügeln. Also eigentlich ohne Backitup etc.

**Comment by nicoh88** [comment]
@valbuz 

Das funktioniert so nicht. Bitte verwende auch `iobroker backup` / `iobroker restore`. Sonst fehlen sämtliche Einstellungen usw.

**Comment by stonemaan** [comment]
Hi, ich habe ein ähnliches Problem. Ich habe vor mein ioBroker von nem Pi auf den Mac umzuziehen. Habe am Pi ein Backup mit Backitup gemacht, und auf dem Mac eingespielt und die AccessoryInfo.xxxx und IdentifierCache.xxx händisch rüber kopiert. Leider erscheinen keine Geräte im Adapter. im Log findet sich unter debug auch kein Fehler.. nun bin ich verwirrt.. Mache ich was falsch? Danke schon mal
