### ISSUE TITLE
Error on 0.6.0

### ISSUE THREAD

**Issue by IONO-ioBrocker** [jensweigele/ioBroker.yahka#21]
update auf 0.6.0 error

Erro: startInstance yahka.0: cannot find start file!
INFO:object change system.adapter.yahka.0

log from ioBroker

**Comment by eumats** [comment]
Am Besten noch mal Debug im Adapter einschalten und dann die Ausgabe hier "posten".

**Comment by IONO-ioBrocker** [comment]
host.raspberrypi | 2017-12-16 01:09:32.850 | error | startInstance yahka.0: cannot find start file!
host.raspberrypi | 2017-12-16 01:09:32.834 | info | object change system.adapter.yahka.0
host.raspberrypi | 2017-12-16 01:09:28.610 | info | object change system.adapter.yahka.0

das ist der log im debung 
kann ich noch irgend wo debug erzeuegen wen ja wie

**Comment by jensweigele** [comment]
Ich vermute du hast über die GitHub Url installiert. Leider funktioniert das mit Yahka nicht, da die JS Dateien im Ordner "Build" liegen. Vielleicht kann @GermanBluefox  hier helfen und eine Anleitung geben, wie man einen Adapter in diesem Fall installieren kann

**Comment by jensweigele** [comment]
Der Adapter kann nun über ein separates Repo installiert werden:
https://github.com/jensweigele/iobroker.yahka-dist

Zudem habe ich version 0.6.0-beta.1 auf NPM veröffentlicht ("latest" zeigt immernoch auf 0.5.5!)
