### ISSUE TITLE
> @ciddi89

### ISSUE THREAD

**Issue by Ghoostplay04** [jensweigele/ioBroker.yahka#210]
> @ciddi89
> 
> Ich bin mir sicher, dass du dafür ein Blockly-Skript benötigst - da der Harmony-Hub Adapter keine passenden Datenpunkte hat. Aber das sollte ja kein Problem sein, dass ist ja das tolle an ioBroker. 😄
> 
> Viele Grüße
> Nico

Ich hätte wohl Interesse an dem Skript da ich da leider auch schon seit einiger zeit Rumprobiere

_Originally posted by @ciddi89 in https://github.com/jensweigele/ioBroker.yahka/issues/190#issuecomment-741869998_

**Comment by nicoh88** [comment]
Siehe [hier](https://forum.iobroker.net/topic/39565/harmony-mit-yahka-über-homekit-steuern).
