### ISSUE TITLE
Yahka läuft nach Installation des aktuellen Master nicht stabil

### ISSUE THREAD

**Issue by McSpitz** [jensweigele/ioBroker.yahka#212]
Ich habe die Github Version von Yahka installiert und seitdem läuft er leider nicht mehr stabil. Alle Geräte zeigen nach kurzer Zeit in rot „Keine Antwort“. Es gibt im Log trotz Verbose Modus keine erkennbaren Fehler.

Vielleicht war es meine Schuld? Ich hatte die ioBroker Version von Yahka bereits konfiguriert am Laufen (Stabil!!) und vorab nicht deinstalliert. Jemand eine Idee warum das so ist?

Was ich schon versucht habe:
- ich habe alles deinstalliert und neu installiert
- PI neu gebootet
- deinstalliert und alles verbliebenen Verzeichnisse gelöscht, die YAHKA angelegt hatte
- eine weitere Instanz angelegt, also .1, gleiches Ergebnis.

Läuft wenn überhaupt so lange bis zur Anmeldung des Gateways, danach dann schon das beschriebene Problem. "Keine Antwort". Das passiert schon wenn ich 1-2 Lampen als Lightbulb anlege mit dem Property On und Passthrough. Ist also von der Config auch kein Hexenwerk was ich da gemacht habe.

**Comment by jensweigele** [comment]
Von so einem Problem habe ich bisher noch nicht gehört. Könntest du bitte trotzdem mal das Log posten?
Deinstallieren oder sowas ist nicht notwendig, das Update sollte einfach funktionieren.

**Comment by jensweigele** [comment]
Vielleicht könnte dieses Bug dafür verantwortlich sein:
https://github.com/homebridge/HAP-NodeJS/issues/856

Der Unterscheid zwischen 0.11 und dem aktuellen Master ist u.a. dass die neuste HAP-NodeJS Lib eingesetzt wird (in der obiger Fehler wohl noch vorhanden ist)

**Comment by McSpitz** [comment]
das kann sein, mein Environment ist auch identisch quasi, außer dass das bei mir unter VMWare läuft...

Node.js v14.15.0 (Es gibt eine neuere Version: v14.15.3 - Empfohlene Version v12.20.0)
NPM 6.14.8

die 0.11 läuft stabil

**Comment by jensweigele** [comment]
@McSpitz  kannst du das bitte mit dem aktuellen Master nochmal probieren?
In der HAP-NodeJS Bibliothek wurde der Fehler vermutlich behoben und im aktuellen Master wird nun die neuste Version genutzt

**Comment by McSpitz** [comment]
@jensweigele nun läuft der Service stabil. Die Funktion mit der Türklingel auf dem Apple TV muss ich aber noch testen - wär ggf. etwas, dass man im Wiki beschreiben könnte.

(Randbemerkung - beim Update wurde aus dem Rolladen-Symbol ein Mann/Frau im. Bett.)

**Comment by Keyronics** [comment]
Hi, ich hab auch die Situation, dass in der Homekit app alle Geräte nicht mehr Reagieren. 
Der Adapter ist latest 0.12.0
Es befinden sich insgesamt 12 Sensoren/Aktoren im Adapter.
NPM v. 6.14.8
Node.js v12.20.0

iobroker befindet sich auf einem Pi 4 4GB mit raspian als os. 
Neustart hat nichts gebracht.

**Comment by jensweigele** [comment]
FYI: In #223 ist die Rede davon, dass Geräte mit 0.13.0 nicht mehr funktionieren, ein Downgrade auf 0.12.0 aber die Lösung bringt.

Es gibt also definitiv Probleme mit der zugrunde liegenden HomeKit Bibliothek.
Diese wurde von 0.11.0 auf 0.12.0 upgedated und hat eine starke Überarbeitung bekommen.
Mit 0.13.0 wurde ein weiteres update genutzt, welches eigentlich einige Probleme beseitigen sollte.

Ich werde mich demnächst nochmal auf dem Issue-Tracker von HAP-NodeJS umsehen (https://github.com/homebridge/HAP-NodeJS/issues/)

**Comment by EduardSarjadjuk** [comment]
https://github.com/jensweigele/ioBroker.yahka/issues/223#issuecomment-759254255

Musst nun doch leider feststellen, dass das Problem auch mit der Version 0.12 besteht. Mit der 0.11 hat es sauber funktioniert.

**Comment by nicoh88** [comment]
Hallo, ich habe ein paar Detailfragen zu euren Problemen:

1. Stehen die Geräte sofort auf "**Keine Antwort**" oder erst nach ein paar Stunden? 8-48 Stunden?
2. Sind alle iOS Geräte im Haus betroffen? Besteht das Problem auch im 3G/LTE/4G/5G-Netz? 
3. Reicht ein WLAN-Reconnect (WLAN deaktivieren, erneut aktivieren bzw. Flugmodus) um das Problem am iOS Gerät zu lösen?

Ich will parallelen zu meinem Problem #217 ausschließen.

Gruß Nico

**Comment by EduardSarjadjuk** [comment]
1. Erst nach ein paar Stunden mal dauerte es ein Tag und mal nur wenige Stunden.

2. Alle Geräte sind betroffen. Ist egal ob per WLAN oder 4G...

3. Nein ein neues Verbinden reicht nicht aus. 

4. Nein

5. Nein

LG

**Comment by nicoh88** [comment]
@EduardSarjadjuk Ok, danke. Keine parallelen zu meinem Problem.

Ohne klugscheißen zu wollen, denke ich, dass man deinen Absturz provozieren kann. 

Meiner Meinung nach kann es nur an einem fehlerhaft konfigurierten Gerät handeln, welches aufgrund der neuen HomeKit Bibliothek nun erst zum "Vorschein" kommt.

Kannst du den Absturz provozieren, indem du in einen bestimmten "Raum" wechselst? Bitte mal jeden Raum aufrufen und schauen ob YAHKA abstürzt. 
Wenn nein, dann wird vermutlich bei irgendeinem Gerät der Status über ioBroker geändert, dann an YAHKA übergeben, HomeKit kennt dann, beispielhaft, nur `0` oder `1`, bekommt von ioBroker aber `2` > Absturz.

Gruß Nico

**Comment by EduardSarjadjuk** [comment]
Hm, also ich habe nur noch 5 Geräte über den Yahka Adapter in HomeKit. Davon sind 3 einfache Schalter hinter denen ein Datenpunkt True /false liegt. Dann habe ich noch 2 Lampen in HomeKit. Diese Lampen sind nur dimmbare Lampen keine RGB bzw. Ambiente Lampen, kann also nur dimmen(level+true/false). Ehrlich gesagt weiß ich nicht was ich da falsch konfiguriert haben sollte. Ich kann denn Absturz nicht provozieren, zumindest konnte ich es nicht ausfindig machen.

**Comment by jensweigele** [comment]
Mit dem aktuellen Master, gibt es nun eine Option auf der Bridge/Kamera/Device, um auf die vorherige Bonjour-Bilbiothek zurück zu gehen - bitte mal testen ob das etwas bringt.

**Comment by EduardSarjadjuk** [comment]
Im Iobroker wird mir nur die Version 0.13 angezeigt

**Comment by al10b** [comment]
Ich habe die Probleme bei Version 0.12.0, bei 0.11.0 funktioniert es einwandfrei.

1. Nach dem Neustart funktioniert die Home App bei 0.12 zunächst, ich kann zunächst auch Lampen schalten. Dann nach 1-2 Minuten zeigt die Home-App noch nichts Ungewöhnliches an, aber es lässt sich schon nichts mehr schalten. Erst wenn ich den Raum wechsele kommt "Keine Antwort".
2. Alle Geräte, auch im 4G-Netz
3. Nein, keine Veränderung
4. Ja (2 Instanzen). Bei beiden dasselbe Verhalten.
5. Ja (1 Kamera), kein Bild, kein Ton.

**Comment by jensweigele** [comment]
@al10b kannst du mal bitte den aktuellen Master testen und "Use Legacy Advertiser" aktivieren?

**Comment by ManuelW77** [comment]
Hallo zusammen, ich möchte mich hier mal anschließen. Habe im ioBroker yahka 0.13.0 installiert und auch das Problem, dass nach einiger Zeit nix mehr erreichbar ist. Erst ein Neustart des yahka Adapters behebt das Problem.

1. nach längerer Zeit, mehrere Stunden
2. ja
3. nein, muss den Adapter neu starten. Im übrigen gehts auch auf HomePods nicht
4. nein
5. nein

Ich beobachte seit gestern auch das Logfile vom ioBroker, konnte aber bisher keine Fehlermeldungen entdecken.

**Comment by jensweigele** [comment]
@ManuelW77 könntest du bitte auch mal den aktuellen Master mit "Use Legacy Advertiser" testen?

**Comment by ManuelW77** [comment]
Ok, habe es eben installiert. Muss ich "Legacy Advertiser" für jedes Gerät aktivieren oder nur für die Bridge?

**Comment by jensweigele** [comment]
Normalerweise nur für die Bridge bzw. Kameras.
Bei den normalen Geräten nur wenn du auch "Publish as own device" angehakt hast (sie also nicht hinter der Bridge betreibst)

**Comment by ManuelW77** [comment]
Ok. Als own Device habe ich keine Geräte eingerichtet, Kamera habe ich nicht vorhanden und für die Bridge habe ich Legacy aktiviert. Ich werde beobachten und berichten.

**Comment by al10b** [comment]
@ jensweigele
Habe die 0.14 vor 20 Minuten installiert. Im Moment scheint alles zu laufen. Ich melde mich, wenn es wieder lodgeht - oder Morgen, wenn es weiterhin läuft. Danke erst einmal.

**Comment by ManuelW77** [comment]
Also bei mir läuft es bis jetzt mit der 0.14.0 stabil, hatte bisher keine Ausfälle.
Ich gebe morgen Abend nach der Arbeit nochmal eine Info wie es ausschaut.

**Comment by EduardSarjadjuk** [comment]
Seit gestern Abend läuft das System bei mir auf der 0.14 und ich habe bisher auch keine Ausfälle mehr.

**Comment by jensweigele** [comment]
Da für einige das Problem scheinbar behoben ist, gibt es nun 0.13.1 auf NPM.
Diejeniegen die den aktuellen Master installiert haben, bitte ich über "install specific version" nun die 0.13.1 zu installieren.
Die 0.14.0 aus dem Master wurde umbenannt zu 0.13.1 und hat noch einen Bugfix für das Löschen von Kameras bekommen.

**Comment by nicoh88** [comment]
> bitte ich über "install specific version" nun die 0.13.1 zu installieren.

Funktioniert aktuell noch nicht, da Version `0.13.1` scheinbar noch nicht in den `ioBroker Sources` ist.

#### Alternativ

```
npm install iobroker.yahka@0.13.1 --loglevel error --prefix "/opt/iobroker"
iobroker upload yahka
iobroker restart yahka
```

Nicht vergessen `Use Legacy Advertiser` in dem einen Bridge-Gerät und ggf. Kameras zu aktivieren.

#### Check im Log

ALT `ciao`:

```
2021-01-15 08:18:54.214  - info: yahka.0 (22744) publishing bridge ioBroker Yahka on 0.0.0.0 using ciao
2021-01-15 08:18:54.241  - info: yahka.0 (22744) publishing camera Kamera Rathaus Muenchberg on 0.0.0.0 using ciao
2021-01-15 08:18:54.245  - info: yahka.0 (22744) publishing camera Kamera Autobahn Muenchberg on 0.0.0.0 using ciao
```

NEU `hapBonjour `

```
2021-01-15 08:19:49.733  - info: yahka.0 (23627) publishing bridge ioBroker Yahka on 0.0.0.0 using hapBonjour
2021-01-15 08:19:49.755  - info: yahka.0 (23627) publishing camera Kamera Rathaus Muenchberg on 0.0.0.0 using hapBonjour
2021-01-15 08:19:49.758  - info: yahka.0 (23627) publishing camera Kamera Autobahn Muenchberg on 0.0.0.0 using hapBonjour
```
