### ISSUE TITLE
Sonos Lautsprecher bzw. generell einen Smartspeaker integrieren

### ISSUE THREAD

**Issue by sharky-os** [jensweigele/ioBroker.yahka#213]
Hallo, 
dank der Anleitung im Wiki für TV-Geräte mit verschiedenen Eingangsquellen ist es mir gelungen einen Sonos Lautsprecher zu integrieren. Er ist als TV-Gerät konfiguriert und ich kann ihn aktivieren/deaktivieren und zwischen vordefinierten Radiosendern wechseln. Die Lautstärke regel ich über einen Service als Lightbulb, was auch gut funktioniert.  Gibt es eine Möglichkeit die Lautstärke als echte Lautstärkeregelung zu integrieren oder das ganze sogar direkt als Smartspeaker/Homepod zu konfigurieren. 
Gruß Marco 
![IMG_2465](https://user-images.githubusercontent.com/46624258/103203017-4c0be480-48f4-11eb-95c5-546d859c95c3.PNG)

**Comment by SmartNightly** [comment]
Hast du mal den Service "TelevisionSpeaker" probiert? Ich wollte meine SONOS Arc am TV so integrieren. Habs auf die Schnelle jedoch nicht hin bekommen, auch nicht mit diesen [Infos](https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/gen/HomeKit-TV.ts). Wäre toll, wenn wir das hinkriegen würden.

**Comment by teilchenB** [comment]
Hi sharky-os, 

kannst du mal ein paar Details zu deiner oben aufgezeigten Lösung für die Senderauswahl bereitstellen? Steuerst du direkt die States von den Sonos-Lautsprechern in Ioboker oder hast du ein extra Skript dafür?

Hier mal mein Sonos-State bei dem ich das Verorten würde:

`sonos.0.root.192_168_178_40.current_station`

Der Ansatz mit dem TelevisionSpeaker ist ganz vielversprechend aber ich habe das bisher auch noch nicht hinbekommen. Homekit zeigt immer nur:" keine Verbindung"

Ich habe es auch noch mit dem Speaker und den Smartspeaker erfolglos probiert.

Evtl. hat hier nochmal jemand einen besseren Ansatz oder eine funktionierende Beispielkonfiguration.

Viele grüße, teilchenB

**Comment by sharky-os** [comment]
Hi, habe auch schon viel mit dem Televisionspeaker probiert, leider erfolglos.
@SmartNightly Danke für den Link, werde noch weiter probieren. 
@teilchenB  Mit dem Current_Station state hat es bei mir nicht funktioniert, aber mit diesem geht es "sonos.0.root.192_168_1_163.favorites_set".
Dann schaust Du bei "sonos.0.root.192_168_1_163.favorites_list" nach der Schreibweise des Senders, und fügst das in Dein Script ein. Ein Foto vom Blockly hänge ich an. 
Dann brauchst noch ein State, in meinem Fall yahka-sonos, was die Zahlen aus Yahka beim ändern eines Senders übernimmt. Anbei ein par Bilder von meinen Einstellungen. 

<img width="1098" alt="Bildschirmfoto 2020-12-31 um 11 40 18" src="https://user-images.githubusercontent.com/46624258/103406989-0ef65b00-4b5d-11eb-92ed-d32c2e5a1b2b.png">

<img width="1288" alt="Bildschirmfoto 2020-12-31 um 11 43 02" src="https://user-images.githubusercontent.com/46624258/103407069-6d233e00-4b5d-11eb-963e-cb7038fab842.png">

<img width="748" alt="Bildschirmfoto 2020-12-31 um 11 15 55" src="https://user-images.githubusercontent.com/46624258/103406243-53342c00-4b5a-11eb-8a63-9034be56d04c.png">

**Comment by SmartNightly** [comment]
Gemäss @nicoh88 in einem anderen [Beitrag](https://github.com/jensweigele/ioBroker.yahka/issues/120#issuecomment-749539991) werden CommunityTypes nicht von der Apple Home App unterstützt. Dazu verwendet er "Eve- oder Controller for HomeKit" App.

Evtl. kann hier jemand sagen, ob Apple Home App TelevisionSpeaker, Speaker oder SmartSpeaker grundsätzlich unterstützt. Oder dies direkt mit der Eve-App mal testen.

**Comment by sharky-os** [comment]
In eve, home+ oder controller wird das ganze Gerät gar nicht angezeigt. Scheinbar werden TV Geräte in den alternativen Apps noch nicht unterstützt. Habe noch einen LG TV, der dort auch nicht angezeigt wird. Televisionspeaker ist kein CommunityTyp. 
Gruß Marco

**Comment by dominusac12** [comment]
Ich hatte das gleiche Problem und bin auf folgende Beiträge gestoßen, die es eigentlich ganz gut zusammenfassen:

https://github.com/NRCHKB/node-red-contrib-homekit-bridged/issues/84#issuecomment-478839236
https://github.com/normen/homebridge-bravia#usage

Demnach sieht es Apple gar nicht vor, dass man die Lautsärke per Homekit App ändern kann. 
Der TelevisionSpeaker Service ist für ähnlich wie beim AppleTV/ Hompod wohl dafür gedacht die Lautstärke über das Controllcenter/ über die Lauter Leiser Tasten zu steuern. Ich glaube diese Funktionalität ist aber für Drittanbieter Geräte noch nicht ausreichend genug implementiert...

**Comment by teilchenB** [comment]
@sharky-os erstmal vielen Dank für deine Unterstützung, ich konnte das mit deiner Hilfe so einrichten und kann jetzt auch die Favoriten in der Homekit-App steuern. Allerdings funktioniert das ganze nur händisch und nicht per Sprachbefehl durch Siri.

Ich habe als Gerät einen Lautsprecher ausgewählt dadurch erhalte ich das passende Symbol in Homekit.
![image](https://user-images.githubusercontent.com/73251329/103462327-bec9f500-4d24-11eb-8ca6-2e63fad8798e.png)

Ich vermute, dass ich deshalb den Lautsprecher (die Bezeichnung kann ich auch nicht ändern) nicht per Siri steuern kann oder ist das generell nicht möglich?

![IMG_2718](https://user-images.githubusercontent.com/73251329/103462672-24b77c00-4d27-11eb-8ec0-ed948cb073f6.PNG)


@dominusac12 Vielen Dank für deinen Beitrag. Ich habe mir die Links mal angeschaut aber wenn ich das richtig verstehe dann konnte eine Steuerung durch emulierten Tastendruck (wie bei einer Fernbedienung) realisiert werden.
Wenn ich so die Lautstärke steuern könnte, währe das für mich auch ok. Leider weiß ich aber nicht wie ich das auf yahka umsetzen müsste.

Es währe einfach nur so genial, wenn ich meine ganzen Sonos Play 1 über yahka an Homekit anbinden könnte. Gibt es noch was anderes als "Brightness" zum Steuern der Lautstärke?

Viele grüße, teilchenB

**Comment by Tombra1889** [comment]
Hallo zusammen,

ich habe das Ganze mal mit meinem Echo Dot probiert.

Gibt es eine Möglichkeit auch die Details anzuzeigen. Also ein normaler Klick auf das Gerät startet und stoppt die Musik, soweit ok. Aber wie könnte Informationen zum Song, Cover etc. übertragen?

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/60692414/103468016-4f202e00-4d55-11eb-80ec-9dee2804706a.png">
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/60692414/103467980-e5078900-4d54-11eb-9cb9-808ab366f6d2.png">

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/60692414/103467992-0d8f8300-4d55-11eb-97fa-5a8a3b58804b.png">


![35058B19-FB52-4A59-BD8E-82B42B8B399E_1_105_c](https://user-images.githubusercontent.com/60692414/103467942-6d395e80-4d54-11eb-8044-2012f8b8c984.jpeg)

**Comment by andiweli** [comment]
Dem würde ich mich anschließen.
Versuche auch seit gestern einen ECHO 2.0 als Smartspeaker einzubinden.
Abgesehen davon, dass die Betriebsanzeige verkehrt ist (Kachel leuchtet wenn aus, Kachel ist aus wenn Musik gespielt wird) bekomm ich weder Lautstärkeregelung, noch die Cover/Titelanzeige hin.

**Comment by Tombra1889** [comment]
Hiermit funktionieren zumindest die grundlegenden Funktionen Play und Pause:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/60692414/103559880-26b04500-4eb7-11eb-9fb7-adc4ad5fbead.png">

**Comment by teilchenB** [comment]
> Hallo zusammen,
> 
> ich habe das Ganze mal mit meinem Echo Dot probiert.
> 
> Gibt es eine Möglichkeit auch die Details anzuzeigen. Also ein normaler Klick auf das Gerät startet und stoppt die Musik, soweit ok. Aber wie könnte Informationen zum Song, Cover etc. übertragen?
> 
> ![35058B19-FB52-4A59-BD8E-82B42B8B399E_1_105_c](https://user-images.githubusercontent.com/60692414/103467942-6d395e80-4d54-11eb-8044-2012f8b8c984.jpeg)

Das Bild zeigt ja ganz gut, dass es zumindest Bedienelemente für Audio in Homekit gibt. wie kann ich herausbekommen wie ich die verknüpfen kann? 

Alternativ währe ja auch eine Lautstärkensteuerung über 2 einfache Buttons denkbar (einen für lauter und einen für leiser). 

Gibt es den [Homekit Accessory Simulator](https://developer.apple.com/documentation/homekit/testing_your_app_with_the_homekit_accessory_simulator) auch für Windows oder eine Alternative dazu die unter Windows 10 funktioniert?
Dann kann man zumindest mal testen, was in Homekit schon geht und was nicht geht.

Viele Grüße, teilchenB

**Comment by sharky-os** [comment]
@teilchenB Bei mir funktioniert Siri auch nicht. Habe das mal mit meinem LG TV probiert, geht auch nicht mit Siri.
Dann habe ich mal versucht meinen Apple TV zu steuern, funktioniert eigentlich alles, bis auf Lautstärkeregelung (Schieberegler wird zwar angezeigt, ist aber ausgegraut). 

Gruß Marco

**Comment by tommyMX** [comment]
> Hi, habe auch schon viel mit dem Televisionspeaker probiert, leider erfolglos. @SmartNightly Danke für den Link, werde noch weiter probieren. @teilchenB Mit dem Current_Station state hat es bei mir nicht funktioniert, aber mit diesem geht es "sonos.0.root.192_168_1_163.favorites_set". Dann schaust Du bei "sonos.0.root.192_168_1_163.favorites_list" nach der Schreibweise des Senders, und fügst das in Dein Script ein. Ein Foto vom Blockly hänge ich an. Dann brauchst noch ein State, in meinem Fall yahka-sonos, was die Zahlen aus Yahka beim ändern eines Senders übernimmt. Anbei ein par Bilder von meinen Einstellungen.
> 
> <img alt="Bildschirmfoto 2020-12-31 um 11 40 18" width="1098" src="https://user-images.githubusercontent.com/46624258/103406989-0ef65b00-4b5d-11eb-92ed-d32c2e5a1b2b.png">
> 
> <img alt="Bildschirmfoto 2020-12-31 um 11 43 02" width="1288" src="https://user-images.githubusercontent.com/46624258/103407069-6d233e00-4b5d-11eb-963e-cb7038fab842.png">
> 
> <img alt="Bildschirmfoto 2020-12-31 um 11 15 55" width="748" src="https://user-images.githubusercontent.com/46624258/103406243-53342c00-4b5a-11eb-8a63-9034be56d04c.png">

Welches Script nutzt du da?
