### ISSUE TITLE
Multistate Taster Problem

### ISSUE THREAD

**Issue by HolgerOnGithub** [jensweigele/ioBroker.yahka#215]
Hallo, ich habe leider im Wiki nichts passendes gefunden. Und hoffe das es eine einfache Lösung gibt.
Ich habe Stromstoßrelais welche über i2c Relais für jeweis eine Sekunde angesteuert werden um Lampen im Haus ein und aus zu schalten. Die Lampen widerum haben parallel Finder Relais welche ebenfalls über i2c als Eingänge den Status liefern (16 Eingänge und dazu 16 Ausgänge in Form von Relais) Die Relais werden durch Scripte nur 1 Sekunde angesteuert. Soweit so gut.
Leider prüft der Yahka Lightbulb Multistate nicht ob die Lampe an oder aus ist, sonder richtet sich stupide nach der Lage der "Schalters" also des Write Datenpunktes.
Wenn ich nun einen Lichtschalter im Haus betätige zeigt das Homekitsymbol zwar richtig an ob die Lampe an oder aus ist (durch den Read Datenpunkt) jedoch wenn ich dann sage das er aus oder einschalten soll, kann es vorkommen das er "falschrum" steht Er schaltet also nicht um. oder macht bei aus die Lampe an etc. ganz problematisch wird es wenn man dann alle Lichter ausschalten lässt da er dann die vermeindlich eingeschalteten ausschaltet und sie dadurch in wirklichkeit einschaltet. 
Nochmal: das Sysmbol in Homkit zeigt es richtig aber die Sprachbefehle richten sich nicht nach den Read Status wie es aussieht.

Ich hoffe ich konnte mein Problem Nachvollziehbar erläutern.

Lösungsvorschläge meinerseits... einen echten Taster als write der den read status wert wirklich nutzen muss.
oder generell eine sortierung der schalterposition bei Readwertänderung. 

Mein Problem ist das ich natürlich nicht einfach bei Read Datenpunktänderung den Write Datenpunkt korregieren kann, da dies natürlich wieder als Schaltvorgang gewertet werden würde. Es sei denn ich könnte es als unbestätigte Änderung durchführen und meine Scripte würden nur bei bestätigten Änderungen reagieren.

Über einen Lösungsvorschlag wäre ich sehr dankbar da ich schon viel Zeit in dieses Problem investiert habe.
Gruss Holger

PS: Guten Rutsch

**Comment by jensweigele** [comment]
Ich bin mir noch nicht sicher, ob ich deinen Aufbau richtig verstehe. Du hast ein Relais welches über einen Stromstoß toggled.
Lampe ist an -> Stromstoß -> Lampe ist aus -> Stromstoß -> Lampe ist an
Das Ganze ist aber schon per Script "abstrahiert", sodass du dort einen Datenpunkt hast "Licht Soll" der entweder 0 oder 1 ist (ein/aus). 
Das Skript wird vermutlich bei einer Flanke den Stromstoß auslösen (bzw. den I2C Befehl senden)

Zusätzlich hast du einen Datenpunkt "Licht Ist", welcher den aktuellen Zustand darstellt. 

Korrekt?

Weiter schreibst du, dass manchmal der falsche Zustand hergestellt wird - sprich: 
"Lampe Ist": AN
"Lampe Soll": AUS
"Lampe Soll" wird aber auf "AN" geschrieben!?

Eine Log Ausgabe hierzu wäre praktisch, um zu sehen, was genau passiert.

**Comment by HolgerOnGithub** [comment]
Vielen Dank für die Antwort: Anbei viele  Bilder 

I2C liest die ist zustände und möchte gern als impuls angesteuert werden


daher habe ich die i2c datenpunkte mit scripte umgewandelt 

somit habe ich datenpunkte die true/false sind wenn geschalten wurde,
jedoch ändern sich diese Datenpunkte halt nicht wenn manuell geschalten
wurde 

die STATUS-DATENPUNKTE ändern sich jedoch und zeigen den wirklichen
Zustand der jeweiligen Lampen an. 

Problem ist also das Homekit mit dem (nennen wir es) Schalterzustand
arbeitet und nicht wirklich mit dem gelesenen Status, obwohl ich ja den
Actual als read und den SET als write eingestellt habe. 

Oder ich habe einen Fehler im Kopf. 

Am 2021-01-03 17:25, schrieb Jens Weigele: 

> Ich bin mir noch nicht sicher, ob ich deinen Aufbau richtig verstehe. Du hast ein Relais welches über einen Stromstoß toggled.
> Lampe ist an -> Stromstoß -> Lampe ist aus -> Stromstoß -> Lampe ist an
> Das Ganze ist aber schon per Script "abstrahiert", sodass du dort einen Datenpunkt hast "Licht Soll" der entweder 0 oder 1 ist (ein/aus).
> Das Skript wird vermutlich bei einer Flanke den Stromstoß auslösen (bzw. den I2C Befehl senden) 
> 
> Zusätzlich hast du einen Datenpunkt "Licht Ist", welcher den aktuellen Zustand darstellt. 
> 
> Korrekt? 
> 
> Weiter schreibst du, dass manchmal der falsche Zustand hergestellt wird - sprich:
> "Lampe Ist": AN
> "Lampe Soll": AUS
> "Lampe Soll" wird aber auf "AN" geschrieben!? 
> 
> Eine Log Ausgabe hierzu wäre praktisch, um zu sehen, was genau passiert. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

  

Links:
------
[1]
https://github.com/jensweigele/ioBroker.yahka/issues/215#issuecomment-753641422
[2]

**Comment by jensweigele** [comment]
Deine Zip-Datei enthält Bilder von deinem Mail-Provider - ich denke die solltest du entfernen.

**Comment by HolgerOnGithub** [comment]
Danke für den Hinweis, Korregiert. 

Am 2021-01-03 23:28, schrieb Jens Weigele: 

> Deine Zip-Datei enthält Bilder von deinem Mail-Provider - ich denke die solltest du entfernen. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

  

Links:
------
[1]
https://github.com/jensweigele/ioBroker.yahka/issues/215#issuecomment-753685283
[2]

**Comment by HolgerOnGithub** [comment]
>  Flanke

Ich möchte nochmals auf Deinen Wortlaut zurückkommen.

Mein Problem ist das der Datenpunkt LAMPE SOLL durch deinen Yahka Adapter auf "true" geschrieben wird wenn dieser die Lampe einschaltet und auf "false" geschrieben wird wenn dieser die Lampe ausschaltet. Wenn die Lampe jedoch manuell ein oder ausgeschalten wird ändert sich im IO Broker zwar der LAMPE IST Wert auf passend "true" für an oder "false" für aus und somit erzeugt der Adapter auch das richtige Symbol in Homekit jedoch denkt Homekit weiterhin aufgrund des LAMPE SOLL das das Gerät aus ist.
                                 Gerät         ioBroker Datenpunkte
                                Lampe       Lampe Soll      Lampe Ist
Ausgangspunkt           off               false                 false
Yahkabefehl on                               true 
daraufhin folgt             on               -"-                   true
Yahkabefehl off                               false
daraufhin folgt            off                -"-                   false

soweit alles gut nun externe Lampenschaltung dazwischen

manuell on                  on                -"-                   true             PROBLEM Lampe Soll steht weiterhin auf false
Yahkabefehl off                               false
daher passiert nun gar nichts und die Lampe bleibt an da sich der Wert Lampe soll nicht ändert false/false

**Comment by HolgerOnGithub** [comment]
Nachtrag false/false wird nicht aktualisiert also ich reagiere auf eine Aktualisierung des Datenpunkt jedoch wird leider das fals bzw. True falls es bereits so steht nicht überschrieben also nicht mal aktualisiert.

**Comment by nicoh88** [comment]
Hallo @HolgerOnGithub,

wenn ich das Problem richtig verstanden habe. Könnte ein neuer Alias Datenpunkt das Problem lösen, wie man es auch beim ZWave2-Adapter machen muss, bei CurrentValue (read) und TargetValue (write). Damit brauchst du auch kein zusätzliches Skript mehr.

Viele Grüße

**Comment by HolgerOnGithub** [comment]
Mit einem AliasDatenpunkt habe ich es bereits probiert. Es Ändert jedoch
nichts daran das ich quasi einen Taster ohne Feste Werte (True/False)
zum Schalten benutze und ich diesen Status nicht Updaten kann ohne auch
das Relais I2C anzusprechen was wiederum da (toggle) ja immer ein
entgegengesetztes Schalten zur Folge haben würde. 

Wenn Befehl von Yahka dann Datenpunkt yahka_lampe_soll auf true ->
Lampe_soll true -> Lampe ist true 

wenn manuell geschalten wurde bleibt aber der Datenpunkt
yahka_lampe_soll auf true und daher wird der Befehl Lampe an nun nicht
mehr im ioBrokerDatenpunkt aktualisiert somit ist auch nichts
auswertbar. 

Im Umkehrschluss kann ich aber auch nicht differenzieren ob sich der
Lampe_Ist geändert hat ohne das dies durch Lampe_soll geschehen ist,
auch wenn ich das könnte würde ich ja nun den Datenpunkt
yahka_lampe_soll aktualisieren müssen und das hätte zur Folge das ja
doch wieder ein Schaltvorgang in Gang gesetzt werden würde und somit die
lampe wieder entgegengesetzt Schalten würde. 

Leider weis ich nicht wie ich es anders Beschreiben soll. 

Am 2021-01-06 07:02, schrieb Nico Hartung: 

> Hallo @HolgerOnGithub [1], 
> 
> wenn ich das Problem richtig verstanden habe. Könnte ein neuer Alias Datenpunkt das Problem lösen, wie man es auch beim ZWave2-Adapter machen muss, bei CurrentValue (read) und TargetValue (write). Damit brauchst du auch kein zusätzliches Skript mehr. 
> 
> Viele Grüße 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

  

Links:
------
[1] https://github.com/HolgerOnGithub
[2]
https://github.com/jensweigele/ioBroker.yahka/issues/215#issuecomment-755100954
[3]

**Comment by jensweigele** [comment]
Mein Vorschlag wäre, dein "Write"-Script anzupassen.

Statt einfach nur auf Änderung zu reagieren, solltest du bei einer Änderung, auch prüfen ob der Wert ungleich dem READ-Wert ist.

Beispiel:
WRITE-Wert steht auf "true" (Lampe soll an sein)
READ-Wert steht auf "true" (Lampe ist an)
Wenn du nun am Schalter ausschaltest, hast du:
WRITE: true
READ: false
Wenn du nun in Homekit ausschaltest, bekommst du:
WRITE: false
READ: false
Wenn du nun in deinem Write-Script prüfst, ob der neue Write-Wert ungleich dem Read-Wert ist, würdest du in obigem Fall nichts tun (da FALSE === FALSE ist)

**Comment by HolgerOnGithub** [comment]
Prinzipell gut, jedoch Triggert leider nichts wenn die Lampe durch
manueller umschaltung bei Licht_IST auf True steht jedoch der Lampe_SOLL
des Yahka noch auf false 

nun will Homekit ausschalten sieht jedoch das der datenpunkt Lampe_Soll
bereits false ist und lässt ihn einfach (noch nicht einmal aktualisiert)
somit würde kein Script anlaufen und nichts passiert. 

Nur wenn ich nun Homkit sage er soll sie anschalten (bleibt die lampe
natürlich an) ABER nun wird auch der Datenpunkt LICHT_Soll auf true
gesetzt. Anschließend ist jetzt ein Ausschalten auch mit Homekit
möglich. Bis halt das nächste mal ausserhalb von der Logik geschalten
wurde. 

Mit anderen worten wenn der Adapter den Wert wenigstens refreshen
(aktualisieren) würde wär mir geholfen. 

Am 2021-01-06 11:19, schrieb Jens Weigele: 

> Mein Vorschlag wäre, dein "Write"-Script anzupassen. 
> 
> Statt einfach nur auf Änderung zu reagieren, solltest du bei einer Änderung, auch prüfen ob der Wert ungleich dem READ-Wert ist. 
> 
> Beispiel:
> WRITE-Wert steht auf "true" (Lampe soll an sein)
> READ-Wert steht auf "true" (Lampe ist an)
> Wenn du nun am Schalter ausschaltest, hast du:
> WRITE: true
> READ: false
> Wenn du nun in Homekit ausschaltest, bekommst du:
> WRITE: false
> READ: false
> Wenn du nun in deinem Write-Script prüfst, ob der neue Write-Wert ungleich dem Read-Wert ist, würdest du in obigem Fall nichts tun (da FALSE === FALSE ist) 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

  

Links:
------
[1]
https://github.com/jensweigele/ioBroker.yahka/issues/215#issuecomment-755213842
[2]

**Comment by jensweigele** [comment]
> nun will Homekit ausschalten sieht jedoch das der datenpunkt Lampe_Soll
bereits false ist und lässt ihn einfach (noch nicht einmal aktualisiert)
somit würde kein Script anlaufen und nichts passiert.

Für Homekit ist die Lampe an, d.h. Homekit schickt "false" und Yahka wird auch "false" schreiben - aber du hast natürlich keine Änderung und daher läuft dein Script nicht an.

Nächster Vorschlag:
Ändere dein Write-Skript zu:
-1: nichts zu tun
0: ausschalten
1: einschalten
Ablauf ist dann in etwa so:

Bei jeder Änderung prüfen ob der Wert <> -1 ist - wenn ja, prüfen ob Wert !== IST, wenn ja: impuls rausgeben
Am Ende des Skripts den Wert auf -1 zurückschreiben (falls der Impuls ausgegeben wird, evtl. in diesem Fall erst NACH dem Impuls auf -1 setzen)

So sollte jeder Schreibbefehl einen Durchlauf deines Skripts bewirken.

**Comment by HolgerOnGithub** [comment]
Also ich habe es nun ganz anders gelöst.
Da der Yahka Adapter bei bereits vorhandenen false diesen auch nicht mit false aktualisiert (was als Trigger jä reichen würde)
habe ich nun per Blockly

`<xml xmlns="https://developers.google.com/blockly/xml">
  <variables>
    <variable id="S6CAfHO%t`cgvP5Huh82">Yahka_Ändert</variable>
    <variable id="MSW02@5|=-gSf/=hoWyb">Manuell_Geändert</variable>
    <variable type="timeout" id="timeout3">timeout3</variable>
    <variable type="timeout" id="timeout2">timeout2</variable>
    <variable type="timeout" id="timeout">timeout</variable>
    <variable type="timeout" id="timeout4">timeout4</variable>
  </variables>
  <block type="variables_set" id="I54.7XPq{32L6Ui{JXux" x="13" y="-112">
    <field name="VAR" id="S6CAfHO%t`cgvP5Huh82">Yahka_Ändert</field>
    <value name="VALUE">
      <block type="logic_boolean" id="izB[*D;ez^1gamVS_@oz">
        <field name="BOOL">FALSE</field>
      </block>
    </value>
    <next>
      <block type="on_ext" id="o%6/BmX/hvI%ZqTtUx-N">
        <mutation xmlns="http://www.w3.org/1999/xhtml" items="1"></mutation>
        <field name="CONDITION">ne</field>
        <field name="ACK_CONDITION"></field>
        <value name="OID0">
          <shadow type="field_oid" id="(Fgxz0|9#eto}ih2|e]T">
            <field name="oid">0_userdata.0.EsWerdeLicht.Taster.Ankleidezimmer</field>
          </shadow>
        </value>
        <statement name="STATEMENT">
          <block type="controls_if" id="(8^PyJKG|V!?]/Y+H1v[">
            <value name="IF0">
              <block type="logic_compare" id=")YQw19+Vq_0oVE*.)$M?">
                <field name="OP">EQ</field>
                <value name="A">
                  <block type="variables_get" id="+`!RNW!75q-tQS.Q[=]J">
                    <field name="VAR" id="MSW02@5|=-gSf/=hoWyb">Manuell_Geändert</field>
                  </block>
                </value>
                <value name="B">
                  <block type="logic_boolean" id="8@5|5|$]j:r;CDkUFJ-(">
                    <field name="BOOL">FALSE</field>
                  </block>
                </value>
              </block>
            </value>
            <statement name="DO0">
              <block type="controls_if" id="iLC-Q2#sc7s2$M.3Q-*G">
                <mutation elseif="1"></mutation>
                <value name="IF0">
                  <block type="logic_operation" id="%k!JzQLzI5*ki;#.suyu" inline="false">
                    <field name="OP">AND</field>
                    <value name="A">
                      <block type="logic_compare" id="UXqh9*1_q7J:(~6r7r+?">
                        <field name="OP">EQ</field>
                        <value name="A">
                          <block type="get_value" id="PpYDHqk5d`[)aOL8$cK$">
                            <field name="ATTR">val</field>
                            <field name="OID">0_userdata.0.EsWerdeLicht.Taster.Ankleidezimmer</field>
                          </block>
                        </value>
                        <value name="B">
                          <block type="logic_boolean" id="P2(7^.,?ZLaBIhM]J1B-">
                            <field name="BOOL">TRUE</field>
                          </block>
                        </value>
                      </block>
                    </value>
                    <value name="B">
                      <block type="logic_compare" id="~YOXG%8jaOSBNqXq1d7`">
                        <field name="OP">EQ</field>
                        <value name="A">
                          <block type="get_value" id="@gTn+Wo;HPVkS=if]$WT">
                            <field name="ATTR">val</field>
                            <field name="OID">0_userdata.0.EsWerdeLicht.Status.Ankleidezimmer</field>
                          </block>
                        </value>
                        <value name="B">
                          <block type="logic_boolean" id="zi}P`H!r;Qgwo88qNPPg">
                            <field name="BOOL">FALSE</field>
                          </block>
                        </value>
                      </block>
                    </value>
                  </block>
                </value>
                <statement name="DO0">
                  <block type="variables_set" id="rNOuTB6AbqnUre/LJL49">
                    <field name="VAR" id="S6CAfHO%t`cgvP5Huh82">Yahka_Ändert</field>
                    <value name="VALUE">
                      <block type="logic_boolean" id="l}/,9l(hu#7-dtZ4h6U!">
                        <field name="BOOL">TRUE</field>
                      </block>
                    </value>
                    <next>
                      <block type="control" id="u!;]x^vD9;V79niexk:c">
                        <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                        <field name="OID">i2c.0.0x21.B4</field>
                        <field name="WITH_DELAY">FALSE</field>
                        <value name="VALUE">
                          <block type="logic_boolean" id="2^g5r;YTi)Oxg!+WQnc:">
                            <field name="BOOL">TRUE</field>
                          </block>
                        </value>
                        <next>
                          <block type="control" id="3[6{4R!d^U*:MiCQc0+/">
                            <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="true"></mutation>
                            <field name="OID">i2c.0.0x21.B4</field>
                            <field name="WITH_DELAY">TRUE</field>
                            <field name="DELAY_MS">1000</field>
                            <field name="UNIT">ms</field>
                            <field name="CLEAR_RUNNING">FALSE</field>
                            <value name="VALUE">
                              <block type="logic_boolean" id="@kkG**Cjo%fn;X1.x?vu">
                                <field name="BOOL">FALSE</field>
                              </block>
                            </value>
                            <next>
                              <block type="timeouts_settimeout" id="BZu)U9y|}3c^q;P=^l9l">
                                <field name="NAME">timeout2</field>
                                <field name="DELAY">3</field>
                                <field name="UNIT">sec</field>
                                <statement name="STATEMENT">
                                  <block type="variables_set" id="SgWKYYG.~X[Wv{UG?UBK">
                                    <field name="VAR" id="S6CAfHO%t`cgvP5Huh82">Yahka_Ändert</field>
                                    <value name="VALUE">
                                      <block type="logic_boolean" id="Eg`u~kiLdnBtbecZJ`_:">
                                        <field name="BOOL">FALSE</field>
                                      </block>
                                    </value>
                                  </block>
                                </statement>
                              </block>
                            </next>
                          </block>
                        </next>
                      </block>
                    </next>
                  </block>
                </statement>
                <value name="IF1">
                  <block type="logic_operation" id="z/~Pf.siE7?OoMicZ*#9" inline="false">
                    <field name="OP">AND</field>
                    <value name="A">
                      <block type="logic_compare" id=",4g`^$.cBY{arN^EJe|h">
                        <field name="OP">EQ</field>
                        <value name="A">
                          <block type="get_value" id="apd8!WOx18WA`~%Q])z_">
                            <field name="ATTR">val</field>
                            <field name="OID">0_userdata.0.EsWerdeLicht.Taster.Ankleidezimmer</field>
                          </block>
                        </value>
                        <value name="B">
                          <block type="logic_boolean" id="lJ7b:85TxMxBha@}rUXJ">
                            <field name="BOOL">FALSE</field>
                          </block>
                        </value>
                      </block>
                    </value>
                    <value name="B">
                      <block type="logic_compare" id="!Ju29_|_H[4H4Vm6x7IX">
                        <field name="OP">EQ</field>
                        <value name="A">
                          <block type="get_value" id="vI10V4hN)%Gv:./E%$HA">
                            <field name="ATTR">val</field>
                            <field name="OID">0_userdata.0.EsWerdeLicht.Status.Ankleidezimmer</field>
                          </block>
                        </value>
                        <value name="B">
                          <block type="logic_boolean" id="yWRJ3mF,Z1(7cM`WzY`9">
                            <field name="BOOL">TRUE</field>
                          </block>
                        </value>
                      </block>
                    </value>
                  </block>
                </value>
                <statement name="DO1">
                  <block type="variables_set" id="j-_,$7BvgrklHJZa/,D~">
                    <field name="VAR" id="S6CAfHO%t`cgvP5Huh82">Yahka_Ändert</field>
                    <value name="VALUE">
                      <block type="logic_boolean" id="h}X+E5BGxPO.=[Ejj*fh">
                        <field name="BOOL">TRUE</field>
                      </block>
                    </value>
                    <next>
                      <block type="control" id="Q;A,5R8!p]N.Xl];Bb(K">
                        <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                        <field name="OID">i2c.0.0x21.B4</field>
                        <field name="WITH_DELAY">FALSE</field>
                        <value name="VALUE">
                          <block type="logic_boolean" id="$-z=I//fE.[~Ij]!;8sp">
                            <field name="BOOL">TRUE</field>
                          </block>
                        </value>
                        <next>
                          <block type="control" id="IUKmP%.Jzk*,G_L0#gz[">
                            <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="true"></mutation>
                            <field name="OID">i2c.0.0x21.B4</field>
                            <field name="WITH_DELAY">TRUE</field>
                            <field name="DELAY_MS">1000</field>
                            <field name="UNIT">ms</field>
                            <field name="CLEAR_RUNNING">FALSE</field>
                            <value name="VALUE">
                              <block type="logic_boolean" id="~EB^$KB$sc{q-U;BSos/">
                                <field name="BOOL">FALSE</field>
                              </block>
                            </value>
                            <next>
                              <block type="timeouts_settimeout" id="E5Z3aZMZ1VUT44eoui$v">
                                <field name="NAME">timeout</field>
                                <field name="DELAY">3</field>
                                <field name="UNIT">sec</field>
                                <statement name="STATEMENT">
                                  <block type="variables_set" id="c:sga`B;jyv]lK`sGuMW">
                                    <field name="VAR" id="S6CAfHO%t`cgvP5Huh82">Yahka_Ändert</field>
                                    <value name="VALUE">
                                      <block type="logic_boolean" id="hkqEZ$JFo]6jALyU.3m@">
                                        <field name="BOOL">FALSE</field>
                                      </block>
                                    </value>
                                  </block>
                                </statement>
                              </block>
                            </next>
                          </block>
                        </next>
                      </block>
                    </next>
                  </block>
                </statement>
              </block>
            </statement>
          </block>
        </statement>
      </block>
    </next>
  </block>
  <block type="variables_set" id="~n)0?Y:_8VMJaJKCq9wH" x="937" y="-113">
    <field name="VAR" id="MSW02@5|=-gSf/=hoWyb">Manuell_Geändert</field>
    <value name="VALUE">
      <block type="logic_boolean" id="EH+$[9_Q4^{(x)bT$PR/">
        <field name="BOOL">FALSE</field>
      </block>
    </value>
    <next>
      <block type="on_ext" id="VAWrGaKS=,rzU$q.,VQL">
        <mutation xmlns="http://www.w3.org/1999/xhtml" items="1"></mutation>
        <field name="CONDITION">ne</field>
        <field name="ACK_CONDITION"></field>
        <value name="OID0">
          <shadow type="field_oid" id="Au)3gX{Oi:UCvoNBZ43E">
            <field name="oid">0_userdata.0.EsWerdeLicht.Status.Ankleidezimmer</field>
          </shadow>
        </value>
        <statement name="STATEMENT">
          <block type="controls_if" id="Z1OR43Wx(LJSm)Tp.7U(">
            <value name="IF0">
              <block type="logic_compare" id="qPL]yl6_Ct]mW^1`?Ox+">
                <field name="OP">EQ</field>
                <value name="A">
                  <block type="variables_get" id="A,_JZK-$UI34@nq1dz={">
                    <field name="VAR" id="S6CAfHO%t`cgvP5Huh82">Yahka_Ändert</field>
                  </block>
                </value>
                <value name="B">
                  <block type="logic_boolean" id="9K`Rkca,xq8lJLrfd_.4">
                    <field name="BOOL">FALSE</field>
                  </block>
                </value>
              </block>
            </value>
            <statement name="DO0">
              <block type="variables_set" id="%1AAw5)#I7`[@.{0YIo8">
                <field name="VAR" id="MSW02@5|=-gSf/=hoWyb">Manuell_Geändert</field>
                <value name="VALUE">
                  <block type="logic_boolean" id="Q+0Iq:O7u1Hc%Mj|N7e%">
                    <field name="BOOL">TRUE</field>
                  </block>
                </value>
                <next>
                  <block type="controls_if" id="ifVB]8cywf|!p(xYe+*K">
                    <value name="IF0">
                      <block type="logic_compare" id="IH!E[5?JV/(spn0#F[87">
                        <field name="OP">EQ</field>
                        <value name="A">
                          <block type="get_value" id="(k9.0R#gpl|cRItYvMWV">
                            <field name="ATTR">val</field>
                            <field name="OID">0_userdata.0.EsWerdeLicht.Status.Ankleidezimmer</field>
                          </block>
                        </value>
                        <value name="B">
                          <block type="logic_boolean" id="s%]d.6])R+(1rxDtH5~T">
                            <field name="BOOL">TRUE</field>
                          </block>
                        </value>
                      </block>
                    </value>
                    <statement name="DO0">
                      <block type="control" id="vZs?Vr%{etgK^`S}VBR)">
                        <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                        <field name="OID">0_userdata.0.EsWerdeLicht.Taster.Ankleidezimmer</field>
                        <field name="WITH_DELAY">FALSE</field>
                        <value name="VALUE">
                          <block type="logic_boolean" id="DHI=yp~sV{K~i+H1^;4z">
                            <field name="BOOL">TRUE</field>
                          </block>
                        </value>
                        <next>
                          <block type="timeouts_settimeout" id="D^4s$;0[.;-8+wfS)n6!">
                            <field name="NAME">timeout3</field>
                            <field name="DELAY">3</field>
                            <field name="UNIT">sec</field>
                            <statement name="STATEMENT">
                              <block type="variables_set" id="3TNUdaJx%+qHEJL7FX[R">
                                <field name="VAR" id="MSW02@5|=-gSf/=hoWyb">Manuell_Geändert</field>
                                <value name="VALUE">
                                  <block type="logic_boolean" id="Fa+,XIhi(Yy|=f3R8N%~">
                                    <field name="BOOL">FALSE</field>
                                  </block>
                                </value>
                              </block>
                            </statement>
                          </block>
                        </next>
                      </block>
                    </statement>
                    <next>
                      <block type="controls_if" id="*PXCzZH4L!`HG%!TdW?f">
                        <value name="IF0">
                          <block type="logic_compare" id="zC2a3+S$vnhHI]d!X|hu">
                            <field name="OP">EQ</field>
                            <value name="A">
                              <block type="get_value" id="Yaq`ueFjB4.)0hCMtj9f">
                                <field name="ATTR">val</field>
                                <field name="OID">0_userdata.0.EsWerdeLicht.Status.Ankleidezimmer</field>
                              </block>
                            </value>
                            <value name="B">
                              <block type="logic_boolean" id=",|o@bSXI(sWwTIV,Gnp4">
                                <field name="BOOL">FALSE</field>
                              </block>
                            </value>
                          </block>
                        </value>
                        <statement name="DO0">
                          <block type="control" id="p^MWyaJ$y:o:lWJI?1%$">
                            <mutation xmlns="http://www.w3.org/1999/xhtml" delay_input="false"></mutation>
                            <field name="OID">0_userdata.0.EsWerdeLicht.Taster.Ankleidezimmer</field>
                            <field name="WITH_DELAY">FALSE</field>
                            <value name="VALUE">
                              <block type="logic_boolean" id="|YCSRgyRbi!`|6:=iJ~_">
                                <field name="BOOL">FALSE</field>
                              </block>
                            </value>
                            <next>
                              <block type="timeouts_settimeout" id="S/)w`OB,TtLoYJ+W~.:M">
                                <field name="NAME">timeout4</field>
                                <field name="DELAY">3</field>
                                <field name="UNIT">sec</field>
                                <statement name="STATEMENT">
                                  <block type="variables_set" id="OCUm@R=M%{C}%zm+bQ9o">
                                    <field name="VAR" id="MSW02@5|=-gSf/=hoWyb">Manuell_Geändert</field>
                                    <value name="VALUE">
                                      <block type="logic_boolean" id="E}%A~p@f!DU-Dc!KDOYF">
                                        <field name="BOOL">FALSE</field>
                                      </block>
                                    </value>
                                  </block>
                                </statement>
                              </block>
                            </next>
                          </block>
                        </statement>
                      </block>
                    </next>
                  </block>
                </next>
              </block>
            </statement>
          </block>
        </statement>
      </block>
    </next>
  </block>
</xml>`

es dahingehend geändet das ich die true und fals Werte selber setzte wenn manuell eine Änderung durchgeführt wird.
Das heißt wenn Lampe Status ändert wird die Relaisansteuerung nicht durchgeführt und auch die Auswertung des Licht_Soll Status unterbunden, dann wird der Status von Licht_Soll geändert und die Bedienung wieder freigegeben.
Wenn Yahka den Licht_Soll ändert wird im umkehrschluss die Verarbeitung des Licht_Ist verhindert und alles schick.


Nur durch dieses Blockly ist es nun möglich das Homekit auf die Frage ob ein bestimmtes Licht eingeschaltet ist auch richtig antwortet.
