### ISSUE TITLE
KNX Rolladen Status wird in Apple Home nicht aktualisiert.

### ISSUE THREAD

**Issue by DirkDoe** [jensweigele/ioBroker.yahka#216]
Hallo,

ich bin neu hier, tüftel aber schon seit einiger Zeit an iobroker und Yahka rum.

Meine Rolladen habe ich alle Yahka integriert und alles läuft soweit auch ganz gut, bis auf die kleine aber nervige Sache,
dass der Status der Rolladen im Apple Home nicht aktualisiert wird wenn man einen manuell (per KNX Taster) fährt und in einer Art Dauerschleife von "wird geöffnet" oder "wird geschlossen" hängen bleibt.
Bestimmt gab es dazu schon Lösungen und Threads, allerdings suche ich mittlerweile auch schon seit 5 Tagen danach und finde irgendwie nichts passendes, da das ganze Thema so mächtig ist, das es einfach unzählige Threads zu allen möglichen Variationen gibt und nichts was ich gefunden habe, hat mir geholfen.

Falls also einer einen Plan davon hat und mir helfen könnte, wäre ich echt dankbar. 
Ich hänge noch meine Yahka und Objekt settings an, falls es weiterhilft.

Danke.

<img width="943" alt="Yahka" src="https://user-images.githubusercontent.com/76871754/103458440-7e5c7e00-4d08-11eb-82e1-e0f5d3dc9413.png">
<img width="1237" alt="Objekte" src="https://user-images.githubusercontent.com/76871754/103458441-80264180-4d08-11eb-8152-c158d8d73975.png">

**Comment by Tomba1889** [comment]
Hey, ich glaube du hast den Status bei PositionState falsch hinterlegt. Leg dir am besten einen Status im User-Ordner an und lass dir diesen als Blockly-Script aktualisieren.
PositionState muss so aussehen:
<img width="826" alt="image" src="https://user-images.githubusercontent.com/60692414/103458780-aef1e700-4d0b-11eb-8a4a-d2023dcca8e2.png">

**Comment by DirkDoe** [comment]
Einwandfrei, ging leichter als gedacht, manchmal hängt man einfach in seiner Schleife fest und braucht neue Denkanstöße.

Ich danke dir 👍 

Zur Lösung meines Problems für die Nachwelt (geht bestimmt auch anders oder leichter?!):
Apple Home bzw Yahka aktualisiert den Status in der App über den Wert der im PositionState steht und nicht über den Wert der Current Position.
Da der Wert der Current Position von Yahka über den KNX Adapter aktualisiert wird, der PositionState aber nicht, habe ich ich mir wie, ähnlich wie von Tomba empfohlen (danke nochmal) ein Blockly Script gebaut, das auf die Änderung von "Tür Küche" also dem Single Object reagiert und PositionState ("Tür Küche Position" also die Absolute Position) auf den Wert des Status angepasst wird. So ändert sich jetzt jedes mal bei manueller Fahrt der Wert der Absoluten Position in Yahka auf den Wert der Aktuellen Position.

<img width="744" alt="Bildschirmfoto 2021-01-02 um 23 11 34" src="https://user-images.githubusercontent.com/76871754/103467501-e5e9ec00-4d4f-11eb-921f-ca2dc142f74d.png">

**Comment by Tomba1889** [comment]
Ich weiß jetzt leider nicht, welche Informationen dir das KNX System ausgibt, daher ggf. auch einfacher möglich.

Du könntest sonst noch die Zeit für das Hoch- und Runterfahren stoppen und dann während dieser Zeit PositionState auf 0 bzw. 1 stellen. Dann hast du in Homekit die korrekte Visualisierung.

Also im Endeffekt bei CurrentPosition mit 0 starten, dann TargetPosition 100 einstellen.
PositionState auf 1 schalten.
25 Sekunden warten.
PositionState auf 2 schalten.
CurrentPosition auf 100 stellen.

**Comment by DirkDoe** [comment]
Auf und Abfahrt hab ich schon gestoppt und in der ETS beim jeweiligen Kanal der Jalousieaktoren hinterlegt, also die tatsächliche Zeit wird in % als CurrentPosition angegeben. 

Aber was meinst du mit 0, 1 und 2? da bin ich jetzt noch nicht dahinter gestiegen, also wo bzw wie kann ich das und wofür überhaupt einstellen?

**Comment by Tombra1889** [comment]
Wenn du links in dem Bereich auf "properties" klickst kommen Informationen zu der jeweiligem Characteristics. PositionState ist von Apple mit drei Werten vorgegeben. Also 0, 1, 2 - 0 und 1 sind die jeweiligen Status wenn sich der Rolladen in Bewegung befindet und 2 ist der, wenn der Rolladen gestoppt ist. So wie ich es in deiner Konfiguration sehe, versuchst du eine 100 zu übertragen, daher ignoriert Homekit es wahrscheinlich.

**Comment by DirkDoe** [comment]
Du meinst diese properties? Da gibts bei mir nicht Decreasing, Increasing und stopped, deswegen check Ichs nicht ^^

<img width="941" alt="Bildschirmfoto 2021-01-03 um 00 04 21" src="https://user-images.githubusercontent.com/76871754/103468250-3e70b780-4d57-11eb-946d-b37d40cceb66.png">

**Comment by Tombra1889** [comment]
ja genau. 0 bedeutet decreasing. Also wenn du in dem Status eine 0 überträgst zeigt der Rolladen in Homekit "decreasing" an. Bei 1 "increasing" und bei 3 "stopped"
Ich würde daher einfach einen weiteren Status in ioBroker anlegen und dann via Blockly diesen Status aus CurrentPosition und TargetPosition zusammenbauen. Apple hat sich das ganze so gedacht, dass mit TargetPosition die Zielposition angegeben wird, daher dies zum Schalten dienen soll. CurrentPosition wird dann vom Aktor übermittelt solange diese Werte ungleich sind soll eine Logik via PositionState die Bewegung zeigen.

**Comment by jensweigele** [comment]
Kann ich das Ticket schließen?
Wie bereits beschrieben, muss "PositionState" zwischen 0 und 2 liegen und stellt nicht die Position dar, sondern den Status:
0 - herunterfahren
1 - hochfahren
2 - steht

**Comment by DirkDoe** [comment]
Jap, sorry. War mega beschäftigt mit allem möglichem (bin am umbauen).
Danke nochmal 😁

**Comment by MarkM500** [comment]
Hallo Zusammen,

bin leider absoluter Neuling in diesem Thema.

Kann mir jemand die einzelnen Schritte erklären? Blocky Script ist komplettes Neuland.

@Dirk Doe: Wie hast Du das tatsächlich jetzt umgesetzt. Kannst Du mir Dein Script zur Verfügung stellen?

Danke Gruss Mark

**Comment by DirkDoe** [comment]
@MarkM500 
Ich habs leider mit dem „selbst erstellten status“ 0, 1 und 2 auch nicht hinbekommen (der mensch ist faul xD und meine Lösung funktioniert einwandfrei mit einem klitzekleinen scriptchen), poste aber morgen mal ein-zwei screenshots von meinem script und den yahka settings.
Letztendlich aktualisiert Blockly einfach nur den Status. Das passiert eben nicht wenn du das script nicht hast und deswegen erkennt home nicht, dass sich was geändert hat, ausser du betätigst im HomeKit nochmal den Rolladen.
Es ist aber halt nicht die absolut richtige Lösung

**Comment by MarkM500** [comment]
Das wäre supi...

**Comment by DirkDoe** [comment]
Also, da bin ich wieder :D 

Ich glaube zwar es wird dich nicht weiter bringen, weil du, so wie es in deinen anderen issues aussieht kein knx nutzt, sondern was anderes?!

Ich habe zuerst mal den Status auf "Current Position" gelegt (weil ich dachte "hey, dann weiß das ding immer wo der Rolladen steht, ist ja schließlich der Status :D") 
Dann habe ich meine absolute Position (weil die ja schreibt) auf "Position State" gelegt und zusätzlich noch auf "Target Position" um dem system durch Target Position auf meine absolute Position sagen zu können wo der Rolladen hin soll.

Das ganz hat dann noch nicht gereicht, da beide Systeme ein bisschen verschieden denken. Also hab ich mir Nächte um die Ohren geschlagen und irgendwann festgestellt, dass Homekit sich über "current position" eben die Position zum visualisieren holt. Damit bin ich auch nicht weitergekommen und hab dann diesen issue eröffnet. 
Den Wert der Positionen hab ich invertiert, weil sonst ist offen = zu und zu = offen :D

Mit meiner Lösung funktioniert eigentlich alles soweit:
"Hey Siri fahre Rolladen A auf 76%"
"Hey Siri fahre Rolladen A zu"
"Hey Siri fahre Rolladen A auf"
Automationen funktionieren usw

Letztendlich aktualisiere ich eben über ein mickriges Blockly-Script das einfach nur die "current position" aktualisiert.

<img width="948" alt="Bildschirmfoto 2021-02-09 um 22 02 11" src="https://user-images.githubusercontent.com/76871754/107429803-a66ba800-6b24-11eb-9207-951d0870e0ef.png">

<img width="1239" alt="Bildschirmfoto 2021-02-09 um 22 03 01" src="https://user-images.githubusercontent.com/76871754/107429806-a8ce0200-6b24-11eb-8cca-ac3f35216435.png">

<img width="687" alt="Bildschirmfoto 2021-02-09 um 22 03 53" src="https://user-images.githubusercontent.com/76871754/107429807-a9ff2f00-6b24-11eb-95ad-0b0072efef9f.png">

Falls du noch Fragen versuch ich dir gerne zu helfen.

Viel Spaß damit

**Comment by MarkM500** [comment]
Hi,

verstehe ich nicht...Weil Du schreibst doch den gleichen Wert von Status in Position. Hätte man dann nicht gleich 3 mal den Status nehmen können. Eigentlich dachte ich, dass Apple bei Postion die Werte 0, 1, 2 erwartet, also Runter, rauf oder Stop?
Kannst Du mir das erklären? Gruss Mark

**Comment by MarkM500** [comment]
HEY SUPER. Gerade ausprobiert. Funktioniert. Tausend Dank.

Gruss,
Mark

**Comment by andremueller83** [comment]
kein Problem - freut mich :)

**Comment by frooonk** [comment]
Hallo andremueller83,

auch ich bedanke mich vielmals für Deine Einstellungen (Rolladen/Jalousien) im ioBroker mit dem YAHKA-Adapter. Super!

Seit dem Einzug vor 4 Jahren (!) bin ich jetzt schon am Herumexperimentieren mit Node RED, wie ich meine Rolladen/Jalousien mit HomeKit steuern kann - und jetzt bin ich hier fündig geworden. Ich frag' mich zwar, wie man auf sowas kommt, weil die Einstellungen im YAHKA-Adapter ja nicht gerade selbsterklärend sind, aber ich bin noch ziemlich neu mit ioBroker unterwegs ...

Eine Frage hätte ich dazu noch: bei den Jalousien möchte ich gerne auch den Lamellenwinkel mit HomeKit steuern und habe dazu die Properties "CurrentHorizontalTiltAngle" bzw. "TargetHorizontalTiltAngle" probiert. Aber leider sieht man keine Auswirkungen in HomeKit. Habe es schon mit und ohne Konversion (invers) 90 probiert. Leider ohne Erfolg... Was mache ich hier falsch?

Vielen Dank nochmals und Grüße,
Frank

**Comment by andremueller83** [comment]
Hallo Frank,
schön das ich dir weiterhelfen konnte. Ich hab mal versucht dein Thema nachzustellen. (selbst habe ich nur Rolladen und keine Jalousien).

Hast du in der ETS die Gruppenadressen für "Absolute Lamellenposition" und "Status aktuelle Lamellenposition" korrekt belegt?

![image](https://user-images.githubusercontent.com/70439951/116809464-738eea00-ab3e-11eb-8620-ec6776c6ffed.png)

Im Yahka könntest du das vermutlich wie folgt umsetzen (wenn das nicht geht, nimm die Einstellungen mal bei TargetHorizontalTiltAngle rein.

![image](https://user-images.githubusercontent.com/70439951/116809655-5eff2180-ab3f-11eb-8cf6-6138a7d64e90.png)

Viele Grüße
André

**Comment by xaser1408** [comment]
Hi @andremueller83 , deine Lösung funktioniert soweit super, danke fürs Bereitstellen. Das einzige Problem was ich habe ist, wenn ich von einem KNX-Taster aus die Steuerung ausführe, dass dann die nächste Aktion über Apple Home nicht funktioniert. Hier mal der Ablauf:
- MDT Glastaster -> Rollo runterfahren
- Apple Home zeigt Status "Geschlossen" -> Rückmeldung funktioniert also
- Apple Home -> klick auf Rollo, um dieses wieder zu öffnen, Text "wird geöffnet" erscheint -> nichts passiert am Rollo
- Apple Home -> noch mal Klick auf Rollo um Aktion zu unterbrechen, Text "Geschlossen" erscheint -> am Rollo passiert nichts
- Apple Home -> noch mal Klick auf Rollo um dieses zu öffnen -> nun fährt das Rollo korrekt
Hast du schon mal so ein Thema gehabt? Habe mir auch mal die Datenpunkte im ioBroker angeschaut, denke das Problem ist, dass der Wert für "Position anfahren" (bzw. absolute Position) nicht gesetzt wird, wenn man über KNX-Taster das Rollo fährt.
Danke und viele Grüße,
Stephan

**Comment by andremueller83** [comment]
Hi Stephan,
ich habe es mal genau wie du beschrieben hast nachgestellt.

MDT Glastaster -> Rollo runterfahren
Apple Home zeigt Status "Geschlossen" -> Rückmeldung funktioniert also
Apple Home -> klick auf Rollo, um dieses wieder zu öffnen, Text "wird geöffnet" erscheint -> nichts passiert am Rollo
--> schon in dem Schritt öffnet bei mir wie geplant das Rollo

Somit sollte es nix mit der Position zu tun haben.

Hast du die Einstellungen exakt so vorgenommen, wie in meinem Screenshot am commented 8. April 2021 hier beschrieben?

Hast du selbst eine ETS Version in welcher du mal einen Busmitschnitt machen könntest?

Poste bitte mal per Screenshot die Einstellungen des Objekts im Yahka Adapter und sofern möglich die Einstellungen (Gruppenadressen) des Jalousieaktors aus der ETS. Viele finde ich ja den Fehler.

Viele Grüße
André

**Comment by xaser1408** [comment]
Hi André,

danke für dein Feedback und das Nachstellen.

Ich denke schon, dass ich die Einstellung so durchgeführt habe, wie du es beschrieben hattest. Aber ich packe mal noch Screenshots von meinen Einstellungen rein, vielleicht übersehe ich ja was:
Yahka (v0.13.1):
![image](https://user-images.githubusercontent.com/100207877/155281902-b7796246-ffac-4dc5-bff2-b55e5aa81568.png)
Jalousien-Aktor:
![image](https://user-images.githubusercontent.com/100207877/155282247-dc0a8360-d0f4-4dbf-a124-1bbe536330c6.png)
MDT-Glastaster:
![image](https://user-images.githubusercontent.com/100207877/155282408-d30c527d-6069-44fc-a303-406f41d74d4f.png)

ETS habe, habe auch zum größten Teil das Projekt selbst entwickelt. Von der Aktor-Seite her ist ABB verbaut (JRA/S8.230.5.1 Jal./Rol.Akt.Fahrzt.man.8f,230V,REG). Busmitschnitt könnte ich anfertigen, wenn dies hilft.

Danke und viele Grüße
Stephan

**Comment by andremueller83** [comment]
Hallo Stephan,
das sieht aus meiner Sicht erstmal alles gut aus.
Schön wäre das du mal einen Busmitschnitt machen könntest was auf dem Bus bei dem Schritt passiert:

Apple Home -> klick auf Rollo, um dieses wieder zu öffnen, Text "wird geöffnet" erscheint -> nichts passiert am Rollo

Kannst du im Aktor einstellen, wann das Objekt "Status Höhe" aktualisiert wird? Evtl. kannst du dort ja mal auf zyklisch und "aller x Sekunden" einstellen. 

So hab ich es bei mir eingestellt (ich habe allerdings einen MDT Jalousieaktor)
![image](https://user-images.githubusercontent.com/70439951/155493302-064272d8-c6a1-4d61-9395-53912955cac8.png)

**Comment by xaser1408** [comment]
Hallo André,

ich habe den ganzen Prozess mal versucht zu protokollieren:
1. Mit MDT Glastaster Rollo schließen. 
In Home sieht es dann so aus:
![IMG_1833](https://user-images.githubusercontent.com/100207877/155505404-0d0ea166-3c02-45ce-8dc6-b6e312f76d23.PNG)
In ioBroker sieht es so aus:
![IMG_1834 (1)](https://user-images.githubusercontent.com/100207877/155505737-037396ad-aa04-4d95-aa11-c454e191d8f3.jpg)
2. Klick in Home um Rollo wieder zu öffnen.
Home sieht dann so aus:
![IMG_1835](https://user-images.githubusercontent.com/100207877/155505951-0b938365-470a-44b8-bd21-e945c523f607.PNG)
Im Busmitschnitt wurden keine Telegram aufgezeichnet:
![IMG_1836](https://user-images.githubusercontent.com/100207877/155506250-86efeb54-02ed-4610-a324-9eac2498e5ea.jpg)
Und im ioBroker sieht es wie folgt aus:
![IMG_1837](https://user-images.githubusercontent.com/100207877/155506490-035c7d9b-de78-427c-b81d-c2488da01c55.jpg)

Sieht so aus, als ob Yahka kein Veränderung des Datenpunktes veranlasst, weil "position anfahren" ja schon auf 0% steht, was ja "offen" bedeutet. Liegt hier vielleicht doch noch ein Bug in Yahka vor? 

Ich konnte zwischenzeitlich auch einen kleinen Workaround finden. Wenn ich "rückmeldung position" in "position anfahren" fortschreiben (z.B. für den Fall dass Steuerung über Glastaster erfolgt), dann funktioniert alles problemlos. So sieht mein Skript aus:
![Bildschirmfoto 2022-02-24 um 11 33 18](https://user-images.githubusercontent.com/100207877/155507881-ee97142d-1d41-4930-952d-d4cab111a718.png)

Vielleicht hast du ja da noch eine Idee?!

Danke und viele Grüße
Stephan

**Comment by andremueller83** [comment]
Hi Stephan,
also das "Position anfahren" nimmst du ja nur, wenn du sagst "Rollade Küche 50%". Wenn du am Glastaster die Rollade runter fährst bleibt "Rollade anfahren" korrekterweise auf 0% das du auf den Glastaster nur die "Fahren" Funktion auslöst. Bei mir steht da auch 0% wie bei dir. Das ist so korrekt - das kann es aus meiner Sicht nicht sein.

Aber - du wirst Dich freuen - ich habe das gleiche Verhalten bei mir jetzt auch nachstellen können. Ich fahre die Rollade herunter und beim ersten Tastendruck auf die Rollade im Homekit geht diese nicht auf. (ist bisher nie aufgefallen, da bei uns die  Rolladen über Sonneneinstrahlung gesteuert werden).

Eine Lösung dafür habe ich leider noch nicht. Vielleicht hat ja jemand anderes hier noch eine Idee.

**Comment by Marc9608** [comment]
Hallo zusammen,

ich stehe seit Tagen auch vor dem Problem meine Rollos in Yakha richtig zu konfigurieren....
Es sind ja mittlerweile 3 Jahre vergangen... vielleicht gab es seit dem ja auch noch Änderungen..

Ich benutze kein KNX. Ich habe Rolladenaktoren von Homematic IP.

Gibt es jemanden der diese bei Yakha drin hat und mir die Konfiguration hier einmal reinstellen könnte?
Ich habe nun endlich alles in meinem Smart Home am laufen.... außer die Rollos. Ich bin um jeden Rat dankbar!
