### ISSUE TITLE
YAHKA Bridge nach Stunden am dauerhaft "DisplayOn" iPad nicht verfügbar (Keine Antwort) | Workaround: WLAN reconnect / Netzwerk-Scan

### ISSUE THREAD

**Issue by nicoh88** [jensweigele/ioBroker.yahka#217]
Hallo HomeKit-Freunde,

vorab erstmal ein gesundes neues Jahr euch allen! Ich möchte heute ein Problem mit euch Teilen, bei dem ich noch keine 100%ige Lösung habe. Ich glaube auch nicht, dass es an YAHKA liegt. Da hier aber einige versierte Personen unterwegs sind, wollte ich mal eure Meinungen / Ideen einholen.

### Umgebung

- Kabel-Modem im Bridge-Mode, OpenWRT Router (TP-Link Archer C7 v2) und 4 OpenWRT APs (TP-Link RE450 v2) per LAN angebunden.
- Raspberry Pi 3B+ mit Raspbian 10.6 für PiHole als DNS
- SelfMade-NAS mit Debian 10.7 (Intel i5, 4x DVB-S2 Ports, SSD, 3 HDDs im RAID 5); ioBroker- + Homebridge-Installation;
- iPad mini 5. Generation an der Wand, immer geöffnete Apple Home App

### Fehler

Nach ein paar Stunden, bisher kein erkennbares Muster, sind die Geräte der iobroker Yahka-Instanz nicht verfügbar. Szenen werden nicht ausgeführt, Geräte werden mit dem roten Schriftzug "Keine Antwort" angezeigt.

### Analyse

- Das iPad ist dauerhaft mit dem WLAN verbunden und im Netzwerk pingbar, keine Aussetzer.
- Hartes Schließen der Home App und erneutes Öffnen löst das Problem nicht.
- Geräte der Yahka-Instanz sind in der Eve-App o.ä. auch nicht erreichbar.
- "ping" vom iPad auf 192.168.137.10 (SelfMade NAS mit ioBroker) erfolgreich.
- "ping" vom iPad auf "iobroker-yahka-822b.local" erfolgreich.
- "avahi-daemon" @ 192.168.137.10 neustarten ohne Verändung.
- Die Geräte der Homebridge-Installation sind in der Apple Home App auf dem iPad ist verfügbar.
- Auf anderen iOS Geräten oder mit macOS sind die Geräte der Yahka-Instanz verfügbar.
- Die zwei Kameras der Yahka-Instanz sind auch verfügbar.

Das finde ich spannend, weil Yahka somit fast als Problemauslöser ausscheidet - da die Kameras über einen eigenen mDNS- / Bonjour-Namen angesprochen werden. Vielleicht werden die von der Home App aber auf andere Art und Weise abgefragt?!

![issue](https://user-images.githubusercontent.com/264264/103909092-8bf87600-5103-11eb-8533-fd93aea0b166.jpg)

### Workaround

1. Workaround: WLAN deaktivieren, WLAN aktivieren, nach 10 Sekunden sind alle Geräte der Yahka-Instanz wieder verfügbar. (Dauerhafte-Lösung: Automation über Kurzbefehle jede volle Stunde?)
2. Workaround: App "IT Tools" öffnen, Netzwerk-Scan durchführen, zurück zur Home-App, alle Geräte der Yahka-Instanz wieder verfügbar.

### Eure Meinung?

Was meint der Rest?

----

Gruß & Danke
Nico

**Comment by andiweli** [comment]
Ich hab nicht wirklich eine Lösung parat, aber seit ich vom iPad mit Homeapp an der Wand auf ein Apple TV für die "Zentrale" gewechselt bin, habe ich das Problem auch nicht mehr.

**Comment by jensweigele** [comment]
Hi Nico,

welche Yahka Version hast du drauf? (es gab einige Bonjour fixes mit der aktuellsten Master-Version)

Ich denke aber unabhängig davon auch nicht, dass Yahka für die Probleme verantwortlich ist.
Wir haben in der Firma ein eigenes Protocol in unseren iOS Geräten, welches die anderen iOS Clients im gleichen Netzwerk ebenfalls über Bonjour sucht/findet.
Dort hatte ich nun schon öfter das Problem, dass manche Access-Points den Bonjour Traffic blockieren (manche sofort, manche erst nach einigen Minuten). Bonjour arbeitet viel mit Broadcasts und irgendein Filter in den APs blockt den Traffic. Billige/Einfache APs "brechen" auch teilweise zusammen wenn mehrere Geräte Bonjour anfragen senden bzw. viel Netzwerktraffic verursachen.

Zwei Vorschläge zur weiteren Eingrenzung: 
1. Alle Anti-Spoof, Anti Intrusion, Firewall etc. Geschichten ausschalten auf den APs
2. kaufe dir mal ein Lightning auf Ethernet Adapter und schau ob es kabelgebunden funktioniert (wobei ich nicht weiß, ob das iPad dann weiterhin als Steuerzentrale fungiert, da es laut Apple ja am Strom angeschloßen sein muss - vielleicht vorher noch ein Lightning-Port-Multiplier holen, damit du das iPad auch laden kannst).

**Comment by nicoh88** [comment]
> Ich hab nicht wirklich eine Lösung parat, aber seit ich vom iPad mit Homeapp an der Wand auf ein Apple TV für die "Zentrale" gewechselt bin, habe ich das Problem auch nicht mehr.

Danke für die Info. Habe ingesamt drei HomeKit-Steuerzentralen: iPad an der Wand am Dauerstrom, HomePod und HomePod mini. In der Regel ist immer der große HomePod die aktive Zentrale, die anderen beiden stehen auf Standby.

> Hi Nico,
> 
> welche Yahka Version hast du drauf? (es gab einige Bonjour fixes mit der aktuellsten Master-Version)

Ich hatte die Master-Version vom "[Dec 23, 2020](https://github.com/jensweigele/ioBroker.yahka/commit/5cb92bc245356910f9659e414ec0c666cce14932)" (State Selector is now reading the objects on every opening) drauf. Habe jetzt die Master von [Heute](https://github.com/jensweigele/ioBroker.yahka/commit/4d60dac9252281345d19a1cb95e7d3501fa173c9) (Release of 0.13.0) drauf und werden nochmal testen.

> Ich denke aber unabhängig davon auch nicht, dass Yahka für die Probleme verantwortlich ist.
> Wir haben in der Firma ein eigenes Protocol in unseren iOS Geräten, welches die anderen iOS Clients im gleichen Netzwerk ebenfalls über Bonjour sucht/findet.
> Dort hatte ich nun schon öfter das Problem, dass manche Access-Points den Bonjour Traffic blockieren (manche sofort, manche erst nach einigen Minuten). Bonjour arbeitet viel mit Broadcasts und irgendein Filter in den APs blockt den Traffic. Billige/Einfache APs "brechen" auch teilweise zusammen wenn mehrere Geräte Bonjour anfragen senden bzw. viel Netzwerktraffic verursachen.

Ok, danke für die Info.

> Zwei Vorschläge zur weiteren Eingrenzung:
> 
> 1. Alle Anti-Spoof, Anti Intrusion, Firewall etc. Geschichten ausschalten auf den APs
> 2. kaufe dir mal ein Lightning auf Ethernet Adapter und schau ob es kabelgebunden funktioniert (wobei ich nicht weiß, ob das iPad dann weiterhin als Steuerzentrale fungiert, da es laut Apple ja am Strom angeschloßen sein muss - vielleicht vorher noch ein Lightning-Port-Multiplier holen, damit du das iPad auch laden kannst).

Danke für deine Vorschläge, werde ich testen. Ich bin die letzten Stunden nochmal in mich gegangen und habe überlegt, was sich die letzten 1-2 Monate geändert hat:

- iPadOS 14.1 - 14.3
- Anschaffung HomePod's (iPad an der Wand nicht mehr alleinige HomeKit-Steuerzentrale)
- Vodafone-Kabel Modem in den Bridge-Mode versetzt
- OpenWRT-Router Wechsel von `Linksys WRT1900AC` auf `TP-Link Archer C7`
- OpenWRT Update alle APs inkl. Router von `19.07.3` auf `19.07.4`
- Anschaffung eufy Security Indoor Cam 2K Pan and Tilt
- Debian-, Homebridge-, ioBroker und YAHKA-Updates

Ich werde jetzt erstmal alle OpenWRT-Geräte auf `19.07.3` downgraden und testen, dann ggf. Update auf `19.07.5`. Das Gute, das Problem tritt eigentlich jeden Morgen, beim Wechsel der Etage und Ausführen der Szene "_Indirekte Beleuchtung_", am iPad an der Wand auf.

Spannend ist und bleibt, dass alle anderen Geräte außer das iPad mit den Geräten der YAHKA-Bridge funktionieren. Des Weiteren reicht ein ausgeführter [Netzwerk-Scan am iPad](https://apps.apple.com/de/app/it-tools-network-analyzer/id324054954), damit die Geräte der YAHKA-Bridge wieder verfügbar sind.

Ich halte euch auf dem Laufenden! 

Gruß Nico

**Comment by nicoh88** [comment]
Soooooo, ich habe ein paar Neuigkeiten, aber noch 100%ige Lösung. Ich arbeitet noch meine Liste ab, um alles andere ausschließen zu können - mal taucht das Problem nach 8 Stunden auf, mal erst nach 48 Stunden. Daher dauert es immer so lange... ⏳

- Wenn das Problem am iPad an der Wand auftritt, haben ALLE HomeKit-Steuerzentralen im Netzwerk (2 HomePods) auch keine Verbindung zur YAHKA-Instanz mehr. Geräte einer andere Homebridge-Instanz im Netzwerk (läuft auf dem gleichen System) und die Kameras der YAHKA-Instanz (bekanntermaßen eigener mDNS) sind verfügbar. 
-> Aber, mobile iOS-Geräte, die nicht dauerhaft aktiv im WLAN sind, wie iPhones, Apple Watch, iPads, die ab und an in den Standby gehen und die WLAN-Verbindung neu aufbauen, haben keine Probleme die YAHKA-Instanz zu erreichen. Da, wie bekannt, iOS Geräte die sich im gleichen Netzwerk wie die HAPs befinden, garnicht über die Steuerzentralen eine Verbindung aufbauen, sondern direkt mit den HAPs kommunizieren.
-> Aber, von extern, beim Deaktivieren der WLAN-Verbindung oder eben unterwegs, ist die YAHKA-Instanz, wenn das Problem besteht, auch nicht erreichbar.

- Habe mal die "**ü**" in den Namen der Kameras sicherheitshalber in "ue" geändert - falls die "xn-" mDNS-Namen irgendwo Probleme machen. **Ohne Erfolg, Problem besteht weiterhin!**

- Alle HomeKit-Steuerzentralen (iPad mit Dauerstrom an der Wand, HomePod WZ und HomePod min Bad) stromlos gemacht und somit neugestartet. **Ohne Erfolg, Problem besteht weiterhin!**

- Aktuell teste ich das OpenWRT Downgrade auf `19.07.3`.

----

Ich bin mittlerweile sehr sicher, dass irgendwann aus noch unbekannten Gründen der mDNS-Name `iobroker-yahka-822b.local` wegfliegt und ein paar Sekunden später wiederverfügbar ist. Aber die dauerhaft im WLAN befindlichen Geräte / HomeKit-Steuerzentralen dies erst nach einem WLAN-Reconnect mitbekommen.

Bestätigung dazu bekomme ich im DNS-Query von meiner Pi-Hole, normalerweise wird der interne DNS-Server bei Bonjour- / Avahi-mDNS garnicht erst abgefragt, sondern nur, wenn er nicht verfügbar wäre - dies ist scheinbar der Fall.

----

Eine dauerhafte Lösung wird vermutlich das hinterlegen von, in meinem Fall, `iobroker-yahka-822b.local` im Local DNS von Pi-Hole.

----

Als IT'ler ist mir aber die Fehler-Ursachen-Analyse sehr wichtig, daher werde ich noch einige weitere Dinge, wie OpenWRT (IGMP-Spoofing bisher nicht aktiv) und Pi-Hole ausschließen.

----

Gruß Nico

**Comment by jensweigele** [comment]
Mit dem aktuellen Master, gibt es nun eine Option auf der Bridge/Kamera/Device, um auf die vorherige Bonjour-Bilbiothek zurück zu gehen. Teste mal bitte ob es dadurch besser wird.

**Comment by MacPro-de** [comment]
Ich habe dieses Problem hier auch und würde die Version ebenfalls gerne testen, aber auch, wenn ich die yahka master über github installiere, scheine ich noch die 0.13.0 zu erhalten. Ich habe unter Ubuntu Server 20.04 netplan.io und systemd-resolvd und sogar die Firewall deinstalliert und verwende jetzt wieder avahi, ifupdown und resolvconf. Trotzdem verschwinden alle yahka Geräte immer wieder nach einer Weile. Ich nutze das Programm "Discovery" unter macOS und überwache damit den mDNS-Bereich "_hap._tcp". Ich habe dann auch noch die IP-Adresse des iobroker Hosts geändert. Danach hat es mehrere Stunden lang problemlos funktioniert, aber dann sind die Geräte trotzdem wieder aus mDNS verschunden. Auch ein yahka Adapter Neustart bewirkt, dass die Geräte wieder für eine paar Minuten in mDNS erscheinen.

**Comment by MacPro-de** [comment]
In der 0.14.0 habe ich im yahka-Adapter die Bridge und alle Kameras so konfiguriert, dass die vorherige Bonjour-Bilbliothek verwendet wird und alles läuft jetzt seit über einer Stunde problemlos. Dann habe ich eine zusätzliche Kamera angelegt, bei der diese Option nicht aktiviert ist und die verschwindet ca. 2 Minuten nach dem yahka-Start aus mDNS. Es scheint also (zumindest bei mir) wirklich an der neuen mDNS-Bilbliothek zu liegen.

**Comment by nicoh88** [comment]
Ich habe bei mir noch nicht die neue NPM-Version 0.13.1 installiert (inkl. aktivieren von `Use Legacy Advertiser`) und kann die Lösung meines Problems noch nicht **bestätigen**, bisher ist das Problem, seit dem Downgrade auf OpenWRT `19.07.3` nicht mehr aufgetreten - ist aber auch noch keine 48 Stunden her.

Ich gehe aber anhand von #212 mittlerweile stark davon aus, dass das Problem nicht OpenWRT oder Pi-Hole auslöst und mit `Use Legacy Advertiser` behoben ist - deshalb mache ich hier schonmal zu. 👍 

Spannend 😕, dass bei mir ein WLAN-Reconnect ausreicht um das Problem zu lösen und es erst nach 8-48 Stunden auftritt, nicht nach 2 Minuten, wie bei anderen Usern im Issue #212 und [homebridge/HAP-NodeJS#856](https://github.com/jensweigele/ioBroker.yahka/issues/212).

Danke für deine Recherche @jensweigele 🎉

**Comment by nicoh88** [comment]
Nachtrag, natürlich hat `Use Legacy Advertiser` mein Problem gelöst.

Weiterhin bleibt offen, warum, dass Problem bei anderen nach 1-5 Minuten aufgetreten ist und bei mir erst nach 12-48 Stunden. Vielleicht irgendeinen OpenWRT-DNS-Cache oder Pi-Hole-Cache.

Gruß
