### ISSUE TITLE
Import / Export

### ISSUE THREAD

**Issue by matze1708** [jensweigele/ioBroker.yahka#22]
Hallo,

ich fände es gut, wenn es eine Import- / Export Funktion geben könnte. In der ich alle bereits konfigurierten Geräte sichern kann und auf einem anderen iobroker wieder einfügen kann, oder als Backup Lösung.

Danke.

**Comment by jensweigele** [comment]
Feature wurde im Admin-Adapter implementiert

**Comment by 420Dope** [comment]
Ich check das irgendwie nicht bzw. kann das nicht finden wie ich den Yahka Adapter backupen und restoren kann.
Kann mir das einer genauer erklären?

**Comment by juamiso** [comment]
Diese "import/export" Funktion ist ein scheint seit Admin v3 drin. Leider für viele (interessante) Adaptern aber nicht vorhanden. Ich finde sehr schade das weder für Yahka noch für Zigbee Adaptern gibt...
