### ISSUE TITLE
0.11.0 -> 0.12.0

### ISSUE THREAD

**Issue by Goersch** [jensweigele/ioBroker.yahka#220]
Hallo,

hab gerade von 0.11.0 auf 0.12.0 aktualisiert:

> yahka.0 | 2021-01-08 21:30:16.434 | error | at endReadableNT (_stream_readable.js:1103:12)
> -- | -- | -- | --
> yahka.0 | 2021-01-08 21:30:16.434 | error | at IncomingMessage.emit (events.js:189:13)
> yahka.0 | 2021-01-08 21:30:16.434 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
> yahka.0 | 2021-01-08 21:30:16.434 | error | at HAPServer._this._handlePairVerify (/opt/iobroker/node_modules/hap-nodejs/src/lib/HAPServer.ts:515:12)
> yahka.0 | 2021-01-08 21:30:16.434 | error | at HAPServer._this._handlePairVerifyStepOne (/opt/iobroker/node_modules/hap-nodejs/src/lib/HAPServer.ts:553:33)
> yahka.0 | 2021-01-08 21:30:16.434 | error | at Object.chacha20_poly1305_encryptAndSeal (/opt/iobroker/node_modules/hap-nodejs/src/lib/util/hapCrypto.ts:90:25)
> yahka.0 | 2021-01-08 21:30:16.434 | error | at Object.createCipheriv (crypto.js:109:10)
> yahka.0 | 2021-01-08 21:30:16.434 | error | at new Cipheriv (internal/crypto/cipher.js:217:22)
> yahka.0 | 2021-01-08 21:30:16.434 | error | at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:115:20)
> yahka.0 | 2021-01-08 21:30:16.434 | error | at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
> yahka.0 | 2021-01-08 21:30:16.434 | error | (25644) Error: Invalid IV length
> yahka.0 | 2021-01-08 21:30:16.434 | error | (25644) uncaught exception: Invalid IV length

Bin danach wieder auf 0.11.0 und alles war wieder gut. Muss ich noch was anderes aktualisieren (alle anderen iobroker adapter und js-controller sind auf der letzten "offiziellen" Version)?

Danke :)
Georg

**Comment by jensweigele** [comment]
Welche NodeJS Version hast du?

Der Fehler kommt von der HomeKit Bibliothek. Hier wird davon gesprochen, dass die Node-Version zu alt ist:
https://github.com/oznu/homebridge-config-ui-x/issues/702

**Comment by Goersch** [comment]
OK, bin auf 10.15.2 - werde mal updaten 

Schön wäre natürlich, wenn das Adapter beim Starten ausgeben würde, dass die Anforderung nicht erfüllt sind 

Danke
Georg

**Comment by Goersch** [comment]
nach update auf node 14 alles OK
