### ISSUE TITLE
Fehler bei allen IP-Cams nach Update auf 0.12.0

### ISSUE THREAD

**Issue by R3play13** [jensweigele/ioBroker.yahka#221]
Hi, nach Update von 0.11.0 auf 0.12.0 bekomme ich bei meinen IP-Cams jeweils den Fehler "(9698) [Video] ffmpeg exited with code: 1 and signal: null (error)" im Error LOG

Der Snapshot wird wie gewohnt aktualisiert, jedoch wen ich den Live-Stream betrachten möchte kommt die Ladeanzeige und irgendwann Fehler keine Antwort.

Desweiteren habe ich bei meinen Streams kein Sound, aber sowohl in 0.11.0 als auch 0.12.0

Nach Downgrade auf 0.11.0 haben sie wieder funktioniert.

**Comment by jensweigele** [comment]
Setze mal bitte die Parameter für "Video-Stream" auf die Standardwerte zurück (Kamera -> Advanced Settings -> Reset to defaults auf der rechten Seite) und schaue ob es dann funktioniert.

**Comment by R3play13** [comment]
Schon probiert, leider immernoch das gleiche Problem. Habe auch die Einstellungen schon vor dem Upgrade kopiert und danach eingefügt, jedoch ebenfalls das gleiche Problem

**Comment by jensweigele** [comment]
Hast du Audio aktiviert?
Wenn ja, musst du eine spezielle FFMPEG Version nutzen, details dazu findest du auch hier:
https://github.com/jensweigele/ioBroker.yahka/issues/82

Außerdem wäre es gut, das VerboseLogging anzuschalten und das Logging des Adapters Log auf "Debug" zu setzen, um zu sehen, mit welchen Argumenten FFMPEG gestartet wird.

**Comment by wendy2702** [comment]
Hi,

ich bin von 0.11 auf 0.13 gewechselt und hatte genau das Problem. Snapshot wird upgedated, Live Stream geht nicht mehr.

Benutze kein Audio und konnte das Problem durch "reset to defaults" für den Livestream lösen.

![grafik](https://user-images.githubusercontent.com/33424168/104458075-2a288800-55ab-11eb-947b-f9a4ae48df8a.png)

**Comment by nicoh88** [comment]
@wendy2702 Danke für die Bestätigung!

> Schon probiert, leider immernoch das gleiche Problem. Habe auch die Einstellungen schon vor dem Upgrade kopiert und danach eingefügt, jedoch ebenfalls das gleiche Problem

@R3play13 Hast du "_reset to defaults_" gemacht und dann ohne Änderungen gespeichert? Oder deine Parameter von vorher wieder reinkopiert?

Gruß

**Comment by R3play13** [comment]
Habe den Reset to default gemacht und dann so abgespeichert.

Meine Parameter aus der vorherigen Version hatte ich seperat geteste. Wobei diese auch Default Parameter waren. Wie schalte ich das Verbose Logging ein?

**Comment by jensweigele** [comment]
Auf der Bridge gibt es eine Option "VerboseLogging".

**Comment by R3play13** [comment]
Okay, habe es jetzt eingeschaltet. Hier die Ausgabe des Logs wenn ich auf den Livestream schalten will.
![YAHKA EXPORT](https://user-images.githubusercontent.com/65589154/104525335-368b0000-5600-11eb-9abd-824f84611144.png)

**Comment by jensweigele** [comment]
Könntest du mal folgende Parameter mit 0.13.0 probieren? (nur Video, kein Audio)
```
[
"-re",
"-i",
"${source}",
"-threads",
"0",
"-vcodec",
"${codec}",
"-an",
"-pix_fmt",
"yuv420p",
"-r",
"${fps}",
"-f",
"rawvideo",
"-tune",
"zerolatency",
"-vf",
"scale=${width}:${height}",
"-b:v",
"${bitrate}k",
"-bufsize",
"${bitrate}k",
"-payload_type",
"99",
"-ssrc",
"${targetVideoSsrc}",
"-f",
"rtp",
"-srtp_out_suite",
"AES_CM_128_HMAC_SHA1_80",
"-srtp_out_params",
"${videokey}",
"srtp://${targetAddress}:${targetVideoPort}?rtcpport=${targetVideoPort}&localrtcpport=${targetVideoPort}&pkt_size=1378"
]
```

Bezüglich des Logs: Auf deinem Screenshot ist nur ein Bruchteil der Kommandozeile zu sehen. Im ioBroker Log-Fenster gibt es einen Knopf "Download Logs" (oder so). Dort kannst du das Log als Text-File runterladen - dann wird es nicht abgeschnitten.

Es wäre gut, wenn du mal eine FFMPEG Kommandozeile aus 0.11.0 und eine aus 0.13.0 hier posten könntest (vergiss nicht die Credentials zu entfernen).

**Comment by R3play13** [comment]
Konnte jetzt die Parameter prüfen aber leider gleiches Problem.

Folgende Konstellationen habe ich jetzt versucht:

0.11.0 Funktionsfähige Parameter:

![0 11 0_Funktionsfähig](https://user-images.githubusercontent.com/65589154/104658572-664f0c00-56c3-11eb-82eb-48771458b752.png)


0.11.0 Default Parameter gleiches Fehlerbild wie bei 0.12.0/0.13.0(aber anderer Errorlog):

![0 11 0_Default_nicht_funktionsfähig](https://user-images.githubusercontent.com/65589154/104658628-87176180-56c3-11eb-9616-3fc0826aa65b.png)


0.13.0 Default Parameter nicht funktionsfähig:

![0 13 0_Default_nicht_funktionsfähig](https://user-images.githubusercontent.com/65589154/104658711-af9f5b80-56c3-11eb-9f30-d79c8934bed9.png)


0.13.0 Vorgeschlagene Parameter nicht funktionsfähig:

![0 13 0_Vorgeschlagene_Parameter_nicht_funktionsfähig](https://user-images.githubusercontent.com/65589154/104658745-be860e00-56c3-11eb-9c60-45a992ef1745.png)


0.13.0 Funktionsfähige Parameter aus 0.11.0 nicht funktionsfähig:

![0 13 0_Funktionsfähige_Parameter_aus_01 1 0](https://user-images.githubusercontent.com/65589154/104658976-23416880-56c4-11eb-9747-e50c76232100.png)


Hoffe ihr könnt mit den Screenshots etwas anfangen.

**Comment by wendy2702** [comment]
Hi,

wie schon von Jens geschrieben sieht es aus als wenn auf den Screenshots eventuell das logfile abgeschnitten ist.

kannst du das iobroker logfile mal runterladen und die Einträge daraus kopieren!

**Comment by R3play13** [comment]
Das ist doch aber das was benötigt wird oder?
Die FFMPEG Zeile die ausgegeben wird, was passiert wenn ich auf den Snapshot drücke um den Stream zu starten.

Mehr ist das nicht. Ich kann auch noch die paar Zeilen davor und danach senden aber die gehören ja zu anderen Sensoren, Leuchten etc...

**Comment by jensweigele** [comment]
Das Log ist ok - aber die letzten drei Bilder sind "Snapshot" Befehle, während die ersten beiden "Stream" Befehle sind.
Das heißt zum Vergleichen bräuchte ich:
funktionierender Aufruf von Snapshot und Stream aus 0.11
nicht funktionierender Aufruf von Snapshot und Stream aus 0.13

**Comment by R3play13** [comment]
Okay, mit 0.11.0 kann ich dienen bei 0.13.0 passiert da aber nichts mehr... das wird dann wohl auch das Problem sein???

0.11.0 funktionierender Aufruf Snapshot+Stream:

![Bildschirmfoto 2021-01-15 um 11 51 12](https://user-images.githubusercontent.com/65589154/104716574-69c8ae80-5728-11eb-8d63-06c131c5db71.png)


0.13.0 von gestern Abend mit in 0.11.0 funktionierenden Parametern und noch die nachfolgende Zeile (da passiert nichts mehr mit dem Stream) :

![Bildschirmfoto 2021-01-15 um 11 57 24](https://user-images.githubusercontent.com/65589154/104717210-405c5280-5729-11eb-9b4b-048642920f82.png)

**Comment by jensweigele** [comment]
Besteht dieses Problem noch?

**Comment by R3play13** [comment]
Hi,

Habe bei mir nun 0.13.1 laufen und keine Probleme mehr mit dem Stream. Allerdings kann ich nicht sagen woran es nun lag.
