### ISSUE TITLE
Please provide release date in changelog

### ISSUE THREAD

**Issue by MC-1984** [jensweigele/ioBroker.yahka#222]
Could you please provide the release date in the changelog (as in version 0.10.0)? I usually wait a few weeks before installing adapter updates and a release date makes that much easier.

Another point is that some adapters are not updated any more. A current release date shows that the adapter gets updated and was not last updated years ago.

**Comment by jensweigele** [comment]
I try to do it in the future.
In the meantime you can find the release dates here: https://www.npmjs.com/package/iobroker.yahka in the "versions" tab.

**Comment by MC-1984** [comment]
Thank you (in general for the adapter and for the release dates)!
