### ISSUE TITLE
Home App stürzt nach Update auf YAHKA 0.12.0 ab

### ISSUE THREAD

**Issue by Schaxxe** [jensweigele/ioBroker.yahka#223]
Sorry, mein erstes Mal bei dem ich einen Fehler melde. Habe das ins ioBroker Forum auch gepostet: https://forum.iobroker.net/topic/40704/home-app-st%C3%BCrzt-nach-update-auf-yahka-0-12-0-ab

Nach dem Update des YAHKA Adapters auf die Version 0.12.0 stürzt sowohl auf dem iPhone (7) als auch dem iPad (Air 2) die Home App sofort nach dem Öffnen ab. iOS sind jeweils aktuell (14.3). Neustart der iOS Geräte brachte keine Besserung.
Nach dem Downgrade auf 0.11.0 funktioniert wieder alles.
in den Logs von iobroker stehen nur die üblichen Info-Meldungen (Adapter Ende bzw. Start nach Update, und hinzufügen meiner Geräte), keine Fehler oder Warnungen.

Node-Version: 12.20.0
Nodejs-Version: 12.20.0
NPM-Version: 6.14.8

**Comment by jensweigele** [comment]
Vielleicht hast du das gleiche Problem andere (und ich auch) schon hatten: https://github.com/jensweigele/ioBroker.yahka/issues/199

Versuche mal die Geräte Stück für Stück zu deaktivieren.
Oder schaue mal nach "lightbulbs" mit den fehlenden Characterisitiken.

Von 0.11 auf 0.12 wurde die Bibliothek zur HomeKit Kommunikation upgedated - vermutlich kommt der Fehler daher.

**Comment by al10b** [comment]
Ich habe dasselbe Problem hier. Tatsächlich habe ich ein [Zigbee-Lightbulb](https://www.amazon.de/Ledvance-Candle-ZigBee-dimmbar-Tuneable-White/dp/B07MQFNCGM/ref=cm_cr_srp_d_product_top?ie=UTF8) in meinen Geräten, bei dem  nur die Farbtemperatur aber keine HLS-Werte einstellbar sind. Ich habe folgerichtig nur _Brightness_, _Saturation_ und _On_ aktiviert. Ich habe probehalber auch mal andere Charateristika ausprobiert, aber nach ein paar Minuten bekomme ich wieder nur "Keine Antwort" in der Home-App. Bei 0.11.0 passiert das nicht.

**Comment by EduardSarjadjuk** [comment]
Hallo, bei mir tritt der Fehler nur in der Version 0.13 auf. Nach einer gewissen Zeit sind die Geräte nicht erreichbar und ich muss du Instanz neu starten. Nach dem Downgrade auf die Version 0.12 geht es wieder.

**Comment by jensweigele** [comment]
Bitte unterscheidet zwischen "Abstürz der HomeKit App" (=App schließt sich sofort einfach (meist direkt nach dem öffnen)) und "Gerät nicht erreichbar", da ich denke, dass es hierfür unterschiedliche Ursachen gibt.

Die Abstürze sind bisher nur bekannt, wenn ungültige bzw. unvollständige Geräte definiert wurden (wie bspw. in #199)
Die "Nicht-Erreichbarkeit" der Geräte hat vermutlich eine andere Ursache (siehe auch #212).

Wer also das "Nicht-Erreichbarkeits-Problem" hat, sollte in #212 weiter diskutieren, während die Abstürze der HomeKit App gerne hier diskutiert werden können.

**Comment by Schaxxe** [comment]
> Vielleicht hast du das gleiche Problem andere (und ich auch) schon hatten: #199
> 
> Versuche mal die Geräte Stück für Stück zu deaktivieren.
> Oder schaue mal nach "lightbulbs" mit den fehlenden Characterisitiken.
> 
> Von 0.11 auf 0.12 wurde die Bibliothek zur HomeKit Kommunikation upgedated - vermutlich kommt der Fehler daher.

Danke für die Rückmeldung. Leider komme ich gerade nicht dazu, das zu verifizieren, versuche aber im Laufe der Woche noch ein Feedback dazu abgeben zu können.

**Comment by jensweigele** [comment]
Mit dem aktuellen Master, gibt es nun eine Option auf der Bridge/Kamera/Device, um auf die vorherige Bonjour-Bilbiothek zurück zu gehen - bitte mal testen ob das etwas bringt.

**Comment by jensweigele** [comment]
Inzwischen gibt es die Version 0.13.1 auf NPM

**Comment by Schaxxe** [comment]
Habe jetzt den 0.13.1 installiert, die Home App funktioniert ohne Absturz.
Frage: Muss/Soll ich jetzt noch meine Lampen prüfen wg den Optionen die in dem anderen Issue stehen? Ich habe halt nur eine drin mit Dimm-Funktion, der Rest ist nur "an" und "aus"

**Comment by nicoh88** [comment]
> Habe jetzt den 0.13.1 installiert, die Home App funktioniert ohne Absturz.
> Frage: Muss/Soll ich jetzt noch meine Lampen prüfen wg den Optionen die in dem anderen Issue stehen? Ich habe halt nur eine drin mit Dimm-Funktion, der Rest ist nur "an" und "aus"

Prima. Wenn alles funktioniert, musst du nichts mehr machen! Hat vermutlich nur fee Fehlersuche gedient.

Gruß

PS: Ich mache hier zu.
