### ISSUE TITLE
Kamera nicht löschbar

### ISSUE THREAD

**Issue by rainbowcat1989** [jensweigele/ioBroker.yahka#225]
Nach erstellen einer Kamera , kann diese nicht mehr gelöscht werden. Neustart von IObroker bereits probiert. Leider erscheint die Kamera auch nicht mehr im Homekit in IOS, somit kann sie nicht neu erstellt werden , da sie schon vorhanden ist in Yahka.

**Comment by jensweigele** [comment]
Versteh ich es richtig, dass du die Kamera nicht in Yahka löschen kannst?

**Comment by rainbowcat1989** [comment]
Exakt. Sie können da drin nicht gelöscht werden.

**Comment by MacPro-de** [comment]
Das ist bei mir genauso. Geräte kann ich über das Webinterface anlegen und löschen, Kameras kann ich anlegen, aber nicht über das Webinterface löschen. Der einzige Weg, eine Kamera zu löschen ist derzeit der, dass ich ein iobroker Backup mache, die gesicherte json-Datei in einem Texteditor öffne, dort die Kamera(s) herauslösche (jede Kamera steht dort zweimal drin) und dann das Backup zurückspiele.

**Comment by jensweigele** [comment]
Auf NPM gibt es nun die Version 0.13.1 die den Bug fixt (und zusätzlich die "legacy advertiser" option ermöglicht).
Sollte mit Version 0.12/013 eine Kamera dupliziert worden sein, wird diese höchstwahrscheinlich nicht funktionieren und sollte gelöscht und neu angelegt werden.

**Comment by galegro** [comment]
Mir geht‘s ähnlich.

Ich sehe nicht eimal mehr die in YAHKA eingetragenen Kameras. In YAHKA wird mir nichts angezeigt.

**Comment by FlippiHimself** [comment]
Hallo,

Ich habe aktuell das gleiche Problem, dass meine Kamera-Einträge sich nicht mehr löschen lassen.
Hier die aktuell installierten Pakete.

@jensweigele Ich habe nach dem NPM Paket gesucht, welches aktueller als Version 0.13.1 sein soll, aber dies ist alles was herausfuinden konnte. Das System ist auf dem aktuellen Stand:
node -v
v15.14.0
npm -v
7.7.6

LG
