### ISSUE TITLE
Aktualisierung nur zögerlich - Home App Neustart erforderlich

### ISSUE THREAD

**Issue by Tombra1889** [jensweigele/ioBroker.yahka#226]
Hallo zusammen,
ich habe insbesondere bei Thermostaten das Problem, dass die Aktualisierungen seitens ioBroker nur sehr zögerlich ankommen. Also die aktuelle Temperatur in Home wird nicht aktualisiert. Wenn die App beendet wird und dann neugestartet wird, wird die aktuelle Temperatur angezeigt.
![D0979C6D-31E0-4D47-807B-0CB996109860_1_201_a](https://user-images.githubusercontent.com/60692414/104637075-92a76000-56a4-11eb-801a-b39c3ae2dd62.jpeg)

Im Beispiel ist die aktuelle Temperatur hier gerade Orange dargestellt.
Ich meine, dass es bei Homebridge die Option "No-Cache" gibt. Kann ich dies hier auch irgendwo für einzelne Status aktivieren?

**Comment by jensweigele** [comment]
Was steht den im Log dazu? (ggfls. Adapter mal auf "Debug-Log" stellen).
Normalerweise werden Änderungen in ioBroker direkt an HomeKit kommuniziert.

**Comment by Tombra1889** [comment]
Ich glaub es lag daran, dass ich 
<img width="968" alt="image" src="https://user-images.githubusercontent.com/60692414/107117308-d6dbe980-6879-11eb-8b3d-6ed48d11c2a4.png">
nicht aktiviert hatte.
