### ISSUE TITLE
AIR_HEATER Keine Antwort V13.1

### ISSUE THREAD

**Issue by Homer-J76** [jensweigele/ioBroker.yahka#227]
Nach dem Update auf Version 13.1 funktioniert bei mir der AIR_HEATER nicht mehr, es wird nur noch Keine Antwort angezeigt.
Gehe ich auf die V13 zurück funktioniert alles wie gehabt.

Grüße

**Comment by jensweigele** [comment]
vermutlich das gleiche wie in #228 - bitte dort weiter tracken
