### ISSUE TITLE
Adapter crasht / startet nicht mit v 0.13.1

### ISSUE THREAD

**Issue by entavio** [jensweigele/ioBroker.yahka#228]
Bei mir startet der Adapter nach Installation v 0.13.1 nicht mehr. 
Alle Devices erhalten im Log den Status "error"

Node.js 14.15.4 
NPM 6.14.10

bin jetzt zurück auf 0.12.0 da funktioniert soweit alles wieder.

**Comment by nicoh88** [comment]
Um das Problem analysieren zu können, benötigen wir einen ausführlichen Debuglog vom Start der Version 0.13.1.

Mit den bisherigen Infos kommen wir vermutlich nicht weiter. 😢 

Danke

**Comment by entavio** [comment]
also er wirft an diversen Geräten Fehler bzgl. variablen hat sich hier grundsätzlich was geändert? 

`

yahka.0 | 2021-01-16 13:44:36.226 | error | (19121) Error: characteristic value 2 is not contained in valid values array! at TargetHeatingCoolingState.Characteristic.validateUserInput (/opt/iobroker/node_modules/hap-nodejs/src/lib/Character
-- | -- | -- | --
yahka.0 | 2021-01-16 13:44:36.225 | error | (19121) uncaught exception: characteristic value 2 is not contained in valid values array!
yahka.0 | 2021-01-16 13:44:36.222 | error | (19121) Error: characteristic value 2 is not contained in valid values array! at TargetHeatingCoolingState.Characteristic.validateUserInput (/opt/iobroker/node_modules/hap-nodejs/src/lib/Character
yahka.0 | 2021-01-16 13:44:36.222 | error | (19121) uncaught exception: characteristic value 2 is not contained in valid values array!
yahka.0 | 2021-01-16 13:44:36.216 | error | (19121) Error: characteristic value 2 is not contained in valid values array! at TargetHeatingCoolingState.Characteristic.validateUserInput (/opt/iobroker/node_modules/hap-nodejs/src/lib/Character
yahka.0 | 2021-01-16 13:44:36.215 | error | (19121) uncaught exception: characteristic value 2 is not contained in valid values array!

**Comment by entavio** [comment]
oder 

`

host.buanet-iobroker1 | 2021-01-16 13:46:14.343 | error | Caught by controller[118]: [Wohnzimmer Stehlampe 2@@Name] characteristic was supplied illegal value: undefined! This might throw errors in the future!
-- | -- | -- | --
host.buanet-iobroker1 | 2021-01-16 13:46:14.343 | error | Caught by controller[118]: [Wohnzimmer Stehlampe 2@@Name] characteristic was supplied illegal value: undefined! This might throw errors in the future!
host.buanet-iobroker1 | 2021-01-16 13:46:14.343 | error | Caught by controller[117]: [Wohnzimmer Stehlampe 1@@Name] characteristic was supplied illegal value: undefined! This might throw errors in the future!
host.buanet-iobroker1 | 2021-01-16 13:46:14.342 | error | Caught by controller[116]: [Wohnzimmer Stehlampe 1@@Name] characteristic was supplied illegal value: undefined! This might throw errors in the future!
host.buanet-iobroker1 | 2021-01-16 13:46:14.342 | error | Caught by controller[115]: [Wohnzimmer Stehlampe 2@@Name] characteristic was supplied illegal value: undefined! This might throw errors in the future!
host.buanet-iobroker1 | 2021-01-16 13:46:14.342 | error | Caught by controller[114]: [Wohnzimmer Stehlampe 1@@Name] characteristic was supplied illegal value: undefined! This might throw errors in the future!

**Comment by entavio** [comment]
was hat es hiermit auf sich? Use Legacy Advertiser:true = use bonjour-hap instead of ciao

**Comment by jensweigele** [comment]
Dein Problem aus dem Log ist, dass du ungültige Werte schickst.

Das die Geräte nicht antworten nach wenigen Minuten kann möglicherweise durch "Use Legacy Advertiser" gelöst werden.

Ich würde aber zuerst die Werte korrigieren.

**Comment by entavio** [comment]
bei Version 0.12.0 sind es die Werte ja aber wohl nicht, dort funktioniert ja alles.... ich habe wie gesagt einige Anpassungen vorgenommen in der Übernahme von Werten bzw. im in Homekit auf dem iPhone / iPad bestimmte Auswahlmöglichkeiten auszublenden, ist das nicht mehr erlaubt? 

z.b. so 

![Bildschirmfoto 2021-01-16 um 14 53 19](https://user-images.githubusercontent.com/58812928/104813622-981eba80-580a-11eb-8bbe-606670a14a07.jpg)

**Comment by ericsboro** [comment]
I had totally the same problem and nothing helped except roll back to 0.13.0.
now everything is operational

**Comment by DanielWeeber** [comment]
Gleiches Problem hier. Logs sehen identisch zu oben aus

**Comment by nicoh88** [comment]
@ericsboro @DanielWeeber: Handelt es sich bei euch auch um ein "`TargetHeatingCoolingState`"?

Gruß

**Comment by entavio** [comment]
@nicoh88 

Mein Post mit TargetHeatingCoolingState war nur beispielhaft und sollte zeigen wie ich diesen Wert angelegt habe und wie der Fehler dazu aussieht

fehlermeldungen habe ich aber auch zu ganz vielen anderen werten wie currentheatingcoolingstate, shutterlevels usw. 

ist also eher ein strukturelles Problem

**Comment by jensweigele** [comment]
Könnt Ihr bitte mal den aktuellen Master testen?
Sieht so aus, als würde die eingesetzte HomeKit Bibliothek nun die Werte validieren.
Fakt ist nicht desto trotz, dass die Werte die Ihr an HomeKit schickt, nicht den Vorgaben bzw. Erwartungen entsprechen.
Wenn eine Zahl gefordert ist, sollte kein "NaN" geschrieben werden.
Wenn eine Characteristic einen Wert zwischen 0 und 3 möchte, sollte man nicht -1 oder 4 schreiben etc.

Yahka sollte den Fehler nun fangen und im Log einen entsprechenden Fehler ausgeben - aber anschließend weiterlaufen.

**Comment by entavio** [comment]
@jensweigele in meinem Fall kann ich ausschließen falsche Werte zu senden sondern ich lasse Werte im vorgegebenen Wertebereich aus, so z.B. die 2 bei targetheatingcoolingmode um die Auswahl in HomeKit nicht zu haben.... wenn das neuerdings nicht den Vorgaben entspricht sind die characteristic properties hinfällig

**Comment by DanielWeeber** [comment]
`

yahka.0 | 2021-01-17 10:19:43.187 | debug | (17397) [.StatusLowBattery] forwarding value from ioBroker(false) to homekit as (0)
yahka.0 | 2021-01-17 10:19:43.187 | debug | (17397) read state from ioBroker [nut.0.status.onbattery]: {"val":false,"ack":true,"ts":1610875144640,"q":0,"from":"system.adapter.nut.0","user":"system.user.admin","lc":1606379293546}
yahka.0 | 2021-01-17 10:19:43.186 | error | (17397) [.ContactSensorState] error while setting value NaN - message: Error: characteristic value NaN is not contained in valid values array!
yahka.0 | 2021-01-17 10:19:43.186 | debug | (17397) [.ContactSensorState] forwarding value from ioBroker(false) to homekit as (null)
yahka.0 | 2021-01-17 10:19:43.186 | debug | (17397) inverse: converting value to homekit: false to NaN
yahka.0 | 2021-01-17 10:19:43.185 | debug | (17397) read state from ioBroker [nut.0.status.onbattery]: {"val":false,"ack":true,"ts":1610875144640,"q":0,"from":"system.adapter.nut.0","user":"system.user.admin","lc":1606379293546}
yahka.0 | 2021-01-17 10:19:43.185 | debug | (17397) [.ColorTemperature] forwarding value from ioBroker(2732) to homekit as (366.03221083455344)
yahka.0 | 2021-01-17 10:19:43.185 | debug | (17397) script: converting value to homekit: 2732 to 366.03221083455344

`

Wenn ich es richtig interpretiere ist bei mir also derjenige ContactSensor problematisch, der nut.0.status.onbattery verwendet

Da verwende ich aber nichts spezielles, im Gegensatz zu vielen anderen Sachen, und nut.0.status.onbattery ist einfach nur ein Boolean, was ja auch korrekt sein sollte

<img width="1416" alt="Bildschirmfoto 2021-01-17 um 10 22 35" src="https://user-images.githubusercontent.com/2935130/104836396-09637980-58ae-11eb-952c-b9158aff0302.png">

**Comment by jensweigele** [comment]
@entavio: laut deinem Log wird aber genau diese 2 gesetzt. Daher die Meldung: 2 ist nicht in den gültigen Werten. Kannst du mal mit Debug-Log prüfen, ob da wirklich eine 2 gesetzt wird und wie das zustande kommt?

@DanielWeeber :  ContactSensorState hat Inverse als "Conversion" und Yahka schreibt im Log:
```2021-01-17 10:19:43.186 | debug | (17397) inverse: converting value to homekit: false to NaN yahka```
Aus deinem "false" with "NaN" und NaN ist nicht in der gültigen Menge [0,1]

**Comment by DanielWeeber** [comment]
Genau, crashed nicht mehr. Hab nun ein "inverse" per script gemacht, was immer 1 oder 0 returned - nun gehts auch ohne Fehler.

Müsste die schon Conversion nicht aus false -> true (bzw 1) machen?

**Comment by entavio** [comment]
Yahka ging bei mir jetzt auch wieder auf grün, hab mal auch den zuliefernden anderen Adapter neu gestartet, aktuell kein error mehr im log

**Comment by CrazyCreator13** [comment]
![Bildschirmfoto 2021-01-17 um 23 42 04](https://user-images.githubusercontent.com/3821732/104858197-e8d30800-591d-11eb-97c9-0a4ee7a8d9c6.png)
Also ich habe bei 0.13.1 und 0.13.2 die gleichen Fehler

**Comment by DanielWeeber** [comment]
Oben die Meldungen vom Controller solltest du dir dringend anschauen, da setzt du Werte außerhalb gültiger Wertebereiche.

Und die vom Yahka... BAD_PORT. Was steht denn bei dir für ein Port drin in der Bridge? Laut Log ist das leer, was auch okay wäre. Aber nicht, dass da ein Leerzeichen oder so drin ist?

**Comment by entavio** [comment]
gehe davon aus das @CrazyCreator13 ebenfalls nichts geändert hat außer den adapter zu updaten... sprich dieser reagiert in den neuen versionen anders als bisher mit Fehlern sobald nicht alle werte einer value characteristic geliefert werden oder diese nicht den vorgaben (Wertebereich, Format o.a.) entsprechen.

**Comment by DanielWeeber** [comment]
Was bei invaliden Eingaben/Werten ja auch vollkommen korrekt ist.

**Comment by CrazyCreator13** [comment]
Genau ... Ich habe nicht geändert, sondern einfach das Update auf 0.13.1 installiert. Als das nicht ging hab ich wieder die 0.13.0 drauf und jetzt habe ich die 0.13.2 probiert aber immer noch diese Fehler. 

Was kann/sollte/muss ich denn tun um die Fehler zu beseitigen bzw. auch um euch zu helfen den Fehler zu finden, falls es einer sein sollte.

**Comment by DanielWeeber** [comment]
Du siehst ja in den roten Zeilen des Logs klar die Problembeschreibung und auch -Lösung. Die musst du alle einzeln durchgehen.

BLV CCC@BLC Drucker@Name ist zB "undefined" also leer, darf es aber nicht sein

bzgl. Port habe ich oben dir eine Frage gestellt.

**Comment by CrazyCreator13** [comment]
Sorry das habe ich vollkommen überlesen und wird natürlich sofort nachgereicht: 
![Bildschirmfoto 2021-01-19 um 02 52 04](https://user-images.githubusercontent.com/3821732/104978066-5ad04d80-5a01-11eb-8ec9-fa4e2761d2c7.png)

Und hier die Einstellungen bei dem angesprochenem BLV CCC
![Bildschirmfoto 2021-01-19 um 02 54 33](https://user-images.githubusercontent.com/3821732/104978320-e77b0b80-5a01-11eb-89b2-8df14b5fb0f5.png)

![Bildschirmfoto 2021-01-19 um 02 54 47](https://user-images.githubusercontent.com/3821732/104978332-eba72900-5a01-11eb-9b39-b90a314fd259.png)

Leider habe ich keine Idee wo ich den Namen vergessen haben könnte einzugeben ...

**Comment by DanielWeeber** [comment]
Trag bei Port mal 0 ein.



Und der Name ist eigentlich klar - du liest da ja den "Ordner" des Shellys aus. Und nicht ein Objekt mit einem Wert was ein Name sein könnte.

Anschaulich:

Falsch ist shelly.0.ID

Richtig wäre zB
shelly.0.ID.irgendeinObjekt

Oder einfach nur "const" anstatt ioBroker.State und dann einen freien Namen wie "Wohnzimmer" eintippen.

**Comment by CrazyCreator13** [comment]
@DanielWeeber 
Alleine das eintragen der 0 bei Port hat schon alle Probleme gelöst 👍 

Hab jetzt aber trotzdem mal bei Yahka unter Name das hier drinnen stehen:
![Bildschirmfoto 2021-01-19 um 03 13 47](https://user-images.githubusercontent.com/3821732/104979356-5e190880-5a04-11eb-9b19-f4eca4dbcd8e.png)

Ich hoffe so hast du das gemeint?

**Comment by DanielWeeber** [comment]
Das ist korrekt, wenn du bei jedem Shelly den Namen ausgefüllt hast.
Ich würde empfehlen ioBroker.State auf "const" zu wechseln und den Namen "hart" einzutippen.

**Comment by CrazyCreator13** [comment]
Das werde ich dann mal nachholen ... Also das mit den Namen. Die Shellys werden aber eh aussterben. Ich will wieder verstärkt auf ZigBee gehen. Ich mag die vielen Geräte in meiner Fritz!box nicht sehen :-D

**Comment by svabo1977** [comment]
Bei mir das selbe ! Installation 13.1 danach crash! Zurück auf 12

**Comment by jensweigele** [comment]
@svabo1977 lies dir mal das Ticket und die Lösungsvorschläge durch...

**Comment by DanielWeeber** [comment]
Poste doch vielleicht mal deinen Log/die Fehlermeldungen?

**Comment by svabo1977** [comment]
![grafik](https://user-images.githubusercontent.com/57860935/105576843-e6393e00-5d75-11eb-9db4-49183579ddbc.png)
![grafik](https://user-images.githubusercontent.com/57860935/105576852-f2250000-5d75-11eb-833e-d72f5932cf99.png)

**Comment by DanielWeeber** [comment]
Meldung ist ja eindeutig. Irgendwo ist ein leerer Wert, der nicht leer sein darf.

Mach mal debug Loglevel von dem Yahka Adapter an, dann siehst du mehr und vor allem auch wo es herkommt.

**Comment by svabo1977** [comment]
ok ich versuchs nochmal . Gebe rückmeldung danke

**Comment by svabo1977** [comment]
![grafik](https://user-images.githubusercontent.com/57860935/105624906-8ef2a680-5e25-11eb-8c2f-b2f386089a94.png)
![grafik](https://user-images.githubusercontent.com/57860935/105624919-a598fd80-5e25-11eb-9904-3f289f37c1c6.png)
so aber richtig weiter weis ich jetzt auch nicht . bin nicht sicher wo ich die werte nachtragen muss, zumal alles unter version 12 fuktioniert. lg

**Comment by DanielWeeber** [comment]
Das macht es aber trotzdem immernoch nicht richtig! Entweder du hast Bock es zu fixen oder du lässt es.

Die neuen Screenshots beinhalten nur Fehler aus dem Controller. Das hat nix mit Yahka zu tun, sollte aber auch alles gefixt werden. Du musst dir die Fehlerbeschreibungen durchlesen. Leider sind die in den Screenshots stark abgeschnitten.

z.B. "Max Velux Rolladen@Rolladen@Target Position characteristic was supplied illegal value: number -1"
Denke ich selbst erklärend. 

So musst du nach und nach jeden Fehler fixen.

Und danach dir die Meldungen vom Yahka anschauen.

**Comment by svabo1977** [comment]
Bin leider nicht ganz so der Crack sorry ! Was heist im Controller fixen ? Wenn du mir das erklären könntest dann hätte ich nen Anfang und könnte die Fehler beheben ! Lg

**Comment by DanielWeeber** [comment]
Schau dir einfach die Objekte an die in den Fehlermeldungen beschrieben sind und beurteile, warum da ein falscher Wert drin steht. Entweder ist im Objekt selber schon etwas falsches (z.B. bei meinem Beispiel kann die Target Position nicht negativ sein, ist aber -1) oder du setzt per Script oder anderem Plugin (wie z.B. Yahka) den falschen Wert. Das kannst leider nur du allein rausfinden.

**Comment by svabo1977** [comment]
Ok danke

**Comment by svabo1977** [comment]
Eine Sache verstehe ich aber immer noch nicht wenn ich in Version 12 keine Fehler logs habe , wieso dann auf einmal in 13.1 ?

**Comment by jensweigele** [comment]
Weil die zugrundeliegende Bibliothek diese Prüfungen eingeführt hat.
Mit 0.13.0 und 0.13.1 ist der Adapter allerdings gecrashed - mit 0.13.2 solltest du nur die Fehler im Log sehen.

**Comment by MaxPhenol** [comment]
Gleiches Problem hier. Adapter crasht auch mit 0.13.2.
`
host.iobroker | 2021-02-01 17:26:01.497 | error | instance system.adapter.yahka.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
host.iobroker | 2021-02-01 17:26:01.497 | error | Caught by controller[9]: [Wohnzimmer Rolladen@Wohnzimmer@Obstruction Detected] characteristic was supplied illegal value: undefined! This might throw errors in the future!
host.iobroker | 2021-02-01 17:26:01.497 | error | Caught by controller[8]: [Esszimmer Rolladen@Esszimmer@On] characteristic was supplied illegal value: undefined! This might throw errors in the future!
host.iobroker | 2021-02-01 17:26:01.497 | error | Caught by controller[7]: [Esszimmer Rolladen@Esszimmer@Obstruction Detected] characteristic was supplied illegal value: undefined! This might throw errors in the future!
host.iobroker | 2021-02-01 17:26:01.497 | error | Caught by controller[7]: [Esszimmer Lämpchen@Lämpchen@On] characteristic was supplied illegal value: undefined! This might throw errors in the future!
host.iobroker | 2021-02-01 17:26:01.497 | error | Caught by controller[6]: [Büro Klimasensor@Büro@Barometric Pressure] characteristic was supplied illegal value: undefined! This might throw errors in the future!
host.iobroker | 2021-02-01 17:26:01.497 | error | Caught by controller[5]: [Büro Klimasensor@Büro@Battery Level] characteristic was supplied illegal value: undefined! This might throw errors in the future!
host.iobroker | 2021-02-01 17:26:01.497 | error | Caught by controller[4]: [Büro Klimasensor@Büro@Current Relative Humidity] characteristic was supplied illegal value: undefined! This might throw errors in the future!
host.iobroker | 2021-02-01 17:26:01.497 | error | Caught by controller[3]: [Büro Klimasensor@Büro@Current Temperature] characteristic was supplied illegal value: undefined! This might throw errors in the future!
host.iobroker | 2021-02-01 17:26:01.496 | error | Caught by controller[2]: [Büro Türkontakt@Büro@Battery Level] characteristic was supplied illegal value: undefined! This might throw errors in the future!
host.iobroker | 2021-02-01 17:26:01.496 | error | Caught by controller[1]: [Büro Arbeitsplatz@Arbeitsplatz@On] characteristic was supplied illegal value: undefined! This might throw errors in the future!
host.iobroker | 2021-02-01 17:26:01.496 | error | Caught by controller[0]: [Büro Arbeitslicht@Arbeitslicht@On] characteristic was supplied illegal value: undefined! This might throw errors in the future!
yahka.0 | 2021-02-01 17:26:00.801 | warn | (10572) Terminated (UNCAUGHT_EXCEPTION): Without reason
yahka.0 | 2021-02-01 17:26:00.801 | info | (10572) terminating
yahka.0 | 2021-02-01 17:26:00.801 | info | (10572) cleaned up ...
yahka.0 | 2021-02-01 17:26:00.800 | info | (10572) cleaning up ...
yahka.0 | 2021-02-01 17:26:00.751 | error | (10572) Cannot read property 'homekit.min' of undefined
yahka.0 | 2021-02-01 17:26:00.751 | error | (10572) TypeError: Cannot read property 'homekit.min' of undefined at Function../yahka.functions/conversion.scale.ts.TIoBrokerConversion_Scale.isScaleParameter (/opt/iobroker/node_modules/iobroker
yahka.0 | 2021-02-01 17:26:00.705 | error | (10572) unhandled promise rejection: Cannot read property 'homekit.min' of undefined
yahka.0 | 2021-02-01 17:26:00.705 | error | (10572) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
`

**Comment by MaxPhenol** [comment]
Die Verwendeten ioBroker Objekte sind alles Aliases. Vielleicht hängts ja damit zusammen.

Aus dem Log oben:
Büro Arbeitslicht@Arbeitslicht@On --> alias.0.Büro.Arbeitslicht.Schalter: true
Büro Klimasensor@Büro@Current Temperature --> alias.0.Büro.Klima.Temperatur: 21.95°C
Wohnzimmer Rolladen@Wohnzimmer@Obstruction Detected --> alias.0.Wohnzimmer.Rolladen.StopReason: "normal"

**Comment by DanielWeeber** [comment]
Bei den Controller-Errors können wir nur Tipps geben, aber das gehört hier hin:
https://github.com/ioBroker/ioBroker.js-controller/issues
Meisten Fehler sind aber "undefined". Heisst also hier ist kein Wert gesetzt, obwohl einer gesetzt sein muss.


Bei dem Yahka Error: Eigentlich auch wieder selbsterklärend. Du nutzt die Conversion Function "scale", und da fehlt bei "Homekit Min" eine Angabe. Darf nicht leer sein. Bei welchem Objekt musst du schauen, sollte aber eigentlich auch im Log stehen. Ist hier vielleicht einfach nur nicht vollständig.

**Comment by MaxPhenol** [comment]
ScaleInt war 0-100.
Problem waren die Aliases. Lasse ich yahka die Werte aus dem Baum der MQTT Objekte holen, läufts.
