### ISSUE TITLE
Community Service "AtmosphericPressureSensor"

### ISSUE THREAD

**Issue by JoachimEngelmann** [jensweigele/ioBroker.yahka#230]
**yahka:** 0.13.2
**Use Legacy Advertiser:** false (bei true das gleiche)
**js-controller:** 3.2.7
**Node.js:** v14.15.4
**NPM:** 6.14.10
**iOS:** 14.3
**getestete Apps:** Apple Home, Controller für HomeKit

Wenn ein Gerät einen Community Service (nur getestet mit AtmosphericPressureSensor) entstehen Probleme. Im Log von Yahka ist kein auffälliges Verhalten zu erkennen:

### 1. Fall:
- Hombridge ist noch nicht im iPhone hinzugefügt
- Service ist zum Gerät hinzugefügt
- Es wird versucht die HomeBridge im iPhone einzurichten
-> Es kommt die Meldung: "Gerät ist nicht kompatibel"

<img src="https://user-images.githubusercontent.com/32760573/104952576-0a3aff00-59c5-11eb-82f0-6f853834ca20.png" data-canonical-src="https://user-images.githubusercontent.com/32760573/104952576-0a3aff00-59c5-11eb-82f0-6f853834ca20.png" width="200"/>

### 2. Fall (sporadisches Auftreten):
- Homebridge ist auf dem iPhone eingerichtet
- Es wird zu einem Gerät z. B. der Service AtmosphericPressureSensor hinzugefügt
-> Alle Geräte lassen sich steuern und zeigen richtigen Status an
-> Alle Geräte zeigen an: "Dieses Gerät antwortet nicht"

<img src="https://user-images.githubusercontent.com/32760573/104952617-2343b000-59c5-11eb-8146-55382056d0db.png" data-canonical-src="https://user-images.githubusercontent.com/32760573/104952617-2343b000-59c5-11eb-8146-55382056d0db.png" width="200"/>

**Comment by Qube2org** [comment]
Same issue here,

js-contoller: 3.2.7
node.js: v14.15.4
npm: 6.14.10
Yahka version: 0.13.1
IOS: 14.3 / MacOS 11.1

**Comment by nicoh88** [comment]
Hi, besteht das Problem nur mit dem CommunityType „AtmosphericPressureSensor“? 

Habe bei mir „KilowattHours“ und „Watts“ problemlos am Laufen.

**Comment by picnicorama** [comment]
Gleiches Verhalten hier ...
yahka: 0.13.2 (0.13.1 verhält sich auch so)
js-controller: 3.2.7
Node.js: v12.20.0
NPM: 6.14.8

**Comment by JoachimEngelmann** [comment]
@nicoh88 Wenn ich z. B. ein "Custom Characteristic" mit „AtmosphericPressureSensor“ hinzufüge verhält es sich genauso. Habe Testweise von meinem Sonoff POW R2 "Watts" als "Custom Characteristic" hinzugefügt und hier wird in der EVE App alles korrekt dargestellt und Apple Home verhält sich auch wie erwartet

**Comment by mdietrich** [comment]
Ich kann das bestätigen. Der "AtmosphericPressureSensor" macht bei mir auch Probleme. Nehme ich den AtmosphericPressureSensor wieder raus, funktioniert wieder alles.

**Comment by vgeannin** [comment]
I have the same problem

**Comment by nicoh88** [comment]
Beim Community Type `AtmosphericPressureSensor` muss der Wert `AtmosphericPressureLevel` mit einer Zahl zwischen `800` - `1200` (mbar) gefüllt sein.

Ich kann das Problem bei mir auch reproduzieren.

![Bildschirmfoto 2021-02-12 um 14 17 40](https://user-images.githubusercontent.com/264264/107773046-5ae01680-6d3d-11eb-910e-0ccbdbe024ad.png)

```
yahka.0 | 2021-02-12 14:17:10.711 | error | (17133) Error: [_AtmosphericPressureSensor] unknown service type: at YahkaServiceInitializer../yahka.homekit-service.ts.YahkaServiceInitializer.initService (/opt/iobroker/node_modules/iobroker.ya
-- | -- | -- | --
yahka.0 | 2021-02-12 14:17:10.658 | error | (17133) unhandled promise rejection: [_AtmosphericPressureSensor] unknown service type:
yahka.0 | 2021-02-12 14:17:10.657 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
yahka.0 | 2021-02-12 14:17:10.646 | info | (17133) adding _AtmosphericPressureSensor with UUID: a78d820d-6a17-4633-8e09-97f3c3d5dd40
```
@jensweigele: Kann es sein, dass es Probleme gibt, wenn man ein Gerät anlegt, welches nur einen `CommunityType` hat und sonst nichts keine weiteren `Types`?

**Comment by vgeannin** [comment]
I'm made an new test and with this parameter it work  :
![Capture d’écran 2021-02-12 à 15 09 25](https://user-images.githubusercontent.com/14293635/107778645-9b8f5e00-6d44-11eb-8586-ba9f3bb104d6.png)
**instead of uint8 in format, I put float**

Vincent

**Comment by unstressable** [comment]
> Hi, besteht das Problem nur mit dem Community Service „AtmosphericPressureSensor“?
> 
> Habe bei mir „KilowattHours“ und „Watts“ problemlos am Laufen.

@nicoh88 kannst du mal einen Screenshot schicken, wie das mit den Watt bei dir aussieht?
Würde gerne meine PV Anlage damit visualisieren.

**Comment by nicoh88** [comment]
> > Hi, besteht das Problem nur mit dem Community Service „AtmosphericPressureSensor“?
> > Habe bei mir „KilowattHours“ und „Watts“ problemlos am Laufen.
> 
> @nicoh88 kannst du mal einen Screenshot schicken, wie das mit den Watt bei dir aussieht? Würde gerne meine PV Anlage damit visualisieren.

Hi, nur kurz zur Klarstellung in Apple Home werden diese "Community Service" nicht angezeigt - als Kachel oder ähnliches. Dazu benötigt man eine HomeKit kompatibele App wie Eve oder "Controller für HomeKit".

![IMG_4340 (2)](https://github.com/user-attachments/assets/90dce139-68bf-4c97-ba67-47241f8a9891)

Gruß Nico

**Comment by unstressable** [comment]
@nicoh88 ahh, das wusste ich nicht. Vielen Dank!

Dann kommt das sowieso nicht infrage.
Belasse es dann hierbei:

![image](https://github.com/user-attachments/assets/480cc22c-a011-49db-81e7-8961d12c4b0f)
