### ISSUE TITLE
HmIP-MOD-HO Unterstützung für Garagentoröffner

### ISSUE THREAD

**Issue by HochdruckHummer** [jensweigele/ioBroker.yahka#231]
Hallo zusammen, 

ich bin das erste mal hier aktiv und hoffe ich mache alles richtig. Ich weiß nichtmal, ob ich mit dieser Anfrage beim Yahka-Adapter richtig bin, oder es sich um ein ioBroker-Problem handelt. Vielleicht bin ich auch nur zu blöd.

Ich habe einen HmIP-MOD-HO gekauft. Diesen nutze ich in der Homematic zum Steuern meines Garagentores. Funktioniert.

Wenn ich das Gerät als Garage Door Opener unter Yahka konfiguriere, kann ich mit CurrentDoorState den Status des Geräts abfragen. Leider ist dies immer falsch, sprich wenn das Tor offen ist wird es als geschlossen angezeigt, wenn es geschlossen ist, wird es als geöffnet angezeigt. IoBroker zeigt den Status CLOSED, in der HomeApp ist das Tor offen. Leider bekomme ich das auch nicht invertiert.

![595F398F-841F-4834-AD8C-6BE5454B13CD](https://user-images.githubusercontent.com/60255369/105885743-d0dc4200-6009-11eb-8b1f-2c90c6aca23b.png)

Mit dem Datenpunkt Door_Command kann ich das Tor zwar einmal Öffnen, kriege es danach aber nicht mehr zu.

Ich stelle gerne weitere Infos zur Verfügung, wenn das Problem hier richtig adressiert ist.
![10824EA7-6A56-4CFB-BDF7-E3E166C8A3BD](https://user-images.githubusercontent.com/60255369/105885633-abe7cf00-6009-11eb-888e-65bcd74e2e4d.png)

**Comment by Tombra1889** [comment]
Hallo, ich lege mir für soetwas immer entsprechende Status in den User-Ordner an. Also zum Beispiel CurrentDoorState und TargetDoorState. Dann verknüpfe ich diese mit yahka. Die eigentlichen Werte ziehe ich mir dann via Blockly-Script aus HM IP. Mir ist aufgefallen, dass es besser funktioniert, wenn man den Status vorher prüft und dann nur bei Änderung nach HM IP schreibt. Also zum Beispiel so: 
<img width="610" alt="image" src="https://user-images.githubusercontent.com/60692414/106329704-39cdef00-6282-11eb-94b5-193130690ce4.png">

Blockly ist eigentlich ziemlich einfach, wenn man sich etwas eingearbeitet hat.

**Comment by Monox83** [comment]
Moin, ich habe das Über die MAP Funktion gemacht, geht auf und zu..
Über Kanal 2 hab ich noch das Licht mit dran.
<img width="1141" alt="Bildschirmfoto 2021-02-13 um 08 55 27" src="https://user-images.githubusercontent.com/24441317/107845125-84e71680-6dd9-11eb-9a2a-9654fb9c5dbf.png">

**Comment by HochdruckHummer** [comment]
Hallo und danke für Eure Antworten, 

die mich zwar noch nicht zum Ziel, aber in die richtige Richtung gedrückt haben.

Der Current State erscheint dank des folgenden Mappings nun korrekt in der Home-App:

![6D520C16-ED1F-4D02-ACBB-B02E6ABB3DDF](https://user-images.githubusercontent.com/60255369/107853575-1de85280-6e17-11eb-858f-970678e51ee6.jpeg)

Leider funktioniert das Setzen des Status aus irgendeinem Grund nicht. In Deinem Beispiel benutzt Du Passtrough auf Door_Command. Mit Passthroug Klicke ich in der Home-App auf das Tor, dann steht dor „öffnet“ oder „schließt“, effektiv tut sich aber nichts.

Habe auch hier schon mit dem Mapping versucht dieses korrekt anzusteuern und habe glaube ich alle Möglichkeiten durch. Steuern kann ich das Tor weiterhin nicht über Yahka. Ich kann den Status ohne Probleme mit ioBroker direkt in den Objekten setzen.

Kann mir jemand mit dem richtigen Mapping für TargetDoorState unter die Arme greifen? Gerne auch per Blockly, aber ich bin darin kompletter Neuling.

**Comment by Monox83** [comment]
Ich prüfe das noch mal bei mir, habe das Modul auch erst seid 2 Tagen

**Comment by Monox83** [comment]
Ja hast recht, es geht auf aber nicht mehr zu und die Lüftungsstellung wird nicht erkannt. Schaue ich mir noch mal genauer an.

**Comment by Monox83** [comment]
So habs hinbekommen,
der haken bei "is simple value" muss raus, mit ging es nicht.
<img width="1136" alt="Bildschirmfoto 2021-02-17 um 07 08 56" src="https://user-images.githubusercontent.com/24441317/108163329-2084c980-70ef-11eb-8b9b-91cd9c6001c2.png">

**Comment by HochdruckHummer** [comment]
Vielen dank, jetzt funktioniert alles wie gewünscht.
Für die Nachwelt dokumentiere ich hier also nochmal alle Einstellungen im Yak-Adapter, damit funktioniert:

Einstellungen für CurrentDoorState
InOut: ioBroker.State
State: hm-rpc.X.XXXXXXXXXXXXXX.1.DOOR_STATE
Conversion: map
0 -> is simple value 1
1 -> is simple value 0
2 -> is simple value 2
3 -> is simple value 3

Einstellungen für HMIP-MOD-HO zu CurrentDoorState in Yahka.
Einstellungen für HMIP-MOD-HO zu CurrentDoorState in Yahka.
Einstellungen für TargetDoorState
InOut: ioBroker.State
State: hm-rpc.X.XXXXXXXXXXXXXX.1.DOOR_COMMAND
Conversion: map
1 -> 0 (nicht „is simple value“ anhaken)
3 -> 1 (nicht „is simple value“ anhaken)

**Comment by Zardhas** [comment]
Hallo zusammen, 
habe die Einstellungen ausprobiert, jedoch wir beim "State" mapping immer nach dem speichern "is simple value" wieder aktiviert.

was mach ich falsch?
