### ISSUE TITLE
Yahka Gerät lässt sich nicht mehr hinzufügen in Apple HomeKit seit dem Update.

### ISSUE THREAD

**Issue by Pete28** [jensweigele/ioBroker.yahka#232]
Hallo 
Ich hab vorhin ein update auf 0.12.0 gemacht und da ging garnichts mehr. Hab dann die Bridge aus meinem Apple HomeKit gelöscht und wollte diese nun neu hinzufügen.
HomeKit findet die Bridge, ich kann auch den pin eingeben, aber nach ca 3 min. warten kommt dann der Fehler das das Gerät nicht hinzugefügt werden kann.

**Comment by jensweigele** [comment]
Prüfe mal bitte ob eine Lösung aus #212 weiterhilft - falls ja, schließe das Ticket bitte.

**Comment by Pete28** [comment]
Hallo

Ich hab die option mit legacy garnicht.


Mit freundlichen Grüßen
Peter Klinglmair

**Comment by Fibbefobbe** [comment]
Gibt es eine Lösung? Habe das gleiche Problem dass HomeKit die Bridge ni hat findet.
