### ISSUE TITLE
please document used ports

### ISSUE THREAD

**Issue by Chris-We** [jensweigele/ioBroker.yahka#233]
please document the used ports of yahka.

I'm running yahka resp. iobroker via docker on a Synology Diskstation.
Once the firewall on the Diskstation is activated the Home App can't connect to the yahka bridge ("Antwortet nicht").
When I deactivate the firewall, the Home App can immediately reach the yahka bridge resp. its devices.
I can reactivate the firewall and the Home App can still find the yahka bridge resp. its devices for some time (1 to 2 days) until the Home App again can't find the devices.

**Comment by griesi** [comment]
I think you need to specify a Port in your yahka configuration and open this port on your synology firewall.

Otherwise a random port is picked which is blocked by your firewall.

**Comment by Chris-We** [comment]
@jensweigele & @griesi  how can I find out which ports have been chosen by the yahka adapter?
And is it necessary to define different ports for each device I have configured to be "published as own device"?

**Comment by griesi** [comment]
@Chris-We: IMHO there is no easy way to find out the port which is chosen by the operating system. Just define the port in your yahka settings and choose a different port for each yahka instance beacause of the incorrect adapter / port assignment in version 0.11 see #224
