### ISSUE TITLE
Yahka stop advertise it on network

### ISSUE THREAD

**Issue by vgeannin** [jensweigele/ioBroker.yahka#234]
Hi All,

it's strange, since the last update, main yahka bridge stop advertise him on my network.
Camera stil advertise
and if I add a new bridge, I can see it on my ios devices but the main bridge stop advertise.

yahka: 0.13.2 (same behaviour with 0.13.1)
Use Legacy Advertiser: false)
js-controller: 3.2.12
Node.js: v12.20.1
NPM: 6.14.10

**Comment by nicoh88** [comment]
Please enable `Use Legacy Advertiser`.
It is an known bug of `hap-nodejs`.

**Comment by vgeannin** [comment]
I enable Use Legacy Advertiser and I still have the PB

![Capture d’écran 2021-01-29 à 13 46 59](https://user-images.githubusercontent.com/14293635/106277083-c5229280-6238-11eb-9003-d3bb67be28ef.png)
Vincent

**Comment by MarkM500** [comment]
Where do you have enabled?
Thats my screenshot without "use Legacy Advertiser"??!!
![Bildschirmfoto 2021-02-05 um 13 55 50](https://user-images.githubusercontent.com/77006589/107036496-09bea880-67ba-11eb-9edf-8442e628741a.png)

Mark

**Comment by vgeannin** [comment]
So I understand what's happen now.
I've several AtmosphericPressureSensor (see issue #230)
So when I disable those sensor everything work
