### ISSUE TITLE
Yahka zeigt Fehlermeldung und startet nicht mehr [The supplied username (4g:af:23:a5:14:f1) is not valid (expected a format like 'XX:XX:XX:XX:XX:XX'  ...]

### ISSUE THREAD

**Issue by RobinErhardt** [jensweigele/ioBroker.yahka#235]
Hallo, ich habe seit den Updaten dauerhaft diese Fehlermeldungen und es geht nichts mehr. Ich habe Versucht, die Versionen downzugraden und wie auch in der Fehlermeldung, also wie ich es herauslese, den Username geändert aber ohne Erfolg.

Jetzige Yahka Version ist: 0.13.1

Hier die Fehlermeldungen:
![Fehlermeldungen Yahka](https://user-images.githubusercontent.com/67264436/106369190-89c6b780-634f-11eb-9a04-93b3d0d9de18.png)

Bitte um Hilfe, vielen Dank!

**Comment by jensweigele** [comment]
"4G" ist keine valide Hex-Zahl, möglicherweise liegt es daran.

**Comment by RobinErhardt** [comment]
Vielen Dank für die schnelle Antwort, durch ersetzen ging es tatsächlich. Das muss man auch erstmal wissen ;)
Vor den Update ging es komischerweise trotzdem, aber ok, vielleicht wurde da etwas abgeändert.

Damit schließe ich den issue
