### ISSUE TITLE
Rolladen ansteuern -bin am Verzweifeln-

### ISSUE THREAD

**Issue by MarkM500** [jensweigele/ioBroker.yahka#236]
Hallo Zusammen,

zu Grundsituation:
1. Habe einen Loratap SC500 mit Tasmota auf Shutter geflahst. Funktioniert über die Konsole tasmota einwandfrei.
2. Wird von Yahka auch erkannt und die States werden durchgereicht.
3. Jetzt kommt das Aber: Bekomme es über das iPhone nicht zum Laufen.., wird angezeigt aber Jalousie macht keinen Mucks.
4. Falsche Konfiguration in Yahka. Bin aber nicht sicher, welche states ich eingeben soll???

So sehen meine Einstellungen gerade aus (wahrscheinlich bin ich völlig verpeilt)
![Bildschirmfoto 2021-02-04 um 16 36 03](https://user-images.githubusercontent.com/77006589/106916115-1c2bda00-6707-11eb-88b6-5c2fa1c88ff5.png)

![Bildschirmfoto 2021-02-04 um 15 59 11](https://user-images.githubusercontent.com/77006589/106912295-2fd54180-6703-11eb-8a11-a0ef013cabf4.png)

Der Befehl die Jalousie auf eine bestimmte Position zu fahren wäre: ShutterPosition <Wert>, aber wo gebe richten Befehl ein?

Hoffe Ihr könnt mich auf den richtigen Weg bringen.
Gruss Mark

**Comment by MarkM500** [comment]
Alsooo

mittlerweile läuft es.

Allerdings wird die aktuelle PositionState noch nicht ans HomeKit übertragen.
Ideen was hier noch falsch ist?

Grüsse

**Comment by Tombra1889** [comment]
Hallo MarkM500, schau mal hier: https://github.com/jensweigele/ioBroker.yahka/issues/216

**Comment by MarkM500** [comment]
Super, dass ist die Lösung.

Aber sorry, keine Ahnung wie umsetzen..öffne #216
