### ISSUE TITLE
Garagentor - Conversion Script

### ISSUE THREAD

**Issue by dominikoyen** [jensweigele/ioBroker.yahka#237]
Hallo,

ich möchte gerne per HMIP AP und iobroker/yahka mehrere Geräte auf meinen Apple-Geräten steuern. Hierzu habe ich bereits einige Conversionen durchführen müssen, was mir bisher aber auch immer gelang. Bei folgender Conversion bin ich allerdings überfragt und zeigt mir Folgendes im Log:

(17591) setForeignState error [hmip.0.devices.3014F744380XXXXXXXXXX.channels.1.doorState] to [undefined]: undefined is not a valid state value

Ich setzt folgende Parameter:
CurrentDoorState  
TargetDoorState

Folgende Conversion:

if (value=="POSITION_UNKNOWN") {value="2";}
if (value=="CLOSED") {value="1";}
if (value=="OPEN") {value="0";}

if (value="2") {value="POSITION_UNKNOWN";} 
if (value="1") {value="CLOSED";} 
if (value="0") {value="OPEN";}

Kann mir jemand sagen, was ich falsch mache?

Danke und Grüße

Dominik

**Comment by jensweigele** [comment]
Du musst einen Wert zurückgeben mit "return".
Also am Ende sowas wie "return value;"

**Comment by dominikoyen** [comment]
oh man wie peinlich, danke funktioniert! Grüße
