### ISSUE TITLE
Position State -New Idea...possible?-

### ISSUE THREAD

**Issue by MarkM500** [jensweigele/ioBroker.yahka#238]
Hi,

because of my absolute Beginners Status, I have some problems to understand howto #216 . Thanks to Tombra1889 for the link.

It is not possible to read the right values in the Result and read/write per script to HomeKit

![Bildschirmfoto 2021-02-07 um 12 04 51](https://user-images.githubusercontent.com/77006589/107144644-c8a2d180-693c-11eb-944a-d7a123e4f84b.png)

Per example:
From Result to read/write the second value: 0 (down) or 1 (up) 
If the first value = third value, write 2

But how to read the values? How to put in Yahka?

So my questions:
1. Is it possible like above? or if not
2. Is here someone, who can give a help to #216?

Thanks
Mark

**Comment by Tombra1889** [comment]
Wenn ich es richtig verstehe, liefert dir deine Technik den Wert "RESULT" zurück, du aber keinen Zugriff auf die einzelnen Status hast. Also zum Beispiel Direction, richtig?

Ich würde dir empfehlen im User-Objektebereich eigene Status anzulegen. 
<img width="989" alt="image" src="https://user-images.githubusercontent.com/60692414/107689820-9e894080-6ca9-11eb-90ec-08605a11f101.png">


Mit Blockly könntest du dann aus dem "RESULT" dir die Werte extrahieren:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/60692414/107689712-7994cd80-6ca9-11eb-9d48-d4432d7045b5.png">

**Comment by MarkM500** [comment]
Habe jetzt folgendes gemacht:
Mit Script "Direction" ausgelesen:
const idJson = 'mqtt.0.stat.WzJa_16848D.RESULT';
const idBew = '0_userdata.0.Positionswechsel';
  on(idJson, function(dp) {
    var d =  JSON.parse(dp.state.val).Shutter1.Direction;
      setState(idBew, d, true);});
Das passt so weit. Ausgelesen wird -1=runter, 0=steht, 1 =rauf.
Also ab in Yahka mit Script:
![Bildschirmfoto 2021-02-11 um 23 10 02](https://user-images.githubusercontent.com/77006589/107705465-0e55f600-6cbf-11eb-9f48-92173dc2aee9.png)
Leider funktioniert es immer noch nicht.
Hmm...Ideen?
Mark

**Comment by MarkM500** [comment]
Vielleicht habe ich auch einen Fehler im Gesamtsystem, deswegen hier nochmal der Gesamtverbund:
![Bildschirmfoto 2021-02-12 um 14 19 28](https://user-images.githubusercontent.com/77006589/107773096-70554080-6d3d-11eb-8271-37bc720570a3.png)
Current Position ist der Status, welchen Tasmota als Zahl zwischen 0-100 zurückgibt.
Position State ist 0,1,2 (-1,0,1), welche über ein Script ausgelesen werden, als Indicator in userdata geschrieben werden und per Script in YAHKA übersetzt werden.
Target Position ist der Befehl mqtt/cmd/ShutterPosition, welchen ich aus den Befehlen in Tasmota angelegt habe. D.h. hiermit gebe ich den Befehl auf eine Target Postion zu fahren.
Mark

**Comment by DirkDoe** [comment]
Genau das Problem hatte ich auch, deswegen habe ich es ja mit dem blockly script gemacht, das ich dir in issue #216  gezeigt habe. 
Du musst den Position State von deinem Tasmota, so aktualisieren, dass Homekit das auch rafft und das ging bei mir eben nur mit dem script, das bei einer Änderung den Wert des Position State auf den Wert des Current State aktualisiert.
Ich hab absolut keinen blassen Schimmer wie Tombra z.B. es hinbekommen hat, das es mit der 0, 1, 2 Lösung alles gut läuft, weil Home sich ja die Position vom Position State abgreift, dieser ihr aber nur 0, 1 oder 2 zeigt und nicht wie bei meiner letztendlichen Lösung die effektiven Prozente.
Ich hoffe ich konnte dir nochmal ein bisschen helfen falls du es noch nicht geschafft hast.

**Comment by MarkM500** [comment]
> Wenn ich es richtig verstehe, liefert dir deine Technik den Wert "RESULT" zurück, du aber keinen Zugriff auf die einzelnen Status hast. Also zum Beispiel Direction, richtig?
> 
> Ich würde dir empfehlen im User-Objektebereich eigene Status anzulegen.
> <img alt="image" width="989" src="https://user-images.githubusercontent.com/60692414/107689820-9e894080-6ca9-11eb-90ec-08605a11f101.png">
> 
> Mit Blockly könntest du dann aus dem "RESULT" dir die Werte extrahieren:
> <img alt="image" width="778" src="https://user-images.githubusercontent.com/60692414/107689712-7994cd80-6ca9-11eb-9d48-d4432d7045b5.png">

@Tombra1889: Kannst Du uns hier nochmal helfen, wie man das ohne Blocky Scripts macht?

Gruss,
Mark
