### ISSUE TITLE
Nur wenn Wert = true an KomeKit übermitteln

### ISSUE THREAD

**Issue by Tyraenor** [jensweigele/ioBroker.yahka#239]
Hallo zusammen,

ich möchte gerne wenn ein Wert im ioBroker auf true gesetzt wird einen Single Press (0) an HomeKit übermitteln.
Wenn das Objekt wieder auf false gesetzt wird, soll nicht an HomeKit übermittelt werden.

Leider wird, auch wenn ich bei conversion auf script stelle und per if abfrage, ob der Wert true ist und dann return 0; schreibe, auch wenn der Wert false lautet 0 an HomeKit geschickt.

Wo hab ich hier den Fehler?

Das steht im Conversion script:
`if(value == true) return 0;`

Wenn ich das auf folgendes ändere:
```
if(value == true) return 0;
else return 1;
```

Dann wird bei Wert false tatsächlich ein Double Press (1) an HomeKit übermittelt.

Ich verstehe einfach nur nicht, warum wenn überhaupt kein return erfolgt, trotzdem 0 übermittelt wird...

**Comment by Typ1er** [comment]
Das Problem hatte ich vorher auch schon in FHEM mit dem 2x Klingeln.  Was ist Parameter „2“?
