### ISSUE TITLE
Garagentor einstellen

### ISSUE THREAD

**Issue by matze1708** [jensweigele/ioBroker.yahka#240]
Hallo,

wie kann ich am besten ein Garagentor einbinden. Ich habe das über KNX gesteuert. Immer wenn am State knx.0.Garage.TOR___Rolladen.Garage_TOR_Tasten_Antrieb_E_A eine 1 übergeben wird, öffnet, stopt oder schließt das tor. 
Ist ein Tor, welches mit einem Knopf bedient wird. 

Dann habe ich über Binäreingänge Reedkontakte in der offen Lage und in der geschlossen Lage montiert. 
Diesen Wert bekomme ich aber über den State knx.0.Garage.TOR___Rolladen.Garage_TOR_Logik_-_geöffnet_geschlossen

Das hatte ich dann im GarageDoorOpener einmal als TargetDoorState und den andere State als CurrentDoorState eingetragen. 

Auf TargetDoorState habe ich ein map mit Iobroker 1 = Homekit 0 und Iobroker 1 = Homekit 1  eingestellt. So das immer nur eine 1 gesendet wird. 

Jedoch kommt keine 2. Eins auf dem KNX Bus an. 

Stelle ich den KNX Adapter auf Button, so dass an diesem Objekt immer eine 1 gesendet wird. Dann spinnt der GarageDoorOpener in der App. er zeigt immer nur offen an. 

Welche Option habe ich? Wie kann ich das lösen?

Danke

**Comment by wavey93** [comment]
> Homekit expects those values "Current Door State" = "Open = 0";"Closed = 1";"Opening = 2";"Closing = 3";"Stopped = 4 "Target Door State" = "Open = 0";"Closed = 1

Any advice on how to use CurrenDoorState "Stopped"?
I use an own state CurrentDoorState that sets the 5 states as you said correctly using javascript. When I trigger TargetDoorState while opening/closing the door controller stops the door and CurrentDoorState is set to "Stopped". However HomeKit does not show the state stopped. All other states are shown correctly. Is this any issue or is state "stopped" only intended in case of "Obstruction Detected"? 

Thanks.

**Comment by Marty56** [comment]
I was wondering as well, how "stopped" of CurrentDoorState  and "Obstruction Detected" is visualised.
I did not see any change in the HomeKit App when "Obstruction Detected" is changed.
The value "stopped" of CurrentDoorState is creating an open visualisation
