### ISSUE TITLE
Waage für die Gasflasche meines Gartengrills

### ISSUE THREAD

**Issue by MarkM500** [jensweigele/ioBroker.yahka#241]
Hi,

habe mir mit HX711 und nem Wemos ne Waage für die Gasflasche meines Gasgrills gebastelt. Diese soll dann akkubetrieben ihren Dienst draussen in meinem Gasgrill absolvieren. D.h. einmal am Tag Info, danach wieder in den DeepSleep gehen (schön batterieschonend). Soweit alles gut.
Hat aber jemand eine Idee, wie ich dies mir schön in Homekit anzeigen lassen kann?
Momentan habe ich das Gewicht als Temperatursensor (Anzeige als Temperatur in °) und die Prozent als Feuchtigkeitssensor in Homekit. Alles Andere als schön.
Ideen?
Gruss Mark

**Comment by Tombra1889** [comment]
Hallo, ich würde es evtl. mit einem BatteryService versuchen. Wahrscheinlich aber auch nicht besonders schön. Ggf. in Kombination mit einem Kontaktsensor, der dann auslöst, wenn die Flasche leer ist.
