### ISSUE TITLE
Feature Request: Gruppierung der Geräteliste

### ISSUE THREAD

**Issue by grdminer** [jensweigele/ioBroker.yahka#244]
Hallo Team,

vielen Dank erstmal für eure Mühe und Einsatz. Der Adapter funktioniert bei mir bisher bestens. 
Einzig die Übersicht in der Geräteliste lässt schnell nach wenn ich viele Geräte hinzufüge. Ich werde um die 100 Geräte dort reinbringen und da wäre eine Gruppierung sehr hilfreich. Soweit ich erkennen kann unterstützt die verwendete Listview eine Gruppierung auf einer Ebene.

Mein Vorschlag wäre hier konkret ein simples Eingabefeld hinzuzufügen welches dann als Gruppierungsmerkmal angewendet wird. So ist es dem Benutzer überlassen wir er sich das gruppiert z.B. nach Raumnamen, Gerätenamen ...

Vielen Dank

**Comment by nicoh88** [comment]
+1

**Comment by jensweigele** [comment]
Ist im aktuellen Master implementiert
