### ISSUE TITLE
feature request: Copy service

### ISSUE THREAD

**Issue by TbsBrggng** [jensweigele/ioBroker.yahka#245]
Hallo,

ok, ich war blind blöd und überhaupt - oder doch nicht:

Es gibt die Funktionalität "Gerät kopieren". Ist es gewollt, dass die Services nicht kopiert werden? Fände es super, wen dem so währe.

Danke,
Tobias

**Comment by grdminer** [comment]
Wenn ich bei mir ein Gerät kopiere bzw. dupliziere werden die zugeordneten Services mit kopiert, das sollte doch das sein was Du möchtest? Oder habe ich Deine Frage vielleicht falsch verstanden? Ich bin auf Version 0.12.0

**Comment by Videonisse** [comment]
Services are also copied when you copy the Device (at least with v13.1). @TbsBrggng It still doesn't work four you, or did you just missed it?

**Comment by TbsBrggng** [comment]
Sorry for my late reply: It works now as you and I expect it to.
I do not know what was my issue in those days. Apologies for the false alarm.
