### ISSUE TITLE
Question: gleiche Services unter einem Gerät

### ISSUE THREAD

**Issue by grdminer** [jensweigele/ioBroker.yahka#246]
Ich bin auf Version 0.12.0 und wolle gerade meinen Heizkessel hinzufügen als einzelnes Gerät mit 3 Temperatursensoren. Sobald ich aber mehr als einen Temperatursensor hinzufüge reagiert Yahka heftig und stürzt, nach "Speichern und Schließen", ab. Ist das eine Limitation von Homekit,  eventuell ein Fehler in Yahka oder ein Bedienfehler von mir? Leider ich dazu nichts finden.

**Comment by Tombra1889** [comment]
Hey, du musst im oberen Teil die folgenden Felder (ServiceSubtyp und Dienstname) pro Temperatursensor unterschiedlich ausfüllen:
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/60692414/110183379-05b09580-7e0f-11eb-8ef2-db6614de55a8.png">

**Comment by grdminer** [comment]
@Tombra1889 Besten Dank, hat funktioniert. Der Service Subtype ist also der entscheidende Punkt. Unterschiedliche Dienstnamen reichen nicht aus.
