### ISSUE TITLE
Feature Request: Community-Characteristic KilowattHours Kommazahl statt Integer

### ISSUE THREAD

**Issue by grdminer** [jensweigele/ioBroker.yahka#247]
Hallo,

bei der Community-Characteristic KilowattHours ist der Typ als uint32 angegeben. Da es z.B. Eve erlaubt auch 2 Nachkommastellen anzuzeigen wäre mein Vorschlag dies auch zu nutzen. Insbesondere bei kleinen Verbrauchern wie z.B. Lampen o.ä. ist die Rundung auf ganze kWh sehr ungenau und erlaubt aus meiner Sicht keine Interpretation des Verbrauchs über einen kürzeren Zeitraum. Alternativ wäre auch Wh denkbar oder aber ein generische Community-Characteristic mit der Option eine Einheit mitzugeben. Falls ich hier etwas übersehen haben sollte bin ich für Hinweise immer dankbar. 

Mein konkreter Anwendungsfall ist die Energieerzeugung über ein Balkonkraftwerk mit 300W welche sich üblicherweise eher im Wh Bereich abspielt als im kWh Bereich. Weiterer Fall ist meine Brunnenpumpe welche zwar deutlich mehr Energie umsetzt aber hier bedeutet 1 kWh Verbrauch auch schon eine Laufzeit von über einer Stunde, ähnliches gilt für Trockner und Waschmaschine.

Vielen Dank!

**Comment by Videonisse** [comment]
You can change this in your own settings for the Characteristic. Just click on the "Characteristic Properties" for Community: KilowattHours. Change to "float" and minStep to "0.01".

![image](https://user-images.githubusercontent.com/13684218/114064831-4bdb9780-989a-11eb-8884-bfdacfa90223.png)

To change it permanently it needs to be done in the file types.js from the repository "[hap-nodejs-community-types](https://github.com/jensweigele/hap-nodejs-community-types)". But I'm not sure it should be changed as many users are using it as it is. But it's great that you individually can change it in Yahka :-)

_(don't forget to close issue if you think it's solved)_

**Comment by grdminer** [comment]
Cool, thanks. Worked for me. I didnt knew/realized that I can override the properties. I thought its a kind of help or documentation. Is there somewhere a documentation with those details?

**Comment by Videonisse** [comment]
Unfortunately not, I just learned my self. I think @jensweigele would love it if someone could contribute to documentation. However, @nicoh88 has been sharing a lot of examples to be found in the Wiki: https://github.com/jensweigele/ioBroker.yahka/wiki

Can you please close the issue?

**Comment by grdminer** [comment]
Thank you for your reply. I saw the wiki examples but didnt read them carefully as they didnt match my cases. I'll read them again just for education. Thanks for your help.
