### ISSUE TITLE
Seit Update auf 0.13.1 startet der Adapter nicht mehr

### ISSUE THREAD

**Issue by Brootmann** [jensweigele/ioBroker.yahka#249]
<img width="1499" alt="Bildschirmfoto 2021-03-15 um 08 53 12" src="https://user-images.githubusercontent.com/65487547/111122916-ffd55580-856e-11eb-88eb-0273a508e0fc.png">
<img width="1498" alt="Bildschirmfoto 2021-03-15 um 08 53 24" src="https://user-images.githubusercontent.com/65487547/111122924-0237af80-856f-11eb-9ba7-da27fb1c24a7.png">
<img width="1491" alt="Bildschirmfoto 2021-03-15 um 08 53 36" src="https://user-images.githubusercontent.com/65487547/111122928-04017300-856f-11eb-85fb-0f387b8dd91f.png">

**Comment by jensweigele** [comment]
Kannst du mal bitte den aktuellen Master testen? Der Crash sollte eigentlich abgefangen werden.

Die generelle Lösung für dein Problem findest du in #228
