### ISSUE TITLE
Make adapter ready for Admin v3

### ISSUE THREAD

**Issue by Apollon77** [jensweigele/ioBroker.yahka#25]
For Admin3 some changes are needed: see http://forum.iobroker.net/viewtopic.php?f=24&t=10268

**Comment by dfrozen** [comment]
If make start yahka 0.6.0-betta3 in Admin 3.0.0
host.orangepiplus	2018-01-07 22:33:52.629	error	startInstance yahka.0: cannot find start file!
host.orangepiplus	2018-01-07 22:33:52.614	info	object change system.adapter.yahka.0
iobroker	2018-01-07 22:33:52.503	info	Update "system.adapter.yahka.0"

**Comment by jensweigele** [comment]
I think this has nothing to do with Admin3 - instead it is wrongly installed.
You have to install it via NPM or you need to use the distribution repository: https://github.com/jensweigele/iobroker.yahka-dist

I'm still checking if it is possible to improve the installation procedure

**Comment by GermanBluefox** [comment]
index.html must be updated to index_m.html.
And translation to 8 Languages. (via google translator)

**Comment by jensweigele** [comment]
@GermanBluefox : is admin 3 already released? I'm only getting 2.0.7 as the latest version
I remember of a thread in the forum where someone wrote about compatiblity issues after doing the changes for admin3 - are they solved in the meantime?

**Comment by Apollon77** [comment]
You should find an "admin-beta" in your Adapterlist. Install it and this is Admin3 :-) SO Stable ist still 2.0.7, Beta is 3.0.10/11 or such.
Because of this "Parallel istall" no problems should exist

**Comment by jensweigele** [comment]
With 0.7.0, the adapter should be compatible to Admin3
