### ISSUE TITLE
Conversion Inverse to support Boolean values - Feature Request

### ISSUE THREAD

**Issue by Videonisse** [jensweigele/ioBroker.yahka#251]
So far I know, currently a script must be used to invert a Boolean value, for example, a "true" to "false". It would be much more convenient if Yahka could do this directly in the "Inverse" Conversion function.

The field "Value" could probably be greyed-out when Yahka detects a Characteristic of the type Boolean.

What do you think about this feature request? Thumb-up if you like it! 

![image](https://user-images.githubusercontent.com/13684218/112899403-649dbd80-90e2-11eb-8f93-6137348107d0.png)

**Comment by jensweigele** [comment]
There is a new "invert" function in the current master which is casting the incoming value to a boolean and negate it.
