### ISSUE TITLE
Mehrere Glühbirnen als eine Lampe

### ISSUE THREAD

**Issue by tonibert** [jensweigele/ioBroker.yahka#252]
Hi, danke für die tolle Arbeit. Ich versuche eine Deckenlampe mit 2 smarten Glühbirnen zu schalten.
Lieder funktioniert das nicht. Ich habe MultipleState probiert , erstmal nur einfach on/off .
Ebenfalls habe ich probiert jede Birne als Service hinzuzufügen. Da startet der Adapter dann nicht mehr.

Grüße und nochmals Danke

**Comment by Tombra1889** [comment]
Hey, du musst dafür einfach den Service zweimal in einem Gerät anlegen:
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/60692414/113315137-410a8b00-930d-11eb-9a56-e361b0805d75.png">
und dann bei Dienstname und Service-Subtype etwas eintragen.

**Comment by tonibert** [comment]
Hey, danke. Aber ich bekomme es nicht hin. Ich frage mal anders.

Wie schaffe ich es eine Birne mit Namen 1-1 und eine Birne mit Namen 1-2 als eine Lampe , mit Namen Deckenlampe zusammenzufassen.
Natürlich probiere ich nebenbei auch aber ich habe bisher keinen Erfolg.

Ich würde gerne im Schritt 
1. 2 einzelne Birnen als eine Lampe ein- und ausschalten und im Schritt
2. 2 einzelne Birnen als eine Lampe dimmen ( Zusatz falls das geht aber so verstehe ich es )

**Comment by Tombra1889** [comment]
Ich glaube, dann ist es wahrscheinlich einfacher die Lampen einfach direkt in Homekit zu Gruppieren, also auf dem iPhone.

**Comment by tonibert** [comment]
Ich würde es sehr gerne über deinen Adapter  gruppieren. Da ich den Schalter der Lampe gerne,demnächst, mit einem Shelly schalten möchte und dann Dimmen etc. über eine  Lampe im Homekit verfügbar machen möchte. So habe ich es auch schon mit einer Hue Birne und einem Shelly in einer Stehlampe umgesetzt. Das geht super und alles ist über Siri/Homekit steuerbar. Nun habe ich aber 2 Birnen in einer Lampe und würde das gerne umsetzen. Sämtliche andere Logik soll gerne im IO Broker bleiben.
Um es meiner Familie zu vereinfachen soll es eben  gruppiert werden. Mache ich etwas falsch oder ist es dafür noch nicht ausgelegt?
Ich habe es auch schon mit einem Link probiert... das ging aber auch nicht.
Dein Adapter ist genau das was ich gesucht habe.Datenpunkt vereinen und Homekit übergeben

**Comment by tonibert** [comment]
Wenn ich es wie von dir beschrieben umsetzte wird via Siri immer nur eine Birne ein und ausgestellt.
Im Homekit habe ich unter einer Lampe dann 2 separat steuerbare Birnen zur Verfügung.

**Comment by Videonisse** [comment]
So far I Know, it,s an Apple Issue. HomeKit doesn't support more than one Lightbulb service within an Accessory. At least using the Home app. 

But maybe if you use the Third-party Eve app it could work. Have you already tested this?

**Comment by tonibert** [comment]
I haven't looked at Eve yet because I haven't had any of it yet. Thanks for the hint.
I'll import it as individual devices and use Shelly's facility and then group it into Homekit.
I thank you.

**Comment by Videonisse** [comment]
Actually, I was curious and created a test device in Yahka. It works fine adding multiple Lightbulb Services to the same Lightbulb Device (with unique Service Types) and then grouping them together to a "single bulb". 

However, I can't find a Grouping function in the Home app so I was using it in the Eve app (Settings -> Groups). 

Thanks for asking this, now I have learned some new and useful today! :-)

**Comment by tonibert** [comment]
Can you please show your example and the settings

**Comment by Videonisse** [comment]
**Yahka** - 1 Device as type Lightbulb and 3 identic Lightbulb services with unique names and Service Subtype:

![image](https://user-images.githubusercontent.com/13684218/113451495-60cfab00-9402-11eb-8f81-6fa5ba4e92a0.png)


**Eve app** - Created Group from 1 Device with 3 Lightbulbs:
![image](https://user-images.githubusercontent.com/13684218/113452443-45659f80-9404-11eb-97a3-3e5b9c7cc69a.png)


**Home app** - the Group is viewed as 1 Lightbulb and can be switch as such directly from the Home view. Open the Device Settings and the Group with all 3 Lights are visible.:
![image](https://user-images.githubusercontent.com/13684218/113452576-8eb5ef00-9404-11eb-97bb-ad4a0b2e604b.png)
![image](https://user-images.githubusercontent.com/13684218/113452597-9d9ca180-9404-11eb-801d-478c1567fd38.png)

**Comment by DutchmanNL** [comment]
leider scheint dies nicht mehr so zu funktionieren ? Habe dazu ein issue erstellt
