### ISSUE TITLE
RollerShutter 2 currentValue Problem

### ISSUE THREAD

**Issue by Typ1er** [jensweigele/ioBroker.yahka#255]
ich habe ein Problem der Anzeige in Home, beim Rollladen bleibt am Ende "wird geöffnet" und "wird geschlossen" stehen und dreht sich im Kreis. selbst wenn ich das Positiostate von Hand setze ändert sich da nichts.

Das PositonState sollte doch folgende Angaben haben:
0 = wird geöffnet
1 = wird geschlossen
2 = stop

was mache ich falsch?

**Comment by Videonisse** [comment]
You don't need to set the "PositionState " as this is calculated automatically based on the "CurrentPosition" and "TargetPosition". If they are equal, it shows Open, Closed or the percentage it's open. Else it shows "Opening" or "Closing".

So your problem is that Target and Current aren't equal.

**Comment by andremueller83** [comment]
Schau bitte mal ob diese Einstellungen bei Dir klappen, falls du Deine Rolläden auch wie ich über KNX hast. Mit diesen Einstellungen funktioniert es bei mir fehlerfrei.

![image](https://user-images.githubusercontent.com/70439951/114080186-610cf200-98ab-11eb-869f-45c98f3dcea6.png)

**Comment by jensweigele** [comment]
keine Antwort => close
