### ISSUE TITLE
Support of the "Primary Service" tag for accessories with multiple services

### ISSUE THREAD

**Issue by Videonisse** [jensweigele/ioBroker.yahka#256]
Does Yahka add the "Primary Service" tag for an Accessory with multiple Services? If yes, is it enabled for the first service created, or how does it work?

From r2 of the Non-Commercial version of the Apple Homekit Specs (2019):
`2.3.2.3 Primary Service
Accessories should list one of its services as the primary service. The primary service must match the primary function
of the accessory and must also match with the accessory category. An accessory must expose only one primary
service from its list of available services.`

Apple Online docs doesn't say much about it: https://developer.apple.com/documentation/homekit/hmservice/1650059-primaryservice?language=objc

**Comment by jensweigele** [comment]
That's not yet implemented in Yahka. I'll leave this open as a future request.
