### ISSUE TITLE
Sensoren werden im Homekit nicht abgebildet

### ISSUE THREAD

**Issue by madstoP** [jensweigele/ioBroker.yahka#258]
Hallo,

ich habe das Modul HmIP-STHO-A erfolgreich über ioBroker im Homekit eingebunden. Temperatur und Luftfeuchte werden auch korrekt angezeigt. Im nächsten Schritt wollte ich nun Homekit mit diesem Sensor die Jalousie mit Hilfe einer Automation steuern, jedoch ist der Sensor als Automation nicht verfügbar. Was mache ich hier falsch? Ich habe schon mehrere Foren durchsucht und bin leider nicht fündig geworden.

**Comment by Videonisse** [comment]
How is your device configured in Yahka? Share Device Type, Services that you use and the Characteristics that are connected to your ioBroker Device.

(you can respond in German if you want)

**Comment by madstoP** [comment]
Ich habe als Value jeweils Actual.temperature and actual.humidity ausgewählt


![7C56FD01-C76C-4DF3-BA26-7007232369A5](https://user-images.githubusercontent.com/82045255/113942589-59910e80-9801-11eb-809a-740dc81e08e2.jpeg)

**Comment by Videonisse** [comment]
> Im nächsten Schritt wollte ich nun Homekit mit diesem Sensor die Jalousie mit Hilfe einer Automation steuern, jedoch ist der Sensor als Automation nicht verfügbar. Was mache ich hier falsch? 

You can't use the Apple Home app to create this. However, you can create an Automation that triggers based on sensor values using a third-party Homekit App. For example the free app from Eve. The Automation is then available in the Home app as well, but can only be edited using the Eve app. 

![image](https://user-images.githubusercontent.com/13684218/114035134-1bd2cb00-987f-11eb-833b-ab71c4b9ea3b.png)

**Comment by madstoP** [comment]
Vielen Dank für den Tipp. Funktioniert!
