### ISSUE TITLE
Kamera Bild drehbar

### ISSUE THREAD

**Issue by matze1708** [jensweigele/ioBroker.yahka#26]
Hallo,

Ich würde mir wünschen das es eine Variable gibt, mit der man das Kamera Bild Snapshot und livestream drehen kann.

Ffmpeg macht das mit transpose.

https://stackoverflow.com/questions/3937387/rotating-videos-with-ffmpeg

**Comment by jensweigele** [comment]
Für solche Spezialfälle kann die FFMPEG Kommandozeile im Adapter geändert werden. Ich schließe daher das Issue
