### ISSUE TITLE
TimeStamp Uhrzeit übergeben

### ISSUE THREAD

**Issue by tonibert** [jensweigele/ioBroker.yahka#261]
Ist es möglich einen Zeitwert  zu übergeben? Ich finde keine Möglichkeit eine Uhrzeit über Siri/Homikit an eine Variable zu übergeben. Ich möchte z.B. eine Uhrzeit an eine Variable weitergeben.

**Comment by Videonisse** [comment]
Have you tried the Service "TimeInformation"? Both the service and the characteristics are depreciated, but maybe it still works with third-party apps?

![image](https://user-images.githubusercontent.com/13684218/114280943-e9220180-9a3b-11eb-9f2f-fdf246c70fc9.png)
