### ISSUE TITLE
Update documentation or help for iobroker.Multistate values

### ISSUE THREAD

**Issue by w00dst0ck** [jensweigele/ioBroker.yahka#263]
Currently I can't find any information, which variables hold the values for iobroker.MultiState if I want to use them in a conversion script.

Thanx

**Comment by Videonisse** [comment]
I don't think it's different if you use the normal state or multi-state, you have one variable and it is "value".

Here is an example from the Forum: https://forum.iobroker.net/topic/37185/gel%C3%B6st-yahka-feedback/14
![image](https://user-images.githubusercontent.com/13684218/114356348-c5aca300-9b70-11eb-877f-1b428a5561ec.png)

**Comment by w00dst0ck** [comment]
![image](https://user-images.githubusercontent.com/1853382/114506614-57c8b000-9c32-11eb-8398-b96d34016b38.png)
I need to generate a value depending on two read values.

**Comment by w00dst0ck** [comment]
Used the Loglevel Debug to realize it is an array.

But when I implement an easy Conversion script like 

```
if (value[0] == value[1]) {return 0;}
if (value[0] > value[1]) {return 1;}
if (value[0] < value[1]) {return 2;}
```
it results in a crashing yahka adapter.

Log:
```
yahka.0 | 2021-04-14 08:29:40.906 | warn | (31535) Terminated (UNCAUGHT_EXCEPTION): Without reason
yahka.0 | 2021-04-14 08:29:40.905 | info | (31535) terminating
yahka.0 | 2021-04-14 08:29:40.904 | info | (31535) cleaned up ...
yahka.0 | 2021-04-14 08:29:40.903 | info | (31535) cleaning up ...
yahka.0 | 2021-04-14 08:29:40.734 | error | (31535) Cannot read property '0' of undefined
yahka.0 | 2021-04-14 08:29:40.733 | error | (31535) TypeError: Cannot read property '0' of undefined at TIoBrokerConversion_Script.eval [as toHKFunction] (eval at TIoBrokerConversion_Script (/opt/iobroker/node_modules/iobroker.yahka/webpack
yahka.0 | 2021-04-14 08:29:40.591 | error | (31535) unhandled promise rejection: Cannot read property '0' of undefined
yahka.0 | 2021-04-14 08:29:40.590 | error | (31535) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

**Comment by w00dst0ck** [comment]
```
if (value) {
    if (value.length == 2) {
        if (value[0] == value[1]) {return 0;}
        if (value[0] > value[1]) {return 1;}
        if (value[0] < value[1]) {return 2;}
    }
}
```

Seems to work!

But I think the mention of the array in the documentation could help others.

**Comment by Omoebert** [comment]
@w00dst0ck  thanks for the advice. I used your script and it works fantastic. It only took me some time until I found the advice with the array over here. Would be great if this is somehow covered in the documentation.
