### ISSUE TITLE
Feature Request: Szenen aus dem ioBroker Szenen-Adapter integrieren

### ISSUE THREAD

**Issue by Elonil** [jensweigele/ioBroker.yahka#264]
Hallo verehrtes Team,

ich hätte eine Frage und hoffe auf eine Implementierungsmöglichkeit im Rahmen des yahka-Adapters. Ich suche aktuell nach einer Möglichkeit die Szenen aus dem Szenen-Adpater auch als Szenen in Apple Home zu integrieren. Aktuell löse ich dies über einen Umweg indem ich die Szenen als Geräte integriere und dafür einen eigenen Szenen-Raum erstellt habe. Besteht die Möglichkeit dies in einer zukünftigen Revision des Adapters zu integrieren?

Viele Grüße
Elonil

**Comment by jensweigele** [comment]
Dafür gibt es keine Schnittstelle von Apple, daher ist es leider nicht möglich und nur über die von dir beschriebenen Umwege möglich.
