### ISSUE TITLE
Alle Adapter offline nach Update auf iOS 14.5

### ISSUE THREAD

**Issue by fliix-de** [jensweigele/ioBroker.yahka#267]
Seit dem neuen iOS Update 14.5 funktionieren bei uns keinerlei Adapter mehr. Wir konnten die Bridge neu verbinden und genau 1x einen Schalter einschalten, jetzt geht wieder nichts mehr. Wir vermuten natürlich daher, dass Apple wieder Änderungen an HomeKit vorgenommen hat.

Gibt es evtl. schon einen Verdacht woran das liegen könnte? Haben testweise über GitHub auch Version 0.14.0 installiert.

Vielen Dank für das tolle Projekt!

**Comment by Videonisse** [comment]
I'm using iOS 14.5 without issues since the beta phase. But my hub (iPad isn't on 14.5 yet). 

What are you using as hub, and is it updated as well?

**Comment by fliix-de** [comment]
> I'm using iOS 14.5 without issues since the beta phase. But my hub (iPad isn't on 14.5 yet).
> 
> What are you using as hub, and is it updated as well?

Thanks for your reply. All my devices are up to date with the latest iOS 14.5. As Hub i have an AppleTV 4K + Apple HomePod Mini. Still not working after complete new setup. Very strange. Yesterday before the update everything was totally fine.

**Comment by Videonisse** [comment]
I updated my ATV4 to tvOS 14.5 and everything seems to work as before. Try to turn off one of your hubs and restart the other and see if it works. If still problems, I think it's better you describe your problem in the forum.

**Comment by fliix-de** [comment]
I will try that later and report here. Thanks.

**Comment by fliix-de** [comment]
I was setting up a new ioBroker to test the configuration and had no issues as well. I deleted the adapter incl. configuration from my original ioBroker and moved the JSON files from the new one here. So far I have no problems anymore. Looks like the ioBroker had problems or the configuration was broken.
