### ISSUE TITLE
Add check to prevent duplicate device names (and thus crashes)

### ISSUE THREAD

**Issue by grimneko** [jensweigele/ioBroker.yahka#27]
I propose to add a name check on the device names to hinder duplicates which result in crashing of the bridge and pain in removing that error (had to delete the original device and re-add everything with a new name to avoid the collision ). If I try to add a device and name it similar to an existing one he should show a kind of error message and not accept it.

**Comment by jensweigele** [comment]
Good point. Will do it with the next version

**Comment by jensweigele** [comment]
I've added two things to avoid this problem:
1. the admin interface now warns if there is already a device with the same name
2. the adapter itself renames devices temporary to avoid duplicate devices
