### ISSUE TITLE
No answer / Keine Antwort in Apple Home

### ISSUE THREAD

**Issue by Binganga** [jensweigele/ioBroker.yahka#272]
Hi,

i am using Yahka with ioBroker on Docker in version 0.13.1 (Synology DS 718+ with a fixed ip).
Sometimes I get the message in my Apple Home App that the yahka-device, which I have added to yahka, isn't available (no answer or similar).

After some minutes it works without doing anything. That happens a lot of time, also before, where I have used my Shelly 2.5 devices with yahka (now they have their own Homekit firmware flashed).

--------

Nochmal auf deutsch:
Auf meiner Synology NAS läuft Docker mit den neuesten Updates für ioBroker. Yahka ist in Version 0.13.1 installiert. Die NAS hat eine feste IP.

Oft ist es so, dass meine yahka-Geräte, die ich also selbst angelegt habe, in der Apple Home App mit "Keine Antwort" gekennzeichnet sind. Ich hatte das früher sehr oft, als ich noch meine Shelly 2.5 Geräte hatte (drei Stück). Nachdem ich da eine alternative Homekit Firmware geflasht habe, trat das Problem seltener für die restlichen Geräte in der Home App auf.

**Info zu meinem Synology NAS DS718+:**
PLATTFORM: LINUX
BETRIEBSSYSTEM: LINUX
DIE ARCHITEKTUR: X64
CPUS: 4
GESCHWINDIGKEIT: 1501 MHZ
MODELL: INTEL(R) CELERON(R) CPU J3455 @ 1.50GHZ
RAM: 9.5 GB
NODE.JS: V12.16.2
NPM: 6.14.4

**Comment by Monox83** [comment]
Hi, hast du eine Lösung dafür?

ich habe gerade das, Problem, dass alle Geräte die nicht erreichbar sind.
Habe schon yahka 0.14 Probier und Downloaden des js-Controller auf 3.3.8.

Grüße Monox

**Comment by Binganga** [comment]
Läuft bei dir ioBroker als Docker Image oder auf einem Raspberry PI?

**Comment by Monox83** [comment]
Weder noch, ist eine VM mit Debian im VMM auf einer Synology DS918+

**Comment by Binganga** [comment]
Puhh, da bin ich dann überfragt. Die VM hat aber auch alle Portfreigaben?

**Comment by Monox83** [comment]
ja, hatte nur updates von unterwegs im iobroker gemacht, es kommt aber auch kein Fehler im log.
ich glaub ich werde den mal löschen und neu machen, vorher noch ein backup und mal schauen ob dann geht.

**Comment by PhilippLeitner** [comment]
Hallo, ich habe das gleiche Problem. Hat es sich durch das neu machen erledigt? 
LG

**Comment by Monox83** [comment]
Es hat gereicht der Bridge eine neue Mac/Benutzernamen zu geben, danach mussten die Geräte wieder den Räumen zugeordnet werden. Seit dem läuft es ohne Probleme.

Monox

**Comment by Binganga** [comment]
Puh, bei mir ist es sporadisch immer noch so, dass manchmal alle Geräte nicht erreichbar sind

**Comment by Kaiman77** [comment]
Gleiches Problem hier auch.
iobroker im Docker auf Synology. Wenn ich den nicht alle 30 Minuten neu starten, sind die Geräte sporadisch nicht erreichbar über einen Homepod Mini

**Comment by PhilippLeitner** [comment]
Genau das gleiche Verhalten zeigt er bei mir auch. Sogar nach einer neuinstallation

**Comment by Binganga** [comment]
Bei mir ebenso. Mir ist noch aufgefallen, dass sogar die Diskstation in dieser Zeit nicht erreichbar ist. Als ob der Adapter alles lahm legt und nach einer Weile wieder alles Laufen lässt. 

Ist euch dieses Verhalten auch aufgefallen?

**Comment by Monox83** [comment]
Friert die DS auch ein, wenn der Adapter deaktiviert ist?

**Comment by Binganga** [comment]
Nein. Das tat Sie mich nie in den letzten Jahren. Erst seitdem ich yahka nutze passiert es für x-Sekunden(?), dass diese nicht erreichbar ist. Nach dieser Zeit geht es, als ob nichts war.

**Comment by Kaiman77** [comment]
Die Erreichbarkeit der DS ist bei mir nicht beeinträchtigt. iobroker und DS sind weiterhin problemlos erreichbar und laufen auch problemlos.
Die Verfügbarkeit der Services war die Tage jetzt auch nur auf dem homepod nicht da, vom iPhone konnte ich Homekit Geräte (die aus dem yahka) weiterhin ansteuern.
