### ISSUE TITLE
Möglichkeit yahka remote Zugriff

### ISSUE THREAD

**Issue by janhp** [jensweigele/ioBroker.yahka#274]
Lieber Dev & Community,

gibt es eine Möglichkeit remote auf Homekit zuzugreifen OHNE apple tv/ipad/homepod im Haus?

Danke für die Auskunft.

**Comment by Videonisse** [comment]
Why do you create an issue here for that type of question? Please close this and ask the question in the forum.

**Comment by Baenker** [comment]
Das ist von Apple nicht vorgesehen. Dies ist allerdings wirklich kein Issue. Für solche Fragen gibt es das Forum
