### ISSUE TITLE
Gardena Smart Sileno einbinden

### ISSUE THREAD

**Issue by spirit0607** [jensweigele/ioBroker.yahka#276]
![366FD63B-3AA9-460A-A58F-D8905B39B729](https://user-images.githubusercontent.com/69988146/119382186-fd575080-bcc1-11eb-9956-3c411c9cea5c.jpeg)
Hallo zusammen, 
würde gerne einen Gardena Smart Sileno Rasenmäher einbinden, evtl. als Fan o.ä. 
Hat dies schonmal jemand geschafft? Ich habe zwar den Adapter erfolgreich installiert, scheitere jedoch an der Einrichtung.

**Comment by Baenker** [comment]
Mit welchen Datenpunkt wird denn der Mähe gestartet und mit was für einen Wert? Eignetlich ist es ganz einfach:

1: Neuen Datenpunkt einrichten unter userdata als number. 
2: Datenpunkt in yahka einbinden
3. Script schreiben. Reagiert auf den Datenpunkt. Wenn Datenpunkt == 1 dann schalte Datenpunkt vom Gerät und mit einer Verzögerung von x Sekunden den Datenpunkt unter userdata wieder auf 0.
