### ISSUE TITLE
Convert Humidity Values from Homematic to Homekit

### ISSUE THREAD

**Issue by stevoboy** [jensweigele/ioBroker.yahka#277]
Dear all,

from Homekit humidity values are coming in the format 60,50%. Homekit needs it without digits so 60%. How can I covert this value ?

**Comment by jensweigele** [comment]
You could use the conversion function "scaleInt" with 0-100 and 0-100 as a workaround.
I leave this ticket as a feature request open (-> create a "round" conversion)

**Comment by jensweigele** [comment]
Current master contains a "round" function
