### ISSUE TITLE
Missing the lists under Objects

### ISSUE THREAD

**Issue by COMHOME** [jensweigele/ioBroker.yahka#28]
I would like to set a switch to off with a script. It would be awesome, if the configured devices would be listed in ioBroker on the "Objects" tab.

**Comment by jensweigele** [comment]
Sounds good. But on the other side: yahka is just passing through data points - so you could already change the associated datapoint of your switch, couldn‘t you?

**Comment by COMHOME** [comment]
Hm, i tried to connect Loxone Lights via yahka with Siri. Every room got their light-controller with different scenes. So i added a button for every single light scene. After using Siri, the button is "on", but i'd like to reset it. I don't have the data points to set "off" after turning "on", or am i missing something?

**Comment by jensweigele** [comment]
Sorry, but I don't get you.
Are you turning a scene on with siri and want to turn that scene off again? (after some time)

**Comment by COMHOME** [comment]
I use a Switch to set a scene, and i would like to turn the Switch Off after the command...

**Comment by jensweigele** [comment]
Ok. The State of the Switch needs to be bound to an ioBroker State (you can create custom states in the ioBroker admin menu).
Then you could easily change this state with a script

**Comment by COMHOME** [comment]
Hmm... could you push me a little more in the right direction please?

**Comment by jensweigele** [comment]
Maybe I missunderstood you.
Could you post you config of Yahka please?
