### ISSUE TITLE
Gerät mit mehreren Services als ein Gerät anzeigen

### ISSUE THREAD

**Issue by andiweli** [jensweigele/ioBroker.yahka#280]
Hi zusammen

Folgendes Problem...

Ich möchte einen Xiaomi Fan in meine Homekit Installation einbinden.
Mit dem iobroker.ham Wrapper und dem passenden HAM-Plugin soweit kein Problem.
Ich seh im Objektbaum alle Werte die sich auch ändern wenn ich in der Hersteller-App von Xiaomi etwas verändere.
Ich kann auch über Yahka dann einen Lüfter einrichten und auch Ein/Ausschalten.

Da der Lüfter aber einige Funktionen hat, die ich gerne auf Buttons legen möchte, habe ich zusätzlich zum Service "Fan" der die eigentliche Ein/Aus-Steuerung übernimmt, folgende Services dazugeschalten und immer mit diesem ersten "Fan"-Service mit Link-To verlinkt:

- 2ter Fan (damit ein Schieber für den Silent-Mode angezeigt wird)
- 4 Outlets (um eine von 4 Lüfterstufen direkt anzusteuern, jede Stufe ist ein extra Value im Objektbaum)

![Bildschirmfoto 2021-07-13 um 23 28 28](https://user-images.githubusercontent.com/11447150/125527707-3a461829-0eff-436a-bb02-778aa6551e4a.png)

Wenn ich das aber mache, wird mir das ganze nicht mehr als Kachel mit einem animierten Lüfter angezeigt, sondern als Steckerleiste (vermutlich wegen der Outlets).

Lasse ich die Outlets mal weg und lasse nur den 2ten Fan für den 2ten Schieber des Silent-Modes drin, steht in der Kachel "Alle an" (vermutlich wenn beide Fans an sind) - und beim Draufklicken "Eingeschaltet - Eingeschaltet".

![IMG_2065](https://user-images.githubusercontent.com/11447150/125528461-fd6028b9-4514-4be8-b1ee-39daa2a6a52b.jpeg)

![IMG_2064](https://user-images.githubusercontent.com/11447150/125528485-ac3186c4-8f79-48fb-86ca-5ba0c75e0b2b.PNG)

Lässt sich das irgendwie umgehen, dass trotz mehrerer Services NUR der Fan in der Kachel in der Home App angezeigt wird und ich trotzdem bei längerem Draufdrücken auf die Kachel die anderen Settings habe? - Oder ist das technisch einfach nicht möglich mit Yahka?

Danke für eure Hilfe!

**Comment by jensweigele** [comment]
Das hat mit Yahka nichts zu tun sondern ist eine Sache der Apple Home App - sorry.
