### ISSUE TITLE
can not delete cameras

### ISSUE THREAD

**Issue by DerT94** [jensweigele/ioBroker.yahka#283]
Hey,

I created a camera and would like to delete ist.
But if I click on "delete device" nothing happens,

BR
T

**Comment by LuxBibi** [comment]
Hi,

I have the exact same issue. Did you manage to remove this camera ... I was able to remove another device I've created. (Sonos). So seems to be linked with the "Camera" type device ... I do not want to delete the whole adapter, and recreate everything without the cam .... 
Thx for sharing your actual view.
Luc

**Comment by jensweigele** [comment]
Works for me with 0.13.1
