### ISSUE TITLE
CurrentDoorState wird in Homekit nicht geändert

### ISSUE THREAD

**Issue by mdaudi1982** [jensweigele/ioBroker.yahka#286]
Hallo,

Ich habe mein Garagentor (KNX Schaltaktor) mit dem yahka Adapter verbunden, zwei Datenpunkte Current und Target erstellt und ein Script per Blockly gebaut. Dieses läuft soweit sehr gut, jedoch wenn ich das Tor per Homekit steuere, ändert sich der CurrentDoorState nicht. Wenn ich das Tor jedoch über meine KNX Visualisierung steuere, wird der CurrentDoorState auch im Homekit geändert. Eine Idee, woran das liegen könnte?

Beste Grüße,
Micha

**Comment by jensweigele** [comment]
CurrentDoorState ist der aktuelle Status und wird von HomeKit nicht geschrieben sondern nur angezeigt. Schau mal ob es einen TargetDoorState gibt - der könnte von HomeKit geschrieben werden.
