### ISSUE TITLE
Sortierung der Devices

### ISSUE THREAD

**Issue by HansPeterMeier** [jensweigele/ioBroker.yahka#29]
Hallo, ich würde mich über eine Sortierung der Devices freuen. Im Moment ist alles ein wenig durcheinander vom teste her.
Möchte nun auch ungern alle Devices neu Einpflege, da es doch ein wenig Arbeit ist.

Gruß und Danke

**Comment by jensweigele** [comment]
Meinst du eine manuelle Sortierung per Drag+Drop oder Automatisch (nach Name oder Typ?)?

**Comment by HansPeterMeier** [comment]
Eine Automatische nach Name wäre schön, im Moment sind meine komplett durcheinander, da ich welche löschen musste und neue hinzugefügt habe. Nun sind die mit Wohnzimmer beginnende leider komplett verteilt in der Liste. Man könnte vielleicht später auch drüber nachdenken eine Sortierung durch Rolle oder Funktion einzupflegen, das hat aber Zeit. Bin schon froh das sich jemand sich das annimmt. Meine Kenntnisse reichen dafür leider nicht aus. :(

**Comment by jensweigele** [comment]
Ab 0.6.0 sind die Geräte alphabetisch sortiert - die Sortierung wird aber nur beim Öffnen der Admin-Maske und beim hinzufügen von Geräten durchgeführt.
