### ISSUE TITLE
Kamera - Variablen aus den "Stream Eigenschaften"

### ISSUE THREAD

**Issue by nicoh88** [jensweigele/ioBroker.yahka#291]
Hi Jens,

mir ist beim Updaten einer Kamera im YAHKA aufgefallen, bei `v0.14` und auch im aktuellen `#master`, dass einige Variablen, welche über die Felder bei den Stream Eigenschaften gefüllt werden, nicht ordnungsgemäß an den `ffmpeg` Befehl übergeben werden - sondern die Standard- bzw. alte Werte verwendet werden.

`${source}` funktioniert
`${width}`, `${height}`, `${fps}` beispielsweise nicht, hier kann man eintragen was man will, es wird immer `1280`, `720` bzw. `30` verwendet.

Kannst du das mal prüfen?

Gruß Nico

**Comment by jensweigele** [comment]
Width, Height und FPS wird durch den Video Request festgelegt.
D.h. wenn dein Gerät ein kleines Display hat, sollte es ein kleinere Auflösung anfordern als ein Gerät mit großen Display.
In den Kamera Eigenschaften gibt man nur Max-Werte an - das wiederum sendet HomeKit and die Clients um zu sagen: "Ich kann ein Bild mit max A x B Pixeln bei einer maximalen FPS von C").

Wenn du das Debug-Log aktivierst, sollte beim Starten des Videos der Request im Log erscheinen:
```
this.FLogger.debug('Session Request:' + JSON.stringify(request, undefined, 2));
```  

Kannst du das nochmal prüfen und ggfls. das Ticket schließen?

**Comment by nicoh88** [comment]
Ok, verstehe. Mein Fehler. Verstanden.

![Bildschirmfoto 2021-09-23 um 12 36 03](https://user-images.githubusercontent.com/264264/134493864-39007076-aed5-403d-a353-029d7e60d48a.png)

Aber, dann wird wenigsten "max. FPS" ignoriert - dieser steht bei mir auf `1`. Weil wie du dich erinnerst, flicke ich aus Webcam-Standbildern, welche alle 10-60 Sekunden aktualisiert werden, ein Stream mit `-loop 1` zusammen.

```
root@frida ~ # ps -ef | grep -i ffmpeg
iobroker  224955  224058 15 12:40 ?        00:00:03 ffmpeg -loop 1 -nostats -nostdin -y -re -i https://webcam.muenchberg.de/rathaus.jpg -an -sn -dn -codec:v libx264 -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 16514873 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params P9ypE2lMNSHSamS06uzH4tlyGlI1EvirlEd5UNYx srtp://192.168.137.46:62700?rtcpport=62700&localrtcpport=62700&pkt_size=1378
```

Siehe `-r 30`.

Mir grundsätzlich egal, weil es funktioniert. Aber warum soll er 30x das Standbild in der Sekunde verarbeiten, wenn auch 1x reichen würde. Produziert nur unnötig Wärme auf der CPU. 😃 

Gruß Nico

**Comment by jensweigele** [comment]
Das Gerät fordert nunmal 30fps an. Im Advertisement sollte alles richtig laufen (siehe https://github.com/jensweigele/ioBroker.yahka/blob/de187acd9bda46e6782a23b8002e6f498fba7571/src/yahka.homekit-ipcamera.ts#L56)

Kannst du mal testen was passiert wenn du im Call Parameter fest "-r 1" schreibst? Funktioniert dann der Stream noch für das Endgerät?

**Comment by nicoh88** [comment]
Ja, habe es schon mit `-r 1` probiert - es funktioniert. Lass alles so wie es ist, dann habe ich "max. FPS" falsch interpretiert.
