### ISSUE TITLE
Yahka Bridge not found on Homekit

### ISSUE THREAD

**Issue by stevoboy** [jensweigele/ioBroker.yahka#292]
Dear all,

I had Yahka installed quite a while ago with a successful integration into Homekit. I deinstalled it a while and would like to reactivate it now. However it cannot be found by Homekit anymore. 
![image](https://user-images.githubusercontent.com/84937873/134759598-967d75df-1acd-4be0-9d89-fda1e0ad276b.png)

This is my set-up:
- IOS 15 on the Iphone
- Synology NAS running IoBroker container in the docker
- The NAS is connected to the router with one LAN cable running on one IP
- Bonjour deactivated: 
![image](https://user-images.githubusercontent.com/84937873/134759656-db263865-32fc-442c-84e2-bf1a23d3dc02.png)

- Yahka Instance name: 
![image](https://user-images.githubusercontent.com/84937873/134759672-88866f16-8cf9-4e7e-a43b-3d1942a29671.png)

- Yahka Bridge Set-up: 
![image](https://user-images.githubusercontent.com/84937873/134759707-ec1d3a7c-76b0-4b21-bfdd-816cfb9c5af4.png)

I tried with different Yahka Names, usernames and PinCodes. 

I would appreciate your support!

**Comment by Nordmann76** [comment]
Hi, I had the same issue. After adding a device (just any random skeleton) the bridge showed up in the installation.
Not sure if this works for you too.

**Comment by jensweigele** [comment]
Did this work for you? I'm not sure if you need to have a device registered to have the bridge discovered by HomeKit

**Comment by Nordmann76** [comment]
Yes, it worked for me. Not sure if it is related and normally it should not be necessary. I also named the bridge HomekitServer like other people mentioned.

**Comment by stevoboy** [comment]
It does not work for me. I renamed yahka to the following but cannot be found anymore. I had yahka running successfully running 2 month ago but now it is not found on the Apple home app anymore 
![image](https://user-images.githubusercontent.com/84937873/136690262-17d2503e-a7ab-4d9e-a9f3-d45cfdb737c6.jpeg)
![image](https://user-images.githubusercontent.com/84937873/136690265-3fea9868-b231-4728-9b2d-f5fcf110b7e1.jpeg)
![image](https://user-images.githubusercontent.com/84937873/136690270-53c01fe3-77a1-4b5f-a7b0-c80b62b3142b.jpeg)
![image](https://user-images.githubusercontent.com/84937873/136690272-eb842600-5a4a-49ae-9107-40a55a4643c7.jpeg)
![image](https://user-images.githubusercontent.com/84937873/136690276-349a178a-169c-4708-aed2-5747ab05b17c.jpeg)

**Comment by Nordmann76** [comment]
Hi Stevoboy,
did you remove your old bridge from the Apple Home app?
I tried to add a second home bridge (on yahka-1) and it worked out of the box (without any device). I removed it from my home and reattached it. Works like a charm.
Sorry, I know it is frustrating when things don't work as expected.
But as I said in the comments before, with the first installation I had many problems. Not sure what the cause was.
I run the yahka adapter on a raspberry pi4 and the AppleHome app on a iPhone with iOS 15.0.1

**Comment by mhoster83** [comment]
I have exactly the same problem. Running HomeKit on IOS 15.0.1 and iobroker on a virtual linux server.

**Comment by mhoster83** [comment]
Is it possible to set the IP Address an Port somewhere in the HomeKit app or do you mean to adjust the settings in the adapter?

**Comment by mhoster83** [comment]
Unfortunately it didn't work. When I change the port to the port of the iobroker, the adapter throw an error, that the port is already in use.

**Comment by stevoboy** [comment]
> I was able to close in on the problem. I installed the adapter on a local raspberry pi and it worked immediately. The problem seems to be related to my iobroker server is a cloud server and connected via vpn to my local network. Apparently the adapter is not accepting the VPN client as a network device. Does anyone have an idea? Thanks

Sorry what's your set-up situation with VPN? I try to understand if I am in the same situation.
I am running a Synology DS920+ with DSM7. On this NAS I have docker installed, Within a docker container buanet iobroker is running. Within this ioBroker, Yahka is running as an instance - see above my screenshots.
With this set-up, Yahka worked some time back. I then deinstalled the bridge on Apple Homekit App. Now trying to reinstall does not work.

**Comment by unstressable** [comment]
> Have you tried turning on the "legacy advertiser" option?

I tried the "legacy advertiser" option, but it does not have any affect.
I tried to set this option only at the bridge's properties, and then I set it at the bridge's and the device's properties. For example an temperature sensor.
It does not affect.

My question is, why does it work with the v0.11.0 and earlier, but not with the newer ones. Not even by using the "legacy advertiser" option :(

**Comment by mobilutz** [comment]
@stevoboy The problem here is, that ioBroker is running in docker.
Although it depends how you have the docker setup, but I doubt that the network is a macvlan.

Without macvlan network YAHKA will not work 😦 
https://github.com/buanet/ioBroker.docker/issues/132

I got around this, by adding another multihost iobroker as a "child" and having only YAHKA running there, but every other adapter inside the default docker ioBroker.

I hope this helps.

**Comment by stevoboy** [comment]
@mobilutz Hi Lutz, I managed to solve the problem in the meantime.

I had my iobroker docker container running as bridge. After migrating it to a container configured as host, yahka worked.
The biggest issue was this migration.
I had to setup a new container configured as host in which I integrated the original container.
This experiment cost me two weeks of my life but I am glad I did it.
HomeKit yahka is after initial set up just much easier to use and works with Siri voice control of HomePod mini. We hardly use wall Switches anymore now.

**Comment by LuxBibi** [comment]
Hallo alle ..
Hatte gleiches "Problem" .. Hab gerade rausgefunde, dass beim Ändern des Benutzernamens (MAC-Adress format in YAHKA-Adapter), dass dann YAHKA-Bridge neu in der IOS APP auftaucht (über +) .. Zumindest hat dies bei mir geholfen .. ;-) .. 

Bin gerade mittels Buanet/Docker von V4 auf V6 umgestiegen/upgrade.

Gruss aus Luxembourg, ;-)
Luc
