### ISSUE TITLE
Neue Gruppen funktionieren nicht korrekt (Auf-/Zuklappen)

### ISSUE THREAD

**Issue by unstressable** [jensweigele/ioBroker.yahka#297]
Wenn man mehrere Einzelobjekte in eine Gruppe packt, verschwinden diese nicht alle, wenn man die Gruppe zuklappt:
Aufgeklappt:
![image](https://user-images.githubusercontent.com/50423935/135754514-d79430d8-c5ff-4336-a8fd-e687271acef2.png)
Zugeklappt:
![image](https://user-images.githubusercontent.com/50423935/135754527-bec7abfb-71dc-4a12-8804-0c27b6be37f6.png)

Letztlich wird immer nur das oberste verborgen.

**Comment by jensweigele** [comment]
Ist im Master nun gefixed
