### ISSUE TITLE
Devices not responding (YAHKA not working)

### ISSUE THREAD

**Issue by Git-Romer** [jensweigele/ioBroker.yahka#298]
Hi
have for some time problems with the Yahka adapter. In the app all devices appear as unresponsive although everything works via the Iobroker interface. This happens over a long period of time and really works only on a whim. Unfortunately I can't find any error message in the log that would indicate anything. Restarting the instance does not really seem to help (works in the first 10 min and then it's gone again (connection comes and goes)).
I'm keeping all adapters up to date and also the iobroker and the npm, nodejs ...  modules are up to date (reccomended version of the IoBroker)
Is there a debug mode or a solution for my problem?

**Comment by jensweigele** [comment]
Which version are you using?
Have you tried to use the "legacy advertiser" option?

**Comment by snookyly** [comment]
Hi there, same issue here. Latest version of yahka in latest iobroker. After a minute or two all devices become unresponsive. How to enable the "legacy advertiser" option? Thanks for the great adapter. Your help is highly appreciated.

**Comment by fupsi42** [comment]
Hi all,

same here with my homepod mini. All devices are unresponsive.
yahka 0.12.0 on iobroker 5.1.25

**Comment by VrankyX** [comment]
I have the same problem but with version 0.13.1

After going back to version 0.12.0 everything works fine.

**Comment by unstressable** [comment]
> I have the same problem but with version 0.13.1
> 
> After going back to version 0.12.0 everything works fine.

same here, but in my case only 0.11.0 and earlier work. 0.12.0 and later are bad. even with the acivated "legacy advertiser" option.

**Comment by Git-Romer** [comment]
> 

Thanks guys I will try this.
Sad that there is no support for this issue.

**Comment by Git-Romer** [comment]
V0.13.1 and having everything up to date seems to have fixed the issue for now
Closing the Ticket here

**Comment by unstressable** [comment]
> V0.13.1 and having everything up to date seems to have fixed the issue for now Closing the Ticket here

I don't think the problem is fixed.
v0.13.1 is from 2021-01-14.

I already tried it and even 0.14.0

Both don't work.

The legacy advertiser has problems since versions after 0.11.0!
