### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Yury777** [jensweigele/ioBroker.yahka#3]
yahka.0	2017-04-13 12:24:25.429	info	cleaned everything up...
yahka.0	2017-04-13 12:24:25.428	error	at Array.forEach (native)
yahka.0	2017-04-13 12:24:25.428	error	at Bridge. (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/Accessory.js:740:22)
yahka.0	2017-04-13 12:24:25.428	error	at Characteristic.setValue (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/Characteristic.js:155:10)
yahka.0	2017-04-13 12:24:25.428	error	at emit (events.js:182:7)
yahka.0	2017-04-13 12:24:25.428	error	at emitMany (events.js:108:13)
yahka.0	2017-04-13 12:24:25.428	error	at Accessory. (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/Accessory.js:77:14)
yahka.0	2017-04-13 12:24:25.428	error	at Accessory._identificationRequest (/opt/iobroker/node_modules/iobroker.yahka/node_modules/hap-nodejs/lib/Accessory.js:111:10)
yahka.0	2017-04-13 12:24:25.428	error	at Accessory.emit (events.js:172:7)
yahka.0	2017-04-13 12:24:25.428	error	at emitTwo (events.js:87:13)
yahka.0	2017-04-13 12:24:25.428	error	at Accessory. (/opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-bridge.js:52:25)
yahka.0	2017-04-13 12:24:25.428	error	TypeError: Cannot read property 'debug' of undefined
yahka.0	2017-04-13 12:24:25.424	error	uncaught exception: Cannot read property 'debug' of undefined
yahka.0	2017-04-13 12:24:21.910	info	creating bridge
yahka.0	2017-04-13 12:24:21.909	info	adapter ready, checking config
yahka.0	2017-04-13 12:24:21.873	info	starting. Version 0.5.4 in /opt/iobroker/node_modules/iobroker.yahka, node: v4.8.0

**Comment by Yury777** [comment]
errors is printed when adding a bridge on iphone

**Comment by jensweigele** [comment]
Could you please retest with version 0.5.5?
