### ISSUE TITLE
Scrollen in Objekten funktioniert nicht

### ISSUE THREAD

**Issue by jopebe** [jensweigele/ioBroker.yahka#301]
Bei mir kann ich fast keinen Service hinzufügen, da ich in den Objekten nicht richtig scrollen kann. Ich sehe immer nur einen Ausschnitt von Instanzen. Klicke ich dann auf ein Objekt, geht der Baum auf, wird aber unten an den unmöglichsten Stellen abgeschnitten.
IoBroker (Up to date)  auf Raspberry
Alle Adapter auf neuestem Stand
Chrome auf WIN 10 PC als Browser.
Hat jemand eine Idee, woran das liegen kann?
Vielen Dank im Voraus

**Comment by andre1974** [comment]
Bei mir dasselbe.

Raspberry pi 4 mit 4gb RAM 
Browser ist Firefox und Safari.

**Comment by jensweigele** [comment]
Auch bei dir dasselbe: 

> Kannst du mal einen Screenshot anhängen (und markieren wo du nicht scrollen kannst)?

**Comment by andre1974** [comment]
> 
> 
> Auch bei dir dasselbe:
> 
> > Kannst du mal einen Screenshot anhängen (und markieren wo du nicht scrollen kannst)?

Gerne.... In dieser Ansicht ist scrollen nicht möglich...
![Screenshot (39)](https://user-images.githubusercontent.com/11474126/140105240-29120d19-6b79-476f-bcd1-57f2a2f67d8c.png)

**Comment by jensweigele** [comment]
Welche Yahka Version ist das?

**Comment by andre1974** [comment]
Version 0.12.0

**Comment by jensweigele** [comment]
Ab Version 0.13.0 ist der Fehler behoben
