### ISSUE TITLE
Alarmanlage

### ISSUE THREAD

**Issue by Hiaslbos** [jensweigele/ioBroker.yahka#31]
Hi, ich versuche die Alarmanlagensteuerung von Homematic einzubinden. Ich habe dazu lediglich bei SecuritySystemTargetState den "State" des Gerätes aus dem hm-rpc Adapter eingetragen. Die Sirene erscheint dann im Apple HomeKit mit den Statusanzeigen "Zuhause","Abwesend","Nacht" und "Aus"... ich kann aber keine Automatisierung mit irgendwelchen Türkontakten vornehmen. Kann man es irgendwie so einstellen, dass man den Status "An" oder "Aus" bekommt? Oder ist alles richtig im yahka eingestellt und der Fehler liegt eher im Apple HomeKit selbst?

LG
M.

**Comment by jensweigele** [comment]
ich habe mal zum testen eine Alarmanlage und einen ContactSensor angelegt und kann in der HomeKit Automation den Status der Alarmanlage abhängig von dem Sensor ändern (bspw. "Wenn Tür geschloßen zwischen 9.00 und 17.00, schalte Alarmanlage auf "Abwesend").

Das ist doch das was du machen möchtest oder?

**Comment by Hiaslbos** [comment]
Ja, nur wie bringe ich die Alarmanlage zum auslösen...? ich möchte programmieren: wenn Fensterkontakt auf, dann Sirene und Blitz an...



Von meinem iPhone gesendet

**Comment by jensweigele** [comment]
Soweit ich das sehe, ist das nicht in Homekit vorgesehen.
Eine Alarmanlage ist ein fertiges/komplettes System für Homekit. Du kannst nur Umschalten zwischen dem Betriebsmodus und du kannst den Status anzeigen lassen (tampered, fault etc).

Ich kenne die Homematic Alarmanlage nicht, aber wenn du dort einen/mehre Datenpunkte hast, um den Alarm auszulösen, könntest du diesen Datenpunkt als Switch in Homekit bringen und über eine Automatisierung den Switch schalten (Fenster auf -> Switch an -> löst den Alarm aus)

**Comment by jensweigele** [comment]
Ich schließe das Ticket. Falls noch Fragen sind, einfach wieder öffnen!
