### ISSUE TITLE
YAHKA Error after updating to 0.13.1

### ISSUE THREAD

**Issue by iobFan** [jensweigele/ioBroker.yahka#310]
Hi zusammen,

bisher lief YAHKA problemlos.. Mit dem Update auf 0.13.1 gerade startet der Adapter nicht mehr..

Könnt ihr euch das bitte mal genauer anschauen und mir helfen?

Danke vorab.

<html>
<body>

yahka.0 | 2021-11-16 16:24:19.215 | error | Exception-Code: ERR_SOCKET_BAD_PORT: options.port should be >= 0 and < 65536. Received .
-- | -- | -- | --
yahka.0 | 2021-11-16 16:24:19.214 | error | RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received . at new NodeError (internal/errors.js:322:7) at validatePort (internal/validators.js:216:11) at Server.listen (net.js:1457:5) at EventedHTTPServer.listen (/opt/iobroker/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20) at HAPServer.listen (/opt/iobroker/node_modules/hap-nodejs/src/lib/HAPServer.ts:316:21) at Bridge.Accessory.publish (/opt/iobroker/node_modules/hap-nodejs/src/lib/Accessory.ts:1252:18) at devicesToPublish (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.homekit-bridge.ts:27:31) at /opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.homekit-bridge.ts:73:41 at Array.forEach (<anonymous>) at THomeKitBridge../yahka.homekit-bridge.ts.THomeKitBridge.init (/opt/iobroker/node_modules/iobroker.yahka/webpack:/yahka.homekit-bridge.ts:73:26)
yahka.0 | 2021-11-16 16:24:19.214 | error | unhandled promise rejection: options.port should be >= 0 and < 65536. Received .
yahka.0 | 2021-11-16 16:24:19.213 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>

**Comment by jensweigele** [comment]
Welcher Wert ist bei "Port" eingetragen?

**Comment by PatrickDa87** [comment]
Hallo @jensweigele,
der Wert war standardmäßig auf "0" hinterlegt und ich habe auch keine Änderung vorgenommen. Habe gerade einmal den Port 65535 eingetragen und jetzt startet der Adapter wieder.

Irgendwas scheint mit der automatischen Port-Festlegung nicht zu klappen.

**Comment by PatrickDa87** [comment]
Hm ich habe jetzt wieder die 0 eingetragen und er startet. Dann muss beim Update irgendein Problem aufgetreten sein.. Direkt nach dem Update ist der Adapter mit der Fehlermeldung nicht mehr gestartet.

Kannst du dann aus meiner Sicht schließen, falls das nur ein lokales Problem bei mir war...

Danke :)
