### ISSUE TITLE
was ich bis jetzt analysieren konnte :

### ISSUE THREAD

**Issue by aeitschdot** [jensweigele/ioBroker.yahka#313]
gibts hierzu ein Update? Den ACTIVITY_STATE gibts wohl, zumindest mit der AP Nutzung, nicht mehr.

---

was ich bis jetzt analysieren konnte : 

Es gibt fuer rollaeden eine seperate funtion wobei man 

- current position
- target position
- Position state

Dafuer gibt es convertion, alles gut. …. problem ist folgendes bei HM-Aktoren : 

- man hat einen level wert (hoehe in % )
- es gibt einen ac tivity wert (0 = nix, 1 = aufmachen, 2= zumachen, 3 = stop)

Yahka macht es erst richtig, nimmt den activity state und setzt z.b. auf “aufmachen”,  da der level wert sich aber gleichzeitig aendert geht aufmachen/zumachen sofort auf offen/zu (je nach em level wert).

Um das zu loesen sollen also die activitaet status abgefragt werden und nur wen der 0 oder 3 ist den wert vom level uebernehmen

damit währen die HM-IP BROLL dan fertig implementiert und andere Sachen sollte auch behoben sein.
Den BROLL selber hab ich im moment so konfiguriert (geht außer die jetzige Laufrichtung)

<img width="1160" alt="Schermafbeelding 2020-03-06 om 09 47 35" src="https://user-images.githubusercontent.com/7318445/76067365-85ebb300-5f8f-11ea-93d3-e6415a43e089.png">

_Originally posted by @DutchmanNL in https://github.com/jensweigele/ioBroker.yahka/issues/74#issuecomment-595665294_

**Comment by jensweigele** [comment]
Bitte die Diskussion in dem originalen Thread fortführen
