### ISSUE TITLE
Error: "characteristic value expected valid finite number and received "NaN" (number)"

### ISSUE THREAD

**Issue by SolarX2** [jensweigele/ioBroker.yahka#315]
Hi,

I'm suddenly receiving following error message with a Zigbee light that had been working fine with HomeKit.

`Caught by controller[0]: [Yahka-0@Küche Licht@Küche Licht@Color Temperature] characteristic value expected valid finite number and received "NaN" (number)`

`instance system.adapter.yahka.0 terminated with code 6 (UNCAUGHT_EXCEPTION)`

Could you please help.

Cheers

**Comment by jensweigele** [comment]
Depends on your config, but I think your source device is providing a value of "null", "undefined" or "NaN" and thus the Yahka conversion function is converting it to NaN. Can you have a look at the value from the source device and post the config of that datapoint?
