### ISSUE TITLE
Feature request: Room assignment within ioBroker

### ISSUE THREAD

**Issue by Trustmania** [jensweigele/ioBroker.yahka#317]
If technically possible, it would be awesome, if devices can be assigned to available / existing rooms. This would prevent, that changes on devices has to be reconfigured.

UseCase: I'm mapping a lot devices from DigitalStrom via ioBroker to HomeKit.

**Comment by jensweigele** [comment]
That's not possible through Yahka. Yahka is only providing devices and cannot manipulate the HomeKit database (where the room assignment is stored)
