### ISSUE TITLE
Steuerung mehrerer Leuchten gleichzeitig

### ISSUE THREAD

**Issue by fabwins** [jensweigele/ioBroker.yahka#319]
Bei uns im Bad haben wir zum einen eine indirekte Beleuchtung, als auch Spiegelleuchten. Ich möchte nun mittels einem einzigen Eintrag in der Home app beide Datenpunkte gleichzeitig steuern (schalten) Wie würden Sie dies lösen? Ich habe es mit zwei Services bei einem Gerät probiert, als auch zwei Multistate Einträge in einem Service. 
Ich danke Ihnen sehr für die Hilfe

**Comment by DaHi35** [comment]
Hi fabwins,

in der Home-App kann man mehrere Geräte gruppieren und somit zu einem Gerät zusammenfügen. Ist das vielleicht die Funktion die Du suchst?

Gruß,
DaHi35

**Comment by krobipd** [comment]
entweder wie @DaHi35 geschrieben hat. oder du machst einen Datenpunkt der dann die zwei lichter per blockly ansteuert. diesen Datenpunkt nimmst du für HomeKit her. somit hast du nur ein HomeKit gerät und im Hintergrund macht halt das blockly die Arbeit.

**Comment by Baenker** [comment]
Könnte man das Issue schließen. Lösung wurde genannt
