### ISSUE TITLE
Feature Request: Add Sprinkler and Faucets IOS11 Devices

### ISSUE THREAD

**Issue by captaindork** [jensweigele/ioBroker.yahka#32]
Hi again, 
Sorry, trying to reopen #14 
Thanks for updating to latest HAP, however Sprinkler and faucets are not yet part of yahka.
As per my understanding this is because it was also not part of HAP-NodeJS.
However now they should be included as per https://github.com/KhaosT/HAP-NodeJS/issues/504 
Could this be integrated to yahka now?

Thanks in Advance!! Happy you are continuing development!!!

**Comment by jensweigele** [comment]
With 0.7.0, the following services were added: Faucet, IrrigationSystem and Valve
