### ISSUE TITLE
Wrong datatype when changing Bosch Outlet

### ISSUE THREAD

**Issue by simi101** [jensweigele/ioBroker.yahka#320]
When I try so change the State of my Bosch Outlet. I get the following error:

` State value to set for "bshb.0.hdm:ZigBee:847127fffe17777c.PowerSwitch.switchState" has to be type "string" but received type "boolean"`

To change the state I have to use  "ON" or "OFF", but how can I change this is yahka?

**Comment by D2xU** [comment]
How did you solve the problem? I have now an error like this with a sonoff device which just work fine for months but now I get the same errormessage with „numbers“ and „boolean“

**Comment by simi101** [comment]
Maybe use the conversion setting like this:
<img width="885" src="https://user-images.githubusercontent.com/97468334/196471124-2dd02d6b-545d-4a32-8b51-4319317eb96c.png">

**Comment by D2xU** [comment]
I guess it's thr right way but doesnt work either...
This ist the output with the mapping:
![grafik](https://user-images.githubusercontent.com/44578384/196516766-aa5fbe80-486b-4d27-aea4-ed5ec52ef148.png)

Without the mapping I get these errors:
![grafik](https://user-images.githubusercontent.com/44578384/196517037-e4c0119c-e67d-4251-bea0-43ca83d65fb0.png)

Is it poosible that yahka didnt use "0" or "1" as "true" and "false"?

**Comment by simi101** [comment]
I have mixed it up. I think you have to use true/false for iobroker and 0/1 for HomeKit.

**Comment by D2xU** [comment]
![grafik](https://user-images.githubusercontent.com/44578384/196738862-2344b97d-eb6f-455d-9021-a1401c11f363.png)
When I chenage it I get a different errormassage:
![grafik](https://user-images.githubusercontent.com/44578384/196739306-2030a5c8-8e34-42ee-a53c-9b3a55ab0964.png)
