### ISSUE TITLE
yahka will not start - system.adapter.yahka.0 terminated with code 6 (UNCAUGHT_EXCEPTION

### ISSUE THREAD

**Issue by 0x1234567890** [jensweigele/ioBroker.yahka#324]
My yahka will not start up anymore. 
Did anyone know why?

Log
`<html>
<body>

yahka.0 | 2022-01-23 22:55:50.304 | info | (3044) starting. Version 0.13.1 in /opt/iobroker/node_modules/iobroker.yahka, node: v14.17.3, js-controller: 3.3.22
-- | -- | -- | --
host.raspberrypi | 2022-01-23 22:55:48.351 | info | instance system.adapter.yahka.0 started with pid 3044
host.raspberrypi | 2022-01-23 22:55:47.284 | info | Restart adapter system.adapter.yahka.0 because enabled
host.raspberrypi | 2022-01-23 22:55:47.284 | error | instance system.adapter.yahka.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.raspberrypi | 2022-01-23 22:55:47.284 | error | Caught by controller[50]: [iobroker D3DA@Sonnenaufgang Schlafzimmer 20min@Sonnenaufgang Schlafzimmer 20min@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.284 | error | Caught by controller[49]: [iobroker D3DA@Büro Licht@Büro Licht E27@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.284 | error | Caught by controller[49]: [iobroker D3DA@Abschließen@Abschließen@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.283 | error | Caught by controller[49]: [iobroker D3DA@Tür@Tür@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.283 | error | Caught by controller[49]: [iobroker D3DA@SwitchBot@SwitchBot@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.283 | error | Caught by controller[48]: [iobroker D3DA@Alexa Wecker@Alexa Wecker Frühschicht@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.283 | error | Caught by controller[47]: [iobroker D3DA@Lichterkette Schlafzimmer Schalter@Lichterkette Schlafzimmer Schalter@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.283 | error | Caught by controller[46]: [iobroker D3DA@Luftentfeuchter@Luftentfeuchter@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.283 | error | Caught by controller[45]: [iobroker D3DA@Klimaanlage Sicherung@Klimaanlage Sicherung@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.282 | error | Caught by controller[44]: [iobroker D3DA@Klimaanlage Schlafzimmer@Klimaanlage@Temperature Display Units] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.282 | error | Caught by controller[43]: [iobroker D3DA@Klimaanlage Schlafzimmer@Klimaanlage@Rotation Speed] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.282 | error | Caught by controller[42]: [iobroker D3DA@Klimaanlage Schlafzimmer@Klimaanlage@Cooling Threshold Temperature] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.282 | error | Caught by controller[41]: [iobroker D3DA@Klimaanlage Schlafzimmer@Klimaanlage@Current Temperature] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.282 | error | Caught by controller[40]: [iobroker D3DA@Klimaanlage Schlafzimmer@Klimaanlage@Active] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.282 | error | Caught by controller[39]: [iobroker D3DA@Klimaanlage@Klimaanlage@Temperature Display Units] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.281 | error | Caught by controller[39]: [iobroker D3DA@Klimaanlage@Klimaanlage@Cooling Threshold Temperature] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.281 | error | Caught by controller[39]: [iobroker D3DA@Klimaanlage@Klimaanlage@Rotation Speed] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.281 | error | Caught by controller[39]: [iobroker D3DA@Klimaanlage@Klimaanlage@Current Temperature] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.281 | error | Caught by controller[39]: [iobroker D3DA@Klimaanlage@Klimaanlage@Active] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.281 | error | Caught by controller[38]: [iobroker D3DA@Büro Rollo@Büro Rollo@Target Position] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.281 | error | Caught by controller[37]: [iobroker D3DA@Büro Deckenlicht@Büro Deckenlicht@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.280 | error | Caught by controller[36]: [iobroker D3DA@Bewegungsmelder Treppe@Bewegungsmelder Treppe@Motion Detected] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.280 | error | Caught by controller[35]: [iobroker D3DA@Alexa Bremen Next@Alexa Bremen Next@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.280 | error | Caught by controller[34]: [iobroker D3DA@zuhause@zuhause@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.280 | error | Caught by controller[33]: [iobroker D3DA@Deckenlampe Wohnzimmer@Deckenlampe Wohnzimmer@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.280 | error | Caught by controller[32]: [iobroker D3DA@Bewegungsmelder Küche@Bewegungsmelder Küche@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.280 | error | Caught by controller[31]: [iobroker D3DA@Lichterkette Küche Schalter@Lichterkette Küche Schalter@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.279 | error | Caught by controller[30]: [iobroker D3DA@Lichterkette klein Küche Schalter@Lichterkette klein Küche Schalter@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.279 | error | Caught by controller[29]: [iobroker D3DA@Deckenlampe Küche Schalter@Deckenlampe Küche Schalter@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.279 | error | Caught by controller[28]: [iobroker D3DA@Bewegungsmelder Flur@Bewegungsmelder Flur@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.279 | error | Caught by controller[27]: [iobroker D3DA@gelber Sack@gelber Sack@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.279 | error | Caught by controller[26]: [iobroker D3DA@Papiermüll@Papiermüll@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.279 | error | Caught by controller[25]: [iobroker D3DA@Restmüll@Restmüll@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.278 | error | Caught by controller[24]: [iobroker D3DA@Deckenlampe Bad@Deckenlampe Bad@Color Temperature] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.278 | error | Caught by controller[23]: [iobroker D3DA@Deckenlampe Bad@Deckenlampe Bad@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.278 | error | Caught by controller[22]: [iobroker D3DA@Alleine@Alleine@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.278 | error | Caught by controller[21]: [iobroker D3DA@Deckenlampe Schlafzimmer@moonlight@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.278 | error | Caught by controller[20]: [iobroker D3DA@Deckenlampe Schlafzimmer@Deckenlampe Schlafzimmer@Color Temperature] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.277 | error | Caught by controller[19]: [iobroker D3DA@Deckenlampe Schlafzimmer@Deckenlampe Schlafzimmer@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.277 | error | Caught by controller[18]: [iobroker D3DA@meteroite@meteroite@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.277 | error | Caught by controller[17]: [iobroker D3DA@Büro Licht@Büro Licht E27@Brightness] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.277 | error | Caught by controller[16]: [iobroker D3DA@Büro Rollo@Büro Rollo@Target Position] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.277 | error | Caught by controller[15]: [iobroker D3DA@Büro Licht@Büro Licht E27@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.277 | error | Caught by controller[14]: [iobroker D3DA@SwitchBot@SwitchBot@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.276 | error | Caught by controller[13]: [iobroker D3DA@Luftentfeuchter@Luftentfeuchter@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.276 | error | Caught by controller[12]: [iobroker D3DA@Klimaanlage Sicherung@Klimaanlage Sicherung@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.276 | error | Caught by controller[12]: [iobroker D3DA@Klimaanlage Schlafzimmer@Klimaanlage@Temperature Display Units] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.276 | error | Caught by controller[11]: [iobroker D3DA@Klimaanlage Schlafzimmer@Klimaanlage@Current Temperature] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.276 | error | Caught by controller[10]: [iobroker D3DA@Klimaanlage Schlafzimmer@Klimaanlage@Rotation Speed] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.275 | error | Caught by controller[9]: [iobroker D3DA@Klimaanlage@Klimaanlage@Temperature Display Units] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.275 | error | Caught by controller[8]: [iobroker D3DA@Klimaanlage@Klimaanlage@Cooling Threshold Temperature] characteristic was supplied illegal value: number 10 exceeded minimum of 16
host.raspberrypi | 2022-01-23 22:55:47.275 | error | Caught by controller[7]: [iobroker D3DA@Klimaanlage@Klimaanlage@Cooling Threshold Temperature] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.275 | error | Caught by controller[6]: [iobroker D3DA@Klimaanlage@Klimaanlage@Current Temperature] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.275 | error | Caught by controller[5]: [iobroker D3DA@Klimaanlage@Klimaanlage@Rotation Speed] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.275 | error | Caught by controller[4]: [iobroker D3DA@Büro Rollo@Büro Rollo@Current Position] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.274 | error | Caught by controller[3]: [iobroker D3DA@Büro Rollo@Büro Rollo@Position State] characteristic value expected valid finite number and received "undefined" (undefined)
host.raspberrypi | 2022-01-23 22:55:47.274 | error | Caught by controller[2]: [iobroker D3DA@Deckenlampe Wohnzimmer@Deckenlampe Wohnzimmer@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.274 | error | Caught by controller[1]: [iobroker D3DA@gelber Sack@gelber Sack@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.274 | error | Caught by controller[0]: [iobroker D3DA@Papiermüll@Papiermüll@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.274 | error | Caught by controller[0]: [iobroker D3DA@Restmüll@Restmüll@On] characteristic value expected boolean and received undefined
host.raspberrypi | 2022-01-23 22:55:47.274 | error | Caught by controller[0]: [iobroker D3DA@Deckenlampe Bad@Deckenlampe Bad@Color Temperature] characteristic was supplied illegal value: number 4000 exceeded maximum of 500
host.raspberrypi | 2022-01-23 22:55:47.273 | error | Caught by controller[0]: [iobroker D3DA@Deckenlampe Bad@Deckenlampe Bad@Color Temperature] characteristic was supplied illegal value: number 4000 exceeded maximum of 500
host.raspberrypi | 2022-01-23 22:55:47.273 | error | Caught by controller[0]: [iobroker D3DA@Deckenlampe Schlafzimmer@Deckenlampe Schlafzimmer@Color Temperature] characteristic was supplied illegal value: number 2700 exceeded maximum of 500
host.raspberrypi | 2022-01-23 22:55:47.272 | error | Caught by controller[0]: [iobroker D3DA@Deckenlampe Schlafzimmer@Deckenlampe Schlafzimmer@Color Temperature] characteristic was supplied illegal value: number 2700 exceeded maximum of 500
yahka.0 | 2022-01-23 22:55:44.786 | info | (2975) terminating with timeout
yahka.0 | 2022-01-23 22:55:43.273 | debug | (2975) [Büro Rollo.TargetPosition] set was initiated from ioBroker - exiting here
yahka.0 | 2022-01-23 22:55:43.273 | debug | (2975) [Büro Rollo.TargetPosition] got a set event, hkValue: 0
yahka.0 | 2022-01-23 22:55:43.270 | debug | (2975) [Büro Rollo.TargetPosition] forwarding value from ioBroker (undefined) to homekit as (undefined)
yahka.0 | 2022-01-23 22:55:43.270 | debug | (2975) [Büro Rollo.TargetPosition] got a change notify event, ioValue: undefined
yahka.0 | 2022-01-23 22:55:43.269 | debug | (2975) [homepilot.0.devices.RolloTronStandardDuoFern.1010010.level_inverted] firing target state change event:undefined
yahka.0 | 2022-01-23 22:55:43.181 | warn | (2975) Terminated (UNCAUGHT_EXCEPTION): Without reason
yahka.0 | 2022-01-23 22:55:43.179 | info | (2975) terminating
yahka.0 | 2022-01-23 22:55:43.178 | info | (2975) cleaned up ...
yahka.0 | 2022-01-23 22:55:43.177 | info | (2975) cleaning up ...

</body>
</html>`

**Comment by jensweigele** [comment]
the log is telling you the errors: `characteristic value expected boolean and received undefined`
You have a lot of characteristics where you provide the wrong values and this is not accepted anymore by the underlaying HomeKit Library.
