### ISSUE TITLE
Can not start yahka 0.6.1

### ISSUE THREAD

**Issue by dfrozen** [jensweigele/ioBroker.yahka#33]
root@orangepiplus:/opt/iobroker# node node_modules/iobroker.yahka/main.js --force --logs 
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
module.js:327
    throw err;
    ^

Error: Cannot find module 'ip'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-ipcamera.js:6:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by dfrozen** [comment]
when install in log:
 Cannot write files: /opt/iobroker/node_modules/iobroker.js-controller/lib/objects/../../../../iobroker-data/files/yahka.admin/_data.json: ENOENT: no such file or directory

**Comment by NicoChrist** [comment]
Hallo,

i have the same problem.


host.raspberrypi | 2018-01-30 12:29:27.819 | error | instance system.adapter.yahka.0 terminated with code 1 ()
-- | -- | -- | --
host.raspberrypi | 2018-01-30 12:29:27.819 | error | Caught by controller[3]: at Module.require (module.js:353:17)
host.raspberrypi | 2018-01-30 12:29:27.818 | error | Caught by controller[3]: at Function.Module._load (module.js:300:12)
host.raspberrypi | 2018-01-30 12:29:27.818 | error | Caught by controller[3]: at Module.load (module.js:343:32)
host.raspberrypi | 2018-01-30 12:29:27.818 | error | Caught by controller[3]: at Object.Module._extensions..js (module.js:416:10)
host.raspberrypi | 2018-01-30 12:29:27.818 | error | Caught by controller[3]: at Module._compile (module.js:409:26)
host.raspberrypi | 2018-01-30 12:29:27.818 | error | Caught by controller[3]: at Object. (/opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-ipcamera.js:6:10)
host.raspberrypi | 2018-01-30 12:29:27.818 | error | Caught by controller[3]: at require (internal/module.js:12:17)
host.raspberrypi | 2018-01-30 12:29:27.817 | error | Caught by controller[3]: at Module.require (module.js:353:17)
host.raspberrypi | 2018-01-30 12:29:27.817 | error | Caught by controller[3]: at Function.Module._load (module.js:276:25)
host.raspberrypi | 2018-01-30 12:29:27.817 | error | Caught by controller[3]: at Function.Module._resolveFilename (module.js:325:15)
host.raspberrypi | 2018-01-30 12:29:27.817 | error | Caught by controller[3]: Error: Cannot find module 'ip'
host.raspberrypi | 2018-01-30 12:29:27.817 | error | Caught by controller[3]: ^
host.raspberrypi | 2018-01-30 12:29:27.816 | error | Caught by controller[3]: throw err;
host.raspberrypi | 2018-01-30 12:29:27.816 | error | Caught by controller[3]: module.js:327
host.raspberrypi | 2018-01-30 12:29:27.816 | error | Caught by controller[2]: *** WARNING *** For more information see
host.raspberrypi | 2018-01-30 12:29:27.816 | error | Caught by controller[2]: *** WARNING *** Please fix your application to use the native API of Avahi!
host.raspberrypi | 2018-01-30 12:29:27.816 | error | Caught by controller[1]: *** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
host.raspberrypi | 2018-01-30 12:29:27.815 | error | Caught by controller[1]: *** WARNING *** For more information see
host.raspberrypi | 2018-01-30 12:29:27.815 | error | Caught by controller[1]: *** WARNING *** Please fix your application to use the native API of Avahi!
host.raspberrypi | 2018-01-30 12:29:27.814 | error | Caught by controller[0]: *** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.

**Comment by dfrozen** [comment]
It was solved in a rather strange way. Removed yahka 0.5.5, replaced nodejs 6.x.x
has new installed 0.6.1

**Comment by jensweigele** [comment]
The warnings could be ignored.
The "Cannot find module 'ip'" should be solved with 0.7.0 (which was released just yet)
