### ISSUE TITLE
Add user, after iCloud Keychain reset

### ISSUE THREAD

**Issue by Anzic23** [jensweigele/ioBroker.yahka#332]
homkit bridge was created in iobroker yahka, I'm the admin in it. Added two users. One of the user lost his iPhone and could not restore the iCloud Keychain, so his 'house' did not respond. Reset the keychain and created a new one. Home didn't catch up. I deleted this user and invited it again. But in my 'residents' this user automatically disappears... accordingly, the user cannot use 'home'. What can I do?
adapter v 0.13.1
js 3.3.18
NODE.JS: V12.22.7
NPM: V6.14.15

**Comment by jensweigele** [comment]
That's not related to Yahka and can't be solved here
