### ISSUE TITLE
OPNsense -> ioBroker (im VLAN) -> iPhone

### ISSUE THREAD

**Issue by Chiller2019** [jensweigele/ioBroker.yahka#348]
Servus,

ich versuche den Yahka-Server einzubinden am iPhone aber dieser wird partou nicht angezeigt. Damals mit der FRITZ!Box ging das einwandfrei, bei OPNsense allerdings nicht und ich weiß nicht wo ich meine Fehlersuche beginnen soll deswegen wollte ich hier in die Runde fragen.

Firewall ist für WLAN und ioBroker für in komplett verfügbar. Ich kann auch am iPhone den ioBroker aufrufen.

Liebe Grüße

**Comment by xxavarlonxx** [comment]
Moin,
hier ähnlich, hatte auch von fritzbox auf Opnsense umgestellt, wochenlang kein Stress mit Yahka und Homekit. Seit dieser Woche nur noch Probleme. Entweder er findet die Bridges nicht mehr und wenn dann kann er die Geräte nicht schalten. Was allerdings wichtig sein könnte grundsätzlich, wenn später iobroker und iPhone in unterschiedlichen Netzen hängen, dass du das PKG udpbroadcastrelay installierst für den Bonjour Multicast.

Aber nichtsdestotrotz, Yahka funktioniert bei mir auch nicht mehr wenn iobroker und IPhoen im selben Netz hängen. die FW blockiert auch nichts laut Log File, also schon ein Problem auf Anwendungsebene.

ios 15.5

**Comment by Chiller2019** [comment]
> Moin, hier ähnlich, hatte auch von fritzbox auf Opnsense umgestellt, wochenlang kein Stress mit Yahka und Homekit. Seit dieser Woche nur noch Probleme. Entweder er findet die Bridges nicht mehr und wenn dann kann er die Geräte nicht schalten. Was allerdings wichtig sein könnte grundsätzlich, wenn später iobroker und iPhone in unterschiedlichen Netzen hängen, dass du das PKG udpbroadcastrelay installierst für den Bonjour Multicast.
> 
> Aber nichtsdestotrotz, Yahka funktioniert bei mir auch nicht mehr wenn iobroker und IPhoen im selben Netz hängen. die FW blockiert auch nichts laut Log File, also schon ein Problem auf Anwendungsebene.
> 
> ios 15.5

Ja gut das ich nicht der einzige bin. Aber das mit dem Multicast hab ich nicht bedacht. Das könnte stimmen. Ich bin mir auch nicht mehr sicher aber damals wurde der ioBroker's Hostname geändert bei der FritzBox zum Namen des Benutzernamen in Yahka aber ich weiß nicht mehr wie weil du ja ":" nicht nutzen kannst dann müsste es wohl "-" sein oder "_". Aber ich hatte bei keinem Erfolg, vielleicht lag es aber bei mir auch am Multicast und es ist ne Mischung aus beiden Vorrausetzungen.

**Comment by Chiller2019** [comment]
ES GEHT!

Als Erweiterung "mDNS" installieren.
Dienste -> mDNS Repeater -> aktivieren, beide Schnittstellen auswählen und er wird angezeigt.
