### ISSUE TITLE
Keine Geräte nach Update von 0.14.0 auf 0.15.0 im Konfigmenü

### ISSUE THREAD

**Issue by Tombra1889** [jensweigele/ioBroker.yahka#359]
Im Konfigmenü werden nach dem Update von 0.14.0 auf 0.15.0 keine Geräte mehr angezeigt.

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/60692414/196023048-36523914-e076-4aa6-85eb-e23152924bae.png">

**Comment by jpawlowski** [comment]
Same here. A downgrade to version 0.13.2 is required.

**Comment by backfisch88** [comment]
same

hope fix comes soon

**Comment by HansPeterMeier** [comment]
Ist bei mir auch so

**Comment by peer69** [comment]
Same here.

**Comment by jensweigele** [comment]
Can you please check what happens when using the current master?
I've reverted the 0.15 merge

**Comment by jensweigele** [comment]
Just saw that someone also published that broken version to NPM - I'm going to release a 0.16 to revert the changes...

**Comment by Tombra1889** [comment]
it works

**Comment by jensweigele** [comment]
0.16.0 is now also published to NPM

**Comment by TA2k** [comment]
@Tombra1889 which Admins and js-controller you are using?

**Comment by TA2k** [comment]
Please try "Benutzer definierte Installation"
with url
https://github.com/TA2k/ioBroker.yahka
The latest commit missed the grunt build this leads to empty admin screen
