### ISSUE TITLE
Nach Update auf 0.16.0 zeigt Admin weiterhin 0.15.0 an

### ISSUE THREAD

**Issue by wendy2702** [jensweigele/ioBroker.yahka#363]
Hi,

habe gerade das update auf 0.16.0 gemacht was laut log erfolgreich war:

`
<html><body>

host.iobroker | 2022-10-17 08:05:39.659 | info | instance system.adapter.yahka.4 started with pid 22242
-- | -- | -- | --
host.iobroker | 2022-10-17 08:05:39.391 | info | instance system.adapter.yahka.2 started with pid 22234
host.iobroker | 2022-10-17 08:05:39.351 | info | instance system.adapter.yahka.1 started with pid 22228
host.iobroker | 2022-10-17 08:05:39.290 | info | instance system.adapter.yahka.0 started with pid 22221
host.iobroker | 2022-10-17 08:05:39.229 | info | iobroker upload [0] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.png yahka.png image/png
host.iobroker | 2022-10-17 08:05:38.995 | info | iobroker  upload [1] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js.map  yahka.admin.js.map application/json
host.iobroker | 2022-10-17 08:05:38.679 | info | iobroker  upload [2] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js  yahka.admin.js application/javascript
host.iobroker | 2022-10-17 08:05:38.662 | info | iobroker upload [3] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/words.js words.js application/javascript
host.iobroker | 2022-10-17 08:05:38.660 | info | iobroker upload [4] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index_m.html index_m.html text/html
host.iobroker | 2022-10-17 08:05:38.659 | info | iobroker upload [5] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index.html index.html text/html
host.iobroker | 2022-10-17 08:05:38.657 | info | iobroker  upload [6] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/home_icon_large.png  home_icon_large.png image/png
host.iobroker | 2022-10-17 08:05:38.653 | info | iobroker  upload [7] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/js/metro.min.js  ext/metroui/js/metro.min.js application/javascript
host.iobroker | 2022-10-17 08:05:38.645 | info | iobroker  upload [8] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/selection.json  ext/metroui/fonts/selection.json application/json
host.iobroker | 2022-10-17 08:05:38.643 | info | iobroker  upload [9] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.woff  ext/metroui/fonts/metro.woff font/woff
host.iobroker | 2022-10-17 08:05:38.631 | info | iobroker  upload [10] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.ttf  ext/metroui/fonts/metro.ttf font/ttf
host.iobroker | 2022-10-17 08:05:38.610 | info | iobroker  upload [11] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.svg  ext/metroui/fonts/metro.svg image/svg+xml
host.iobroker | 2022-10-17 08:05:38.606 | info | iobroker  upload [12] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.eot  ext/metroui/fonts/metro.eot application/vnd.ms-fontobject
host.iobroker | 2022-10-17 08:05:38.602 | info | iobroker  upload [13] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro.min.css  ext/metroui/css/metro.min.css text/css
host.iobroker | 2022-10-17 08:05:38.601 | info | iobroker  upload [14] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-schemes.min.css  ext/metroui/css/metro-schemes.min.css text/css
host.iobroker | 2022-10-17 08:05:38.596 | info | iobroker  upload [15] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-rtl.min.css  ext/metroui/css/metro-rtl.min.css text/css
host.iobroker | 2022-10-17 08:05:38.590 | info | iobroker  upload [16] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-responsive.min.css  ext/metroui/css/metro-responsive.min.css text/css
host.iobroker | 2022-10-17 08:05:38.590 | info | instance system.adapter.yahka.4 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.iobroker | 2022-10-17 08:05:38.094 | info | iobroker  upload [17] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-icons.min.css  ext/metroui/css/metro-icons.min.css text/css
host.iobroker | 2022-10-17 08:05:37.983 | info | instance system.adapter.yahka.2 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.iobroker | 2022-10-17 08:05:37.885 | info | iobroker  upload [18] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-colors.min.css  ext/metroui/css/metro-colors.min.css text/css
host.iobroker | 2022-10-17 08:05:37.881 | info | stopInstance system.adapter.yahka.4 killing pid 1363
host.iobroker | 2022-10-17 08:05:37.483 | info | instance system.adapter.yahka.1 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.iobroker | 2022-10-17 08:05:37.453 | info | instance system.adapter.yahka.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.iobroker | 2022-10-17 08:05:36.923 | info | iobroker  upload [19] yahka.admin  /opt/iobroker/node_modules/iobroker.yahka/admin/css/yahka.admin.css  css/yahka.admin.css text/css
host.iobroker | 2022-10-17 08:05:36.599 | info | stopInstance system.adapter.yahka.4 send kill signal
host.iobroker | 2022-10-17 08:05:36.555 | info | stopInstance system.adapter.yahka.4 (force=false, process=true)
host.iobroker | 2022-10-17 08:05:36.341 | info | stopInstance system.adapter.yahka.2 send kill signal
host.iobroker | 2022-10-17 08:05:36.340 | info | iobroker Update "system.adapter.yahka.4"
host.iobroker | 2022-10-17 08:05:36.311 | info | iobroker Update "system.adapter.yahka.3"
host.iobroker | 2022-10-17 08:05:36.308 | info | stopInstance system.adapter.yahka.1 send kill signal
host.iobroker | 2022-10-17 08:05:36.307 | info | stopInstance system.adapter.yahka.2 (force=false, process=true)
host.iobroker | 2022-10-17 08:05:36.294 | info | iobroker Update "system.adapter.yahka.2"
host.iobroker | 2022-10-17 08:05:36.288 | info | stopInstance system.adapter.yahka.1 (force=false, process=true)
host.iobroker | 2022-10-17 08:05:36.258 | info | iobroker Update "system.adapter.yahka.1"
host.iobroker | 2022-10-17 08:05:36.257 | info | stopInstance system.adapter.yahka.0 send kill signal
host.iobroker | 2022-10-17 08:05:36.249 | info | stopInstance system.adapter.yahka.0 (force=false, process=true)
host.iobroker | 2022-10-17 08:05:36.235 | info | iobroker Update "system.adapter.yahka.0"
host.iobroker | 2022-10-17 08:05:36.173 | info | iobroker changed 8 packages in 4s164 packages are looking for funding  run `npm fund` for details
host.iobroker | 2022-10-17 08:05:31.925 | info | iobroker Installing iobroker.yahka@0.16.0... (System call)
host.iobroker | 2022-10-17 08:05:31.924 | info | iobroker NPM version: 8.15.0
host.iobroker | 2022-10-17 08:05:31.597 | info | iobroker Update yahka from @0.13.1 to @0.16.0
host.iobroker | 2022-10-17 08:05:30.410 | info | iobroker upgrade yahka@0.16.0 --debug

</body>
</html>
`

Im Admin wird mir jetzt als installierte Version 0.15.0 angezeigt und immer noch ein Update auf 0.16.0 angeboten:

![grafik](https://user-images.githubusercontent.com/33424168/196102108-c437188c-3863-40e6-9d82-ce603e3de3e4.png)

**Comment by TA2k** [comment]
Wird bald behoben sein wenn die v 0.17 erscheint

**Comment by TA2k** [comment]
Du kannst schon mal installation via GitHub probieren dann sollte es korrekt sein

**Comment by wendy2702** [comment]
Sieht nach Github jetzt so aus:

![grafik](https://user-images.githubusercontent.com/33424168/196131220-d8f56044-51e1-490d-a8a0-878996c2848d.png)

Denke das Repo muss noch aktualisiert werden.

**Comment by TA2k** [comment]
Ja genau. Alle Yahka Funktionen funktionieren bei dir?

**Comment by jpawlowski** [comment]
It seems the root of the tree is new:

![instances - iobroker 2022-10-18 17-36-06](https://user-images.githubusercontent.com/75446/196477132-58f968c1-4dcb-41a7-84c8-8dfaf58b8cb9.jpg)

One can expand it and devices can be added/changed as usual. However, the Yahka device itself is now represented by this empty root only can it's properties cannot be changed or viewed at anymore.

**Comment by wendy2702** [comment]
Frage: Gefühlt bekomme ich seitdem Update immer die Antwort:

"Das Element ..." wurde eingeschaltet.

Habt ihr das auch oder liegt das an einem Apple Update?

**Comment by jpawlowski** [comment]
Notifications konfigurierst du ausschließlich in der Apple Home App. Wenn du da welche kriegst, die du nicht willst, kannst du sie nur dort abstellen. Yahka kann das nicht vorbelegen.

**Comment by wendy2702** [comment]
Worauf beziehst du deine Antwort?

**Comment by jpawlowski** [comment]
Auf deine Frage

**Comment by wendy2702** [comment]
Wo stelle ich denn ein wie Siri antworten soll?

Früher da als Antwort zum Beispiel:

"Fernsehen wurde eingeschaltet"

Seit irgendeinem Update

"Das Element Fernsehen wurde eingeschaltet"

Und das kann man konfigurieren? Wäre mir neu

**Comment by jpawlowski** [comment]
Du hast vorher nicht geschrieben, dass es um eine Sprachantwort geht, weshalb ich von mir ausgegangen bin und dachte, es geht um die Push Benachrichtigungen.
Aber dass man die Antworten von Siri nicht beeinflussen kann und sie auch nicht von ioBroker generiert werden, hast du dir ja nun selbst beantwortet :-)

**Comment by wendy2702** [comment]
Ich zitiere mich mal selber:

"Frage: Gefühlt bekomme ich seitdem Update immer die Antwort:

"Das Element ..." wurde eingeschaltet."

Wenn da steht ich bekomme eine Antwort bedeutet das zumindest für mich das es sich um etwas gesprochenes handelt.

Ob das andere allerdings auch haben weiß ich leider immer noch nicht bzw. Wann bzw. Womit das gekommen ist.

**Comment by wendy2702** [comment]
Schliesse hier da fehler nicht mehr auftritt.
