### ISSUE TITLE
Nach Upgrade auf 0.17.0 wird IPv4 Adresse nicht mehr announced

### ISSUE THREAD

**Issue by berndmr** [jensweigele/ioBroker.yahka#365]
Version 0.13.1 - alles funktioniert
Version 0.17.0 - nur ipv6 Adresse im ZeroConf sichtbar. Keine Verbindung.

(_hap._tcp ioBroker)

**Comment by TA2k** [comment]
Was passiert wenn du den ciao Advertiser in den einstellung auswählst
<img width="529" alt="image" src="https://user-images.githubusercontent.com/1307684/196802895-4fbf7c3f-c293-421b-a157-1033899dfc68.png">

**Comment by berndmr** [comment]
Danke, die Einstellung kannte ich nicht. 

"Use CIAO Advertiser" published die IPv4 und alles geht wieder.

**Comment by berndmr** [comment]
Node: 4.0.23

AHHH - Listen nur auf die 192.xxx

**Comment by berndmr** [comment]
Egal was, ich bekomme ihn nicht dazu auf der IPV6 zu hören. 
Aber der AVAHI Mode puplished nur die IPV6.

**Comment by TA2k** [comment]
Node 4 klingt sehr niedrig.
Vielleicht mal node auf 18 upgraden
Welches Betriebssystem verwendest du

**Comment by berndmr** [comment]
Sorry, js-controller ist 4.0.23
Node ist v14.20.0
Freebsd 12.1

**Comment by TA2k** [comment]
Ok dann geht wohl nur der ciao advertiser oder man kann versuchen das system zu updaten. node und freebsd
