### ISSUE TITLE
Keine Auswahl

### ISSUE THREAD

**Issue by ThWunderlin** [jensweigele/ioBroker.yahka#37]
Seit dem update auf IoBroker 2.0.9 kann ich keine Datenpunkte mehr auswählen und ändern.

**Comment by GermanBluefox** [comment]
In 3.1.10 ist fixed.

**Comment by ThWunderlin** [comment]
Super Danke

2018-02-14 21:22 GMT+01:00 jensweigele <notifications@github.com>:
