### ISSUE TITLE
Restore nicht möglich

### ISSUE THREAD

**Issue by hohmannc85** [jensweigele/ioBroker.yahka#374]
Nach dem Restore mit dem Backup Adapter (2 verschiedene Systeme mit unterschiedlichen Sicherungen getestet) sind die geräte alle da, der adapter springt kurz auf grün und bleibt auf rot. ein backup ist nicht verwertbar

**Comment by kaese2002** [comment]
Kameras dabei? FFMPEG installiert?

**Comment by hohmannc85** [comment]
Einmal ja, ffmpeg war installiert. Beim anderen mal nicht!
Wenn ich Instanz lösche und alles neu eintrage geht es sofort

**Comment by Baenker** [comment]
Es gibt ja ein spezielles Backup. Hast Du die zip genommen und den Inhalt in den entsprechenden Ordner kopiert? Das das normale Backup nicht funktioniert ist logisch

**Comment by Baenker** [comment]
Hier der Hinweis:

https://github.com/jensweigele/ioBroker.yahka/wiki/ioBroker.yahka-auf-ein-anderes-System-umziehen

**Comment by kaese2002** [comment]
> Hier der Hinweis:
> 
> 
> 
> https://github.com/jensweigele/ioBroker.yahka/wiki/ioBroker.yahka-auf-ein-anderes-System-umziehen

Alt...Besuch mal nicht mehr machen, wurde in Backitup integriert...

**Comment by Baenker** [comment]
Quelle? Bei mir im Backup Ordner wird immer noch eine extra yahka-Backup Datei erstellt? Das ist der Inhalt des Ordners. Bei meinen letzten Restore habe ich das in das entsprechende Verzeichnis kopiert und es lief wieder. Habe nichts mitbekommen das es nun anders sein soll…

**Comment by kaese2002** [comment]
> Quelle? Bei mir im Backup Ordner wird immer noch eine extra yahka-Backup Datei erstellt? Das ist der Inhalt des Ordners. Bei meinen letzten Restore habe ich das in das entsprechende Verzeichnis kopiert und es lief wieder. Habe nichts mitbekommen das es nun anders sein soll…

https://github.com/simatec/ioBroker.backitup/issues/519

**Comment by Baenker** [comment]
Du hast gesehen das ich diese Anforderung in dem Adapter geschrieben habe? Es ist wie ich es beschrieben habe. Backitup erstellt zum normalen Backup ein yahka Backup. Dieses Backup muss man nach dem eigentlichen Backup in den yahka Order restoren….

**Comment by Baenker** [comment]
Könnte man das Issue hier schlißen. Lösung wurde genannt.
