### ISSUE TITLE
Yahka Backitup-Herstellung fügt Geräte nicht hinzu

### ISSUE THREAD

**Issue by kaese2002** [jensweigele/ioBroker.yahka#375]
Hallo

Ich habe meine Installation auf ein neues Gerät umgezogen...Es läuft soweit alles, außer Yahka. Hier lässt sich das Backup nicht einspielen. Es wird positiv quittiert, der Adapter startet neu, aber in der Config bleibt es leer. Den Punkt mit dem zusätzlich umzuziehenden Ordner kenne ich, sollte bei Backitup 2.5.x aber nicht mehr relevant sein oder?

Vielleicht hat ja jemand eine Idee. Danke

https://user-images.githubusercontent.com/23189052/204904991-52df55ff-7ce5-4888-8d7a-62ab8eaf2790.mp4

**Comment by kaese2002** [comment]
Komplettes iobroker Backup nochmal eingespielt, dann direkt, ohne den Yahka Adapter vorher zu starten das Yahka Backup hinterher geschoben, dann hats funktioniert.

**Comment by Baenker** [comment]
dann schließ doch bitte das issue hier
