### ISSUE TITLE
Fehlermeldungen im IoBroker Log;  1: InOutParams / 2: Umwandlungsparameter Auswahl geht nicht

### ISSUE THREAD

**Issue by mrieglhofer** [jensweigele/ioBroker.yahka#38]
Hallo

1)Gestern wurden plötzlich meine YAHKA  Geräte nicht mehr in IoS erkannt und konnte auch lange nicht wieder zum laufen gebracht werden. Mittlerweile läuft er wieder, aber ich habe im Log jede Menge Fehlermeldungen, die ich nicht beheben kann. 

Daten: 
IoBroker mit Buanet Image.latest auf Synology DS713+
YAHKA 0.7 (automatisch aktualisiert beim Einspielen des Backups)

Probiert:
Image gelöscht, neu geladen und Backup eingespielt. Keine Erfolg. Keine Erkennung im IoS
Alte Version/neue Version, keine Änderung
Adapter gelöscht und neu installiert. Keine Erkennung.
Im Terminal apt-get Upgrade durchgeführt. Danach wieder im IoS erkannt. Aber Fehlermeldungen bleiben

2)  1: InOutParams / 2: Umwandlungsparameter 
Button zur Auswahl der Objekte mit den ... hat keine Funktion, sowohl bei IE als auch bei FF. Auswahl bei Objekten und einfügen in das passende Feld funktioniert.

Aber zumindest funktioniert die Erkennung wieder. Bei jeder Änderung in der Konfiguration kommt dieser Fehlerliste. Die Einträge bei den Ereignissen schreibt der Adapter aber trotzdem.

[YAHKA_Konfiguration.pdf](https://github.com/jensweigele/ioBroker.yahka/files/1694847/YAHKA_Konfiguration.pdf)

lg
Markus Rieglhofer

**Comment by jensweigele** [comment]
Welche Admin Version hast du drauf?

**Comment by jensweigele** [comment]
Ich vermute du hast Admin 2.0.9 drauf - mit 0.7.1 sollte die Auswahl wieder funktionieren (gerade released)
