### ISSUE TITLE
iOS 16 mit neuem Pincode

### ISSUE THREAD

**Issue by kaim2m** [jensweigele/ioBroker.yahka#386]
Ich haben Probleme mit neuem ios 16 und zwar kann ich den neuen Pincode nur im Format xxxx-xxxx-xxxx-xxxx eingeben.
Gibt es hierfür eine Lösung ?

**Comment by DonLuigi1992** [comment]
Habe das selbe Problem. Pincode ändern im Adapter auf das neue Apple Format hat nicht geholfen. Fix?

**Comment by do1osc** [comment]
Gleiches Problem bei mir

**Comment by adieball** [comment]
Bei mir auch. Eventuell der Grund für die anderen "not found" Probleme?

**Comment by gfacek** [comment]
@adieball Das habe ich mir auch gedacht

**Comment by do1osc** [comment]
Gibt es keine Lösung dafür ?

**Comment by DutchmanNL** [comment]
Man kan einfach den 8 stelligen Code (ohne Bindestrich!, der automatisch hinzugefügt wird so lassen!) und auf weiter klicken.

sonst könnte man ja auch keine bisherigen gekaufte Geräte in HomeKit hinzufügen

**Comment by DonLuigi1992** [comment]
Hat bei mir erst nach mehreren Versuchen funktioniert. Vorher wurde immer wieder angezeigt, dass der Code falsch wäre...

**Comment by do1osc** [comment]
Lösung des Problems:
- Bridge umbenennen
- Username umbenennen

dann geht es wieder.

**Comment by DutchmanNL** [comment]
> Hat bei mir erst nach mehreren Versuchen funktioniert. Vorher wurde immer wieder angezeigt, dass der Code falsch wäre...

Merkwürdig, habe die von mir beschriebene Lösung auf mehren Instanzen so einsetzen können, Basis ist das man wohl die Standard mac Adresse ändern sollte in einen persönlichen Wert sonst gehts meist schief (war aber schon immer so)

**Comment by Baenker** [comment]
Könnte man den Issue evtl schließen? Das „Problem“ ist ja keins und die Lösung wurde genannt
