### ISSUE TITLE
Fehlermeldung bei Installation

### ISSUE THREAD

**Issue by bytec77** [jensweigele/ioBroker.yahka#39]
Hallo, 

ich bekomme bei der Installation des Adapters Fehler angezeigt. Die Instanz zeigt zwar grün an aber ich wenn ich bei Service hinzufügen auf die drei Punkte klicke bekomme ich keine Auswahlliste der Geräte. 

Anbei den Konsolen Output:

`npm install https://github.com/jensweigele/ioBroker.yahka/tarball/master --production --prefix "/opt/iobroker"

authenticate-pam@1.0.2 install /opt/iobroker/node_modules/authenticate-pam
node-gyp rebuild

make: Verzeichnis „/opt/iobroker/node_modules/authenticate-pam/build“ wird betreten
  CXX(target) Release/obj.target/authenticate_pam/authenticate_pam.o
../authenticate_pam.cc:30:31: fatal error: security/pam_appl.h: Datei oder Verzeichnis nicht gefunden
 #include <security/pam_appl.h>
                               ^
compilation terminated.
authenticate_pam.target.mk:94: die Regel für Ziel „Release/obj.target/authenticate_pam/authenticate_pam.o“ scheiterte
make: *** [Release/obj.target/authenticate_pam/authenticate_pam.o] Fehler 1
make: Verzeichnis „/opt/iobroker/node_modules/authenticate-pam/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.0-3-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/authenticate-pam
gyp ERR! node -v v6.12.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
iobroker@1.0.0 /opt/iobroker
└─┬ iobroker.yahka@0.7.0 
  └─┬ debug@2.6.9 
    └── ms@2.0.0 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 (node_modules/authenticate-pam):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1`

**Comment by jensweigele** [comment]
Scheinbar fehlt dir das Paket "pam-devel".
Abhängig von deiner Linux Distri gibt es verschiedene Wege zur Installation.
apt-get install pam-devel
oder
yum install pam-devel

Ansonsten mal googlen wie du das installieren kannst. Anschließend den Adapter nochmal installieren!

**Comment by bytec77** [comment]
Danke jetzt läuft die Installation schonmal sauber durch.

Nach wie vor kann ich aber keine Geräte auswählen, wenn ich die drei Punkte drücke geht kein Fenster mit dem Auswahlmenü auf.

**Comment by bytec77** [comment]
Das bekomme ich angezeigt im LOG, wenn ich einen Service versuche hinzuzufügen und dann zu speichern. 



`

yahka.0 | 2018-02-08 19:59:30.029 | error | [On] could not create inout-function: ioBroker.State with params: undefined
-- | -- | -- | --
yahka.0 | 2018-02-08 19:59:30.028 | info | adding test with UUID: 93101509-6c6d-4299-a0cf-b078fe762444
yahka.0 | 2018-02-08 19:59:30.023 | info | adapter ready, checking config
yahka.0 | 2018-02-08 19:59:30.017 | info | starting. Version 0.7.0 in /opt/iobroker/node_modules/iobroker.yahka, node: v6.12.3
host.iobroker | 2018-02-08 19:59:29.574 | info | instance system.adapter.yahka.0 started with pid 21451
host.iobroker | 2018-02-08 19:59:27.104 | info | instance system.adapter.yahka.0 terminated with code 0 (OK)
Caught | 2018-02-08 19:59:27.104 | error | by controller[173]: Thu, 08 Feb 2018 18:59:27 GMT socket.io-parser encoded {'type':2,'data':['setState','system.adapter.yahka.0.alive',{'val':false,'ack':true,'from':'system.adapter.yahka.0'}],'options':{'compress':true},'id':4,'nsp':'/'} as 24['setState','system.adapter.yahka.0.alive',{'val':false,'ack':true,'from':'system.adapter.yahka.0'}]
Caught | 2018-02-08 19:59:27.104 | error | by controller[173]: Thu, 08 Feb 2018 18:59:27 GMT socket.io-parser encoding packet {'type':2,'data':['setState','system.adapter.yahka.0.alive',{'val':false,'ack':true,'from':'system.adapter.yahka.0'}],'options':{'compress':true},'id':4,'nsp':'/'}
Caught | 2018-02-08 19:59:27.104 | error | by controller[173]: Thu, 08 Feb 2018 18:59:27 GMT socket.io-client:manager writing packet {'type':2,'data':['setState','system.adapter.yahka.0.alive',{'val':false,'ack':true,'from':'system.adapter.yahka.0'}],'options':{'compress':true},'id':4,'nsp':'/'}
Caught | 2018-02-08 19:59:27.104 | error | by controller[173]: Thu, 08 Feb 2018 18:59:27 GMT socket.io-client:socket emitting packet with ack id 4
Caught | 2018-02-08 19:59:27.104 | error | by controller[172]: Thu, 08 Feb 2018 18:59:27 GMT socket.io-client:socket calling ack 3 with [null,'system.adapter.yahka.0.alive']
Caught | 2018-02-08 19:59:27.104 | error | by controller[172]: Thu, 08 Feb 2018 18:59:27 GMT socket.io-parser decoded 33[null,'system.adapter.yahka.0.alive'] as {'type':3,'nsp':'/','id':3,'data':[null,'system.adapter.yahka.0.alive']}
Caught | 2018-02-08 19:59:27.103 | error | by controller[172]: Thu, 08 Feb 2018 18:59:27 GMT engine.io-client:socket socket receive: type 'message', data '33[null,'system.adapter.yahka.0.alive']'
Caught | 2018-02-08 19:59:27.103 | error | by controller[172]: Thu, 08 Feb 2018 18:59:27 GMT engine.io-client:socket flushing 1 packets in socket
Caught | 2018-02-08 19:59:27.103 | error | by controller[171]: Thu, 08 Feb 2018 18:59:27 GMT socket.io-parser encoded {'type':2,'data':['pushLog','system.adapter.admin.0',{'message':'yahka.0 cleaned everything up...','severity':'info','from':'yahka.0','ts':1518116367069},null],'options':{'compress':true},'nsp':'/'} as 2['pushLog','system.adapter.admin.0',{'message':'yahka.0 cleaned everything up...','severity':'info','from':'yahka.0','ts':1518116367069},null]
Caught | 2018-02-08 19:59:27.103 | error | by controller[171]: Thu, 08 Feb 2018 18:59:27 GMT socket.io-parser encoding packet {'type':2,'data':['pushLog','system.adapter.admin.0',{'message':'yahka.0 cleaned everything up...','severity':'info','from':'yahka.0','ts':1518116367069},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.103 | error | by controller[171]: Thu, 08 Feb 2018 18:59:27 GMT socket.io-client:manager writing packet {'type':2,'data':['pushLog','system.adapter.admin.0',{'message':'yahka.0 cleaned everything up...','severity':'info','from':'yahka.0','ts':1518116367069},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.103 | error | by controller[171]: Thu, 08 Feb 2018 18:59:27 GMT engine.io-client:socket flushing 1 packets in socket
Caught | 2018-02-08 19:59:27.103 | error | by controller[171]: Thu, 08 Feb 2018 18:59:27 GMT socket.io-parser encoded {'type':2,'data':['setState','system.adapter.yahka.0.alive',{'val':false,'ack':true,'from':'system.adapter.yahka.0'}],'options':{'compress':true},'id':3,'nsp':'/'} as 23['setState','system.adapter.yahka.0.alive',{'val':false,'ack':true,'from':'system.adapter.yahka.0'}]
Caught | 2018-02-08 19:59:27.103 | error | by controller[171]: Thu, 08 Feb 2018 18:59:27 GMT socket.io-parser encoding packet {'type':2,'data':['setState','system.adapter.yahka.0.alive',{'val':false,'ack':true,'from':'system.adapter.yahka.0'}],'options':{'compress':true},'id':3,'nsp':'/'}
Caught | 2018-02-08 19:59:27.103 | error | by controller[171]: Thu, 08 Feb 2018 18:59:27 GMT socket.io-client:manager writing packet {'type':2,'data':['setState','system.adapter.yahka.0.alive',{'val':false,'ack':true,'from':'system.adapter.yahka.0'}],'options':{'compress':true},'id':3,'nsp':'/'}
Caught | 2018-02-08 19:59:27.103 | error | by controller[171]: Thu, 08 Feb 2018 18:59:27 GMT socket.io-client:socket emitting packet with ack id 3
Caught | 2018-02-08 19:59:27.103 | error | by controller[170]: Thu, 08 Feb 2018 18:59:19 GMT engine.io-client:socket flushing 2 packets in socket
Caught | 2018-02-08 19:59:27.103 | error | by controller[169]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoded {'type':2,'data':['pushLog','system.adapter.admin.0',{'message':'yahka.0 adding test with UUID: 93101509-6c6d-4299-a0cf-b078fe762444','severity':'info','from':'yahka.0','ts':1518116359376},null],'options':{'compress':true},'nsp':'/'} as 2['pushLog','system.adapter.admin.0',{'message':'yahka.0 adding test with UUID: 93101509-6c6d-4299-a0cf-b078fe762444','severity':'info','from':'yahka.0','ts':1518116359376},null]
Caught | 2018-02-08 19:59:27.103 | error | by controller[168]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoding packet {'type':2,'data':['pushLog','system.adapter.admin.0',{'message':'yahka.0 adding test with UUID: 93101509-6c6d-4299-a0cf-b078fe762444','severity':'info','from':'yahka.0','ts':1518116359376},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.103 | error | by controller[167]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:manager writing packet {'type':2,'data':['pushLog','system.adapter.admin.0',{'message':'yahka.0 adding test with UUID: 93101509-6c6d-4299-a0cf-b078fe762444','severity':'info','from':'yahka.0','ts':1518116359376},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.103 | error | by controller[166]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoded {'type':2,'data':['pushLog','system.adapter.admin.0',{'message':'yahka.0 adapter ready, checking config','severity':'info','from':'yahka.0','ts':1518116359376},null],'options':{'compress':true},'nsp':'/'} as 2['pushLog','system.adapter.admin.0',{'message':'yahka.0 adapter ready, checking config','severity':'info','from':'yahka.0','ts':1518116359376},null]
Caught | 2018-02-08 19:59:27.102 | error | by controller[165]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoding packet {'type':2,'data':['pushLog','system.adapter.admin.0',{'message':'yahka.0 adapter ready, checking config','severity':'info','from':'yahka.0','ts':1518116359376},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.102 | error | by controller[164]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:manager writing packet {'type':2,'data':['pushLog','system.adapter.admin.0',{'message':'yahka.0 adapter ready, checking config','severity':'info','from':'yahka.0','ts':1518116359376},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.102 | error | by controller[163]: Thu, 08 Feb 2018 18:59:19 GMT engine.io-client:socket flushing 1 packets in socket
Caught | 2018-02-08 19:59:27.102 | error | by controller[162]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoded {'type':2,'data':['pushLog','system.adapter.admin.0',{'message':'yahka.0 starting. Version 0.7.0 in /opt/iobroker/node_modules/iobroker.yahka, node: v6.12.3','severity':'info','from':'yahka.0','ts':1518116359374},null],'options':{'compress':true},'nsp':'/'} as 2['pushLog','system.adapter.admin.0',{'message':'yahka.0 starting. Version 0.7.0 in /opt/iobroker/node_modules/iobroker.yahka, node: v6.12.3','severity':'info','from':'yahka.0','ts':1518116359374},null]
Caught | 2018-02-08 19:59:27.102 | error | by controller[161]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoding packet {'type':2,'data':['pushLog','system.adapter.admin.0',{'message':'yahka.0 starting. Version 0.7.0 in /opt/iobroker/node_modules/iobroker.yahka, node: v6.12.3','severity':'info','from':'yahka.0','ts':1518116359374},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.102 | error | by controller[160]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:manager writing packet {'type':2,'data':['pushLog','system.adapter.admin.0',{'message':'yahka.0 starting. Version 0.7.0 in /opt/iobroker/node_modules/iobroker.yahka, node: v6.12.3','severity':'info','from':'yahka.0','ts':1518116359374},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.102 | error | by controller[159]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:socket calling ack 2 with [null,[{'val':true,'ack':true,'ts':1518112073812,'q':0,'from':'system.adapter.admin.0','lc':1518112073812}]]
Caught | 2018-02-08 19:59:27.102 | error | by controller[158]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser decoded 32[null,[{'val':true,'ack':true,'ts':1518112073812,'q':0,'from':'system.adapter.admin.0','lc':1518112073812}]] as {'type':3,'nsp':'/','id':2,'data':[null,[{'val':true,'ack':true,'ts':1518112073812,'q':0,'from':'system.adapter.admin.0','lc':1518112073812}]]}
Caught | 2018-02-08 19:59:27.102 | error | by controller[157]: Thu, 08 Feb 2018 18:59:19 GMT engine.io-client:socket socket receive: type 'message', data '32[null,[{'val':true,'ack':true,'ts':1518112073812,'q':0,'from':'system.adapter.admin.0','lc':1518112073812}]]'
Caught | 2018-02-08 19:59:27.102 | error | by controller[156]: Thu, 08 Feb 2018 18:59:19 GMT engine.io-client:socket flushing 1 packets in socket
Caught | 2018-02-08 19:59:27.102 | error | by controller[155]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoded {'type':2,'data':['getStates',['system.adapter.admin.0.logging']],'options':{'compress':true},'id':2,'nsp':'/'} as 22['getStates',['system.adapter.admin.0.logging']]
Caught | 2018-02-08 19:59:27.102 | error | by controller[154]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoding packet {'type':2,'data':['getStates',['system.adapter.admin.0.logging']],'options':{'compress':true},'id':2,'nsp':'/'}
Caught | 2018-02-08 19:59:27.102 | error | by controller[153]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:manager writing packet {'type':2,'data':['getStates',['system.adapter.admin.0.logging']],'options':{'compress':true},'id':2,'nsp':'/'}
Caught | 2018-02-08 19:59:27.102 | error | by controller[152]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:socket emitting packet with ack id 2
Caught | 2018-02-08 19:59:27.102 | error | by controller[151]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:socket calling ack 1 with [null,['system.adapter.admin.0.logging']]
Caught | 2018-02-08 19:59:27.101 | error | by controller[150]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser decoded 31[null,['system.adapter.admin.0.logging']] as {'type':3,'nsp':'/','id':1,'data':[null,['system.adapter.admin.0.logging']]}
Caught | 2018-02-08 19:59:27.101 | error | by controller[149]: Thu, 08 Feb 2018 18:59:19 GMT engine.io-client:socket socket receive: type 'message', data '31[null,['system.adapter.admin.0.logging']]'
Caught | 2018-02-08 19:59:27.101 | error | by controller[148]: Thu, 08 Feb 2018 18:59:19 GMT engine.io-client:socket flushing 10 packets in socket
Caught | 2018-02-08 19:59:27.101 | error | by controller[147]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoded {'type':2,'data':['subscribe','yahka.0.checkLogging',null],'options':{'compress':true},'nsp':'/'} as 2['subscribe','yahka.0.checkLogging',null]
Caught | 2018-02-08 19:59:27.101 | error | by controller[146]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoding packet {'type':2,'data':['subscribe','yahka.0.checkLogging',null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.101 | error | by controller[145]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:manager writing packet {'type':2,'data':['subscribe','yahka.0.checkLogging',null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.101 | error | by controller[144]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoded {'type':2,'data':['setState','system.adapter.yahka.0.outputCount',{'val':8,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'} as 2['setState','system.adapter.yahka.0.outputCount',{'val':8,'ack':true,'from':'system.adapter.yahka.0'},null]
Caught | 2018-02-08 19:59:27.101 | error | by controller[143]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoding packet {'type':2,'data':['setState','system.adapter.yahka.0.outputCount',{'val':8,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.101 | error | by controller[142]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:manager writing packet {'type':2,'data':['setState','system.adapter.yahka.0.outputCount',{'val':8,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.101 | error | by controller[141]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoded {'type':2,'data':['setState','system.adapter.yahka.0.inputCount',{'val':0,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'} as 2['setState','system.adapter.yahka.0.inputCount',{'val':0,'ack':true,'from':'system.adapter.yahka.0'},null]
Caught | 2018-02-08 19:59:27.101 | error | by controller[140]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoding packet {'type':2,'data':['setState','system.adapter.yahka.0.inputCount',{'val':0,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.101 | error | by controller[139]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:manager writing packet {'type':2,'data':['setState','system.adapter.yahka.0.inputCount',{'val':0,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.101 | error | by controller[138]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoded {'type':2,'data':['setState','system.adapter.yahka.0.uptime',{'val':0,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'} as 2['setState','system.adapter.yahka.0.uptime',{'val':0,'ack':true,'from':'system.adapter.yahka.0'},null]
Caught | 2018-02-08 19:59:27.100 | error | by controller[137]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoding packet {'type':2,'data':['setState','system.adapter.yahka.0.uptime',{'val':0,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.100 | error | by controller[136]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:manager writing packet {'type':2,'data':['setState','system.adapter.yahka.0.uptime',{'val':0,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.100 | error | by controller[135]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoded {'type':2,'data':['setState','system.adapter.yahka.0.memHeapUsed',{'val':15.33,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'} as 2['setState','system.adapter.yahka.0.memHeapUsed',{'val':15.33,'ack':true,'from':'system.adapter.yahka.0'},null]
Caught | 2018-02-08 19:59:27.100 | error | by controller[134]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoding packet {'type':2,'data':['setState','system.adapter.yahka.0.memHeapUsed',{'val':15.33,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.100 | error | by controller[133]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:manager writing packet {'type':2,'data':['setState','system.adapter.yahka.0.memHeapUsed',{'val':15.33,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.100 | error | by controller[132]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoded {'type':2,'data':['setState','system.adapter.yahka.0.memHeapTotal',{'val':22.03,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'} as 2['setState','system.adapter.yahka.0.memHeapTotal',{'val':22.03,'ack':true,'from':'system.adapter.yahka.0'},null]
Caught | 2018-02-08 19:59:27.100 | error | by controller[131]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoding packet {'type':2,'data':['setState','system.adapter.yahka.0.memHeapTotal',{'val':22.03,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.100 | error | by controller[130]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:manager writing packet {'type':2,'data':['setState','system.adapter.yahka.0.memHeapTotal',{'val':22.03,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.100 | error | by controller[129]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoded {'type':2,'data':['setState','system.adapter.yahka.0.memRss',{'val':44.55,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'} as 2['setState','system.adapter.yahka.0.memRss',{'val':44.55,'ack':true,'from':'system.adapter.yahka.0'},null]
Caught | 2018-02-08 19:59:27.100 | error | by controller[128]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoding packet {'type':2,'data':['setState','system.adapter.yahka.0.memRss',{'val':44.55,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.100 | error | by controller[127]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:manager writing packet {'type':2,'data':['setState','system.adapter.yahka.0.memRss',{'val':44.55,'ack':true,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.100 | error | by controller[126]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoded {'type':2,'data':['setState','system.adapter.yahka.0.connected',{'val':true,'ack':true,'expire':30,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'} as 2['setState','system.adapter.yahka.0.connected',{'val':true,'ack':true,'expire':30,'from':'system.adapter.yahka.0'},null]
Caught | 2018-02-08 19:59:27.100 | error | by controller[125]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoding packet {'type':2,'data':['setState','system.adapter.yahka.0.connected',{'val':true,'ack':true,'expire':30,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.100 | error | by controller[124]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:manager writing packet {'type':2,'data':['setState','system.adapter.yahka.0.connected',{'val':true,'ack':true,'expire':30,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.100 | error | by controller[123]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoded {'type':2,'data':['setState','system.adapter.yahka.0.alive',{'val':true,'ack':true,'expire':30,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'} as 2['setState','system.adapter.yahka.0.alive',{'val':true,'ack':true,'expire':30,'from':'system.adapter.yahka.0'},null]
Caught | 2018-02-08 19:59:27.099 | error | by controller[122]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoding packet {'type':2,'data':['setState','system.adapter.yahka.0.alive',{'val':true,'ack':true,'expire':30,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.099 | error | by controller[121]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:manager writing packet {'type':2,'data':['setState','system.adapter.yahka.0.alive',{'val':true,'ack':true,'expire':30,'from':'system.adapter.yahka.0'},null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.099 | error | by controller[120]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoded {'type':2,'data':['subscribe','*.logging',null],'options':{'compress':true},'nsp':'/'} as 2['subscribe','*.logging',null]
Caught | 2018-02-08 19:59:27.099 | error | by controller[119]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoding packet {'type':2,'data':['subscribe','*.logging',null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.099 | error | by controller[118]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:manager writing packet {'type':2,'data':['subscribe','*.logging',null],'options':{'compress':true},'nsp':'/'}
Caught | 2018-02-08 19:59:27.099 | error | by controller[117]: Thu, 08 Feb 2018 18:59:19 GMT engine.io-client:socket flushing 1 packets in socket
Caught | 2018-02-08 19:59:27.099 | error | by controller[116]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoded {'type':2,'data':['getKeys','*.logging'],'options':{'compress':true},'id':1,'nsp':'/'} as 21['getKeys','*.logging']
Caught | 2018-02-08 19:59:27.099 | error | by controller[115]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-parser encoding packet {'type':2,'data':['getKeys','*.logging'],'options':{'compress':true},'id':1,'nsp':'/'}
Caught | 2018-02-08 19:59:27.099 | error | by controller[114]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:manager writing packet {'type':2,'data':['getKeys','*.logging'],'options':{'compress':true},'id':1,'nsp':'/'}
Caught | 2018-02-08 19:59:27.099 | error | by controller[113]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:socket emitting packet with ack id 1
Caught | 2018-02-08 19:59:27.099 | error | by controller[112]: Thu, 08 Feb 2018 18:59:19 GMT socket.io-client:socket calling ack 0 with [null,{'_id':'system.adapter.yahka.0','type':'instance','common':{'name':'yahka','version':'0.7.0','news':{'0.7.0':{'en':'Fixed the ID select dialog in Admin3, added new services and fixed some other bugs','de':'Der ID-Auswahldialog in Admin3 wurde korrigiert, neue Dienste hinzugefügt und kleinere Fehler behoben','ru':'Исправлено диалоговое окно выбора идентификатора в Admin3','pt':'Corrigido o diálogo de seleção de ID em Admin3','nl':'Vaste het ID selectiedialoog in Admin3','fr':'Correction du dialogue de sélection d'ID dans Admin3','it':'Risolta la finestra di dialogo di selezione dell'ID in Admin3','es':'Se corrigió el diálogo de selección de ID en Admin3','pl':'Naprawiono okno dialogowe wyboru identyfikatora w Admin3'},'0.6.1':{'en':'Fixed a bug which prevent Yahka from Start','de':'Fixed a bug which prevent Yahka from Start','ru':'Fixed a bug which prevent Yahka from Start'},'0.6.0':{'en':'Support for IP-Cameras','de':'Support für IP-Kameras','ru':'Поддержка IP-Камер'},'0.5.5':{'en':'Make a config dialog bigger','de':'Config-Dialog ist vergrößert','ru':'Увеличен размер окна настроек'}},'title':'Homekit','desc':{'en':'yet another Homekit adapter','de':'noch ein weiterer Homekit-Adapter','ru':'Homekit драйвер','pt':'ainda outro adaptador Homekit','nl':'nog een andere Homekit-adapter','fr':'encore un autre adaptateur Homekit','it':'ancora un altro adattatore Homekit','es':'otro adaptador para el Homekit','pl':'kolejny adapter Homekit'},'platform':'Javascript/Node.js','mode':'daemon','icon':'yahka.png','enabled':true,'extIcon':'https://raw.githubusercontent.com/jensweigele/ioBroker.yahka/master/admin/yahka.png','keywords':['homekit','siri'],'readme':'https://github.com/jensweigele/ioBroker.yahka/blob/master/README.md','loglevel':'info','type':'iot-systems','materialize':true,'config':{'minWidth':800,'width ':1440,'minHeight':600,'height ':860},'authors':[{'name':'Jens Weigele','email':'iobroker.yahka@gmail.com'}],'installedVersion':'0.7.0','host':'iobroker'},'native':{'firstTimeInitialized':true,'bridge':{'devices':[{'configType':'customdevice','manufacturer':'','model':'','name':'test','serial':'','enabled':true,'category':'8','services':[{'name':'test','subType':'','type':'Switch','characteristics':[{'name':'On','enabled':true}]}]}],'ident':':yahka.0','name':':yahka.0','serial':':yahka.0','username':'de:b7:5e:8f:6e:6c','pincode':'123-45-678','port':0,'verboseLogging':false,'configType':'bridge'},'cameras':[]},'acl':{'object':1636}}]

`

**Comment by bytec77** [comment]
Ich habe jetzt mal die 0.6.1 installiert und mit dieser Version funktioniert es. Das Auswahlmenü der Objekte klappt wie erwartend auf. 
Aber warum es nicht mit der 0.7 geht habe ich noch nicht rausgefunden.

**Comment by jensweigele** [comment]
Welche Admin Version hast du drauf?

**Comment by bytec77** [comment]
Ich habe die 2.09 drauf.

**Comment by jensweigele** [comment]
mit 0.7.1 sollte die Auswahl wieder funktionieren (gerade released)
