### ISSUE TITLE
Gerät kann nicht hinzugefügt werden

### ISSUE THREAD

**Issue by dssp007** [jensweigele/ioBroker.yahka#393]
Leider lässt sich yahka aktuell nicht als neue Bridge in Homekit einfügen.
Gerätepin wird tadellos gefressen danach ca. 3 min warten dann die Meldung, dass das Gerät nicht hinzugefügt werden kann, da Gerät nicht erreichbar.

**Comment by gfacek** [comment]
Ich hatte bei mir das gleiche Problem. Da ich ohnehin auf etwas schneller Hardware umziehen wollte, habe ich das gemacht. Anschließend konnte ich wieder yahka wieder mit Homekit verbinden. #387

**Comment by dssp007** [comment]
Also ich hab jetzt die Tage selbst noch einmal verschiedene Dinge versucht. Nachdem ich den Adapter, komplett deinstalliert und ihn wieder installiert hatte (2 mal) hat es heute funktioniert. Woran es jetzt genau lag kann ich leider  nicht sagen.
