### ISSUE TITLE
Nach Update auf node.js 18.15.0 keine Verbindung zur Bridge in Apple Home App

### ISSUE THREAD

**Issue by invidianer** [jensweigele/ioBroker.yahka#406]
Nach Update auf node.js 18.15.0 neue YAHKA-Instanz (yahka.1) erstellt, kann diese (Bridge) aber in Apple Home App nicht hinzufügen ("Gerät nicht erreichbar"). Außerdem sind alle mit der "alten" Instanz (yahka.0) erstellten Geräte "nicht erreichbar" in der Apple Home App.
Nach Downgrade auf node.js 16.19.1 funktioniert alles wieder!

**Comment by Grothesk242** [comment]
Duplicate
https://github.com/jensweigele/ioBroker.yahka/issues/403

**Comment by invidianer** [comment]
Did not see! Sorry! Can be closed.
