### ISSUE TITLE
Yahka v1.0.2 update

### ISSUE THREAD

**Issue by JogiBarbarski** [jensweigele/ioBroker.yahka#415]
Mein System: Raspberry Pi 4, 8 GB, 64Bit Debian Bullseye ioBroker.admin v6.4.1 Node.js: v18.15.0 NPM: 9.5.0 js-Controller JS-Controller Installiert: 4.0.24 Betriebssystem: Linux NEUESTE auf SSD 1 TB
Habe heute das Update durchgeführt auf v1.0.2 und im Adapter war nichts mehr an Geräten zu sehen. In HomeKit läuft wohl noch alles. Habe Adapter neu gestartet , ohne Erfolg. Im Yahka Adapter wird mir Speichen Speichern/schließen angezeigt . Weiß nicht was passiert wenn ich auf Speichen drücke. Nicht das es dann nicht mehr geht.

**Comment by JogiBarbarski** [comment]
Bin wieder zurück gegangen auf v0.17.0. Unter v0.17.0 ist wieder alles da.

**Comment by MacPro-de** [comment]
Hier das selbe Problem.

**Comment by MINKI1985** [comment]
Wird auch [hier](https://github.com/jensweigele/ioBroker.yahka/issues/412) bereits besprochen. Ich verlinke das mal...

**Comment by ticaki** [comment]
> Wird auch [hier](https://github.com/jensweigele/ioBroker.yahka/issues/412) bereits besprochen. Ich verlinke das mal...

Das hier betrifft jedoch nicht die Version 0.17 (die macht bei mir keine Probleme) sondern 1.0.2

**Comment by MINKI1985** [comment]
> > Wird auch [hier](https://github.com/jensweigele/ioBroker.yahka/issues/412) bereits besprochen. Ich verlinke das mal...
> 
> Das hier betrifft jedoch nicht die Version 0.17 (die macht bei mir keine Probleme) sondern 1.0.2

Titel ist irreführend. Aber es geht genau um dieses Thema hier. Ich habe es nur mal verlinkt.

**Comment by ManuZz80** [comment]
selbes Problem, keine Geräte mehr angezeigt, aber alles funktioniert - trotzdem doof :)

**Comment by jpawlowski** [comment]
Was ist mit https://github.com/jensweigele/ioBroker.yahka/pull/416, behebt der das Problem und man müsste ihn nur akzeptieren, um eine Version 1.0.3 als Fix auszurollen?

**Comment by TDCroPower** [comment]
Version 1.0.3 ist draus mit enthaltenem PR von TA2K!

**Comment by JogiBarbarski** [comment]
Ihr seit perfekt. Es geht alles und man sieht alles mit v1.0.3. Herzlichen Dank.

**Comment by JogiBarbarski** [comment]
Danke
