### ISSUE TITLE
Enhance Documentation ...

### ISSUE THREAD

**Issue by Apollon77** [jensweigele/ioBroker.yahka#42]
see Forum: http://forum.iobroker.net/viewtopic.php?p=125255#p125241

maybe an idea to enhance infos for Windows user ?!

**Comment by nicoh88** [comment]
@Apollon77:

Findest du den alten Post im Forum noch? Der Link geht nicht mehr.
Bist du Windows-User? Kannst du was im "Wiki" dokumentieren?

Gruß Nico

**Comment by Apollon77** [comment]
dann leider "kaputt" un nein ich bin kein Windows user
