### ISSUE TITLE
Verbindung Fehlgeschlagen

### ISSUE THREAD

**Issue by agentur81** [jensweigele/ioBroker.yahka#426]
Hallo zusammen!

Ich bin neu mit iobroker und bekomme die Verbindung zu HomeKit nicht hin.

- Iobroker auf raspi 4
- Steuerzentrale auf HomePod Mini
- Yakah Version 0.17
- Sonstige Adapter: JavaScript & HomePilot 2.0

Es ist ein frisch aufgesetztes System, daher alles aktuell…

Ich komm im HomeKit bis zur Codeabfrage (falscher Code wird festgestellt).

Dann kommt immer „Verbindung fehlgeschlagen - es ist ein Fehler aufgetreten“ …

Habe schon alle Konfigurationsmöglichkeiten getestet (anderer Benutzername, Mac-Adresse des Raspi, usw…)

wäre im jede Hilfe dankbar!

Tobias

**Comment by 01findus** [comment]
Hallo Guten Abend, habe das gleiche Problem:

Bei der Eingabe wird der Code nicht akzeptiert.

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/22724681/232254791-d0a518e4-407b-4037-bf17-f65fafd4df47.png">


Apple Gerate auf IOS 16.4.1:
Yakah Version v0.17.0
IOBroker Version: v6.3.5
raspi 4 Version: 
iobroker@iobroker:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian

Beste Grüße
Alexander

**Comment by 01findus** [comment]
So jetzt bin ich weiter gekommen:

Lösung:

1. Update auf latest Version über Linux level oder IOBroker Terminal:

`iobroker@iobroker:/var/log $ iobroker upgrade yahka@1.0.3
BE CAREFUL: THIS IS A MAJOR UPGRADE, WHICH WILL MOST LIKELY INTRODUCE BREAKING CHANGES!
Would you like to upgrade yahka from @0.17.0 to @1.0.3 now? [(y)es, (n)o]: y
Update yahka from @0.17.0 to @1.0.3
NPM version: 8.19.3
Installing iobroker.yahka@1.0.3... (System call)

changed 3 packages in 17s
`

2. Den Pincode in den Instanzeinstellungen: yahka.0  wirklich stumpf eingeben wie es in Beispiel steht als "123-45-678" und beim hinzufügen in der Homeapp einfach tippen auch wenn die Bindestriche anders angezeigt werden.

--> Dann ging es bei mir.

**Comment by agentur81** [comment]
> So jetzt bin ich weiter gekommen:
> 
> Lösung:
> 
> 1. Update auf latest Version über Linux level oder IOBroker Terminal:
> 
> `iobroker@iobroker:/var/log $ iobroker upgrade yahka@1.0.3 BE CAREFUL: THIS IS A MAJOR UPGRADE, WHICH WILL MOST LIKELY INTRODUCE BREAKING CHANGES! Would you like to upgrade yahka from @0.17.0 to @1.0.3 now? [(y)es, (n)o]: y Update yahka from @0.17.0 to @1.0.3 NPM version: 8.19.3 Installing iobroker.yahka@1.0.3... (System call)
> 
> changed 3 packages in 17s `
> 
> 2. Den Pincode in den Instanzeinstellungen: yahka.0  wirklich stumpf eingeben wie es in Beispiel steht als "[123-45-678](tel:123-45-678)" und beim hinzufügen in der Homeapp einfach tippen auch wenn die Bindestriche anders angezeigt werden.
> 
> --> Dann ging es bei mir.

Perfekt! Hat zwar zwei drei Anläufe gebraucht? Hat aber dann einwandfrei funktioniert! 

Danke dir!
