### ISSUE TITLE
Geräte in AppleWatch ohne Funktion "not configured"

### ISSUE THREAD

**Issue by bierking** [jensweigele/ioBroker.yahka#427]
Hallo,
die Homekit App der AppleWatch zeigt keine Geräte mehr "not configured nicht verfügbar" obwohl es in iOS und MacOS funktioniert. Ich kann momentan nicht beurteilen ob es ggf. auch daran liegt, dass seit iOS 16 nur noch Homepods und AppleTVs als Zentrale zulässig sind und ich aktuell ohne Zentrale unterwegs bin. Legacy oder CIAO sowie der Reset der Uhr (Cache löschen und neu ziehen der Daten aus der iCloud) machen keinen Unterschied. 

Versions:
iOS 16.4.1
Watch OS 9.5
Adapter version: 1.0.3
JS-Controller version: 4.0.24
Node version: 18.16.0
NPM 9.5.0
Operating system: Debian 11 x64

**Comment by delta2308151984** [comment]
Moin, ist zwar schon älter der Thread aber ich habe aktuell das gleiche Problem. Hast du eine Lösung gefunden?

**Comment by WurstwasserFabi** [comment]
Ich habe es immer wieder kurzzeitig hinbekommen. Ich habe in der Apple Watch den Cache Speicher gelöscht und die Daten aus Apple Home neu gezogen. Allerdings klappte es nach wenigen malen wieder nicht mehr. Ich hatte irgendwann keinen Nerv mehr dafür und auch Probleme mit meiner besseren Hälfte. Abhilfe hat bei mir der Apple TV geschaffen. Alternativ würde ein HomePod Abhilfe schaffen.

**Comment by Baenker** [comment]
Könnte man den Issue schließen? Das Problem hat ja nun nicht mit Yahka zu tun. Der Adapter zeigt ja auf anderen Geräten die Geräte und funktioniert.
