### ISSUE TITLE
Allow to set min values for scaleInt and scaleFloat

### ISSUE THREAD

**Issue by mdietz666** [jensweigele/ioBroker.yahka#43]
Some functions are not ranged starting from 0, e.g. in HomeKit the TargetHorizontalTiltAngle for WindowCoverings, it is from -90 to 90.
The current implementation is assuming to always start from 0, so it would be good to have a min and max value setting for homeKit and ioBroker values.

**Comment by jensweigele** [comment]
I merged your pull request with some minor adaptions (-> develop branch)
