### ISSUE TITLE
Family Sharing funktioniert nicht

### ISSUE THREAD

**Issue by merasil** [jensweigele/ioBroker.yahka#437]
Hi,

ich weiß nicht ob ich zu blöd bin, aber früher hatte ich mit FHEM und dem Homebridge-Modul ein "Zuhause" erstellen und dieses mit meiner Frau per Familienfreigabe teilen können. Seit meinem Umstieg auf iobroker und yahka funktioniert das nicht mehr (ich bekomme die Option zum sharen gar nicht angezeigt)...  In den Homekit-Einstellungen auf dem iPhone steht, dass man für diese Funktion eine Homekit-Zentrale bräuchte, was yahka meines Wissens nach nicht ist.
Meine aktuelle Lösung sind einfach zwei yahka adapter in denen ich alles doppelt pflegen muss. Was mache ich falsch?

**Comment by ManuelW77** [comment]
Deine HomeKit Zentrale ist zB ein HomePod, Apple TV etc.
 Das hat mit iobroker und yahka nichts zu tun.

**Comment by merasil** [comment]
ja war mir nicht bewusst. Früher konnte das iPad noch die Zentrale sein. Das geht jetzt nicht mehr... zumindest mit unserem iPad mini nicht. Hab mir einen Apple TV gekauft und siehe da: ich kann wieder sharen etc. Danke!
