### ISSUE TITLE
Installationsfehler

### ISSUE THREAD

**Issue by smilois** [jensweigele/ioBroker.yahka#45]
Moin,

ich erhalte bei der Installation des Adapters nachstehende Fehlermeldung. Was kann/muss ich tun um die Installation durchzuführen?

$ ./iobroker add yahka
npm install iobroker.yahka --production --prefix "C:/ioBroker" (System call)
gyp
 
ERR!
 
configure error
 gyp
 ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.gyp ERR!
 stack
     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! 
stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! 
stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp 
ERR!
 System Windows_NT 10.0.16299
gyp
 
ERR!
 
command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\curve25519-n2gyp ERR! node -v v4.5.0
gyp ERR!
 node-gyp -v v3.4.0gyp ERR! not ok 

gyp
 
ERR! configure error
 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.gyp ERR!
 
stack
     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)gyp
 ERR!
 stack
     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR!
 stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp
 ERR! System Windows_NT 10.0.16299
gyp 
ERR! 
command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"gyp ERR! cwd
 C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\ed25519
gyp ERR! node -v v4.5.0gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
 
gyp
 
ERR!
 
configure error
 
gyp
 ERR! 
stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp
 ERR!
 
stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp 
ERR! 
stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.16299gyp
 ERR! 
command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"gyp
 
ERR! cwd
 C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\mdnsgyp ERR! node -v v4.5.0
gyp
 ERR! node-gyp -v v3.4.0gyp 
ERR! not ok 
npm
 
ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iobroker.yahka" "--production" "--prefix" "C:/ioBroker"
npm ERR! node v4.5.0npm 
ERR! npm  v2.15.9npm 
ERR! code ELIFECYCLE

npm ERR! curve25519-n2@1.1.3 install: `node-gyp rebuild`npm ERR! Exit status 1

npm ERR!
 npm ERR! Failed at the curve25519-n2@1.1.3 install script 'node-gyp rebuild'.

npm ERR! This is most likely a problem with the curve25519-n2 package,npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs curve25519-n2npm 
ERR! Or if that isn't available, you can get their info via:npm ERR! 
npm ERR!     npm owner ls curve25519-n2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:npm ERR!     C:\ioBroker\node_modules\iobroker\npm-debug.log

host.VISU install adapter yahka
npm install iobroker.yahka --production --prefix "C:/ioBroker" (System call)
gyp
 
ERR!
 
configure error
 
gyp
 
ERR! 
stack Error: Can't find Python executable "python", you can set the PYTHON env variable.gyp
 ERR!
 stack
     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)gyp ERR!
 
stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11gyp ERR! 
stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.16299
gyp
 ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\curve25519-n2gyp ERR! node -v v4.5.0
gyp ERR!
 node-gyp -v v3.4.0
gyp ERR! not ok 
gyp
 
ERR!
 
configure error
 
gyp
 ERR!
 stack Error: Can't find Python executable "python", you can set the PYTHON env variable.gyp
 ERR!
 
stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)gyp ERR!
 stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! 
stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp 
ERR! System Windows_NT 10.0.16299
gyp ERR!
 command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"gyp 
ERR! 
cwd
 C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\ed25519
gyp
 ERR! node -v v4.5.0gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

gyp
 
ERR! 
configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp
 ERR! stack
     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp
 ERR! 
stack
     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp
 ERR!
 
stack     at FSReqWrap.oncomplete (fs.js:82:15)gyp
 ERR!
 
System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"gyp 
ERR! cwd C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\mdnsgyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm
 
ERR!
 Windows_NT 10.0.16299
npm ERR!
 argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iobroker.yahka" "--production" "--prefix" "C:/ioBroker"
npm ERR! node v4.5.0npm
 ERR! npm  v2.15.9npm ERR! code
 ELIFECYCLE
npm ERR! curve25519-n2@1.1.3 install: `node-gyp rebuild`
npm ERR!
 Exit status 1
npm
 
ERR!
 npm ERR! Failed at the curve25519-n2@1.1.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the curve25519-n2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm
 
ERR!     npm bugs curve25519-n2npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls curve25519-n2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:npm 
ERR!     C:\ioBroker\node_modules\iobroker\npm-debug.log
host.VISU install adapter yahka
npm install iobroker.yahka --production --prefix "C:/ioBroker" (System call)
gyp
 
ERR!
 
configure error
 
gyp
 ERR!
 stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR!
 
stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)gyp
 
ERR! 
stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)

gyp ERR! System Windows_NT 10.0.16299gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"

gyp ERR! cwd C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\curve25519-n2gyp ERR! node -v v4.5.0
gyp ERR! 
node-gyp -v v3.4.0gyp ERR! not ok 

gyp
 
ERR!
 
configure error 
gyp
 ERR! 
stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp
 
ERR!
 
stack
     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp
 ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)

gyp ERR! 
System Windows_NT 10.0.16299gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\ed25519
gyp ERR! node -v
 v4.5.0gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

gyp
 
ERR!
 configure error
 
gyp
 ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR!
 
stack
     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)gyp
 
ERR! 
stack
     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11gyp 
ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! 
System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\mdnsgyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm
 
ERR!
 Windows_NT 10.0.16299
npm
 
ERR! argv
 "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iobroker.yahka" "--production" "--prefix" "C:/ioBroker"npm ERR! 
node
 v4.5.0npm
 ERR! 
npm  v2.15.9
npm
 
ERR! code
 ELIFECYCLE

npm ERR! curve25519-n2@1.1.3 install: `node-gyp rebuild`npm 
ERR!
 Exit status 1
npm
 ERR! npm 
ERR! Failed at the curve25519-n2@1.1.3 install script 'node-gyp rebuild'.
npm
 ERR! This is most likely a problem with the curve25519-n2 package,
npm ERR! not with npm itself.npm ERR! Tell the author that this fails on your system:
npm
 
ERR!
     node-gyp rebuildnpm ERR!
 You can get information on how to open an issue for this project with:npm ERR!
     npm bugs curve25519-n2npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls curve25519-n2
npm 
ERR! There is likely additional logging output above.

npm 
ERR! Please include the following file with any support request:
npm ERR!
     C:\ioBroker\node_modules\iobroker\npm-debug.log
host.VISU install adapter yahka
ERROR: host.VISU Cannot install yahka
ERROR: process exited with code 13

**Comment by eumats** [comment]
Das steht gleich vorne im Log:
[...]
Can't find Python executable "python", you can set the PYTHON env variable.gyp ERR!
[...]

-> google: python windows installieren

**Comment by smilois** [comment]
Moin,
Python ist jetzt wieder drauf, Kernfehler bleibt. NODE Version 4.5 auch drauf.
Log jetzt wie folgt:

$ ./iobroker add yahka
npm install iobroker.yahka --production --prefix "C:/ioBroker" (System call)
gyp
 ERR! build error gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR!
 
stack
     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp
 
ERR! System
 Windows_NT 10.0.16299
gyp
 ERR! 
command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp
 ERR! cwd
 C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\curve25519-n2gyp
 
ERR!
 node -v v4.5.0gyp ERR! node-gyp -v v3.4.0
gyp
 ERR! not ok 
gyp
 
ERR! build error
 gyp
 ERR!
 
stack
 Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp
 
ERR!
 
stack
     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp 
ERR!
 
stack     at emitTwo (events.js:87:13)
gyp ERR!
 
stack     at ChildProcess.emit (events.js:172:7)gyp 
ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.16299gyp
 ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"gyp ERR! cwd C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\ed25519
gyp ERR! node -v v4.5.0

gyp ERR! node-gyp -v v3.4.0gyp ERR! not ok 

gyp
 
ERR!
 build error
 
gyp
 ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp
 
ERR!
 
stack
     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)gyp
 ERR!
 stack
     at emitTwo (events.js:87:13)gyp
 ERR! stack     at ChildProcess.emit (events.js:172:7)gyp
 ERR! 
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp 
ERR! System Windows_NT 10.0.16299gyp 
ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\mdnsgyp 
ERR! node -v
 v4.5.0gyp ERR!
 node-gyp -v v3.4.0gyp ERR!
 not ok 
npm
 
ERR!
 Windows_NT 10.0.16299
npm ERR!
 argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iobroker.yahka" "--production" "--prefix" "C:/ioBroker"npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! curve25519-n2@1.1.3 install: `node-gyp rebuild`
npm
 ERR! Exit status 1npm 
ERR! npm ERR!
 Failed at the curve25519-n2@1.1.3 install script 'node-gyp rebuild'.npm 
ERR! This is most likely a problem with the curve25519-n2 package,npm 
ERR! not with npm itself.npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm 
ERR!
     npm bugs curve25519-n2npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls curve25519-n2
npm 
ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:npm 
ERR!     C:\ioBroker\node_modules\iobroker\npm-debug.log
host.VISU install adapter yahka
npm install iobroker.yahka --production --prefix "C:/ioBroker" (System call)
gyp
 
ERR! build error 
gyp
 ERR! stack
 Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp
 
ERR! 
stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)gyp
 ERR!
 
stack
     at emitTwo (events.js:87:13)
gyp 
ERR! stack
     at ChildProcess.emit (events.js:172:7)gyp 
ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)gyp
 
ERR! System Windows_NT 10.0.16299
gyp ERR! command
 "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"gyp ERR! cwd C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\curve25519-n2
gyp 
ERR! node -v v4.5.0gyp
 ERR! node-gyp -v v3.4.0gyp ERR! not ok 

gyp
 
ERR! 
build error 
gyp
 ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)gyp ERR!
 stack     at emitTwo (events.js:87:13)gyp ERR! 
stack     at ChildProcess.emit (events.js:172:7)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.16299

gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"gyp ERR! 
cwd
 C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\ed25519
gyp 
ERR! node -v
 v4.5.0gyp ERR! node-gyp -v v3.4.0
gyp
 ERR!
 not ok 
gyp
 ERR! build error 
gyp 
ERR!
 
stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp
 ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

gyp
 
ERR!
 
System
 Windows_NT 10.0.16299
gyp
 
ERR! 
command
 "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp
 ERR!
 cwd C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\mdnsgyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
 
npm
 
ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iobroker.yahka" "--production" "--prefix" "C:/ioBroker"npm 
ERR! node v4.5.0npm ERR! npm  v2.15.9
npm
 ERR! code ELIFECYCLE
npm 
ERR! curve25519-n2@1.1.3 install: `node-gyp rebuild`npm ERR! Exit status 1

npm ERR! npm ERR! Failed at the curve25519-n2@1.1.3 install script 'node-gyp rebuild'.

npm
 ERR! This is most likely a problem with the curve25519-n2 package,npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:
npm
 ERR!     node-gyp rebuildnpm
 ERR!
 You can get information on how to open an issue for this project with:npm 
ERR!     npm bugs curve25519-n2npm 
ERR! Or if that isn't available, you can get their info via:npm 
ERR! npm ERR!     npm owner ls curve25519-n2
npm ERR! There is likely additional logging output above.


npm 
ERR!
 Please include the following file with any support request:
npm
 
ERR!     C:\ioBroker\node_modules\iobroker\npm-debug.log
host.VISU install adapter yahka
npm install iobroker.yahka --production --prefix "C:/ioBroker" (System call)
gyp
 ERR! build error 
gyp
 
ERR!
 
stack
 Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp
 
ERR!
 stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)gyp ERR! stack
     at emitTwo (events.js:87:13)gyp ERR! stack
     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.16299gyp
 ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"gyp ERR! cwd
 C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\curve25519-n2gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0

gyp ERR! not ok 
gyp
 
ERR! build error 
gyp
 ERR!
 stack
 Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR!
 
stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR!
 stack
     at emitTwo (events.js:87:13)gyp 
ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp 
ERR!
 stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)gyp
 ERR! System Windows_NT 10.0.16299
gyp ERR! 
command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"gyp
 
ERR!
 cwd
 C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\ed25519
gyp ERR! node -v v4.5.0gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

gyp
 
ERR!
 build error 
gyp
 ERR!
 
stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR!
 stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)gyp
 ERR!
 
stack     at emitTwo (events.js:87:13)
gyp
 
ERR! stack     at ChildProcess.emit (events.js:172:7)gyp ERR!
 stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)gyp ERR! 
System Windows_NT 10.0.16299
gyp 
ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"gyp
 ERR! cwd C:\ioBroker\node_modules\iobroker.yahka\node_modules\hap-nodejs\node_modules\mdnsgyp ERR! node -v v4.5.0
gyp ERR!
 node-gyp -v v3.4.0gyp ERR! not ok 

npm
 
ERR!
 Windows_NT 10.0.16299
npm
 ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iobroker.yahka" "--production" "--prefix" "C:/ioBroker"npm ERR! node v4.5.0
npm
 ERR!
 npm  v2.15.9npm
 ERR! code
 ELIFECYCLE
npm
 ERR! curve25519-n2@1.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1npm ERR! 

npm ERR! Failed at the curve25519-n2@1.1.3 install script 'node-gyp rebuild'.npm ERR! This is most likely a problem with the curve25519-n2 package,
npm ERR! not with npm itself.
npm 
ERR!
 Tell the author that this fails on your system:npm 
ERR!     node-gyp rebuildnpm 
ERR! You can get information on how to open an issue for this project with:npm ERR!     npm bugs curve25519-n2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 

npm ERR!     npm owner ls curve25519-n2npm ERR! There is likely additional logging output above.


npm ERR! Please include the following file with any support request:npm 
ERR!     C:\ioBroker\node_modules\iobroker\npm-debug.log
host.VISU install adapter yahka
ERROR: host.VISU Cannot install yahka
ERROR: process exited with code 13

**Comment by jensweigele** [comment]
Hast du Visual Studio installiert?
Wenn ja welche?

Im Grunde kannst du dich für die Installation unter Windows an die Anleitung von HomeBridge halten:
https://github.com/nfarina/homebridge/wiki/Install-HomeBridge-on-Windows-10-(new)

Node 4.5 sollte jedoch reichen.

**Comment by jensweigele** [comment]
Problem gelöst?
Falls nein, Ticket bitte wieder eröffnen
