### ISSUE TITLE
 installieren iobroker.yahka

### ISSUE THREAD

**Issue by githubaxlo** [jensweigele/ioBroker.yahka#46]
./iobroker add yahka
npm install iobroker.yahka --production --prefix "/ opt / iobroker" (Systemaufruf)
gyp
 WARN EACCES-Benutzer "root" hat keine Berechtigung, auf das Dev-Verzeichnis zuzugreifen "/root/.node-gyp/6.13.0"gyp WARN EACCES versucht, eine Neuinstallation mit dem temporären Dev-Verzeichnis durchzuführen" / opt / iobroker / node_modules / curve25519-n2 / .node-gyp "

gyp WARN install hat einen Fehler bekommen, Rollback-Installation
gyp WARN install hat einen Fehler bekommen, Rollback-Installation
gyp ERR! Fehler konfigurieren
gyp ERR! Stack Fehler: ENOSPC: Kein Platz mehr auf dem Gerät, mkdir '/opt/iobroker/node_modules/curve25519-n2/.node-gyp'gyp ERR! Stack bei Fehler (nativ)

gyp ERR! System Linux 4.9.59-v7 + gyp ERR! Befehl "/ usr / bin / node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "Wiederaufbau"
gyp ERR! cwd / opt / iobroker / knotenknoten / curve25519-n2
gyp ERR! Knoten -v v6.13.0
gyp ERR! Knoten-gyp-v v3.4.0
gyp ERR! nicht ok

npm
 
ERR! Linux 4.9.59-v7 + npm ERR! argv "/ usr / bin / node" "/ usr / bin / npm" "installieren" "iobroker.yahka" "--production" "--prefix" "/ opt / iobroker"
Npm ERR! Knoten v6.13.0
Npm ERR! npm v3.10.10

Npm ERR! Code ELIFECYCLE

Npm ERR! curve25519-n2@1.1.3 install: `node-gyp rebuild`npm ERR! Beenden Sie den Status 1
Npm ERR!
Npm ERR! Fehler bei der curve25519-n2@1.1.3 install script 'node-gyp rebuild'.
Npm ERR! Stellen Sie sicher, dass Sie die neueste Version von node.js und npm installiert haben.
Npm ERR! Wenn Sie dies tun, ist dies wahrscheinlich ein Problem mit dem curve25519-n2-Paket,

Npm ERR! nicht mit npm selbst.
Npm ERR! Sagen Sie dem Autor, dass dies auf Ihrem System fehlschlägt: npm ERR! Knoten-Gyp-Neuaufbau
Npm ERR! Informationen zum Öffnen eines Problems für dieses Projekt erhalten Sie mit:
Npm ERR! npm Fehler curve25519-n2
Npm ERR! Oder wenn das nicht verfügbar ist, können Sie ihre Informationen erhalten über:

Npm ERR! npm Besitzer ls curve25519-n2npm ERR! Wahrscheinlich ist oben eine zusätzliche Protokollierung vorhanden.

Npm ERR! Bitte fügen Sie die folgende Datei mit einer Supportanfrage bei: npm ERR! /opt/npm-debug.log
Npm ERR! Code 1

host.ioBroker-Pi Installationsadapter yahka
npm install iobroker.yahka --production --prefix "/ opt / iobroker" (Systemaufruf)
gyp
 WARN EACCES
 Benutzer "root" hat keine Berechtigung, auf das Dev-Verzeichnis "/root/.node-gyp/6.13.0" zuzugreifen
gyp
 WARN EACCES versucht mit dem temporären Dev-Verzeichnis "/opt/iobroker/node_modules/curve25519-n2/.node-gyp" erneut zu installieren
gyp
WARN install hat einen Fehler bekommen, Rollback-Installation
gyp
 WARN install hat einen Fehler bekommen, Rollback-Installation
gyp
 ERR! konfiguriere Fehler gyp ERR! Stack-Fehler: ENOSPC: Kein Platz mehr auf dem Gerät, mkdir '/opt/iobroker/node_modules/curve25519-n2/.node-gyp'
gyp ERR! Stack bei Fehler (nativ)
gyp ERR! System Linux 4.9.59-v7 +
gyp ERR! Befehl "/ usr / bin / node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "Wiederaufbau"
gyp ERR! cwd / opt / iobroker / knotenknoten / curve25519-n2
gyp ERR! Knoten -v v6.13.0
gyp
 
ERR! node-gyp -v v3.4.0gyp ERR! nicht ok

npm
 ERR!

Linux 4.9.59-v7 +
npm
 ERR! argv "/ usr / bin / node" "/ usr / bin / npm" "installieren" "iobroker.yahka" "--production" "--prefix" "/ opt / iobroker"
Npm ERR! Knoten v6.13.0npm ERR! npm v3.10.10
Npm ERR! Code ELIFECYCLE

Npm ERR! curve25519-n2@1.1.3 install: `node-gyp rebuild`npm ERR! Beenden Sie den Status 1
Npm ERR!
Npm ERR! Fehler bei der curve25519-n2@1.1.3 install script 'node-gyp rebuild'.
Npm ERR! Stellen Sie sicher, dass Sie die neueste Version von node.js und npm installiert haben.
Npm ERR! Wenn Sie dies tun, ist dies wahrscheinlich ein Problem mit dem curve25519-n2-Paket,
Npm ERR! nicht mit npm selbst.
Npm ERR! Sagen Sie dem Autor, dass dies auf Ihrem System fehlschlägt:
Npm ERR! Knoten-Gyp-Neuaufbau
Npm ERR! Informationen zum Öffnen eines Problems für dieses Projekt erhalten Sie mit:
Npm ERR! npm Fehler curve25519-n2
Npm ERR! Oder wenn das nicht verfügbar ist, können Sie ihre Informationen erhalten über:
Npm ERR! npm Besitzer ls curve25519-n2
Npm ERR! Wahrscheinlich ist oben eine zusätzliche Protokollierung vorhanden.

Npm ERR! Bitte fügen Sie die folgende Datei mit einer Supportanfrage bei:
npm
ERR! /opt/npm-debug.lognpm ERR! Code 1

host.ioBroker-Pi Installationsadapter yahka
npm install iobroker.yahka --production --prefix "/ opt / iobroker" (Systemaufruf)
gyp
 WARN EACCES-Benutzer "root" hat keine Berechtigung, auf das Dev-Verzeichnis zuzugreifen "/root/.node-gyp/6.13.0"gyp WARN EACCES versucht, eine Neuinstallation mit dem temporären Dev-Verzeichnis durchzuführen" / opt / iobroker / node_modules / curve25519-n2 / .node-gyp "

gyp
 WARN install hat einen Fehler bekommen, Rollback installgypp WARN Installation hat einen Fehler, Rollback-Installation
gyp ERR! Fehler konfigurieren

gyp ERR! Stack Fehler: ENOSPC: Kein Platz mehr auf dem Gerät, mkdir '/opt/iobroker/node_modules/curve25519-n2/.node-gyp'gyp ERR! Stack bei Fehler (nativ)

gyp ERR! System Linux 4.9.59-v7 + gyp ERR! Befehl "/ usr / bin / node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "Wiederaufbau"
gyp ERR! cwd / opt / iobroker / knotenknoten / curve25519-n2
gyp ERR! Knoten -v v6.13.0

gyp ERR! node-gyp -v v3.4.0gyp ERR! nicht ok

Npm ERR! Linux 4.9.59-v7 +
Npm ERR! argv "/ usr / bin / node" "/ usr / bin / npm" "installieren" "iobroker.yahka" "--production" "--prefix" "/ opt / iobroker" npm ERR! Knoten v6.13.0
Npm ERR! npm v3.10.10

Npm ERR! Code ELIFECYCLE

Npm ERR! curve25519-n2@1.1.3 install: `node-gyp rebuild`npm ERR! Beenden Sie den Status 1
Npm ERR!
Npm ERR! Fehler bei der curve25519-n2@1.1.3 install script 'node-gyp rebuild'.
Npm ERR! Stellen Sie sicher, dass Sie die neueste Version von node.js und npm installiert haben.
Npm ERR! Wenn Sie dies tun, ist dies wahrscheinlich ein Problem mit dem curve25519-n2-Paket,
Npm ERR! nicht mit npm selbst.
Npm ERR! Sagen Sie dem Autor, dass dies auf Ihrem System fehlschlägt:
Npm ERR! Knoten-Gyp-Neuaufbau
Npm ERR! Informationen zum Öffnen eines Problems für dieses Projekt erhalten Sie mit:
Npm ERR! npm Fehler curve25519-n2
Npm ERR! Oder wenn das nicht verfügbar ist, können Sie ihre Informationen erhalten über:
Npm ERR! npm Besitzer ls curve25519-n2
Npm ERR! Wahrscheinlich ist oben eine zusätzliche Protokollierung vorhanden.

Npm ERR! Bitte fügen Sie die folgende Datei mit einer Supportanfrage bei:
Npm ERR! /opt/npm-debug.log

Npm ERR! Code 1
host.ioBroker-Pi Installationsadapter yahka
FEHLER: host.ioBroker-Pi yahka kann nicht installiert werden
FEHLER: Prozess mit Code 13 beendet
#####
Wenn ich nach Vorgabe Fehlerbehebung vogehe bekomme ich folgende Meldung

/opt/iobroker$ sudo apt-get install libavahi-compat-libdnssd-dev

Paketlisten werden gelesen...

Abhängigkeitsbaum wird aufgebaut....

Statusinformationen werden eingelesen....

libavahi-compat-libdnssd-dev ist schon die neueste Version (0.6.32-2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
/opt/iobroker$  

#####
Komm nicht weiter können Sie mir helfen?

**Comment by eumats** [comment]
[...]
gyp ERR! Stack Fehler: ENOSPC: **Kein Platz mehr auf dem Gerät**, mkdir 
[...]
Speichermedium voll?
