### ISSUE TITLE
Thermostat und YAHKA

### ISSUE THREAD

**Issue by jo-foe** [jensweigele/ioBroker.yahka#465]
Hallo,
ich habe eine Frage zu dem Service Thermostat in yahka. 
Ich habe jetzt bereits alle Möglichkeiten ausprobiert. Der Thermostat wird in HomeKit angezeigt. Ich kann aber nichts steuern.
Wenn ich die Datenpunkte der Klimaanlage manuell setzte (Kühle, Heizen, Auto, und aus funktioniert es bestens) Versuche ich es aber über den Themostaten in HomeKit zu erledigen passiert gar nichts.
Nehme ich aber einen Switch, kann ich zumindestens die Klimaanlage an- und ausschalten.
Habt ihr auch Probleme mit dem Thermostat? ich nutze die aktuelle Version von Homekit YAHKA 1.03.

**Comment by Tombra1889** [comment]
Damit funktioniert es bei mir einigermaßen:

<img width="909" alt="image" src="https://github.com/jensweigele/ioBroker.yahka/assets/60692414/e0714690-a8bc-4b54-b408-45e8683e792d">
<img width="839" alt="image" src="https://github.com/jensweigele/ioBroker.yahka/assets/60692414/5801357c-8670-44f8-8858-c395d40b0c8d">
<img width="839" alt="image" src="https://github.com/jensweigele/ioBroker.yahka/assets/60692414/8debf166-6ca8-41a2-b3e2-55c067324cd9">

**Comment by jo-foe** [comment]
vielen Dank für eure Vorschläge. Ich bin jetzt ein Stück weiter ist aber noch nicht perfekt.
ich nutze jetzt den Servicetype HeaterCooler für die Klimaanlage Kältebringer.
<img width="694" alt="Bildschirmfoto 2024-07-16 um 12 07 33" src="https://github.com/user-attachments/assets/6284790a-dc60-4f11-83f3-c58358d43cf5">
nur habe ich noch folgendes Problem.
im ioBroker habe ich die Möglichkeiten für die Knoten CurrentHeaterCoolerState und TargetHeaterCoolerStatezu folgendes zu setzten
0 = could
1 = hot
2 = wet
3 = wind
4 = auto 
im HomeKit
gibt es aber nur 

Kühlung = 2 dann in ioBroker = 0
Heizen = 1 dann in ioBroker = 0
Automatisch = 0 dann in ioBroker = 0

zum Ausschalten ist hier der Knoten Active im ioBroker zuständig (1 oder 0)

die Einstellung wind und wet gibt es im HomeKit HeatCooler gar nicht

wie würdet ihr dies lösen?

**Comment by Flothoger** [comment]
## 3 = wind
Hier könnte man einen zusätzlichen [Fan](https://developer.apple.com/documentation/homekit/hmcharacteristic/characteristic_types#3080319) Service erzeugen. Wenn hier der Status geändert, wird geht die Klimaanlage in den Lüftungsmodus. Falls man im Kühl- / Heizmodus auch die Lüftergeschwindigkeit anpassen kann, könnte man den Fan Service auch hierfür nutzen.
## 2 = wet
Ich denke mal dieser Modus dient zur Entfeuchtung. Auch hier wäre eine Möglichkeit eine zusätzlichen Service, den [Humidifier/Dehumidifier](https://developer.apple.com/documentation/homekit/hmcharacteristic/characteristic_types#3080329) zu nehmen und bei Änderung von _Active_ oder _TargetHumidifierDehumidifierState_ die Anlage in den entsprechenden Modus schalten.

Definitiv machbar, aber um das sauber einzubinden ist ein gut geplantes Javascript / Blockly notwendig.

**Comment by jo-foe** [comment]
Wie wird dies dann in HomeKit dargestellt? Es läuft dann wohl über 2 bzw. 3 Icons? Ich werde es mal testen.
Klingt jedenfalls ganz gut. Mal sehn ob ich es hinbekomme. 
Danke erst einmal.

**Comment by tarikweiss** [comment]
Wenn das Problem behoben ist, dann gerne das Issue schließen. Ansonsten ist dies auch nicht der ganz richtige Ort um Fragen zur Nutzung des Adapters zu stellen. Dazu gern das Forum, Telegram oder Discord nutzen.
