### ISSUE TITLE
Service Dokumentation

### ISSUE THREAD

**Issue by thstickel** [jensweigele/ioBroker.yahka#466]
Hallo zusammen. Ich verzweifele gerade bei der Einbindung meines Nuki-Schlosses via MQTT. Eigentlich bräuchte ich nur eine Dokumenation, welche mir beschreibt, welcher Status im Homekit welchen Zustand des Schlosses beschreibt. Beispiel: Zustand "geschlossen" ist beim Nuki der Status "1". Aber welcher Zustand "geschlossen" im HomeKit beschreibt, weiß ich nicht.
Daher mein Vorschlag, für jeden funktionierenden Service-Typ eine Tabelle mit den nötigen Merkmalen zu beschreiben. Ein Beispiel, wie folgt:

#### LockMechnism (is working)
|Feature         |description           |mandatory      |input options    |
|--------------------|-----------------------|-----------|-----------------|
|**Name**            |shown Name in AppleHome|           |string           |
|**LockCurrentState**|The current state      |  X        |0 = ???          |
|                    |                       |           |1 = ???          |
|                    |                       |           |2 = ???          |
|                    |                       |           |3 = ???          |
|**LockTargetState** |The target state       |  X        |0 = unlocked     |
|                    |                       |           |1 = locked       |

Fehlt hier noch was? Oder ist eine solche Dokumention überhaupt sinnvoll?

**Comment by Baenker** [comment]
Du kannst ja gerne anfangen. Ansonsten kann man zum einen bei Apple direkt nachgucken oder Alternativ Datenpunkt in ioBroker erstellen und den dann mit Homekit beschreiben lassen und schon sieht man welche Zahl für welchen Status gilt.

**Comment by tarikweiss** [comment]
Du kannst diese Sachen auf der Developer-Seite von Apple nachschauen. Leider benötigt es ein wenig wissen, bis man weiß, wie man das lesen muss und vor allem wonach man suchen muss.

https://developer.apple.com/documentation/homekit/hmcharacteristicvaluelockmechanismstate

Hier zum Beispiel für Lock-Current-State. Also HM = der Prefix für Homekit
Characteristic ist das was du suchst, die nächste übergeordnete Sache sind dann die Services

Dann suchst du LockMachnismState

Und dann hast du die "Enum"-Werte (Enum steht für Enumerationen, zu deutsch Aufzählungen)

Und dann stehen die Konstanten, also eben unsecured, secured, jammed, unknown in der korrekten Reihenfolge und ergeben quasi auch die Zahlen, welche erlaubt sind. Also 0 = unlocked (im Apple sprech unsecured), 1  = locked (secured), 2 = jammed (Also Störung, z.B. durch Einbruch oder sowas) und 3 = unknown (gerade nicht bekannt).

**Comment by thstickel** [comment]
@tarikweiss Vielen Dank für den Link und die Erklärung. Jetzt läuft auch alles.
