### ISSUE TITLE
Empty device list after upgrading to V1.0.4

### ISSUE THREAD

**Issue by CPU-6502** [jensweigele/ioBroker.yahka#479]
Error in #413 re-appeard in V1.0.4; downgrading to V1.0.3 resolved the issue. I'm running iobroker in buanet/iobroker:latest-v9 docker image.

**Comment by tarikweiss** [comment]
Do you maybe have some error logs? Is it the same behaviour as in #473?

**Comment by CPU-6502** [comment]
Yes it is the same behavior as in #473, with no errors in the log upon adapter startup. But while performing the update from 1.0.3 to 1.0.4, I got the following message in the event log:

**iobroker Cannot install "pam-devel": sudo: unable to resolve host iobroker: Name or service not knownWARNING: apt does not have a stable CLI interface. Use with caution in scripts.E: Unable to locate package pam-devel**

**Comment by GermanBluefox** [comment]
https://www.iobroker.net/#de/documentation/faq/_040_contibution.md?fehlerindergrafischeoberflchemelden

**Comment by cracyfloyd** [comment]
> Yes it is the same behavior as in #473, with no errors in the log upon adapter startup. But while performing the update from 1.0.3 to 1.0.4, I got the following message in the event log:
> 
> **iobroker Cannot install "pam-devel": sudo: unable to resolve host iobroker: Name or service not knownWARNING: apt does not have a stable CLI interface. Use with caution in scripts.E: Unable to locate package pam-devel**

Same here after upgrade to 1.0.6.
The adapter runs but no devices in the ui to see and not possible to add a new one. in the log are the devices to see after restart the adapter.

**Comment by baetzmr** [comment]
Admin still empty after NPM update to 1.0.6. I could not see any errors in the iobroker log. i am running nodejs 20.17.0 -  adapter seams to work fine. Here is a EDGE log output when opening yahka admin settings page:

 Uncaught AssertionError: The cipher 'chacha20-poly1305' is not supported with your current running nodejs version v. At least a nodejs version of v10.17.0 (excluding v11.0 and v11.1) is required!
    at Object.../node_modules/hap-nodejs/dist/lib/util/hapCrypto.js (:8081/adapter/yahka/…l/hapCrypto.js:17:1)
    at __webpack_require__ (:8081/adapter/yahka/…pack/bootstrap:19:1)
    at Object.../node_modules/hap-nodejs/dist/lib/util/eventedhttp.js (:8081/adapter/yahka/…ventedhttp.js:12:40)
    at __webpack_require__ (:8081/adapter/yahka/…pack/bootstrap:19:1)
    at Object.../node_modules/hap-nodejs/dist/lib/HAPServer.js (:8081/adapter/yahka/…/HAPServer.js:13:23)
    at __webpack_require__ (:8081/adapter/yahka/…pack/bootstrap:19:1)
    at Object.../node_modules/hap-nodejs/dist/lib/Characteristic.js (:8081/adapter/yahka/…racteristic.js:8:21)
    at __webpack_require__ (:8081/adapter/yahka/…pack/bootstrap:19:1)
    at Object.../node_modules/hap-nodejs/dist/lib/definitions/CharacteristicDefinitions.js (:8081/adapter/yahka/…efinitions.js:10:26)
    at __webpack_require__ (:8081/adapter/yahka/…pack/bootstrap:19:1)

index_m.html?0&newRe…rue&0&react=dark:57 
 Uncaught TypeError: Cannot read properties of undefined (reading 'ioBroker_YahkaAdmin')
    at index_m.html?0&newRe…&0&react=dark:57:41
Instances.tsx:1044 Width: lg
index_m.html?0&newRe…ue&0&react=dark:122 
 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'loadSettings')
    at load (index_m.html?0&newRe…0&react=dark:122:24)
    at _load (adapter-settings.js:469:9)
    at adapter-settings.js:526:25
    at SocketClient.findAnswer (socket.io.js:303:20)
    at WebSocket.socket.onmessage (socket.io.js:212:22)
﻿

**Comment by CPU-6502** [comment]
Same issue on V1.0.6, same error during install in event log. 

I should add that I‘m running iobroker on docker using the buanet/iobroker:latest-v7 image

> Yes it is the same behavior as in #473, with no errors in the log upon adapter startup. But while performing the update from 1.0.3 to 1.0.4, I got the following message in the event log:
> 
> **iobroker Cannot install "pam-devel": sudo: unable to resolve host iobroker: Name or service not knownWARNING: apt does not have a stable CLI interface. Use with caution in scripts.E: Unable to locate package pam-devel**

**Comment by tarikweiss** [comment]
Sorry, seemingly there are issues with the build process. We are on it.

**Comment by tarikweiss** [comment]
Seems fixed.

**Comment by CPU-6502** [comment]
Not for me. Still the same in V1.0.8. Also still getting the error message during Installation:

_**iobroker Cannot install "pam-devel": sudo: unable to resolve host iobroker: Name or service not knownWARNING: apt does not have a stable CLI interface. Use with caution in scripts.E: Unable to locate package pam-develThe following apt packages could not be installed: pam-devel. Please install them manually.**_

Running on buanet/iobroker:latest-v10 image (JSController 6.0.11; NodeJS 20.17.0)

**Comment by cracyfloyd** [comment]
v 1.08 does not solve the Problem with empty device List for me. I cant put any new divers too. But this Version published all my devices and it works to Control it. in the Logs i have no errors also the pam-devel error i dont have .

Running on buanet/iobroker:latest-v10 image (JSController 6.0.11; NodeJS 20.17.0)

**Comment by CPU-6502** [comment]
Just installed V1.0.9 - problem seems to be fixed in this release!

**Comment by cracyfloyd** [comment]
Many many thnx. It seems to be worked fine. Congrats.....!!!!!!!!!! (V1.09)

**Comment by Apollon77** [comment]
Reward goes to @tarikweiss ;-)
