### ISSUE TITLE
Issue in v.1.0.5 mit cipher

### ISSUE THREAD

**Issue by tarikweiss** [jensweigele/ioBroker.yahka#483]
`AssertionError: The cipher 'chacha20-poly1305' is not supported with your current running nodejs version v. At least a nodejs version of v10.17.0 (excluding v11.0 and v11.1) is required!`

Das ist das Issue, was bei mir beim öffnen vom Admin für Yahka aufgetreten ist.

Vermutlich im Zusammenhang mit den Version-Upgrades aus 1495e76

**Comment by krobipd** [comment]
Was für nodejs Version hast du installiert? Der Fehler sagt ihm passt die nodejs Version nicht.

**Comment by tarikweiss** [comment]
Scheint ein Build-Issue zu sein. Die Version passt, aber die gebauten Dateien weichen mit mehreren Tausend Änderungen ab.

**Comment by tarikweiss** [comment]
Also ich habe den letzten PR (#482) hier von mir getestet, der funktioniert wunderbar. Dann kam ein build von @GermanBluefox rein und der scheint das Issue mit reingebracht zu haben. Ich habe auch dann einfach bei mir nochmal den build Prozess lokal angestoßen, was dazu führte, dass die Files neugebaut wurden und auch stark abweichen. Das finde ich doch etwas ungewöhnlich. Lokal habe ich node v18.18.2 installiert.
Ich hoffe die Infos helfen um das Build-Issue zu beheben.

**Comment by tarikweiss** [comment]
The issue still appears with the latest version of github (1.0.6). I installed the adapter using the github tab in ioBroker. Can we get together a sustainable solution here?

`AssertionError: The cipher 'chacha20-poly1305' is not supported with your current running nodejs version v. At least a nodejs version of v10.17.0 (excluding v11.0 and v11.1) is required!`

**Comment by tarikweiss** [comment]
Fixed.
