### ISSUE TITLE
yahka 1.0.6 - admin still empty

### ISSUE THREAD

**Issue by krobipd** [jensweigele/ioBroker.yahka#485]
problem is still not fixed with 1.0.6 (https://github.com/jensweigele/ioBroker.yahka/issues/473)
<img width="294" alt="Bildschirmfoto 2024-08-30 um 21 45 29" src="https://github.com/user-attachments/assets/a12baccd-a895-4a37-96f5-f265f71ca84c">

**Comment by Tombra1889** [comment]
same:
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/decc2758-97c3-48c3-a084-3382ea560549">

**Comment by backfisch88** [comment]
same

**Comment by Jakymausi** [comment]
Samer Error !

**Comment by Jakymausi** [comment]
Könnt Ihr euch dies ansehen und Feedback geben? Falls Ihr Logs braucht meldet euch.

**Comment by backfisch88** [comment]
> Könnt Ihr euch dies ansehen und Feedback geben? Falls Ihr Logs braucht meldet euch.

was ansehen?^^

**Comment by 1tomtom** [comment]
ist bei mir ab allen Version ab 1.04 der Fall. nur 1.03 funktioniert noch.

**Comment by spoeh-man** [comment]
Bei mir leider auch ab 1.04

**Comment by marrrkus** [comment]
same here, please fix. 

Noticed an error during update: "Can not install 'pam-devel'" ... running Debian 12, libpam0d-g is installed.

**Comment by tarikweiss** [comment]
The latest version 1.0.8. works for me. I hope for you too! :) Thanks to @GermanBluefox  and @Apollon77 for fixing :)

**Comment by mattreim** [comment]
Version 1.0.8 doesn't work for me and the following message is in the log.

```lua
2024-09-05 22:32:25.668 - error: host.XXX iobroker Cannot install "pam-devel": WARNING: apt does not have a stable CLI interface. Use with caution in scripts.E: Paket pam-devel kann nicht gefunden werden.
2024-09-05 22:32:25.668 - error: host.XXX iobroker The following apt packages could not be installed: pam-devel. Please install them manually.
```

**Comment by spoeh-man** [comment]
1.0.8 Same Probleme here 

Nodejs 20.17.0
Admin 7.1.0

**Comment by Tombra1889** [comment]
> same: <img alt="image" width="1028" src="https://private-user-images.githubusercontent.com/60692414/363435124-decc2758-97c3-48c3-a084-3382ea560549.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDkzOTMsIm5iZiI6MTcyNTYwOTA5MywicGF0aCI6Ii82MDY5MjQxNC8zNjM0MzUxMjQtZGVjYzI3NTgtOTdjMy00OGMzLWEwODQtMzM4MmVhNTYwNTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA3NTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NDk2NDUyNTgyNjc2NTgyODJlNjJhZWM5NWViNTZmMmYyMDNlOGYzMzcxNWJjNjhjMGEyOWY1ZDUwMzllMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rGNQd_JEVKB4fkYJ8KXGVN3-yMKwJjWJgUZ5gqbNL1M">

1.0.8 works for me

**Comment by Apollon77** [comment]
Ok, lets not mix things.

So we have "ui does now work" and we have "potential apt package install errors on update" ... but no one said if this means that it works then or not ... so is it still working? The apt install error should have no effect of installation process. but yes seems that there is a package nort available for your OS. in fact should be libpam0g-dev and maybe an update for the io-package is needed, but thats just "for completeness"

**Comment by spoeh-man** [comment]
ui dos not work

Yahka 1.0.8

Nodejs 20.17.0
Admin 7.1.0

**Comment by backfisch88** [comment]
For me all things working with 1.0.8

**Comment by Apollon77** [comment]
for the once where it did not work? Browser cache deleted? Shift-Reload? "iob upload yahka" ? Afterwards?
WHich error is shown pot in iob logs or also browser console

**Comment by spoeh-man** [comment]
Browser cache deletet no effekt
Reload no effekt
iob upload yahka no effekt

iob Log only the error from pam level

Chrome 
`<div tabindex="-1" class="console-group console-group-messages" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative;"><div tabindex="-1" class="console-message-wrapper console-error-level console-selected" jslog="Item; context: console-message; track: click, keydown: ArrowUp|ArrowDown|ArrowLeft|ArrowRight|Enter|Space|Home|End" role="log" aria-label="Uncaught TypeError: Cannot read properties of undefined (reading 'ioBroker_YahkaAdmin')" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; display: flex; flex-direction: column; margin: 4px; border-radius: 5px; --console-color-black: #000; --console-color-red: rgb(237 78 76); --console-color-green: rgb(1 200 1); --console-color-yellow: rgb(210 192 87); --console-color-blue: rgb(39 116 240); --console-color-magenta: rgb(161 66 244); --console-color-cyan: rgb(18 181 203); --console-color-gray: rgb(207 208 208); --console-color-darkgray: rgb(137 137 137); --console-color-lightred: rgb(242 139 130); --console-color-lightgreen: rgb(161 247 181); --console-color-lightyellow: rgb(221 251 85); --console-color-lightblue: rgb(102 157 246); --console-color-ightmagenta: #f5f; --console-color-lightcyan: rgb(132 240 255); --console-color-white: #fff; background-color: var(--sys-color-tonal-container); --message-corner-rounder-background: var(--sys-color-surface-error); --console-color-lightmagenta: rgb(214 112 214);"><div class="console-row-wrapper" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: row;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start; margin-top: -1px;"><div class="console-message-stack-trace-wrapper" aria-label="index_m.html?0&amp;newRe…rue&amp;0&amp;react=dark:57 Uncaught TypeError: Cannot read properties of undefined (reading 'ioBroker_YahkaAdmin')
    at index_m.html?0&amp;newRe…&amp;0&amp;react=dark:57:41 Stacktabelle maximiert" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://192.168.179.37:8081/adapter/yahka/index_m.html?0&amp;newReact=true&amp;0&amp;react=dark:57" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;"><br class="Apple-interchange-newline">index_m.html?0&amp;newRe<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>rue&amp;0&amp;react=dark:57</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read properties of undefined (reading 'ioBroker_YahkaAdmin')
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://192.168.179.37:8081/adapter/yahka/index_m.html?0&amp;newReact=true&amp;0&amp;react=dark:57:41" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">index_m.html?0&amp;newRe<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>&amp;0&amp;react=dark:57:41</button></span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: monospace; --source-code-font-size: 11px; --source-code-font-family: monospace; width: 921px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | (anonym) | @ | index_m.html?0&newRe…rue&0&react=dark:57
-- | -- | -- | --


</span></div></div></div></div></div></div><div tabindex="-1" class="console-message-wrapper console-error-level" jslog="Item; context: console-message; track: click, keydown: ArrowUp|ArrowDown|ArrowLeft|ArrowRight|Enter|Space|Home|End" role="log" aria-label="Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'loadSettings')" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: column; margin: 4px; border-radius: 5px; --console-color-black: #000; --console-color-red: rgb(237 78 76); --console-color-green: rgb(1 200 1); --console-color-yellow: rgb(210 192 87); --console-color-blue: rgb(39 116 240); --console-color-magenta: rgb(161 66 244); --console-color-cyan: rgb(18 181 203); --console-color-gray: rgb(207 208 208); --console-color-darkgray: rgb(137 137 137); --console-color-lightred: rgb(242 139 130); --console-color-lightgreen: rgb(161 247 181); --console-color-lightyellow: rgb(221 251 85); --console-color-lightblue: rgb(102 157 246); --console-color-ightmagenta: #f5f; --console-color-lightcyan: rgb(132 240 255); --console-color-white: #fff; background-color: var(--sys-color-surface-error); --message-corner-rounder-background: var(--sys-color-surface-error); --console-color-lightmagenta: rgb(214 112 214); border-top-color: transparent;"><div class="console-row-wrapper" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: row;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><devtools-icon role="presentation" name="cross-circle-filled" class="message-level-icon" aria-label="Fehler" style="flex: 1 1 auto; display: inline-block; width: 14px; height: 14px; color: var(--icon-error); vertical-align: sub; position: absolute; box-sizing: border-box; min-width: 0px; min-height: 0px; left: -17px; top: 2px; user-select: none;"><span style="display: block; width: 14px; height: 14px; background-color: currentcolor; mask: var(--icon-url) center /contain no-repeat; --icon-url: var(--image-file-cross-circle-filled);"></span></devtools-icon><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start; margin-top: -1px;"><div class="console-message-stack-trace-wrapper" aria-label="index_m.html?0&amp;newRe…ue&amp;0&amp;react=dark:122 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'loadSettings')
    at load (index_m.html?0&amp;newRe…0&amp;react=dark:122:24)
    at _load (adapter-settings.js:469:9)
    at adapter-settings.js:526:25
    at SocketClient.findAnswer (socket.io.js:303:20)
    at WebSocket.socket.onmessage (socket.io.js:212:22) Stacktabelle minimiert" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="false" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><devtools-icon role="presentation" name="triangle-right" class="console-message-expand-icon" style="flex-grow: 0; flex-shrink: 0; display: inline-block; width: 14px; height: 14px; color: var(--icon-default); vertical-align: baseline; position: relative; box-sizing: border-box; min-width: 0px; min-height: 0px; margin-bottom: -4px;"><span style="display: block; width: 14px; height: 14px; background-color: currentcolor; mask: var(--icon-url) center /contain no-repeat; --icon-url: var(--image-file-triangle-right);"></span></devtools-icon><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://192.168.179.37:8081/adapter/yahka/index_m.html?0&amp;newReact=true&amp;0&amp;react=dark:122" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">index_m.html?0&amp;newRe<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>ue&amp;0&amp;react=dark:122</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read properties of undefined (reading 'loadSettings')
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at load (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://192.168.179.37:8081/adapter/yahka/index_m.html?0&amp;newReact=true&amp;0&amp;react=dark:122:24" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">index_m.html?0&amp;newRe<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>0&amp;react=dark:122:24</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at _load (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://192.168.179.37:8081/js/adapter-settings.js:469:9" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">adapter-settings.js:469:9</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://192.168.179.37:8081/js/adapter-settings.js:526:25" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">adapter-settings.js:526:25</button>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at SocketClient.findAnswer (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://192.168.179.37:8081/socket.io/socket.io.js:303:20" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">socket.io.js:303:20</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at WebSocket.socket.onmessage (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://192.168.179.37:8081/socket.io/socket.io.js:212:22" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">socket.io.js:212:22</button>)</span></span></span></span></span></div></div></div></div></div></div><div tabindex="-1" class="console-message-wrapper console-error-level" jslog="Item; context: console-message; track: click, keydown: ArrowUp|ArrowDown|ArrowLeft|ArrowRight|Enter|Space|Home|End" role="log" aria-label="Failed to load resource: net::ERR_BLOCKED_BY_CLIENT" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: column; margin: 4px; border-radius: 5px; --console-color-black: #000; --console-color-red: rgb(237 78 76); --console-color-green: rgb(1 200 1); --console-color-yellow: rgb(210 192 87); --console-color-blue: rgb(39 116 240); --console-color-magenta: rgb(161 66 244); --console-color-cyan: rgb(18 181 203); --console-color-gray: rgb(207 208 208); --console-color-darkgray: rgb(137 137 137); --console-color-lightred: rgb(242 139 130); --console-color-lightgreen: rgb(161 247 181); --console-color-lightyellow: rgb(221 251 85); --console-color-lightblue: rgb(102 157 246); --console-color-ightmagenta: #f5f; --console-color-lightcyan: rgb(132 240 255); --console-color-white: #fff; background-color: var(--sys-color-surface-error); --message-corner-rounder-background: var(--sys-color-surface-error); --console-color-lightmagenta: rgb(214 112 214);"><div class="console-row-wrapper" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: row;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><devtools-icon role="presentation" name="cross-circle-filled" class="message-level-icon" aria-label="Fehler" style="flex: 1 1 auto; display: inline-block; width: 14px; height: 14px; color: var(--icon-error); vertical-align: sub; position: absolute; box-sizing: border-box; min-width: 0px; min-height: 0px; left: -17px; top: 2px; user-select: none;"><span style="display: block; width: 14px; height: 14px; background-color: currentcolor; mask: var(--icon-url) center /contain no-repeat; --icon-url: var(--image-file-cross-circle-filled);"></span></devtools-icon><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start; margin-top: -1px;"><div class="console-message-stack-trace-wrapper" aria-label="  POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69…866ee9d6&amp;sentry_version=7&amp;sentry_client=sentry.javascript.browser%2F8.27.0 net::ERR_BLOCKED_BY_CLIENT Stacktabelle minimiert" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="false" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><devtools-icon role="presentation" name="triangle-right" class="console-message-expand-icon" style="flex-grow: 0; flex-shrink: 0; display: inline-block; width: 14px; height: 14px; color: var(--icon-default); vertical-align: baseline; position: relative; box-sizing: border-box; min-width: 0px; min-height: 0px; margin-bottom: -4px;"><span style="display: block; width: 14px; height: 14px; background-color: currentcolor; mask: var(--icon-url) center /contain no-repeat; --icon-url: var(--image-file-triangle-right);"></span></devtools-icon><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style ignore-list-link" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://192.168.179.37:8081/node_modules/@sentry/browser/src/transports/fetch.ts:50" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">fetch.ts:50</button> <devtools-request-link-icon class="resource-links" style="display: inline-block; white-space: nowrap; color: inherit; font-size: inherit; font-family: inherit; box-sizing: border-box; min-width: 0px; min-height: 0px; margin-top: -1px; margin-bottom: -2px;"><button class=" link " title="Klicken, um den Netzwerkbereich zu öffnen und die Anfrage für die folgende URL anzuzeigen: https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&amp;sentry_version=7&amp;sentry_client=sentry.javascript.browser%2F8.27.0" jslog="Link; context: request; track: click" style="border: none; background: transparent; margin: 0px; padding: 0px; cursor: pointer;"><devtools-icon name="arrow-up-down-circle" role="presentation" style="flex-grow: 0; flex-shrink: 0; display: inline-block; width: 16px; height: 16px; color: var(--icon-link); vertical-align: middle; position: relative;"><span style="display: block; width: 16px; height: 16px; background-color: currentcolor; mask: var(--icon-url) center /contain no-repeat; --icon-url: var(--image-file-arrow-up-down-circle);"></span></devtools-icon></button></devtools-request-link-icon> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">POST <button class="devtools-link text-button link-style" jslog="Link; context: network-request; track: click" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>866ee9d6&amp;sentry_version=7&amp;sentry_client=sentry.javascript.browser%2F8.27.0</button> net::ERR_BLOCKED_BY_CLIENT</span></span></div></div></div></div></div></div><div tabindex="-1" class="console-message-wrapper console-error-level" jslog="Item; context: console-message; track: click, keydown: ArrowUp|ArrowDown|ArrowLeft|ArrowRight|Enter|Space|Home|End" role="log" aria-label="Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: column; margin: 4px; border-radius: 5px; --console-color-black: #000; --console-color-red: rgb(237 78 76); --console-color-green: rgb(1 200 1); --console-color-yellow: rgb(210 192 87); --console-color-blue: rgb(39 116 240); --console-color-magenta: rgb(161 66 244); --console-color-cyan: rgb(18 181 203); --console-color-gray: rgb(207 208 208); --console-color-darkgray: rgb(137 137 137); --console-color-lightred: rgb(242 139 130); --console-color-lightgreen: rgb(161 247 181); --console-color-lightyellow: rgb(221 251 85); --console-color-lightblue: rgb(102 157 246); --console-color-ightmagenta: #f5f; --console-color-lightcyan: rgb(132 240 255); --console-color-white: #fff; background-color: var(--sys-color-surface-error); --message-corner-rounder-background: var(--sys-color-surface-error); --console-color-lightmagenta: rgb(214 112 214);"><div class="console-row-wrapper" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: row;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><devtools-icon role="presentation" name="cross-circle-filled" class="message-level-icon" aria-label="Fehler" style="flex: 1 1 auto; display: inline-block; width: 14px; height: 14px; color: var(--icon-error); vertical-align: sub; position: absolute; box-sizing: border-box; min-width: 0px; min-height: 0px; left: -17px; top: 2px; user-select: none;"><span style="display: block; width: 14px; height: 14px; background-color: currentcolor; mask: var(--icon-url) center /contain no-repeat; --icon-url: var(--image-file-cross-circle-filled);"></span></devtools-icon><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; flex: 1 1 auto; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style invalid-link" jslog="Link; context: script-location; track: click" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--text-disabled); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: none; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis;">:8081/#tab-instances…m.adapter.yahka.0:1</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received</span></span></span></span></div></div></div></div><div aria-hidden="true" style="box-sizing: border-box; min-width: 0px; min-height: 0px; height: 0px; color: transparent;">﻿</div><div class="source-code" id="console-prompt" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; clear: right; position: relative; margin: 0px 22px 0px 20px;"><div class="widget" jslog="TextField; context: console-prompt; track: change, keydown: Enter|ArrowUp|ArrowDown|PageUp" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: style;"><div class="console-prompt-editor-container" style="box-sizing: border-box; min-width: 0px; min-height: 21px;"><devtools-text-editor style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><div class="cm-editor ͼ1 ͼ3 ͼ4 ͼ5 ͼ6" style="box-sizing: border-box; flex-direction: column; position: relative !important; display: flex !important; color: color: var(--sys-color-on-subtle); cursor: auto;"><div class="cm-announced" aria-live="polite" style="position: fixed; top: -10000px;"></div><div tabindex="-1" class="cm-scroller" style="font-family: var(--source-code-font-family); line-height: 1.4em; height: 23.3984px; overflow-x: auto; position: relative; z-index: 0; display: flex !important; align-items: flex-start !important; font-size: var(--source-code-font-size);"><div spellcheck="false" autocorrect="off" autocapitalize="off" translate="no" contenteditable="true" class="cm-content cm-lineWrapping" role="textbox" aria-multiline="true" aria-label="Konsolenaufforderung" data-language="javascript" aria-autocomplete="list" style="margin: 0px; flex-grow: 2; flex-shrink: 1; display: block; white-space: break-spaces; overflow-wrap: anywhere; box-sizing: border-box; min-height: 100%; padding: 4px 0px; outline: none; word-break: break-word; caret-color: transparent !important; line-height: 1.4em; -webkit-user-modify: read-write-plaintext-only; tab-size: 4;"><div class="cm-line" style="display: block; padding: 0px 2px 0px 6px; caret-color: transparent !important;"><br style="color: rgb(227, 227, 227); font-family: monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; caret-color: rgba(0, 0, 0, 0); white-space: break-spaces; background-color: rgb(40, 40, 40); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">`

**Comment by spoeh-man** [comment]
The Problem is only in Chrome in Safari it works

**Comment by baetzmr** [comment]
Tested a few browsers with 1.0.8

Safari - works
Edge - works
Firefox - works
Chromium (Pi) - empty device list
Chrome - empty device list

All devices working as expected and no errors in the log

**Comment by backfisch88** [comment]
> Tested a few browsers with 1.0.8
> 
> Safari - works Edge - works Firefox - works Chromium (Pi) - empty device list Chrome - empty device list
> 
> All devices working as expected and no errors in the log

Chrome is my main browser. Works for me.

**Comment by EugenEule** [comment]
Downgrade to 1.0.3 -> everything runs without problems
Upgrade to 1.0.4 -> adapter crashes
Upgrade to 1.0.5 -> adapter crashes
Upgrade to 1.0.6 -> adapter runs, but no UI with Firefox and Edge
Upgrade to 1.0.8 -> adapter runs, UI works fine with Firefox, but not with Edge

**Comment by tarikweiss** [comment]
https://github.com/jensweigele/ioBroker.yahka/pull/489

**Comment by mattreim** [comment]
Now it also works with chrome. Thanks

**Comment by spoeh-man** [comment]
1.0.9 fixed the issue for me

**Comment by marrrkus** [comment]
1.0.9 fixed the issue for me

Thank you guys!

**Comment by tarikweiss** [comment]
Adapter should run by now. I think the issue may be closed @GermanBluefox. thank you! :)

**Comment by EugenEule** [comment]
runs fine with Edge! Thanx!
