### ISSUE TITLE
Error: inverse: converting value to ioBroker: false to NaN

### ISSUE THREAD

**Issue by saykl** [jensweigele/ioBroker.yahka#49]
I use to turn on 0. To turn off 1. When I click on the iPhone button, the object is cleared. Type of object is integer.

log https://yadi.sk/d/F4wVJxkm3URZ9j

**Comment by jensweigele** [comment]
Sorry - I'm a bit late, but can you give me the config you used?

**Comment by jensweigele** [comment]
I think the problem should be solved with the current master.
If you still have problems, feel free to reopen the ticket.
