### ISSUE TITLE
Support for Electricity Usage in iOS 18

### ISSUE THREAD

**Issue by boernei** [jensweigele/ioBroker.yahka#499]
Thank you for the great work on Yahka! 
I’m wondering if anyone has looked into the new electricity usage feature introduced in iOS 18 HomeKit. I’m unsure whether Apple implemented this as a new accessory or characteristic. Does anyone have more information on this?

If we can determine how it works, it might be possible to add support for it in Yahka.

**Comment by unstressable** [comment]
I think this is only for matter accessoires.
Homekit native is not in development anymore as far as I know.

on long term we all have to switch to matter.
Hope there will be a good ioBroker integration soon.

**Comment by tarikweiss** [comment]
Hmm, first iobroker integration tests for matter are running. I also think, that the support for energy data in Home is not natively available in HomeKit. You may use the community types and Eve app for energy consumption. Thank you!

**Comment by unstressable** [comment]
@boernei or use this workaround instead:
![Uploading IMG_0288.jpeg…]()

**Comment by tarikweiss** [comment]
Yet it's still a workaround and may not be suitable for your situation, as this may lead to inaccurate responses from Siri if you ask for temperature.
