### ISSUE TITLE
npm rights

### ISSUE THREAD

**Issue by GermanBluefox** [jensweigele/ioBroker.yahka#5]
Hello!
you implementation is good, but it needs some updates.
If you will not maintain it, I could do it for you, but I need npm rights to do that.
can you give it to me?

`npm owner add bluefox`

Thank you.

**Comment by GermanBluefox** [comment]
Looks like I need to rename it to io-homekit...

**Comment by jensweigele** [comment]
Hi,

I will give you the credentials this afternoon or tomorrow.I'm currently on way.

Best Regards

**Comment by jensweigele** [comment]
done
Would you like to maintain the project? 
I'm currently to busy to do anything on it.

**Comment by GermanBluefox** [comment]
I must :) to maintain. 

Thank you.
