### ISSUE TITLE
Regler für Helligkeit oder Rollläden funktionieren seit einiger Zeit nicht mehr zuverlässig

### ISSUE THREAD

**Issue by unstressable** [jensweigele/ioBroker.yahka#504]
Hab YAHKA 1.0.9.

Seit einiger Zeit, vermute iOS 17.x habe ich das Problem, dass die Helligkeitsregler und Rollläden nicht mehr zuverlässig und sehr langsam reagieren.

Auch wenn ich eine neue Testlampe in YAHKA anlege und dort über den Helligkeitsregler eine Helligkeit auswähle kommt diese Infos nur sehr verzögert (wenn überhaupt) in meinem ioBroker Test-Objekt an.
Der Lampenschalter an sich, also Lampe an/aus kommt sofort und zuverlässig.

Interessant dabei: Wenn ich es über Siri steuere und z.B. sage "Lampe auf 10%" egal ob der Befehl von Apple TV, Homepod oder iPhone kommt reagiert es sofort.

Nur in der Homeapp selbst über die Regler funktioniert es nicht zuverlässig.

Habt ihr das auch?

**Comment by tarikweiss** [comment]
Hi, hast du zufällig eine Gerätekonfig (aus dem Yahka)? Dann kann ich das Issue ggf. fixen und einen PR aufmachen. Außerdem könntest du ggf. die State-Typen dahinter dazupacken? Dann kann ich mir ein Testgerät zusammenbauen und versuchen das Problem nachzustellen. Besteht das Issue auch mit Slidern in dimmbaren Lampen?

Danke!

**Comment by unstressable** [comment]
@tarikweiss 
Ja, bei allen Slidern besteht das Problem, auch bei Lampen.

Hier die Konfiguration:
<img width="691" alt="image" src="https://github.com/user-attachments/assets/c8ab7913-efca-4913-a5de-3836b456d323">

<img width="692" alt="image" src="https://github.com/user-attachments/assets/ad7d93fe-7285-47a3-8e02-fe2a3ec66852">

**Comment by tarikweiss** [comment]
Ich schaue mir das Problem mal an. Bei iOS 18.x was ich täglich im Einsatz habe konnte ich keine Probleme mit Slidern feststellen. Gibt es möglicherweise eine Rückkopplung bzgl. `ack=true`?

**Comment by tarikweiss** [comment]
Passiert das in Versoin 1.0.3 auch? Wenn ja, dann vermute ich mal, dass es kein YAHKA spezifisches Problem ist und man müsste den Use-Case mal zusammen anschauen. Gerne dann im Discord oder so.

**Comment by unstressable** [comment]
Bin auf 1.0.9 aktuell.
Hab mehrere Versionen probiert, alle zeigten das Verhalten.

Problem trat nach einem iOS Update auf. Welches weiß ich nicht mehr.

Die angebotene Hilfe ist sehr nett!

Kannst du dich per PN bei mir melden?

**Comment by tarikweiss** [comment]
Schreib mir einfach mal auf Discord, ich kann dich leider nicht finden.

**Comment by unstressable** [comment]
Ich hab das Ganze nochmals getestet und merke, dass es aktuell wie zuvor funktioniert.
Auch zuverlässig. Hab extra 2 Tage getestet.

Was ich vor diesen 2 Tagen geändert hatte ist die feste Zuordnung des Hubs.
Diese option kam auch im Zuge einer der letzten iOS-Updates und stand zuvor auf automatisch.

Ich dachte mir, dass ich das Apple TV im Wohnzimmer nehme, weil dieses per Ethernet angebunden ist.
Zuvor hat er von selbst oft den Homepod gewählt, der eine schlechte Wifi Verbindung hat.

![image](https://github.com/user-attachments/assets/bca07292-c1c1-40df-aef0-e46a25c01c94)

**Comment by unstressable** [comment]
Das einzige, was ich noch feststelle, aber das war leider immer so, ist, dass diese Slider "unter dem Finger zittern".

Also sie reagieren so schnell, dass die Rollos sofort losfahren, wenn man den Slider etwas bewegt.
Das doofe ist aber, dass der Rollo dann wieder anhält, und weiter fährt.

Ich hänge hier mal ein Video an, das zeigt was ich meine. Man sieht es beim hochfahren des Rollos.

Jemand eine Idee, wie man das unterbinden kann?

https://github.com/user-attachments/assets/0c010b0a-15af-4bdc-a5c6-99d2f483ae30

**Comment by tarikweiss** [comment]
Hmm, hier wäre eine Entprellung eine sinnvolle Sache, die an sich mit Skript/Blockly beispielsweise gelöst werden könnte. Ich weiß nicht, ob es an sich mit YAHKA geht (ich glaube nicht). Das wäre dann sonst ein Thema für Discord/Forum. Wenn es sonst kein direktes Issue gibt mit YAHKA (dem Thema betreffend), würde ich dich bitten die Fragen ins Forum auszulagern. Vielen Dank :)

**Comment by tarikweiss** [comment]
Ich habe nochmal geschaut. Also für deinen Use-Case wäre vermutlich der Deferred-State bei der Auswahl das korrekte, der hat nämlich bereits einen Debounce-Timer eingebaut (150ms). Ich hoffe der reicht. Man könnte mal noch einbauen, dass man den selbst konfigurieren kann. Aber bevor ich die Thematik angehen kann bräuchte ich noch etwas Zeit.

**Comment by unstressable** [comment]
Nutze den Defered bereits.
Reicht wohl nicht.

wäre super, wenn man den konfigurieren könnte.

**Comment by unstressable** [comment]
Also mittlerweile läuft es wieder zuverlässig.

Ich habe in der Home App in den Einstellungen einen festen Hub hinterlegt.
Bei mir der AppleTV per LAN angebunden.

Vorher war es auf Automatisch wählen und da wurde oft der Homepod verwendet, der bei mir eine schlechte WLAN Verbindung hat.
