### ISSUE TITLE
Crash wenn man zu Homekit hinzufügt

### ISSUE THREAD

**Issue by wk1991** [jensweigele/ioBroker.yahka#52]
Jedes mal, wenn ich die Bridge zu Homekit adden will, crasht der Adapter.
Node.js ist auf version 6.14, sämtliche libs aus dem Wiki installiert.

Bitte hier um hilfe, stehe leider an

Log:

host.iobroker | 2018-05-01 10:55:44.775 | info | Restart adapter system.adapter.yahka.0 because enabled
-- | -- | -- | --
host.iobroker | 2018-05-01 10:55:44.775 | error | instance system.adapter.yahka.0 terminated with code 0 (OK)
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught by controller[112]: Tue, 01 May 2018 08:55:44 GMT engine.io-client:socket flushing 1 packets in socket
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught  by controller[111]: Tue, 01 May 2018 08:55:44 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":false,"ack":true,"from":"system.adap
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught by controller[110]: Tue, 01 May 2018 08:55:44 GMT socket.io-client:socket emitting packet with ack id 4
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught  by controller[109]: Tue, 01 May 2018 08:55:44 GMT  socket.io-client:socket calling ack 3 with  [null,"system.adapter.yahka.0.alive"]
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught  by controller[108]: Tue, 01 May 2018 08:55:44 GMT  engine.io-client:socket socket receive: type "message", data  "33[null,"system.adapter.yahka.0.alive"]"
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught by controller[107]: Tue, 01 May 2018 08:55:44 GMT engine.io-client:socket flushing 1 packets in socket
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught  by controller[106]: Tue, 01 May 2018 08:55:44 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":false,"ack":true,"from":"system.adap
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught by controller[105]: Tue, 01 May 2018 08:55:44 GMT socket.io-client:socket emitting packet with ack id 3
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught by controller[104]:     at process._tickCallback (internal/process/next_tick.js:104:9)
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught by controller[104]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught by controller[104]:     at endReadableNT (_stream_readable.js:974:12)
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught by controller[104]:     at IncomingMessage.emit (events.js:185:7)
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught by controller[104]:     at emitNone (events.js:86:13)
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught by controller[104]:     at HAPServer. (/opt/iobroker/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught by controller[104]:     at HAPServer._handlePairVerify (/opt/iobroker/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught  by controller[104]:     at HAPServer._handlePairVerifyStepOne  (/opt/iobroker/node_modules/hap-nodejs/lib/HAPServer.js:517:30)
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught  by controller[104]:     at  Object.generateCurve25519PublicKeyFromSecretKey  (/opt/iobroker/node_modules/hap-nodejs/lib/util/encryption.js:42:30)
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught by controller[104]:     at Object.exports.derivePublicKey (/opt/iobroker/node_modules/curve25519-n2/index.js:25:11)
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught by controller[104]: TypeError: binding.curve is not a function
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught by controller[103]: Tue, 01 May 2018 08:55:40 GMT engine.io-client:socket flushing 7 packets in socket
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught  by controller[103]: Tue, 01 May 2018 08:55:40 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.outputCount",{"val":8,"ack":true,"from":"system.ad
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught  by controller[103]: Tue, 01 May 2018 08:55:40 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.inputCount",{"val":0,"ack":true,"from":"system.ada
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught  by controller[103]: Tue, 01 May 2018 08:55:40 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.uptime",{"val":15,"ack":true,"from":"system.adapte
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught  by controller[103]: Tue, 01 May 2018 08:55:40 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.memHeapUsed",{"val":15.92,"ack":true,"from":"syste
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught  by controller[103]: Tue, 01 May 2018 08:55:40 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.memHeapTotal",{"val":21.1,"ack":true,"from":"syste
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught  by controller[103]: Tue, 01 May 2018 08:55:40 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.memRss",{"val":45.43,"ack":true,"from":"system.ada
host.iobroker | 2018-05-01 10:55:44.775 | error | Caught  by controller[103]: Tue, 01 May 2018 08:55:40 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.connected",{"val":true,"ack":true,"expire":30,"fro
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[103]: Tue, 01 May 2018 08:55:40 GMT engine.io-client:socket flushing 1 packets in socket
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[103]: Tue, 01 May 2018 08:55:40 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":true,"ack":true,"expire":30,"from":"
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[102]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket flushing 2 packets in socket
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[101]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["pushLog","system.adapter.admin.0",{"message":"yahka.0  adding Sony with UUID: 51c507b
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[100]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["pushLog","system.adapter.admin.0",{"message":"yahka.0  adapter ready, checking config
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[99]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket flushing 1 packets in socket
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[98]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["pushLog","system.adapter.admin.0",{"message":"yahka.0  starting. Version 0.7.1 in /opt
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[97]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:socket calling ack 2 with  [null,[{"val":true,"ack":true,"ts":1525164854575,"q":0,"from":"system.adapter.admin.0","lc":152516485
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[96]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:socket socket receive: type "message", data  "32[null,[{"val":true,"ack":true,"ts":1525164854575,"q":0,"from":"system.adapter.ad
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[95]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket flushing 1 packets in socket
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[95]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["getStates",["system.adapter.admin.0.logging"]],"options":{"compress":true},"id":2,"ns
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[95]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:socket emitting packet with ack id 2
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[95]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:socket calling ack 1 with  [null,["system.adapter.admin.0.logging"]]
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[95]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:socket socket receive: type "message", data  "31[null,["system.adapter.admin.0.logging"]]"
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[94]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket flushing 10 packets in socket
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[93]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["subscribe","yahka.0.checkLogging",null],"options":{"compress":true},"nsp":"/"}
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[92]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.outputCount",{"val":8,"ack":true,"from":"system.ada
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[91]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.inputCount",{"val":0,"ack":true,"from":"system.adap
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[90]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.uptime",{"val":0,"ack":true,"from":"system.adapter.
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[89]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.memHeapUsed",{"val":17.89,"ack":true,"from":"system
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[88]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.memHeapTotal",{"val":26.1,"ack":true,"from":"system
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[87]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.memRss",{"val":50.25,"ack":true,"from":"system.adap
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[86]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.connected",{"val":true,"ack":true,"expire":30,"from
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[85]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":true,"ack":true,"expire":30,"from":"s
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[84]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["subscribe","*.logging",null],"options":{"compress":true},"nsp":"/"}
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[83]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket flushing 1 packets in socket
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[83]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["getKeys","*.logging"],"options":{"compress":true},"id":1,"nsp":"/"}
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[83]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:socket emitting packet with ack id 1
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[83]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:socket calling ack 0 with  [null,{"_id":"system.adapter.yahka.0","type":"instance","common":{"name":"yahka","version":"0.7.1","n
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[82]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:socket socket receive: type "message", data  "30[null,{"_id":"system.adapter.yahka.0","type":"instance","common":{"name":"yahka"
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[81]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling ignoring poll - transport state "paused"
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[81]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket clearing existing transport polling
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[81]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket setting transport websocket
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[81]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket changing transport and sending upgrade packet
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[81]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling paused
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[81]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling pre-pause polling complete
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[80]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket flushing 1 packets in socket
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[79]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["getObject","system.adapter.yahka.0",null],"options":{"compress":true},"id":0,"nsp":"/
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[78]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:socket emitting packet with ack id 0
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[77]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:socket calling ack 0 with  [null,{"val":false,"ack":true,"ts":1525164922502,"q":0,"from":"system.host.iobroker","lc":15251649224
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[76]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:socket socket receive: type "message", data  "30[null,{"val":false,"ack":true,"ts":1525164922502,"q":0,"from":"system.host.iobro
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught  by controller[75]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:polling polling got data  108:430[null,{"val":false,"ack":true,"ts":1525164922502,"q":0,"from":"system.host.iobroker","lc":15251
host.iobroker | 2018-05-01 10:55:44.774 | error | Caught by controller[74]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling pre-pause writing complete
host.iobroker | 2018-05-01 10:55:44.772 | error | Caught by controller[73]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling we are currently writing - waiting to pause
host.iobroker | 2018-05-01 10:55:44.772 | error | Caught by controller[73]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling we are currently polling - waiting to pause
host.iobroker | 2018-05-01 10:55:44.772 | error | Caught by controller[72]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket pausing current transport "polling"
host.iobroker | 2018-05-01 10:55:44.772 | error | Caught by controller[71]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket probe transport "websocket" pong
host.iobroker | 2018-05-01 10:55:44.772 | error | Caught by controller[70]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling-xhr xhr data null
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught  by controller[69]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:polling-xhr xhr open GET:  http://127.0.0.1:9000/socket.io/?EIO=3&transport=polling&t=MCQwU6Y&b64=1&sid=YvN0yWRInSPorxNiAAAb
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught by controller[68]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling-xhr xhr poll
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught by controller[67]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling polling
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught  by controller[66]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:polling-xhr xhr data  46:420["getState","system.adapter.yahka.0.alive"]
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught  by controller[65]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:polling-xhr xhr open POST:  http://127.0.0.1:9000/socket.io/?EIO=3&transport=polling&t=MCQwU6X&b64=1&sid=YvN0yWRInSPorxNiAAAb
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught by controller[64]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket flushing 1 packets in socket
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught  by controller[63]: Tue, 01 May 2018 08:55:25 GMT  socket.io-client:manager writing packet  {"type":2,"data":["getState","system.adapter.yahka.0.alive"],"options":{"compress":true},"id":0,"nsp":"/
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught by controller[62]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:socket emitting packet with ack id 0
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught by controller[61]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket socket receive: type "message", data "0"
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught by controller[60]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling polling got data 2:40
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught by controller[59]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket probe transport "websocket" opened
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught by controller[58]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling-xhr xhr data null
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught  by controller[57]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:polling-xhr xhr open GET:  http://127.0.0.1:9000/socket.io/?EIO=3&transport=polling&t=MCQwU6T&b64=1&sid=YvN0yWRInSPorxNiAAAb
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught by controller[56]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling-xhr xhr poll
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught by controller[56]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling polling
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught by controller[55]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket creating transport "websocket"
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught by controller[54]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket probing transport "websocket"
host.iobroker | 2018-05-01 10:55:44.771 | error | Caught by controller[54]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket starting upgrade probes
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[54]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:socket transport is open - connecting
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[54]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:manager cleanup
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[54]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:manager open
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[53]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket socket open
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught  by controller[52]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:socket socket receive: type "open", data  "{"sid":"YvN0yWRInSPorxNiAAAb","upgrades":["websocket"],"pingInterval":25000,"pingTime
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught  by controller[51]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:polling polling got data  97:0{"sid":"YvN0yWRInSPorxNiAAAb","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[50]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling ignoring poll - transport state "paused"
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[49]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket clearing existing transport polling
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[48]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket setting transport websocket
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[47]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket changing transport and sending upgrade packet
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[46]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling paused
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[45]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling pre-pause polling complete
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[44]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:manager readyState opening
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[43]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:manager connect attempt will timeout after 20000
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[42]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket setting transport polling
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[41]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling-xhr xhr data null
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught  by controller[40]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:polling-xhr xhr open GET:  http://127.0.0.1:9000/socket.io/?EIO=3&transport=polling&t=MCQwU6P&b64=1
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[39]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling-xhr xhr poll
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[38]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling polling
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[37]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket creating transport "polling"
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[37]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:manager opening http://127.0.0.1:9000
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[37]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:manager readyState closed
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[37]: Tue, 01 May 2018 08:55:25 GMT socket.io-client new io instance for http://127.0.0.1:9000
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[36]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:url parse http://127.0.0.1:9000
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[35]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket socket receive: type "message", data "0"
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[34]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling polling got data 2:40
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[33]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling we are currently polling - waiting to pause
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[32]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket pausing current transport "polling"
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[31]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket probe transport "websocket" pong
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[30]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket probe transport "websocket" opened
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[29]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling-xhr xhr data null
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught  by controller[28]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:polling-xhr xhr open GET:  http://127.0.0.1:9001/socket.io/?EIO=3&transport=polling&t=MCQwU6A&b64=1&sid=27SkhmQwFVJpjzi7AAAa
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[27]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling-xhr xhr poll
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[26]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling polling
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[25]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket creating transport "websocket"
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[24]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket probing transport "websocket"
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[23]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket starting upgrade probes
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[22]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:socket transport is open - connecting
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[21]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:manager cleanup
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[20]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:manager open
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[19]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket socket open
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught  by controller[18]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:socket socket receive: type "open", data  "{"sid":"27SkhmQwFVJpjzi7AAAa","upgrades":["websocket"],"pingInterval":25000,"pingTime
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught  by controller[17]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:polling polling got data  97:0{"sid":"27SkhmQwFVJpjzi7AAAa","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[16]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:manager readyState opening
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[15]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:manager connect attempt will timeout after 20000
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[14]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket setting transport polling
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught by controller[13]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling-xhr xhr data null
host.iobroker | 2018-05-01 10:55:44.770 | error | Caught  by controller[13]: Tue, 01 May 2018 08:55:25 GMT  engine.io-client:polling-xhr xhr open GET:  http://127.0.0.1:9001/socket.io/?EIO=3&transport=polling&t=MCQwU5l&b64=1
host.iobroker | 2018-05-01 10:55:44.768 | error | Caught by controller[12]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling-xhr xhr poll
host.iobroker | 2018-05-01 10:55:44.768 | error | Caught by controller[11]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:polling polling
host.iobroker | 2018-05-01 10:55:44.768 | error | Caught by controller[10]: Tue, 01 May 2018 08:55:25 GMT engine.io-client:socket creating transport "polling"
host.iobroker | 2018-05-01 10:55:44.768 | error | Caught by controller[9]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:manager opening http://127.0.0.1:9001
host.iobroker | 2018-05-01 10:55:44.768 | error | Caught by controller[8]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:manager readyState closed
host.iobroker | 2018-05-01 10:55:44.768 | error | Caught by controller[7]: Tue, 01 May 2018 08:55:25 GMT socket.io-client new io instance for http://127.0.0.1:9001
host.iobroker | 2018-05-01 10:55:44.768 | error | Caught by controller[6]: Tue, 01 May 2018 08:55:25 GMT socket.io-client:url parse http://127.0.0.1:9001
host.iobroker | 2018-05-01 10:55:44.768 | error | Caught by controller[5]: *** WARNING *** For more information see
host.iobroker | 2018-05-01 10:55:44.768 | error | Caught by controller[4]: *** WARNING *** Please fix your application to use the native API of Avahi!
host.iobroker | 2018-05-01 10:55:44.767 | error | Caught  by controller[3]: *** WARNING *** The program 'nsolid' called  'DNSServiceRegister()' which is not supported (or only supported  partially) in the Apple Bonjour compatibility layer of Avahi.
host.iobroker | 2018-05-01 10:55:44.767 | error | Caught by controller[2]: *** WARNING *** For more information see
host.iobroker | 2018-05-01 10:55:44.767 | error | Caught by controller[1]: *** WARNING *** Please fix your application to use the native API of Avahi!
host.iobroker | 2018-05-01 10:55:44.767 | error | Caught by controller[0]: *** WARNING *** The program 'nsolid' uses the Apple Bonjour compatibility layer of Avahi.

**Comment by jensweigele** [comment]
Die ganzen "Caught by Controller"-Meldungen sollten mit den neusten Versionen von ioBroker weg sein.
Bitte updaten, nochmal testen und log-level für yahka auf "Debug" stellen.
