### ISSUE TITLE
feature request:  service-type for power consumption

### ISSUE THREAD

**Issue by schroedingerscat8** [jensweigele/ioBroker.yahka#56]
hi yahka-team,

first all yahka works perfectly (actually yahka is a major reason for me to use iobroker).

However, I have one feature request: display or support for power consumption

Many wall-plugs (like the Fibaro or the Homematic wall plug) include an energy meter, meaning they also measure
- the actual energy consumption
- the total energy consumption

yahka so far just supports the switch-function (on/off)  but seems not to support "energy consumption"

It would be great to have either
- an additional service-typ "Energy meter"
or
- additonlly in the "Merkmalsliste" of the service-type "outlet" the   "Merkmale"   acutal energy-consumption an total energy-consumption.

This feature would be highly appreciated.

best regards
schroedinger

**Comment by jensweigele** [comment]
The Services and Characteristics are predefined by Apple (with their HomeKit protocol).
I try to have a look at iOS12 to see if there are new services/characteristics which support your use-case

For now I'll close the issue.

**Comment by juamiso** [comment]
> hi yahka-team,
> 
> first all yahka works perfectly (actually yahka is a major reason for me to use iobroker).
> 
> However, I have one feature request: display or support for power consumption
> 
> Many wall-plugs (like the Fibaro or the Homematic wall plug) include an energy meter, meaning they also measure
> 
> * the actual energy consumption
> * the total energy consumption
> 
> yahka so far just supports the switch-function (on/off) but seems not to support "energy consumption"
> 
> It would be great to have either
> 
> * an additional service-typ "Energy meter"
>   or
> * additonlly in the "Merkmalsliste" of the service-type "outlet" the   "Merkmale"   acutal energy-consumption an total energy-consumption.
> 
> This feature would be highly appreciated.
> 
> best regards
> schroedinger

Hi, I was also looking for displaying power levels and I have found out that you can use lightlevel sensor ”CurrentAmbientLightLevel” as a workaround to this. It shows live a value from 0 to 100.000, only that it reads “lux” next to it. But otherwise for me is working ;)

**Comment by dfrozen** [comment]
Apple HomeKit no avalabe  "Energy meter" deviases.  Only CurrentAmbientLightLevel is suitable for transferring via yahka to Apple devices, there should be some watering device for consumption, but has not yet found the exact parameter.

**Comment by schroedingerscat8** [comment]
very good idea. I've tried that -> and it works. Indeed a good workaround

**Comment by sannc** [comment]
Is there any news on this issue. I would prefer a final solution, not just a workaround … maybye iOS 14 has the necessary service types?

**Comment by nicoh88** [comment]
https://github.com/jensweigele/ioBroker.yahka/issues/120#issuecomment-733587461

**Comment by sannc** [comment]
Cool. Danke :-)

**Comment by nick2525** [comment]
does Apple accept some kind of feedback on the protocol?  Is it possible to write something to Apple to add power consumption?  This is not at all friendly, as the trend is to protect the environment.
