### ISSUE TITLE
Fehler beim installieren unter Windows 7 

### ISSUE THREAD

**Issue by juergen2908** [jensweigele/ioBroker.yahka#59]
Hallo Jens,

ich habe ioborker auf Windows 7 x64 am laufen. ich bekomme beim instllieren des yahka folgenden Fehler:

`
$ ./iobroker add yahka 
NPM version: 3.10.10
npm install iobroker.yahka --production --save --prefix "C:/ioBroker" (System call)
gyp
 
ERR! configure error gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp 
ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"gyp ERR! cwd C:\ioBroker\node_modules\iobroker.yahka\node_modules\curve25519-n
gyp ERR! node -v v6.11.1

gyp ERR! node-gyp -v v3.4.0gyp ERR! not ok 

npm
 ERR! Windows_NT 6.1.7601npm ERR! 
argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iobroker.yahka" "--production" "--save" "--prefix" "C:/ioBroker"npm ERR! node v6.11.1
npm ERR! npm 
 v3.10.10npm ERR! code ELIFECYCLE

npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n@1.4.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the curve25519-n package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs curve25519-n
npm ERR! Or if that isn't available, you can get their info via:

npm ERR!     npm owner ls curve25519-nnpm ERR!
 There is likely additional logging output above.

npm ERR! Please include the following file with any support request:npm ERR!     C:\ioBroker\node_modules\iobroker\npm-debug.log
npm
 ERR! code 1
host.iobroker-PC install adapter yahka
NPM version: 3.10.10npm install iobroker.yahka --production --save --prefix "C:/ioBroker" (System call)

gyp
 ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)

gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\ioBroker\node_modules\iobroker.yahka\node_modules\curve25519-n
gyp ERR! node -v v6.11.1gyp 
ERR! node-gyp -v v3.4.0gyp ERR! not ok 

npm
 ERR!
 Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iobroker.yahka" "--production" "--save" "--prefix" "C:/ioBroker"npm ERR! node v6.11.1
npm ERR! npm  v3.10.10

npm ERR! code ELIFECYCLE

npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n@1.4.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the curve25519-n package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs curve25519-n
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls curve25519-n
npm ERR!
 There is likely additional logging output above.

npm ERR! Please include the following file with any support request:npm ERR!     C:\ioBroker\node_modules\iobroker\npm-debug.log
npm ERR! code 1

host.iobroker-PC install adapter yahka
NPM version: 3.10.10
npm install iobroker.yahka --production --save --prefix "C:/ioBroker" (System call)
gyp
 
ERR! configure error gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack
     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601

gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"gyp ERR! cwd C:\ioBroker\node_modules\iobroker.yahka\node_modules\curve25519-n
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Windows_NT 6.1.7601npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iobroker.yahka" "--production" "--save" "--prefix" "C:/ioBroker"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n@1.4.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the curve25519-n package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs curve25519-n
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls curve25519-n
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ioBroker\node_modules\iobroker\npm-debug.log
npm ERR! code 1

host.iobroker-PC install adapter yahka
ERROR: host.iobroker-PC Cannot install yahka
ERROR: process exited with code 1
`

installiert ist 
node.js v6.11.1
 npm 3.10.10
 js-controller 1.4.2
python 2.7.14

LG

Jürgen

**Comment by jensweigele** [comment]
ERR! configure error gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

Python kann nicht gefunden werden. 
Schau dir mal #45 an, dort ist ein Link auf eine andere Anleitung, mit der eigentlich alles funktionieren sollte.
Falls nicht, bitte Ticket wieder eröffnen
