### ISSUE TITLE
typescript compile error

### ISSUE THREAD

**Issue by jensweigele** [jensweigele/ioBroker.yahka#6]
@GermanBluefox: the current master brings some typescript compile errors:

Compiling...
Using tsc v2.2.0
typings/index.d.ts(2,1): error TS6053: File 'typings/es6-promise/es6-map.d.ts' not found.
yahka.ioBroker-adapter.ts(22,21): error TS2304: Cannot find name 'Map'.
yahka.ioBroker-adapter.ts(22,70): error TS2304: Cannot find name 'Map'.
yahka.ioBroker-adapter.ts(23,22): error TS2304: Cannot find name 'Map'.
yahka.ioBroker-adapter.ts(23,71): error TS2304: Cannot find name 'Map'.

Is there something not commited?

**Comment by GermanBluefox** [comment]
https://github.com/jensweigele/ioBroker.yahka/commit/e26e71f2df1bff42cb3b403b2110c82139508358#diff-ce57164ed8bba082e0c3b2f1508f11b6
