### ISSUE TITLE
Missing Conversion funktion for Momematic IP Blind Actuators

### ISSUE THREAD

**Issue by BenHel** [jensweigele/ioBroker.yahka#60]
Current conversion function HomematicDirectionToHomekitPositionState covers only Homematic classic direction state:

hm-rpc.0.XXX.1.DIRECTION
    0 NONE 
    1 UP 
    2 DOWN

and converts it into Homekit equivalents.

However Homematic IP does not have a 'Direction' state and the actual direction must be determined by status of 'Process' state and comparison of 'LEVEL' state (old value vs. new value).

hm-rpc.2.XXX.4.PROCESS
    0 STABLE     - Motor not running
    1 NOT_STABLE - Motor running

hm-rpc.2.XXX.4.LEVEL
    old:   0 % new: 100 % Direction = UP
    old: 100 % new:   0 % Direction = Down
    etc. 
    
Thnaks a lot!

**Comment by DutchmanNL** [comment]
I assume this can be closed as HomeMatic  IP. actor has the "ACTIVITY_STATE" state with 

0 = unknown
1 = opening
2 = closing
3 = stopped

**Comment by nicoh88** [comment]
@BenHel @DutchmanNL 

Were you able to solve the problem?

**Comment by nicoh88** [comment]
Leider, keine Antwort. Schließe Issue!  
Unfortunately, no answer. Close Issue!
