### ISSUE TITLE
Its always crashing

### ISSUE THREAD

**Issue by Rexima** [jensweigele/ioBroker.yahka#61]
host.RUMHEIM01	2018-08-08 19:04:58.871	error	instance system.adapter.yahka.0 terminated with code 6 (uncaught exception)
Caught	2018-08-08 19:04:58.871	error	by controller[105]: Wed, 08 Aug 2018 17:04:58 GMT engine.io-client:socket flushing 1 packets in socket
Caught	2018-08-08 19:04:58.871	error	by controller[105]: Wed, 08 Aug 2018 17:04:58 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":false,"ack":true,"from":"system.adapter.ya
Caught	2018-08-08 19:04:58.870	error	by controller[104]: Wed, 08 Aug 2018 17:04:58 GMT socket.io-client:socket emitting packet with ack id 8
Caught	2018-08-08 19:04:58.870	error	by controller[103]: Wed, 08 Aug 2018 17:04:58 GMT engine.io-client:socket flushing 1 packets in socket
Caught	2018-08-08 19:04:58.870	error	by controller[102]: Wed, 08 Aug 2018 17:04:58 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":false,"ack":true,"from":"system.adapter.ya
Caught	2018-08-08 19:04:58.869	error	by controller[101]: Wed, 08 Aug 2018 17:04:58 GMT socket.io-client:socket emitting packet with ack id 7
Caught	2018-08-08 19:04:58.869	error	by controller[100]: Wed, 08 Aug 2018 17:04:57 GMT engine.io-client:socket flushing 1 packets in socket
Caught	2018-08-08 19:04:58.869	error	by controller[99]: Wed, 08 Aug 2018 17:04:57 GMT socket.io-client:manager writing packet {"type":2,"data":["setState","system.adapter.yahka.0.alive",{"val":false,"ack":true,"from":"system.adapter.yah
Caught	2018-08-08 19:04:58.868	error	by controller[98]: Wed, 08 Aug 2018 17:04:57 GMT socket.io-client:socket emitting packet with ack id 6
Caught	2018-08-08 19:04:58.868	error	by controller[97]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
Caught	2018-08-08 19:04:58.868	error	by controller[97]: at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught	2018-08-08 19:04:58.867	error	by controller[97]: at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
Caught	2018-08-08 19:04:58.867	error	by controller[97]: at Manager.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:133:20)
Caught	2018-08-08 19:04:58.867	error	by controller[97]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught	2018-08-08 19:04:58.867	error	by controller[97]: at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
Caught	2018-08-08 19:04:58.866	error	by controller[97]: at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
Caught	2018-08-08 19:04:58.866	error	by controller[97]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.yahka/yahka.function-factory.js:71:13)
Caught	2018-08-08 19:04:58.866	error	by controller[97]: at /opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-bridge.js:153:17
Caught	2018-08-08 19:04:58.866	error	by controller[97]: at /opt/iobroker/node_modules/hap-nodejs/lib/util/once.js:12:13
Caught	2018-08-08 19:04:58.865	error	by controller[97]: Error: This callback function has already been called by someone else; it can only be called one time.
Caught	2018-08-08 19:04:58.865	error	by controller[96]: Wed, 08 Aug 2018 17:04:57 GMT socket.io-client:socket calling ack 4 with [null,{"val":true,"ack":false,"ts":1533744053700,"q":0,"from":"system.adapter.yahka.0","lc":1533744053672}]
Caught	2018-08-08 19:04:58.865	error	by controller[95]: Wed, 08 Aug 2018 17:04:57 GMT engine.io-client:socket socket receive: type "message", data "34[null,{"val":true,"ack":false,"ts":1533744053700,"q":0,"from":"system.adapter.yahka.0"
Caught	2018-08-08 19:04:58.864	error	by controller[94]: Wed, 08 Aug 2018 17:04:57 GMT socket.io-client:socket calling ack 3 with [null,{"val":true,"ack":false,"ts":1533744053700,"q":0,"from":"system.adapter.yahka.0","lc":1533744053672}]
Caught	2018-08-08 19:04:58.864	error	by controller[94]: Wed, 08 Aug 2018 17:04:57 GMT engine.io-client:socket socket receive: type "message", data "33[null,{"val":true,"ack":false,"ts":1533744053700,"q":0,"from":"system.adapter.yahka.0"
Caught	2018-08-08 19:04:58.864	error	by controller[93]: Wed, 08 Aug 2018 17:04:57 GMT engine.io-client:socket flushing 2 packets in socket
Caught	2018-08-08 19:04:58.863	error	by controller[92]: Wed, 08 Aug 2018 17:04:57 GMT socket.io-client:manager writing packet {"type":2,"data":["getState","hm-rpc.0.OEQ1212661.3"],"options":{"compress":true},"id":5,"nsp":"/"}
Caught	2018-08-08 19:04:58.863	error	by controller[91]: Wed, 08 Aug 2018 17:04:57 GMT socket.io-client:socket emitting packet with ack id 5
Caught	2018-08-08 19:04:58.863	error	by controller[90]: Wed, 08 Aug 2018 17:04:57 GMT socket.io-client:manager writing packet {"type":2,"data":["getState","hm-rpc.0.OEQ1212661.3"],"options":{"compress":true},"id":4,"nsp":"/"}
Caught	2018-08-08 19:04:58.862	error	by controller[90]: Wed, 08 Aug 2018 17:04:57 GMT socket.io-client:socket emitting packet with ack id 4
Caught	2018-08-08 19:04:58.862	error	by controller[89]: Wed, 08 Aug 2018 17:04:57 GMT engine.io-client:socket flushing 1 packets in socket
Caught	2018-08-08 19:04:58.862	error	by controller[89]: Wed, 08 Aug 2018 17:04:57 GMT socket.io-client:manager writing packet {"type":2,"data":["getState","hm-rpc.0.OEQ1212661.3"],"options":{"compress":true},"id":3,"nsp":"/"}
Caught	2018-08-08 19:04:58.861	error	by controller[88]: Wed, 08 Aug 2018 17:04:57 GMT socket.io-client:socket emitting packet with ack id 3
Caught	2018-08-08 19:04:58.861	error	by controller[87]: Wed, 08 Aug 2018 17:04:55 GMT engine.io-client:socket flushing 1 packets in socket
Caught	2018-08-08 19:04:58.860	error	by controller[87]: Wed, 08 Aug 2018 17:04:55 GMT socket.io-client:manager writing packet {"type":2,"data":["subscribe","hm-rpc.0.OEQ1212661.3",null],"options":{"compress":true},"nsp":"/"}
Caught	2018-08-08 19:04:58.859	error	by controller[87]: ka wyboru\nZaktualizuj tłumaczenia"},"1.1.2":{"en":"Fixing the saving of project\nFixing the background selector\nFixing the null pointer problem\nFixing the selection helper\nUpda

**Comment by jensweigele** [comment]
For me it looks like #55 
Will try to check that

**Comment by jensweigele** [comment]
Do you still have this problem?
