### ISSUE TITLE
Very high MEM usage

### ISSUE THREAD

**Issue by captaindork** [jensweigele/ioBroker.yahka#62]
Hi,

Thanks again for this great adapter!
However I have serious RAM issues. In a normal idle idle state my ioBroker shows around 40% of free RAM (RPI3). I an quite happy with this, but whenever yahka is restarted (or crashes) my whole ioBroker crashes (ENOMEM Exception).
In my opinion this is due to the fact, that when yahka is started it shows 300 to 400 MB of MEM usage for the first ~30s.
So what I am doing to mitigate this is to stop all adapters, start yahka, wait till MEM usage from yahka gets lower, then start all other adapters.
Issue is: This can only be done in a controlled fashion. Whenever yahka restarts due to a crash, everything crashes...

Sure I could probably mitigate all this by buying Hardware with more RAM... but to be honest 40% free in a normal State should be enough, Right? However it isn‘t for yahka.
Is there any Chance to do some performance tuning for yahka, or some throttling during yahka start?

Thanks

**Comment by captaindork** [comment]
Unfortunately still present, to be honest even worse. Any log that would help?

**Comment by foxriver76** [comment]
I don't think that high RAM usage is caused by the logging. How many devices do you use with YAHKA? Mem usage at adapter start is round about 45 MB growing to 75 MB over time on my system, but I do not use many devices with the adapter. Maybe it somehow correlates with the number of devices.

**Comment by jensweigele** [comment]
Please try again with version 0.8.2

**Comment by captaindork** [comment]
Absolutely Insane @jensweigele !

I an using yahka since the early 0.5.0 releases and can tell: It never ran that good!
Consumption starts with 36, goes up to 110, then 118, then back to 86 and 46. All this within a minute, without errors and without iobroker crashing even if i start it as the last adapter.

Even if yahka always stayed my preferred HK Interface (coming from homebridge-Homematic and also Node-red) this one was really frustrating. You can‘t believe how happy I am -> Thanks for your work on finding this one!!!
