### ISSUE TITLE
Parameter des Service werden nicht angezeigt

### ISSUE THREAD

**Issue by vansemtt** [jensweigele/ioBroker.yahka#69]
![yahka-problem](https://user-images.githubusercontent.com/38660422/46421029-9318c880-c731-11e8-87e7-55ec06afff2b.png)
Hallo,
wie im angehängten .png zu sehen, werden mir die ausgewählten Parameter nicht angezeigt. Die InOut Params sind nicht einmal auswählbar.
Habe den Adapter bereits neu installiert, und verwende die aktuelle Version.
Liebe Grüße
Matthias Vanselow

**Comment by jensweigele** [comment]
Welcher Browser und welche Admin Version nutzt du?

**Comment by vansemtt** [comment]
Moin Jens,
ich benutze firefox und die aktuelle Admin Version 3.5.10... und: Ups: aufgrund Deiner Frage gerade Safari probiert, und da funktioniert es einwandfrei.
Die Safari Version ist: Version 12.0.1 (13606.2.104.1.2),
firefox ist 63.0.3 (64-Bit)

Liebe Grüße
Matthias Vanselow

Tel.:     04533 204511
Mobil: 0170 400 8989
Mail:   matthias@vanselow.com

Datum: Dienstag, 4. Dezember 2018 um 21:14
Cc: vansemtt <matthias@vanselow.com>, Author <author@noreply.github.com>


Welcher Browser und welche Admin Version nutzt du?

**Comment by jensweigele** [comment]
Wird mit der naechsten Version gefixt sein
