### ISSUE TITLE
Rolläden über KNX

### ISSUE THREAD

**Issue by matze1708** [jensweigele/ioBroker.yahka#7]
Hallo,

gibt es im Yahka eine möglichkeit , wenn ich die Rolläden über KNX steuer, die Werte um zudrehen?

Das heißt, meine Aktoren geben zurück 0% für Rolladen auf und 100% für Rolladen zu. 

Wenn ich die Rolläden über yahka eingebunden habe, dann zeigt es mir bei 0% Rolladen geschlossen und bei 100% Rolladen geöffnet an. 

Kann man das irgendwie einbauen?

Danke

**Comment by GermanBluefox** [comment]
Du bist schon weit gekommen. :)

Pull request?

31 Июл 2017 г. 16:10 пользователь "matze1708" <notifications@github.com>
написал:

**Comment by matze1708** [comment]
Das ist TypeScipt oder? Da kenne ich mich nicht mit aus...

Es würde doch gehen wenn ich die ID vom KNX Objekt, welches mir den Wert z.B. 65% gibt mit 100 Subtrahieren.

Also 100- ID

Was meinst du?

Kann der yahka das ggf. auch ohne Klasse? Sprich als Variable vorgeben?

Wollte ich eben probieren... dann habe ich aber deine Nachricht gesehen.

**Comment by matze1708** [comment]
Weitere Idee.....und GLeichzeitig Frage:

`239     "ioBroker.State.OnlyACK": function (adapter:ioBroker.IAdapter, parameters:any):IInternalInOutFunction { 
240         if (typeof parameters !== "string") 
241             return undefined; 
242         let stateName:string = parameters; 
243 
 
244         return new TIoBrokerInOutFunction_State_OnlyACK(adapter, stateName); 
245     }, 
`

Wenn man hier im Parameter eine Rechnung vorgibt... Wie muss die aussehen?

**Comment by matze1708** [comment]
@Bluefox
Hattest du dir meine Nachricht angesehen? Hast du eine Idee oder Ansatz?

**Comment by matze1708** [comment]
Hallo,
das Thema ist bei mir noch offen. Können wir uns über einen Lösungsansatz unterhalten

**Comment by DutchmanNL** [comment]
Fuer interessierte, script im forum welches dies moeglich macht

- alle KNX rollaeden eine enum.functions.rolladen gruppieren
- script erstellt neue objecten und rechnet die werte um

http://forum.iobroker.net/viewtopic.php?f=20&t=7340&p=95386&hilit=knx#p95386

**Comment by jensweigele** [comment]
In der nächsten Version gibt es eine Conversion Function "inverse". Damit kann man deine Anforderung erfüllen. In das "Parameterfeld" musst du den Maximalwert eintragen. Willst du also 0 - 100 auf 100 - 0 mappen, muss in das Parameterfeld der wert "100".

Testen kannst du das ganze schon gegen den aktuellen Master oder du wartest auf das nächste Release

**Comment by DutchmanNL** [comment]
Cool, super das du das als Standard einbaust!

**Comment by matze1708** [comment]
Klasse! Das finde ich richtig gut.
Danke!

**Comment by COMHOME** [comment]
Habe nun auch auf die Beta aktualisiert - finde jedoch keine Möglichkeit, "inverse" auszuwählen in der Combo-Box - weiß jemand, an welcher Stelle ich das einbauen kann?

**Comment by Ropdepil** [comment]
Hi, 
habe versucht fibaro roller shutter 2 einzubinden. bei mir ist auch das problem, dass die positionen vertauscht sind. also 100%=göffnet und 0%=geschlossen. habe es mit inverse probiert aber funktioniert leider nicht. es wird immer der Wert "null" gesendet. Weiß jemand um Rat? LG

**Comment by COMHOME** [comment]
Hi, hast du auf inverse gestellt und 100 in das Feld eingetragen? Sonst funktioniert die Berechnung natürlich nicht...

**Comment by Ropdepil** [comment]
ahhh :) Danke für den Hinweiß. Pfobier ich gleich mal aus

**Comment by Ropdepil** [comment]
Jetzt geht es! Danke nochmal für die schnelle Hilfe!!
was bei Fibaro bisschen blöd ist, dass der Wert Level von 0-99 geht. Also wenn ich wenn 100 gesendet wird macht er deswegen nicht. Wie könnte man das mit yahka lösen?

**Comment by COMHOME** [comment]
Trag doch eine 99 ein statt 100

**Comment by mdietz666** [comment]
Hi, ich hab die Funktion bei mir geändert, die das Umrechnen übernimmt.
Sie ist jetzt flexibler:
- muss nicht mehr bei 0 anfangen, d.h. es geht auch -90 bis +90
- es funktionieren auch negative Werte und inverse werte, also geht auch
ioBroker 0-100, umgerechnet zu 90 bis -90
Es kombiniert also auch die Invert Funktion
Könnte das bitte jemand so einbauen?
v
"scaleInt": function (adapter, parameters) {
var paramArray = JSON.parse(parameters);
function getParameter(name) {
if (paramArray === undefined)
return undefined;
var value = paramArray[name];
if (value === undefined)
return undefined;
if (typeof value === 'number')
return value;
else
return parseInt(value);
}
return {
toHomeKit: function (value) {
var num = undefined;
if (typeof value !== 'number')
num = parseInt(value);
else
num = value;
var homeKitMax = getParameter("homekit.max");
var ioBrokerMax = getParameter("iobroker.max");
let homeKitMin = getParameter("homekit.min");
let ioBrokerMin = getParameter("iobroker.min");
let newValue = Math.round(((num-ioBrokerMin) / (ioBrokerMax-ioBrokerMin)) *
(homeKitMax-homeKitMin)+homeKitMin);
adapter.log.debug('scaleInt: converting value to homekit: ' + value + ' to '
+ newValue);
return newValue;
},
toIOBroker: function (value) {
var num = undefined;
if (typeof value !== 'number')
num = parseInt(value);
else
num = value;
var homeKitMax = getParameter("homekit.max");
var ioBrokerMax = getParameter("iobroker.max");
let homeKitMin = getParameter("homekit.min");
let ioBrokerMin = getParameter("iobroker.min");
let newValue = Math.round(((num-homeKitMin) / (homeKitMax-homeKitMin)) * (
ioBrokerMax-ioBrokerMin)+ioBrokerMin);
adapter.log.debug('scaleInt: converting value to ioBroker: ' + value + ' to
' + newValue);
return newValue;
}
};

VG
Markus

Am 3. März 2018 um 10:21 schrieb Ropdepil <notifications@github.com>:

**Comment by Ropdepil** [comment]
hallo mdietz666,
danke für deine Hilfe. Muss vorweg sagen, dass ich mich noch nicht so gut auskenne was programmieren anbetrifft. Versteh ich das richtig, dass ich jetzt ein skript in iobroker anlegen muss mit deiner vorlage und dann diesen als datenpunkt im yahka adapter oder wo trage ich diese funktion ein?
Also meine fibaro aktoren können einen Werte von 0 (geöffnet) bis 99 (geschlossen) annehmen. -1 ist für den aktor wieder 99 aber weiter nimmt er keine zahlen an im negativen bereich. ich bräucht quasi eine inverse funktion die mir die zahlen 0-99 umdreht. 
LG und vielen Dank

**Comment by jensweigele** [comment]
Im aktuellen Develop-Branch sind die Änderungen von @mdietz666  drin.

**Comment by Cytron1980** [comment]
Hallo zusammen, 
Habe den Adapter in Version 0.7.1 installiert. Jedoch möchte ich ebenfalls die Umkehr der Rollläden realisieren. mir werden bei der Umwandlungsfunktion nur die drei üblichen Verdächtigen angezeigt... also nichts mit inverse etc... woran kann das liegen ?
Gruß Roman

**Comment by eumats** [comment]
RTFM
Guck mal unter https://github.com/jensweigele/ioBroker.yahka/wiki/Installation-and-Troubleshooting im Bereich Troubleshooting. Das sollte helfen.

**Comment by Cytron1980** [comment]
Och Mensch,
das Ärgert mich jetzt. Hab TFM schon gelesen gehabt, dachte aber, dass das Troubleshooting für den Fall, dass Fehler im Log auftauchen gültig ist.
Aber :  Es Hat geklappt ! Dankeschön :)
Sehr gute Arbeit deinerseits.

Schöne Grüße

Roman
