### ISSUE TITLE
No Category and Service-Typ to select

### ISSUE THREAD

**Issue by kristofferkokus** [jensweigele/ioBroker.yahka#71]
Hello i can not pick any Category nor Service-Typ like seen in the pictures
<img width="1477" alt="bildschirmfoto 2018-10-22 um 19 03 56" src="https://user-images.githubusercontent.com/44375593/47306754-923ace80-d62d-11e8-8f32-005026220257.png">
<img width="1481" alt="bildschirmfoto 2018-10-22 um 19 04 22" src="https://user-images.githubusercontent.com/44375593/47306755-95ce5580-d62d-11e8-967b-89732174ea5b.png">

**Comment by jensweigele** [comment]
Which Browser and which admin version are you using?

**Comment by jensweigele** [comment]
Looks a bit like this: https://github.com/jensweigele/ioBroker.yahka/issues/80

Please reopen the issue if this problem still exists
