### ISSUE TITLE
Not showing up in Home App

### ISSUE THREAD

**Issue by henkhb** [jensweigele/ioBroker.yahka#73]
I can't add the Yahka Bridge to ios. After entering the pin code nothing could be found by the device. Any ideas? Running ioBroker on Synology disk station.

**Comment by adrianoje** [comment]
Yes, please try to rename the Yahka bridge in the instance settings. As soon as i putted in another name it appeard in Homekit (had before the same issue)

**Comment by jensweigele** [comment]
as @adrianoje  said: rename the adapter.
The next version will use another name by default.
