### ISSUE TITLE
Thermostat Manuel / Aus / Heizung Problem

### ISSUE THREAD

**Issue by theAnDrO40** [jensweigele/ioBroker.yahka#78]
Hallo habe ein Floureon Thermostat und habe da zwei kleine Problem Ansicht funktioniert das super mit dem Yahka Adapter. Nun zu meinem Problemen das Thermostat versteht set_mode damit kann ich zwischen Manuel Mode = 0 und Auto Mode = 1 dann gibt es noch set_power damit kann ich das Thermostat anschalten und ausschalten. Bei vorgewählter Temperatur und eingeschaltetem Thermostat auf Heizung set_power = 1 und set_temp = xy wird der Raum aufgeheizt das ist der Manual Mode.So das Problem ist wenn ich mit Siri arbeite z.B. Siri stelle das Thermostat in Raum X auf 28 Grad springt er im HoneKit auf automatisch laut Log mit dem Zahlenwert 3 das müsste eigentlich auf Heizung gestellt werden set_power = 1, set_temp = xy und nicht auf automatisch und für den Modus automatisch müsste er extra set_mode = 1 ausführen. Wäre das realisierbar ? 

Ich danke schonmal im Voraus

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jensweigele** [comment]
Verstehe deine Beschreibung nicht ganz. Wenn du per Siri die Heizung einschaltest, wird „set_mode“ auf 3 gesetzt?

**Comment by theAnDrO40** [comment]
Sorry für die umständliche Beschreibung ich probiere es nochmal.
Also wenn ich das über Siri einstellen lasse sprich „Siri stelle das Thermostat in Raum X auf 28 grad“ z.B. Springt er direkt im HomeKit auf automatisch was dem Wert set_power 3 entspricht das Thermostat kennt aber nur set_power 0 = aus oder 1 für Thermostat an also Aus oder Heizung im HomeKit plus zusätzlich den Befehl für set_mode 1 für den Auto Mode was in dem HomeKit dem Befehl automatisch entsprechen würde wo er direkt hinspringt und halt set_mode 0 wieder für Manual Mode was dem vorherigen Manual einstellten werden entsprechen würde. Ich hoffe es ist nicht wieder zu kompliziert geschrieben 

Also dem HomeKit entsprechen bei Thermostat :

Aus = set_power 0 oder set_mode 0 (von automatisch wieder in den Manual Mode vorherige Einstellung)
Heizung = set_power 1 oder set_mode 0 (von automatisch wieder in den Manual Mode vorherige Einstellung)
Automatisch = set_mode 1 (für die eingespeicherten Daten im Thermostat)

Kühlung kommt nicht vor im Thermostat wäre in dem Fall auch wieder Thermostat ausgeschaltet 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jensweigele** [comment]
Ich kann deiner Beschreibung immernoch nicht ganz folgen, vermute aber, das dir die neue "Map" Conversion Funktion helfen könnte.
Damit solltest du deinen Konfiguration abbilden können:
0 <-> 0
1 <-> 1
1 <-> 2
1 <-> 3
