### ISSUE TITLE
Zigbee Adapter / Tradfri / HSV RGB Hex

### ISSUE THREAD

**Issue by theAnDrO40** [jensweigele/ioBroker.yahka#79]
Hallo zusammen zu meinem Problem. Ich habe mir einen zigbee Stick zugelegt cc2531 um Ikea Tradfri daran zu betreiben min habe ich ein Problem Dimmen funktioniert einwandfrei und an und ausschalten das einzige was nicht funktioniert ist colortemp und color. Bei dem Problem mit color bin ich schon einen kleinen Schritt weiter habe heraus gefunden das es in Hex eingegeben werden muss. Kann das irgendwie heraus aus dem Adapter realisiert werden ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jensweigele** [comment]
Kannst du mal ein Screenshot machen, wie die Datenpunkte aussehen bzw. welche Werte man senden muss?

**Comment by theAnDrO40** [comment]
Gerne werde ich dir dann hier reinstellen wenn ich nachher zuhause bin.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by theAnDrO40** [comment]
Also habe schon einen Weg gefunden zwar ein wenig umständlich aber nach langer Suche hat es geklappt mittels JavaScript wandeln der HSV in RGB / Hex

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Cobblepott** [comment]
Hallo, ich habe dasselbe Problem. Gibt es dazu schon was Neues?

@theAnDrO40: Wie hast löst Du das momentan?

**Comment by theAnDrO40** [comment]
@Cobblepott habe das gelöst mit einem JavaScript den ich dir hier posten kann plus die Einstellungen im YAHKA Adapter 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vain90** [comment]
Hallo zusammen,
ich habe ein GLEDOPTO RGB+CCT. Via des zigbee Adapter möchte dieser auch einen RGB (HEX) Wert als Farbe haben. Wie theAnDrO40 bereits geschrieben hat, gibt es eine Lösung via JavaScript. Diese funktioniert bei mir auch. Hier der entsprechende Forumsbeitrag: https://www.forum.iobroker.net/topic/16282/yahka-hue-color-nach-hex-convertieren/25

Allerdings ist das doch irgendwie eine Krücke und verkompliziert das ganze doch erheblich.
Man benötigt für jede RGB Leuchte zwei virtuelle Datenpunkte und das entsprechende Script.

Richtig schön wäre es aber, wenn man direkt in dem Yahka eine Umwandlung in RGB vollziehen könnte. Wobei das nicht ganz trivial scheint. Man muss die Werte aus dem Hue-Wert und der Saturation berechnen. Aber vielleicht gibt es da eine Möglichkeit.

Ich würde mich auf jeden Fall sehr freuen.

**Comment by nicoh88** [comment]
+1

[Hier](https://forum.iobroker.net/post/379827) schön dokumentiert.

**Comment by nicoh88** [comment]
Duplicate of #76

**Comment by nicoh88** [comment]
Lösung in #76
