### ISSUE TITLE
Thermostat im yahka

### ISSUE THREAD

**Issue by matze1708** [jensweigele/ioBroker.yahka#8]
Hallo,

wie kann ich beim anlegen eines Thermostates es so einstellen, das immer auf Heizen gestellt ist?

Ich meine die Funktion für die Betriebsart. 

Lässt sich da eine Constante eintragen?

Wie ich dies probiert habe, hatte ich z.B. eine 2 auf der rechten Seite eingestellt. Thermostat in der App hatte nicht geantwortet.

Bitte um ein Beispiel.

Danke :-)

**Comment by jensweigele** [comment]
Eine Konstante kannst du mit der "InOutFunction" "const" realisieren. Den Wert den du möchtest muss in das Parameterfeld (neben der InOutFunction).
Hier https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js kannst du die notwendigen Konstanten finden. In deinem Fall: Characteristic.CurrentHeaterCoolerState.HEATING = 2;

**Comment by matze1708** [comment]
Danke! Versuche ich
Das Semikolon am Ende ist notwendig?

**Comment by jensweigele** [comment]
Du musst nur den Wert eintragen ("2" - ohne ")

**Comment by matze1708** [comment]
Sorry jetzt muss ich nochmal einhaken, 

Es muss dann im Feld nur 2 stehen nicht Characteristic.CurrentHeaterCoolerState.HEATING = 2

und const als InoutFunction. 

Ich meine das hatte ich schon mal so gemacht....

**Comment by jensweigele** [comment]
Ja, einfach nur 2
