### ISSUE TITLE
Wie füge ich eine Conversion Function hinzu?

### ISSUE THREAD

**Issue by DanielWeeber** [jensweigele/ioBroker.yahka#81]
Habe mir einen Fork erstellt, da die aktuellen Conversion Functions bei weitem nicht ausreichen alles abzubilden.
Wollte dann meine eigene Funktion hinzufügen (Colortemperatur wird von Apple als Einheit Mired übergeben, ioBroker erwartet Kelvin), leider ohne Erfolg.

Habe einen Eintrag in io-package.json unter native (id yahka.meta._conversionFunctions) und in yahka.function-factory.js dort wo level255 und hue auch ist die Function hinzugefügt. Keine Syntaxfehler im Log, etc. Adapter startet normal.

Wird nicht in der GUI angezeigt. Wo ist mein Fehler?

**Comment by jensweigele** [comment]
Aus meiner Sicht sollte das funktionieren.
Hast du den Adapter in ioBroker auch installiert/upgedated und hochgeladen? (iobroker upload yahka)

Ich überarbeite gerade die Conversion und IO Funktionen und hatte vor die Funktionen aus den Metadaten zu entfernen, da ich dachte das das eh niemand nutzt.
Kannst du mir die Funktionen geben, die dir fehlen?

**Comment by DanielWeeber** [comment]
Bin aktuell gerade unterwegs, vielen Dank für deine Antwort.
Den upload hab ich bestimmt vergessen, wäre meine erste Änderung im ioBroker gewesen. Muss da noch lernen.

Bei der aktuellen Version des hue package wird für Farbeinstellung Kelvin als Einheit erwartet, Apple gibt aber Mired aus. Dazu bräuchte ich eine Conversion Function (1e6/<input>). Mit der neuen Version und der Scriptmöglichkeit sollte das ja gehen, das muss ich mir aber noch in Ruhe anschauen.
