### ISSUE TITLE
Microphone zur IPCamera hinzufügen

### ISSUE THREAD

**Issue by DanielWeeber** [jensweigele/ioBroker.yahka#82]
Kannst du vielleicht den Service Microphone (https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#3196) zur IPCam hinzufügen? So würden wir auch Ton haben.
ffmpeg muss enable libfdk-aac haben, damit das klappt.
Und natürlich eine zweite Map, sah für Homebridge so aus:

>         if(this.audio){
>         ffmpegCommand+= ' -map 0:1' +
>         ' -acodec ' + acodec +
>             ' -profile:a aac_eld' +
>             ' -flags +global_header' +
>            ' -f null' +
>           ' -ar ' + asamplerate + 'k' +
>          ' -b:a ' + abitrate + 'k' +
>         ' -bufsize ' + abitrate + 'k' +
>           ' -ac 1' +
>           ' -payload_type 110' +
>           ' -ssrc ' + audioSsrc +
>           ' -f rtp' +
>         ' -srtp_out_suite AES_CM_128_HMAC_SHA1_80' +
>       ' -srtp_out_params ' + audioKey.toString('base64') +
>        ' srtp://' + targetAddress + ':' + targetAudioPort +
>         '?rtcpport=' + targetAudioPort +
>          '&localrtcpport=' + targetAudioPort +
>           '&pkt_size=' + packetsize;
>        }
>

**Comment by nicoh88** [comment]
@DanielWeeber Hi, wurde der Wunsch mit der Version` 0.11.0` gelöst oder besteht der Wunsch noch immer?

**Comment by jensweigele** [comment]
@DanielWeeber : im aktuellen Master "könnte" das funktionieren.
Du musst in der Kamera "Enable Audio" anhaken und die FFMPEG Audio-Parameters auf standard zurücksetzen.
Ich kann das nur mit Video-Files testen und dort hat es nur mit libfdk_aac funktioniert und Video und Audio waren nicht synchron. Vielleicht funktioniert das aber mit "richtiger" Hardware besser.

**Comment by DanielWeeber** [comment]
Vielen Dank, dass du dir das mal anschaust.
Leider funktioniert mit 0.12.0 gar keine Kamera mehr, egal ob Enable Audio angeklickt ist oder nicht.

```

2020-11-18 00:32:17.664 - debug: yahka.0 (25782) Snapshot run: ffmpeg -re -i rtsp://admin:******@192.168.1.7:554/live/ch1 -t 1 -s 640x360 -f image2 -
--
2020-11-18 00:32:20.789 - debug: yahka.0 (25782) Stream run: ffmpeg -nostats -nostdin -y -re -i rtsp://admin:*******@192.168.0.7:554/live/ch1 -map 0:v:0 -threads 0 -vcodec libfdk_aac -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 4881847 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params QdYSpj0A5aP+WGNAIjyxQXuh4IOl+Vg2H37AAuLj srtp://192.168.1.136:64405?rtcpport=64405&localrtcpport=64405&pkt_size=1378
2020-11-18 00:32:20.996 - debug: yahka.0 (25782) FFMPEG: received first frame
2020-11-18 00:32:22.455 - error: yahka.0 (25782) [Video] ffmpeg exited with code: 1 and signal: null (error)


```

**Comment by jensweigele** [comment]
Sorry - hab mich falsch ausgedrückt.
Für Video muss "lib264" bleiben.
Für Audio wird über die Parameter aktuell IMMER libfdk_aac genutzt. Wichtig ist, dass FFMpeg das unterstützt (was es standardmäßig nicht macht)

Probier nochmal bitte mit lib264 mit Enable Audio.

Falls du Probleme hast, führe FFMPEG mal manuell im Terminal aus (mit der Kommandozeile die Yahka im Log generiert).
Damit kannst du zumindest mal sehen, ob FFMPEG einen Fehler wirft.

**Comment by DanielWeeber** [comment]
```
root@iobroker:~/ffmpeg_sources/fdk-aac# ffmpeg -nostats -nostdin -y -re -i "rtsp://admin:**********@192.168.0.7:554/live/ch1" -map 0:v:0 -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 3209284 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params sU+5xarRNYwUWrkMWQ+OaIUmfyZFiVZyb3rUR+tB srtp://192.168.1.186:52625?rtcpport=52625&localrtcpport=52625&pkt_size=1378 -map 0:a:0 -acodec libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 24k -b:a 24k -bufsize:a 24k -ac 1 -payload_type 110 -ssrc 9242561 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 5lfV6Zzcx71HGANRDr1TvH0ffGQ55Podl3au/QGs srtp://192.168.1.186:54348?rtcpport=54348&localrtcpport=54348&pkt_size=1378
[1] 22182
[2] 22183
[3] 22184
[4] 22185
**root@iobroker:~/ffmpeg_sources/fdk-aac# bash: -map: Kommando nicht gefunden.**
ffmpeg version 3.2.12-1~deb9u1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, rtsp, from 'rtsp://admin:123456@192.168.0.7:554/live/ch1':
  Metadata:
    title           : hysxrtpsion
  Duration: N/A, start: 0.005322, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x360, 24.92 tbr, 90k tbn, 180k tbc
    Stream #0:1: Data: none
[libx264 @ 0x7fc746cc45a0] VBV maxrate unspecified, assuming CBR
[libx264 @ 0x7fc746cc45a0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
[libx264 @ 0x7fc746cc45a0] profile High, level 3.1
Output #0, rtp, to 'srtp://192.168.1.186:52625?rtcpport=52625':
  Metadata:
    title           : hysxrtpsion
    encoder         : Lavf57.56.101
    Stream #0:0: Video: h264 (libx264), yuv420p, 1280x720, q=-1--1, 299 kb/s, 30 fps, 90k tbn, 30 tbc
    Metadata:
      encoder         : Lavc57.64.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/299000 buffer size: 299000 vbv_delay: -1
SDP:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=hysxrtpsion
c=IN IP4 192.168.1.186
t=0 0
a=tool:libavformat 57.56.101
m=video 52625 RTP/AVP 99
b=AS:299
a=rtpmap:99 H264/90000
a=fmtp:99 packetization-mode=1
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:sU+5xarRNYwUWrkMWQ+OaIUmfyZFiVZyb3rUR+tB

Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))

```

**Comment by jensweigele** [comment]
```
**root@iobroker:~/ffmpeg_sources/fdk-aac# bash: -map: Kommando nicht gefunden.**
```
Das wird die Ursache deines Problems sein. Ich schaue nachher mal, mit welcher FFMpeg Version ich getestet habe.

**Comment by jensweigele** [comment]
Kannst du beim manuellen Ausführen mal die 3 http://-Adressen in Quotes (") setzen?
ZSH kommt mit den URL angaben in der Kommandozeile nicht klar und wirft auch komische Fehlermeldungen.
Yahka macht das beim starten richtig - es geht nur darum, die tatsächliche Fehlermeldung von FFMPEG zu bekommen.

**Comment by DanielWeeber** [comment]
aha!

```
root@iobroker:~/bin# ffmpeg -nostats -nostdin -y -re -i "rtsp://admin:*****@192.168.0.7:554/live/ch1" -map 0:v:0 -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 10191016 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 2YH0Anlmat5VU2mf0q1lIqbTs+o4CaLae8RaMk8s "srtp://192.168.1.186:52405?rtcpport=52405&localrtcpport=52405&pkt_size=1378" -map 0:a:0 -acodec libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 24k -b:a 24k -bufsize:a 24k -ac 1 -payload_type 110 -ssrc 7214040 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params er85hzE1QqpmiBRLF34sHyKimdb3wT34uOOsGCjs "srtp://192.168.1.186:49836?rtcpport=49836&localrtcpport=49836&pkt_size=1378"
ffmpeg version N-99929-gbb7bb44 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --prefix=/root/ffmpeg_build --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --bindir=/root/bin --extra-libs=-ldl --enable-gpl --enable-libfdk-aac --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      56. 60.100 / 56. 60.100
  libavcodec     58.112.103 / 58.112.103
  libavformat    58. 64.100 / 58. 64.100
  libavdevice    58. 11.102 / 58. 11.102
  libavfilter     7. 90.100 /  7. 90.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, rtsp, from 'rtsp://admin:123456@192.168.0.7:554/live/ch1':
  Metadata:
    title           : hysxrtpsion
  Duration: N/A, start: 0.003167, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x360, 25 fps, 25 tbr, 90k tbn, 180k tbc
    Stream #0:1: Data: none
Stream map '0:a:0' matches no streams.
To ignore this, add a trailing '?' to the map.
root@iobroker:~/bin# 
```

**Comment by DanielWeeber** [comment]
Scheint gelöst zu sein, wenn man 
`-map 0:a:0?`
nimmt.

Jedenfalls kommt dann kein Fehler mehr bei ffmpeg.

**Comment by jensweigele** [comment]
Ja, damit wird der Fehler unterdrückt.
Aber die eigentliche Aussage ist ja, dass deine Kamera kein Audio unterstützt - genauer gesagt hat der  Stream "rtsp://admin:*****@192.168.0.7:554/live/ch1" keine Audio-Spur.

**Comment by DanielWeeber** [comment]
Jetzt wollt ich einmal hilfreich sein...
Hab die falsche Kamera genommen. Klappt. Es laggt ehrlich gesagt ziemlich, aber da teste ich auch nochmal weiter.

**Comment by jensweigele** [comment]
Hast du das schonmal Kamera + Sound via FFMPEG mit einer anderen Software hinbekommen (homebridge oder so)?

**Comment by jensweigele** [comment]
@DanielWeeber kannst du bitte nochmal die aktuelle Version aus dem Master installieren und die Audio + Video Parameter zurücksetzen?
In meinem Test läuft es nun flüssig

**Comment by DanielWeeber** [comment]
Im Gegensatz dazu, wenn ich den RTSP Stream per VLC öffne, dauert es 5-6 Sekunden, bis Audio durchgehend ankommt - aber es geht dann richtig gut!

**Comment by jensweigele** [comment]
Hast du nochmal die letzte Version des Master getestet und die Audio und Video parameter auf Standard zurückgesetzt?

**Comment by DanielWeeber** [comment]
Jo hatte ich. Gerade extra nochmal aktualisiert. Es fängt eigentlich sofort an mit dem Ton, dann 2-3 Sekunden Pause, dann gehts weiter. Stört mich nicht sehr, ist aber da.

**Comment by jensweigele** [comment]
Falls das mit HomeBridge oder einer anderen Software besser läuft: kannst du mal bitte schauen, welche Parameter an FFMPEG übergeben werden?
Ich hab recht lange die verschiedenen Parameter durchgespielt und bin mit den aktuellen Standards zum besten Erfolg gekommen.
Wobei ich auch ein Beispiel-Video habe, bei dem Bild und Ton stottern und FFMPEG das wohl nicht richtig hinbekommt.

**Comment by DanielWeeber** [comment]
Ich teste immer mit VLC gegen. 99% geht es da ruckelfrei, 1% mit ähnlichem Verhalten. Werde mal ein Homebridge installieren und schauen, wie es sich da verhält

**Comment by jensweigele** [comment]
@DanielWeeber bist du hierzu schon gekommen?

**Comment by DanielWeeber** [comment]
Schwierig ganz genau zu sagen, aber relativ ähnlich.

Ich werde mal eine andere Cam beschaffen und damit mal testen. Melde mich

**Comment by jensweigele** [comment]
Danke - mach das Ticket bitte wieder auf wenn du noch etwas herausbekommst - aus meiner Sicht sollte alles funktionieren
