### ISSUE TITLE
minTemp/maxTemp bei Thermostat

### ISSUE THREAD

**Issue by DanielWeeber** [jensweigele/ioBroker.yahka#84]
Hey,

schön wäre eine Möglichkeit die minTemp und maxTemp einzustellen bei dem Thermostat. HomeKit bietet das ohne Probleme, ist nur ein Eintrag.

https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2468

So hatte ich das im homebridge Plugin für maxcube gelöst:

https://github.com/normen/homebridge-platform-maxcube/blob/master/thermostat.js#L50

Ich suche auch schon die ganze Zeit die passende Stelle im Yahka, würde dann einen PR machen. 

Vielleicht findest du es ja schneller als ich ;)

**Comment by DanielWeeber** [comment]
Ich habe hier die letzten zwei Abende gesucht, aber soweit bin ich einfach noch nicht in deinen Code eingestiegen, dass ich es komplett verstanden hätte.
Wenn du mir einen Tipp gibst schaue ich gern weiter und erstelle einen PR.

**Comment by jensweigele** [comment]
Schau ich mir demnächst an - bin gerade dabei die IO und Conversion Functions umzubauen.

**Comment by DanielWeeber** [comment]
Einstellen der Parameter funktioniert. Super, danke.
Rest schau ich mir morgen genauer an.

**Comment by DanielWeeber** [comment]
Soll ich nach was speziellen schauen? Funktioniert super bis jetzt.

**Comment by jensweigele** [comment]
Nein , einfach nur schauen ob merkwürdige Sachen passieren.
