### ISSUE TITLE
Script Conversion Function killt Adapter

### ISSUE THREAD

**Issue by DanielWeeber** [jensweigele/ioBroker.yahka#85]
Hey,

hatte versucht Programmcode einzugeben in die neue Scriptfunktion, sowas wie "if (value == 1) { return 1 }". 
Daraufhin startete der Adapter nicht mehr, weil die io-package.json nur noch eine Zeile enthielt, und zwar diese hier:

> "_id": "yahka.meta_serviceDictionary",

Neuinstallation vom Adapter half dann aus

//edit:

> return (value == true?true);

killt die io-package.json zwar nicht, funktioniert aber auch nicht. 
Bei dem Beispiel würde ich gern nur den State weiterleiten an Apple, wenn value==true.
Anwendungszweck: ProgrammableSwitchEvent bei Doorbell. Die Signalisierung des Türklingel-Signals. Wenn ich z.B. ein Objekt kurz auf true, dann auf false schalte (=Türklingeln) wird es an Apple zwei mal gemeldet (einmal true, einmal false). Macht dann 2x klingeln bei Apple.

**Comment by jensweigele** [comment]
Kannst du das reproduzieren?
Ich habe dein Script (if....) bei mir eingebaut und konnte deinen Effekt nicht nachvollziehen.
Zumal das Admin-Interface nichts an der io-package.json ändert - es werden lediglich die Adapter Eigenschaften geändert.

Bezüglich der Türklingel: ich schau mir das bei Gelegenheit mal an. Dein Script liefert "undefined" an HomeKit, wenn der Klingelwert auf "false" geht - ich gehe davon aus, das die Klingel dann weiterhin zweimal in HomeKit signalisiert wird!?

**Comment by DanielWeeber** [comment]
Script-Fehler reproduzieren schaue ich heute Abend.
Ich schreibe nur jetzt schon, weil ich auf das zweite eine Antwort weiss: ja ;)
Wobei das halt nur ein möglicher Anwendungsfall wäre. Hab es jetzt über weitere virtuelle Datenpunkte gelöst

**Comment by DanielWeeber** [comment]
Hab grad schon getestet. Tatsächlich kann ich es gerade nicht mehr reproduzieren. Sobald es nochmal auftritt melde ich mich.

**Comment by kugelkopf123** [comment]
Hatte etwas ähnliches. Habe auch versucht ein Skript für mein Thermostat Mode zu einzufügen. War nichts großes. Eher sowas hier:  
if (value  == 1) {
        return 3;
    } 
 if (value  == 2) {
        return 1;
    } 
Danach startete der Adapter zwar wie gewohnt, war allerdings nicht mehr zu erreichen vom iPhone oder iPad aus. Habe das Skript wieder gelöscht aber es half nichts. Habe die üblichen Sachen probiert, neustart, Thermostat Gerät gelöscht, Neustart... Nichts hilft. Weiterhin sagt das iDevice die Geräte würden nicht antworten. Habe die MAC Adresse vom Adapter geändert um Ihn neu Hinzufügen zu können. Auch das brachte keine Besserung. Die Bridge lässt sich garnicht mehr hinzufügen. Ich komme bis zur Codeeingabe und danach bricht er ab.

**Comment by DanielWeeber** [comment]
Neuinstallation vom Adapter hilft dann auf jeden Fall. Einstellungen gehen nicht verloren beim "drüber installieren". 
Bitte deinen Log posten, müsste ne große rote Fehlermeldung sein.

**Comment by jensweigele** [comment]
Ich schließe dieses Issue. Sollte es Probleme geben, gerne wieder öffnen.
