### ISSUE TITLE
Option für Auswahl des Interfaces

### ISSUE THREAD

**Issue by DanielWeeber** [jensweigele/ioBroker.yahka#86]
Aktuell kann man nicht wählen auf welchem Interface die Instanz von Yahka läuft.
Avahi/mDNS sollten dann auch weiter funktionieren.
Aktueller Anwendungsfall bei mir: Habe zwei Subnetze. Möchte diese trennen mit einer eigenen Yahka Instanz, sodass die nur bestimmte Geräte hat und auch nur in diesem Subnetz gefunden wird.

Borsti im Forum hat ein ähnliches Problem:

https://forum.iobroker.net/viewtopic.php?f=20&t=20420

**Comment by jensweigele** [comment]
Soweit ich das sehe, gibt HAP-NodeJS das nicht her.
Nach kurzer Durchsicht des Codes, müsste man einen Pull-Request erstellen, um folgende Zeile um die IP zu erweitern:
https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/util/eventedhttp.js#L60

**Comment by DanielWeeber** [comment]
Ich frage, weils in Homebridge ging. Da hatte ich aber nur eine Instanz von homebridge auf eth1 (anstatt eth0) dann.

Avahi konfigurieren https://github.com/nfarina/homebridge/issues/607
mDNS Interface in HAP-NodeJS ändern (hier die homebrige Configzeile. Wird dann gesetzt bei HAP-NodeJS unter lib/server.js https://github.com/nfarina/homebridge/issues/1957

**Comment by jensweigele** [comment]
Danke für die Infos. Schau ich mir mal an!

**Comment by jensweigele** [comment]
Kannst du das mal mit dem aktuellen Master testen?
Bei mir auf dem Mac funktioniert der Adapter nur mit 0.0.0.0, wenn ich eine der IPs auswähle, erhalte ich EADDRINUSE (Port 5353) - der Port ist durch den mdnsResponder schon in Benutzung.

**Comment by jensweigele** [comment]
@DanielWeeber : konntest du das mal testen?

**Comment by DanielWeeber** [comment]
Leider noch nicht. Versuche es nächste Woche zu schaffen!

**Comment by DanielWeeber** [comment]
Spät, aber aktuell habe ich einen docker container auf einer Syno, wo das Interface ovs_eth0 heisst und nicht mehr eth0. Ist also "identisches" Problem wie hier gelöst werden sollte.
Erst musste ich Yahka auf das exakte Interface setzen, anstatt auf 0.0.0.0, damit Bonjour wieder klappte.  Nun funktioniert eigentlich alles wieder, bis auf die Kameras. Da scheint er noch über eth0 gehen zu wollen.
