### ISSUE TITLE
Carbon dioxide sensor CarbonDioxideLevel value and StatusActive not displayed

### ISSUE THREAD

**Issue by sonntam** [jensweigele/ioBroker.yahka#87]
I'm using Yahka Version 0.9.0 and I'm trying to display the data of carbon dioxide concentration sensor that outputs values in ppm units.

In Yahka I configured a sensor device with the "CarbonDioxideSensor" Service-Type.
The properties "CarbonDioxideLevel" and "CarbonDioxidePeakLevel" are assigned to ioBroker states. For testing I also tried to use the "const" output with a fixed value. But on the app the values are not shown (see screenshot below).

![asset](https://user-images.githubusercontent.com/6692408/50736381-352acf80-11bd-11e9-986f-7d29c5c463d5.png)

The other part that does not work is the "StatusActive" property. It always shows as inactive on the iPhone. I tried using the constant values 1, true, "true".

The only thing that seems to work is the "CarbonDioxideDetected" property. If I put a constant "1" there an alarm will go off on my iPhone.

**Comment by jensweigele** [comment]
Can you please post a screenshot of the configuration?

**Comment by sonntam** [comment]
Sure, here you go:

This is the state in the object tree: `mqtt.0.nodemcu.MH-Z19_Bedroom_634939.value`
![screenshot 2019-01-06 19 58 02](https://user-images.githubusercontent.com/6692408/50740383-c31eae80-11ed-11e9-82bd-7b7b1dc44bd9.png)

And this is the yahka config:
![screenshot 2019-01-06 20 02 00](https://user-images.githubusercontent.com/6692408/50740398-0b3dd100-11ee-11e9-9810-c34a5ce3c1d6.png)

**Comment by jensweigele** [comment]
Mit dem aktuellen Master sollte das Problem behoben sein.
Da ich einiges Umgestellt habe, wäre ich über Rückmeldungen, ob der Adapter an sich noch funktioniert dankbar!
