### ISSUE TITLE
Alle Geräte nicht mehr erreichbar...

### ISSUE THREAD

**Issue by thoduh** [jensweigele/ioBroker.yahka#9]
Nach einiger Zeit sind alle 66 Geräte (Homematic/CCU2) auf Fehler bzw. gesperrt.
Beim letzten mal musste ich die Mac-Adresse ändern und alle Geräte neu zuordnen, was sehr viel Zeit gekostet hat.

Ich bin überrascht wie extrem schlecht yahka.0 läuft (im Vergleich zu Homebridge).

Hat denn sonst niemand hier dieses Problem? Gibt es dazu keine Abhilfe?

Im Logfile steht nix.

Wenn ich jetzt ein neues Gerät hinzufüge, funktioniert das neue auch, die anderen Geräte aber nicht.

**Comment by jansios** [comment]
Schau Dir mal Issue #1 an, da geht es um das gleiche Thema. Leider hat sich der öffnende User nie wieder gemeldet, wie es scheint. Mehrere Issues zum selben Thema finde ich unpraktisch, wir sollten es dort konsolidiert betrachten, oder?

**Comment by jensweigele** [comment]
Ich schließe das Issue da es ein Duplikat zu https://github.com/jensweigele/ioBroker.yahka/issues/1 ist
