### ISSUE TITLE
Device properties via variable

### ISSUE THREAD

**Issue by ImhotepDE** [jensweigele/ioBroker.yahka#91]
Read out device properties optionally via ioBrocker.State or similar.

With this you can automatically read and enter the firmware, serial number, manufacturer etc..

<img width="794" alt="image" src="https://user-images.githubusercontent.com/46678124/51165153-90d11900-189f-11e9-9085-b859698d1eeb.png">

**Comment by ImhotepDE** [comment]
As soon as I add the service, there is always an error message:

TypeError: Cannot read property 'toString' of undefined

**Comment by jensweigele** [comment]
Where do you get this error?
In the admin console or when starting the adapter?

**Comment by ImhotepDE** [comment]
Once I add and save the service.

ioBroker.yahka does not start then and the error occurs in the LOG

**Comment by ImhotepDE** [comment]
If I don't specify a service typ (AccessoryInformation Service), there's a mistake:

Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service:

**Comment by jensweigele** [comment]
can you please enable the debug log for the Yahka Adapter?

**Comment by ImhotepDE** [comment]
`yahka.0	2019-01-24 11:31:41.209	info	adapter ready, checking config
yahka.0	2019-01-24 11:31:41.179	info	starting. Version 0.8.2 in /opt/iobroker/node_modules/iobroker.yahka, node: v8.15.0
yahka.0	2019-01-24 11:31:17.978	info	terminating
yahka.0	2019-01-24 11:31:17.910	info	cleaned up ...
yahka.0	2019-01-24 11:31:17.909	info	cleaning up ...
yahka.0	2019-01-24 11:31:17.905	error	at Adapter.emit (events.js:208:7)
yahka.0	2019-01-24 11:31:17.905	error	at emitNone (events.js:106:13)
yahka.0	2019-01-24 11:31:17.905	error	at TIOBrokerAdapter.adapterReady (/opt/iobroker/node_modules/iobroker.yahka/yahka.ioBroker-adapter.js:29:14)
yahka.0	2019-01-24 11:31:17.905	error	at TIOBrokerAdapter.createHomeKitBridges (/opt/iobroker/node_modules/iobroker.yahka/yahka.ioBroker-adapter.js:52:27)
yahka.0	2019-01-24 11:31:17.905	error	at new THomeKitBridge (/opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-bridge.js:14:14)
yahka.0	2019-01-24 11:31:17.905	error	at THomeKitBridge.init (/opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-bridge.js:24:38)
yahka.0	2019-01-24 11:31:17.905	error	at THomeKitBridge.createDevice (/opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-bridge.js:74:18)
yahka.0	2019-01-24 11:31:17.905	error	at THomeKitBridge.initService (/opt/iobroker/node_modules/iobroker.yahka/yahka.homekit-bridge.js:88:26)
yahka.0	2019-01-24 11:31:17.905	error	at new Service.AccessoryInformation (/opt/iobroker/node_modules/hap-nodejs/lib/gen/HomeKitTypes.js:2660:8)
yahka.0	2019-01-24 11:31:17.905	error	at Service.AccessoryInformation.Service.addCharacteristic (/opt/iobroker/node_modules/hap-nodejs/lib/Service.js:80:13)
yahka.0	2019-01-24 11:31:17.905	error	Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: xxxxxx-xxx-xxx-xxx-xxxxxxx
yahka.0	2019-01-24 11:31:17.904	error	uncaught exception: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: xxxxxx-xxx-xxx-xxx-xxxxxxx
yahka.0	2019-01-24 11:31:17.859	info	adding Ikea with UUID: xxxxx-xxx-xxx-x-xxxxxxxx
yahka.0	2019-01-24 11:31:17.830	info	adapter ready, checking config
yahka.0	2019-01-24 11:31:17.803	info	starting. Version 0.8.2 in /opt/iobroker/node_modules/iobroker.yahka, node: v8.15.0
yahka.0	2019-01-24 11:30:45.031	info	terminating
yahka.0	2019-01-24 11:30:44.951	info	cleaned up ...
yahka.0	2019-01-24 11:30:44.950	info	cleaning up ...`

**Comment by jensweigele** [comment]
Go to the "Adapters" Page
Click on the GitHub button (the button with the cat)
Select "Yahka" and click "install"
That's it

**Comment by ImhotepDE** [comment]
sorry, which button is meant?

![image](https://user-images.githubusercontent.com/46678124/51675836-26258900-1fd5-11e9-98e9-0d34d40d5c7f.png)

**Comment by ImhotepDE** [comment]
I found it... thank you.

**Comment by ImhotepDE** [comment]
The error is also present with the current version. 

Could you please write a working example where the AccessoryInformation Service function is used and also works

**Comment by jensweigele** [comment]
Can you please post the log again?
I've tried several times - just added the AccessoryInformation, checked "Model", "Serialnumber" and "Manufacturer", used the State-Function and used javascript datapoint.

**Comment by ImhotepDE** [comment]
yahka.0	2019-01-24 12:54:59.193	error	at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4990:18)
yahka.0	2019-01-24 12:54:59.193	error	at Adapter.emit (events.js:208:7)
yahka.0	2019-01-24 12:54:59.193	error	at emitNone (events.js:106:13)
yahka.0	2019-01-24 12:54:59.193	error	at TIOBrokerAdapter../yahka.ioBroker-adapter.ts.TIOBrokerAdapter.adapterReady (/opt/iobroker/node_modules/iobroker.yahka/main.js:2169:14)
yahka.0	2019-01-24 12:54:59.193	error	at TIOBrokerAdapter../yahka.ioBroker-adapter.ts.TIOBrokerAdapter.createHomeKitBridges (/opt/iobroker/node_modules/iobroker.yahka/main.js:2192:27)
yahka.0	2019-01-24 12:54:59.193	error	at new THomeKitBridge (/opt/iobroker/node_modules/iobroker.yahka/main.js:1583:14)
yahka.0	2019-01-24 12:54:59.193	error	at THomeKitBridge../yahka.homekit-bridge.ts.THomeKitBridge.init (/opt/iobroker/node_modules/iobroker.yahka/main.js:1595:42)
yahka.0	2019-01-24 12:54:59.193	error	at THomeKitBridge../yahka.homekit-bridge.ts.THomeKitBridge.createDevice (/opt/iobroker/node_modules/iobroker.yahka/main.js:1669:22)
yahka.0	2019-01-24 12:54:59.193	error	at THomeKitBridge../yahka.homekit-bridge.ts.THomeKitBridge.initService (/opt/iobroker/node_modules/iobroker.yahka/main.js:1711:23)
yahka.0	2019-01-24 12:54:59.193	error	at Accessory.addService (/opt/iobroker/node_modules/hap-nodejs/lib/Accessory.js:150:59)
yahka.0	2019-01-24 12:54:59.193	error	TypeError: Cannot read property 'toString' of undefined
yahka.0	2019-01-24 12:54:59.193	error	uncaught exception: Cannot read property 'toString' of undefined

**Comment by jensweigele** [comment]
Did you fill in the "Subtype" Fields?
The error you get has something to do with the Subtypes of the services.
Please let them empty - unless really needed.
If you enable the debug log again, you should see the service it tries to initialize just before the error occurs.

**Comment by ImhotepDE** [comment]
If I leave the service subtype empty, the error occurs:

yahka.0	2019-01-24 13:16:23.398	error	Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxxxxxxxx
yahka.0	2019-01-24 13:16:23.397	error	uncaught exception: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxxxxxxxx

**Comment by jensweigele** [comment]
Can you post more of the log?
I want to see which characteristic it is (and on which service)
Please make sure that the loglevel is debug

**Comment by jensweigele** [comment]
Any news on this?

**Comment by ImhotepDE** [comment]
sorry...

I have tested it with a heating thermostat, it works, with the lamp comes the said error

**Comment by jensweigele** [comment]
Can you make a screenshot of your configuration of the said lamp?
