### ISSUE TITLE
Can't upgrade from 0.8.2 to 0.9.0

### ISSUE THREAD

**Issue by Mr-REM-Esq** [jensweigele/ioBroker.yahka#97]
iobroker | 2019-01-26 22:40:44.073 | info | exit 0
-- | -- | -- | --
iobroker | 2019-01-26 22:40:44.060 | info | Adapter "yahka" updated
iobroker | 2019-01-26 22:40:44.004 | info | upload [0] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/css/yahka.admin.css css/yahka.admin.css text/css
iobroker | 2019-01-26 22:40:43.944 | info | upload [1] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-colors.min.css ext/metroui/css/metro-colors.min.css text/css
iobroker | 2019-01-26 22:40:43.880 | info | upload [2] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-icons.min.css ext/metroui/css/metro-icons.min.css text/css
iobroker | 2019-01-26 22:40:43.818 | info | upload [3] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-responsive.min.css ext/metroui/css/metro-responsive.min.css text/css
iobroker | 2019-01-26 22:40:43.759 | info | upload [4] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-rtl.min.css ext/metroui/css/metro-rtl.min.css text/css
iobroker | 2019-01-26 22:40:43.700 | info | upload [5] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-schemes.min.css ext/metroui/css/metro-schemes.min.css text/css
iobroker | 2019-01-26 22:40:43.609 | info | upload [6] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro.min.css ext/metroui/css/metro.min.css text/css
iobroker | 2019-01-26 22:40:43.524 | info | upload [7] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.eot ext/metroui/fonts/metro.eot application/vnd.ms-fontobject
iobroker | 2019-01-26 22:40:43.343 | info | upload [8] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.svg ext/metroui/fonts/metro.svg image/svg+xml
iobroker | 2019-01-26 22:40:43.258 | info | upload [9] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.ttf ext/metroui/fonts/metro.ttf application/x-font-ttf
iobroker | 2019-01-26 22:40:43.164 | info | upload [10] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.woff ext/metroui/fonts/metro.woff application/font-woff
iobroker | 2019-01-26 22:40:42.985 | info | upload [11] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/selection.json ext/metroui/fonts/selection.json application/json
iobroker | 2019-01-26 22:40:42.896 | info | upload [12] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/js/metro.min.js ext/metroui/js/metro.min.js application/javascript
iobroker | 2019-01-26 22:40:42.836 | info | upload [13] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/home_icon_large.png home_icon_large.png image/png
iobroker | 2019-01-26 22:40:42.774 | info | upload [14] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index.html index.html text/html
iobroker | 2019-01-26 22:40:42.711 | info | upload [15] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index_m.html index_m.html text/html
iobroker | 2019-01-26 22:40:42.649 | info | upload [16] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/words.js words.js application/javascript
iobroker | 2019-01-26 22:40:42.576 | info | upload [17] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js yahka.admin.js application/javascript
iobroker | 2019-01-26 22:40:42.501 | info | upload [18] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js.map yahka.admin.js.map application/json
iobroker | 2019-01-26 22:40:42.414 | info | upload [19] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.png yahka.png image/png
iobroker | 2019-01-26 22:40:42.387 | info | got /opt/iobroker/node_modules/iobroker.yahka/admin
iobroker | 2019-01-26 22:40:31.765 | info | npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.yahka"
iobroker | 2019-01-26 22:40:31.731 | info | /root/.npm/_logs/2019-01-26T19_40_31_656Z-debug.log
iobroker | 2019-01-26 22:40:31.729 | info | npm ERR!
iobroker | 2019-01-26 22:40:31.728 | info | A complete log of this run can be found in:
iobroker | 2019-01-26 22:40:31.726 | info | npm ERR!
iobroker | 2019-01-26 22:40:31.725 | info |  
iobroker | 2019-01-26 22:40:31.655 | info | npm ERR! Please check if you have git installed and in your PATH.
iobroker | 2019-01-26 22:40:31.655 | info | npm ERR! Failed using git.
iobroker | 2019-01-26 22:40:31.655 | info | npm ERR!
iobroker | 2019-01-26 22:40:31.655 | info | npm ERR! No git binary found in $PATH
iobroker | 2019-01-26 22:40:31.655 | info | npm ERR! undefined
iobroker | 2019-01-26 22:40:31.655 | info | npm ERR!
iobroker | 2019-01-26 22:40:31.655 | info | npm ERR! Error while executing:npm ERR! undefined ls-remote -h -t https://github.com/homespun/hap-nodejs-community-types.git
iobroker | 2019-01-26 22:40:31.650 | info | npm ERR! code ENOGIT
iobroker | 2019-01-26 22:40:16.445 | info | npm install iobroker.yahka@0.9.0 --production --save --prefix "/opt/iobroker" (System call)
iobroker | 2019-01-26 22:40:15.852 | info | NPM version: 6.4.1
iobroker | 2019-01-26 22:40:15.245 | info | Update yahka from @0.8.2 to @0.9.0
iobroker | 2019-01-26 22:40:13.762 | info | upgrade yahka
admin.0 | 2019-01-26 14:59:12.233 | info | Repository received successfully.
host.iobroker | 2019-01-26 14:59:09.974 | info | Update repository "latest" under "http://download.iobroker.net/sources-dist-latest.json"
admin.0 | 2019-01-26 14:59:09.933 | info | Request actual repository...
host.iobroker | 2019-01-26 03:23:35.033 | info | Delete log file iobroker.2019-01-19.log
iobroker | 2019-01-26 00:14:55.618 | info | exit 0
iobroker | 2019-01-26 00:14:55.605 | info | Adapter "yahka" updated
iobroker | 2019-01-26 00:14:55.548 | info | upload [0] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/css/yahka.admin.css css/yahka.admin.css text/css
iobroker | 2019-01-26 00:14:55.489 | info | upload [1] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-colors.min.css ext/metroui/css/metro-colors.min.css text/css
iobroker | 2019-01-26 00:14:55.424 | info | upload [2] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-icons.min.css ext/metroui/css/metro-icons.min.css text/css
iobroker | 2019-01-26 00:14:55.366 | info | upload [3] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-responsive.min.css ext/metroui/css/metro-responsive.min.css text/css
iobroker | 2019-01-26 00:14:55.310 | info | upload [4] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-rtl.min.css ext/metroui/css/metro-rtl.min.css text/css
iobroker | 2019-01-26 00:14:55.252 | info | upload [5] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-schemes.min.css ext/metroui/css/metro-schemes.min.css text/css
iobroker | 2019-01-26 00:14:55.161 | info | upload [6] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro.min.css ext/metroui/css/metro.min.css text/css
iobroker | 2019-01-26 00:14:55.076 | info | upload [7] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.eot ext/metroui/fonts/metro.eot application/vnd.ms-fontobject
iobroker | 2019-01-26 00:14:54.898 | info | upload [8] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.svg ext/metroui/fonts/metro.svg image/svg+xml
iobroker | 2019-01-26 00:14:54.814 | info | upload [9] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.ttf ext/metroui/fonts/metro.ttf application/x-font-ttf
iobroker | 2019-01-26 00:14:54.729 | info | upload [10] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.woff ext/metroui/fonts/metro.woff application/font-woff
iobroker | 2019-01-26 00:14:54.547 | info | upload [11] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/selection.json ext/metroui/fonts/selection.json application/json
iobroker | 2019-01-26 00:14:54.463 | info | upload [12] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/js/metro.min.js ext/metroui/js/metro.min.js application/javascript
iobroker | 2019-01-26 00:14:54.406 | info | upload [13] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/home_icon_large.png home_icon_large.png image/png
iobroker | 2019-01-26 00:14:54.345 | info | upload [14] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index.html index.html text/html
iobroker | 2019-01-26 00:14:54.280 | info | upload [15] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index_m.html index_m.html text/html
iobroker | 2019-01-26 00:14:54.219 | info | upload [16] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/words.js words.js application/javascript
iobroker | 2019-01-26 00:14:54.145 | info | upload [17] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js yahka.admin.js application/javascript
iobroker | 2019-01-26 00:14:54.075 | info | upload [18] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js.map yahka.admin.js.map application/json
iobroker | 2019-01-26 00:14:53.992 | info | upload [19] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.png yahka.png image/png
iobroker | 2019-01-26 00:14:53.967 | info | got /opt/iobroker/node_modules/iobroker.yahka/admin
iobroker | 2019-01-26 00:14:43.441 | info | npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.yahka"
iobroker | 2019-01-26 00:14:43.409 | info | npm ERR! /root/.npm/_logs/2019-01-25T21_14_43_336Z-debug.log
iobroker | 2019-01-26 00:14:43.409 | info | npm ERR! A complete log of this run can be found in:
iobroker | 2019-01-26 00:14:43.333 | info | npm ERR! Please check if you have git installed and in your PATH.
iobroker | 2019-01-26 00:14:43.333 | info | npm ERR! Failed using git.
iobroker | 2019-01-26 00:14:43.333 | info | npm ERR!
iobroker | 2019-01-26 00:14:43.333 | info | npm ERR! No git binary found in $PATH
iobroker | 2019-01-26 00:14:43.333 | info | npm ERR! undefined
iobroker | 2019-01-26 00:14:43.330 | info | npm ERR!
iobroker | 2019-01-26 00:14:43.330 | info | npm ERR! Error while executing:npm ERR! undefined ls-remote -h -t https://github.com/homespun/hap-nodejs-community-types.git
iobroker | 2019-01-26 00:14:43.325 | info | npm ERR! code ENOGIT
iobroker | 2019-01-26 00:14:27.538 | info | npm install iobroker.yahka@0.9.0 --production --save --prefix "/opt/iobroker" (System call)
iobroker | 2019-01-26 00:14:26.943 | info | NPM version: 6.4.1
iobroker | 2019-01-26 00:14:26.353 | info | Update yahka from @0.8.2 to @0.9.0

**Comment by Mr-REM-Esq** [comment]
<img width="931" alt="2019-01-26 22 56 03" src="https://user-images.githubusercontent.com/42520242/51792087-ab6b9200-21bd-11e9-8130-c6597ecf5670.png">

**Comment by jensweigele** [comment]
`npm ERR! No git binary found in $PATH`

A new dependency requires to have git installed. I'll check if I can change the dependency which is requiring git.

For the meantime, you can work around this error by installing git

**Comment by Mr-REM-Esq** [comment]
I've installed git. But...


iobroker | 2019-01-28 14:33:33.192 | info | npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.yahka"
-- | -- | -- | --
iobroker | 2019-01-28 14:33:33.162 | info | npm ERR! /root/.npm/_logs/2019-01-28T11_33_33_055Z-debug.log
iobroker | 2019-01-28 14:33:33.162 | info | npm ERR! A complete log of this run can be found in:
iobroker | 2019-01-28 14:33:33.051 | info | npm ERR!
iobroker | 2019-01-28 14:33:33.051 | info | npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursivenpm ERR! fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-d2e12e6b': Отказано в доступе
iobroker | 2019-01-28 14:33:33.046 | info | npm ERR! code 128
iobroker | 2019-01-28 14:33:13.254 | info | npm install iobroker.yahka@0.9.0 --production --save --prefix "/opt/iobroker" (System call)
iobroker | 2019-01-28 14:33:12.669 | info | NPM version: 6.4.1
iobroker | 2019-01-28 14:33:12.076 | info | Update yahka from @0.8.2 to @0.9.0
iobroker | 2019-01-28 14:33:10.610 | info | upgrade yahka

**Comment by Goersch** [comment]
same problem here

**Comment by jensweigele** [comment]
Please install git if there is an error stating that "git" cannot be found.

**Comment by jensweigele** [comment]
The latest commit on master should remove the need for having git installed.
