### ISSUE TITLE
beim benutzen der inverse startet die Instanz nicht

### ISSUE THREAD

**Issue by avdic89** [jensweigele/ioBroker.yahka#98]
Wenn ich die inverse benutze (Rallladensteuerung) startet die Instanz nicht mehr. Vor der Version 0.9.0 und 0.9.1 lief alles ohne Probleme. Jedoch tritt jetzt auch nach einem Downgrade das gleiche Problem auf.

Auszug aus dem Log: (iobeoker läuft im Docker (DS218+))

host.buanet-iobroker3 | 2019-01-28 13:40:53.782 | error | instance system.adapter.yahka.0 terminated with code 0 (OK)
-- | -- | -- | --
host.buanet-iobroker3 | 2019-01-28 13:40:53.782 | error | Caught by controller[0]: at TIOBrokerAdapter.__dirname../yahka.ioBroker-adapter.ts.TIOBrokerAdapter.adapterReady (/opt/iobroker/node_modules/iobroker.yahka/main.js:2356:14)
host.buanet-iobroker3 | 2019-01-28 13:40:53.782 | error | Caught by controller[0]: at TIOBrokerAdapter.__dirname../yahka.ioBroker-adapter.ts.TIOBrokerAdapter.createHomeKitBridges (/opt/iobroker/node_modules/iobroker.yahka/main.js:2379:27)
host.buanet-iobroker3 | 2019-01-28 13:40:53.782 | error | Caught by controller[0]: at new THomeKitBridge (/opt/iobroker/node_modules/iobroker.yahka/main.js:1770:14)
host.buanet-iobroker3 | 2019-01-28 13:40:53.782 | error | Caught by controller[0]: at THomeKitBridge.__dirname../yahka.homekit-bridge.ts.THomeKitBridge.init (/opt/iobroker/node_modules/iobroker.yahka/main.js:1782:42)
host.buanet-iobroker3 | 2019-01-28 13:40:53.782 | error | Caught by controller[0]: at THomeKitBridge.__dirname../yahka.homekit-bridge.ts.THomeKitBridge.createDevice (/opt/iobroker/node_modules/iobroker.yahka/main.js:1856:22)
host.buanet-iobroker3 | 2019-01-28 13:40:53.782 | error | Caught by controller[0]: at THomeKitBridge.__dirname../yahka.homekit-bridge.ts.THomeKitBridge.initService (/opt/iobroker/node_modules/iobroker.yahka/main.js:1887:22)
host.buanet-iobroker3 | 2019-01-28 13:40:53.782 | error | Caught by controller[0]: at THomeKitBridge.__dirname../yahka.homekit-bridge.ts.THomeKitBridge.initCharacteristic (/opt/iobroker/node_modules/iobroker.yahka/main.js:1912:57)
host.buanet-iobroker3 | 2019-01-28 13:40:53.781 | error | Caught by controller[0]: at TIOBrokerAdapter.__dirname../yahka.ioBroker-adapter.ts.TIOBrokerAdapter.CreateBinding (/opt/iobroker/node_modules/iobroker.yahka/main.js:2499:64)
host.buanet-iobroker3 | 2019-01-28 13:40:53.781 | error | Caught by controller[0]: at Object.createConversionFunction (/opt/iobroker/node_modules/iobroker.yahka/main.js:994:61)
host.buanet-iobroker3 | 2019-01-28 13:40:53.781 | error | Caught by controller[0]: at Object.__dirname../yahka.functions/conversion.inverse.ts.TIoBrokerConversion_Inverse.create [as inverse] (/opt/iobroker/node_modules/iobroker.yahka/main.js:610:29)
host.buanet-iobroker3 | 2019-01-28 13:40:53.781 | error | Caught by controller[0]: TypeError: this.castToNumber is not a function

**Comment by DanielWeeber** [comment]
Identischer Fehler hier.

**Comment by asgothian** [comment]
Identischer Fehler bei mir auch

**Comment by jensweigele** [comment]
Ich versuche mir das in den nächsten Tagen anzuschauen

**Comment by jensweigele** [comment]
Mit dem aktuellen NPM Paket (0.9.1) bzw. dem aktuellen Master, sollte der Adapter wieder started

**Comment by peer69** [comment]
Funktionier bei mir wieder. Vielen Dank!
